### ISSUE TITLE
The first RTP packet that triggers OnTrack wouldn't be received (trivial)

### ISSUE THREAD

**Issue by enobufs** [pion/webrtc#1001]
### Your environment.
  - Version: v2.1.18

### What did you do?
Use an audio track (opus), both ends have a local track (bidirectional).
Sending a dummy RTP packet from both ends.

### What did you expect?
The RTP packets should be received by the remote.

### What happened?
The first RTP packet sent by the sender successfully triggered remote's OnTrack() callback, but the packet never gets received.

I know, the RTP stream is not guaranteed delivery but the first packet of sender->receiver always lost. For test purposes, as it is lost always, I have to write the packet more than once - a bit silly.

This is definitely trivial, but it would be nice if the first packet correctly surfaces on track.Read()/ReadRTP().

**Comment by illuspas** [comment]
That's it, I also encountered this problem, Every time.

Version: v2.2.0

I created a H264 session, Then I use wireshark to capture packets.nThe received packets are as follows.
```
677	6.498123	192.168.0.6	192.168.0.8	RTP	79	PT=DynamicRTP-Type-102, SSRC=0xEA16D44E, Seq=2578, Time=542359578
678	6.498124	192.168.0.6	192.168.0.8	RTP	68	PT=DynamicRTP-Type-102, SSRC=0xEA16D44E, Seq=2579, Time=542359578
680	6.498674	192.168.0.6	192.168.0.8	RTP	1132	PT=DynamicRTP-Type-102, SSRC=0xEA16D44E, Seq=2580, Time=542359578
```

But in the debug output of my program, It returns from the second package
```
Connection State has changed checking 
Connection State has changed connected 
2020/02/17 21:23:51 [D] [rtc.go:187] SequenceNumber=2579 NAL marker=false =[104 206 60 128]
2020/02/17 21:23:51 [D] [rtc.go:187] SequenceNumber=2580 NAL marker=false =[101 184 0 4]
2020/02/17 21:23:51 [D] [rtc.go:187] SequenceNumber=2581 NAL marker=false =[101 2 107 128]
```
The 2578 package is missing,  And it must be the sps of h264.

**Comment by Sean-Der** [comment]
This shouldn't be difficult to fix! I will grab.

**Comment by illuspas** [comment]
Any updates? I figured out what the problem was.

In this step, a packet of RTP data is read to get the PayloadType
https://github.com/pion/webrtc/blob/b0d95d59dacc18ccee71e24aa639765e22550ae2/peerconnection.go#L787
Then use it to get codec from mediaEngine.
https://github.com/pion/webrtc/blob/b0d95d59dacc18ccee71e24aa639765e22550ae2/peerconnection.go#L800

As a result, the first packet of data is no longer available.

**Comment by jech** [comment]
I'm being bitten by this, it causes a spurious PLI for every stream.
