### ISSUE TITLE
Update godoc link

### ISSUE THREAD

**Issue by at-wat** [pion/webrtc#1009]
Currently linked to https://pkg.go.dev/github.com/pions/webrtc. (Still linked to pion**s**)

There is a new document site https://pkg.go.dev/github.com/pion/webrtc/v2 which can explicitly handle package versions.

**Comment by at-wat** [comment]
Would be better to check other repositories.

**Comment by Sean-Der** [comment]
@at-wat I will grab this! Will send you PRs tomorrow to update all our godoc links to pkg.go.dev across all repos.

**Comment by Sean-Der** [comment]
Done!
