### ISSUE TITLE
How to generate "Golang base64 Session Description"

### ISSUE THREAD

**Issue by juexun** [pion/webrtc#1019]
Hi, I'm a newbie to pion.
 I run the examples with `go run examples.go` under `webrtc/examples`
While I tried the broadcast by accessed the url `http://localhost/example/js/broadcast/` on Chrome browser, I got the `Browser base64 Session Description`.
The question is how to generate the `Golang base64 Session Description`.
Could anybody help me?
Thanks a lot

**Comment by Sean-Der** [comment]
Hi @juexun 

Thanks for checking out Pion! You can generate it by running `curl localhost:8080/sdp -d "Browser SDP"` then the broadcast binary will print it to stdout.

[broadcast](https://github.com/pion/webrtc/tree/master/examples/broadcast) has more documentation around it. Please re-open or reach out on Slack if you have more questions.

thanks

**Comment by RathanakSreang** [comment]
@Sean-Der I also fact this issue.
And  I try follow your command above but it still does not work.

**Comment by Sean-Der** [comment]
@RathanakSreang are you running the curl command on the same computer you ran broadcast/main.go?

Thanks

**Comment by RathanakSreang** [comment]
@Sean-Der  Yes, I do. But the result i got is just HTML code instead.

**Comment by Sean-Der** [comment]
Something else is listening on :8080 then. Probably examples.go ? I would use the JSFiddle link in the broadcast README, and make sure nothing else is running.

**Comment by robmunro-sg** [comment]
I've just tried this on the lastest trunk branch - I also just get the raw HTML
using: go run examples.go --address localhost:8080
then curl localhost:8080/sdp -d "Browser SDP"

**Comment by NickThorne123** [comment]
OK so I was having a mental block about where $BROWSER_SDP comes from. So will explain here for the benefit of others.

Say you want to run the reflect example, then open the reflect jsfiddle page linked from [here](https://github.com/pion/webrtc/tree/master/examples/reflect). Click on the text [A] from the box called "Browser base64 Session Description". Then go back into the linux bash shell / osx terminal where you have installed the webrtc examples and done a `export GO111MODULE=on
go get github.com/pion/webrtc/v3/examples/reflect`

Now in the examples/reflect directory, enter
`echo $BROWSER_SDP | reflect`
where $BROWSER_SDP is the text [A] we copied from the jsfiddle "Browser base64 Session Description" box. 

The terminal will then print another base64 string which we past into the other box in the jsfiddle page.
Should work now...

**Comment by hammerheaddown** [comment]
can you send us some info on how exactly we are supposed to do this on a windows pc?

isnt there a batch file file or something we could use?

**Comment by NielsDom** [comment]
> curl localhost:8080/sdp -d "Browser SDP"

Hi, curl localhost:8080/sdp -d "Browser SDP". not working for me, it shows: 
curl: (7) Failed to connect to localhost port 8080: Connection refused

Thank you

**Comment by AlexanderMatveev** [comment]
```bash
curl localhost:8080/sdp -d "Browser SDP"
```
Gives `done` in stdout and panic in application:

> panic: illegal base64 data at input byte 7
> 
> goroutine 1 [running]:
> join/signal.Decode(0xc0001b0580, 0xb, 0x1416ac0, 0xc0001c4260)
>         /Users/alex/GoProjects/join/signal/signal.go:63 +0xd9
> main.main()
>         /Users/alex/GoProjects/join/main.go:22 +0xc5

**Comment by Sean-Der** [comment]
Hey @AlexanderMatveev you don't want to send `"Browser SDP"` but the base64 value in the textarea
\
![2021-03-20-103304_525x117_scrot](https://user-images.githubusercontent.com/1302304/111880269-ae123e00-8967-11eb-8572-59fa655da3d0.png)

**Comment by Sean-Der** [comment]
If you get a chance would you mind updating the docs to be more descriptive? This has confused multiple people, not sure of a better way to work it though.

**Comment by AlexanderMatveev** [comment]
@Sean-Der Thanks for response, I got it from code. But I didn't found any information about where must I get this base64-string.

**Comment by Sean-Der** [comment]
Hey @AlexanderMatveev I updated the instructions in https://github.com/pion/webrtc/commit/31d90467aea75612ac4dc21b09ed1036e9ec6500

Mind trying again?

**Comment by AlexanderMatveev** [comment]
@Sean-Der following updated readme.

At [Start a publisher section](https://github.com/pion/webrtc/tree/master/examples/broadcast#start-a-publisher):

> - Click Publish a Broadcast
> - Copy the string in the first input labelled Browser base64 Session Description

There is no value in textareas at linked jsfiddle (https://jsfiddle.net/1jc4go7v/), see video:

https://user-images.githubusercontent.com/1456669/111887011-397ce500-89e3-11eb-8375-e03171f7a861.mov

It requires some JSON I gusess. Still can't understand, where must I get it.

**Comment by Sean-Der** [comment]
Ah so the issue is your STUN requests are timing out.

Can you remove
```
    iceServers: [
      {
        urls: 'stun:stun.l.google.com:19302'
      }
    ]
```

From the Javascript and Go code and try again? We have STUN on by default and don't do Trickle ICE. If that works for you I will make a note of it.
