### ISSUE TITLE
Why is srflx raddr 0.0.0.0 ? 

### ISSUE THREAD

**Issue by wattanakorn495** [pion/webrtc#1022]
### Your environment.
  - Version: v2.1.18
  - Other Information - ubuntu armv8 rk3399

### What did you do?

I try to connect browser client with gstreamer-receive client which runing on nanopi rk3399 board
but srflx raddr in the sdp answer always 0.0.0.0 
### What did you expect?
should raddr be host addr ?
### What happened?
srflx raddr in the sdp answer always 0.0.0.0

ex:
a=candidate:foundation 2 udp 2130706431 192.168.1.101 54656 typ host generation 0
a=candidate:foundation 1 udp 1694498815 xxx.xxx.xxx.234 62779 typ srflx raddr 0.0.0.0 rport 62779 generation 0
a=candidate:foundation 2 udp 1694498815 xxx.xxx.xxx.234 62779 typ srflx raddr 0.0.0.0 rport 62779 generation 0

**Comment by Sean-Der** [comment]
This is by design! I don't know the exact spec, but for privacy reasons the raddr value is nulled out.

 WebRTC is trying to move away from host candidate IPs being available anywhere like [mDNS candidates](https://tools.ietf.org/html/draft-ietf-rtcweb-mdns-ice-candidates-04)

**Comment by Sean-Der** [comment]
I currently have mDNS candidates off by default, but they can be enabled via the `SettingEngine` they will fail in some networks where host candidates currently work.

**Comment by Sean-Der** [comment]
Hey @wattanakorn495 I am going to resolve this, please re-open if this is an issue/I didn't fully understand the problem!

I am getting ready to release `v2.2.0` and aggressively triaging stuff :)
