### ISSUE TITLE
Make Track an interface

### ISSUE THREAD

**Issue by at-wat** [pion/webrtc#1025]
To deal with a MediaStreamTrack coming from an another package like pion/mediadevices, Track would be better to be an interface something like:
```go
type Track interface {
  ID() string
}
type LocalTrack interface {
  Track
  ReadRTP() (*rtp.Packet, error)
  ...
}
type RemoteTrack interface {
  Track
  WriteRTP(*rtp.Packet) error
  ...
}
type RTPSender interface {
  ReplaceTrack(LocalTrack) error
}
type RTPReceiver interface {
  ReplaceTrack(RemoteTrack) error
}
```
ref: https://github.com/pion/mediadevices/pull/39#discussion_r378651046

It might require a lot of breaking changes, so it would be a v3 matter.

**Comment by Sean-Der** [comment]
@at-wat :+1:, my goal is to publish a new release this weekend. Then feel free to break anything/everything you want in master :)

If you wouldn't mind adding stuff to https://github.com/pion/webrtc/wiki/PlanningV3 that would be really helpful. I want to make sure our new changes interact well with.
* Better Stats
* NACK
* Congestion Control
* SVC/Simulcast 

All of these are hurt by the current API. So would be awesome if we get it right the first time :)

**Comment by Sean-Der** [comment]
I am covering here https://github.com/pion/webrtc/projects/17

`/v3` has been complicated because of all the use cases I am trying to cover. I am sure we will come to a good solution, but need to get it all into one place.
