### ISSUE TITLE
Regression in the number of outbound data

### ISSUE THREAD

**Issue by gqgs** [pion/webrtc#1026]
### Your environment.
  - Version: e9d5bc5a92f3ff48977b5548bbd5acb9ff8dd6e1
  - Browser: Chrome 78.0.3904.97

### What did you do?

Executed the [reflect example](https://github.com/pion/webrtc/tree/master/examples/reflect).

### What did you expect?

Not sure yet which exact version produced the regression but back in version 20f2d1899ebbbdb3879444a03a7dc956a3b51126 the browser was still able to produce a steady 15 encoded frames per second. RTCOutboundRTPVideoStream graphs:

![20f2d1899ebbbdb3879444a03a7dc956a3b51126](https://user-images.githubusercontent.com/32180229/74479833-a5128b80-4e8e-11ea-9e13-8dbe31ca3d7f.png)

I expected this to still be the case in the master branch.

### What happened?

The amount of outbound data has decreased.

![e9d5bc5a92f3ff48977b5548bbd5acb9ff8dd6e1](https://user-images.githubusercontent.com/32180229/74480062-fe7aba80-4e8e-11ea-9c9c-b70b84f6d416.png)

The number of encoded frames in particular looks significantly more erratic than before.
The result is a very choppy stream on the receiving side.

**Comment by Sean-Der** [comment]
Thanks for the report @gqgs!

I will be able to look into this in about two hours. If you have the time trying a few different commits and getting it into a smaller commit range would be super helpful :)

thanks

**Comment by gqgs** [comment]
Thanks for the reply @Sean-Der.

If I'm not mistaken the issue was already present in commit ce8de088e73c1dfe23e881448682ca0fcd82581b so it was something that changed between 20f2d1899ebbbdb3879444a03a7dc956a3b51126 and the aforementioned commit.
Unfortunately I have no way of bisecting this further at the moment but I will post any updates here as soon as I have the opportunity to look further into it.

**Comment by Sean-Der** [comment]
Hey @gqgs I can confirm https://github.com/pion/webrtc/commit/ce8de088e73c1dfe23e881448682ca0fcd82581b is the commit causing the issue. I am going to revert and will close this ticket with it.

Sorry for all the bugs you are hitting, but it really helps me :)

**Comment by gqgs** [comment]
Thanks @Sean-Der :)
