### ISSUE TITLE
Wrong Payload type for audio tracks in Firefox

### ISSUE THREAD

**Issue by chrbsg** [pion/webrtc#1030]
### Your environment.
  - Version: 2.1.18
  - Browser: Firefox 59 Linux
  - Other Information - 

### What did you do?

"Chrome  uses RTP payload type value 111, but Firefox uses 109. The PT is actually dynamically assigned, so it does not have to be 111, but pion by default ignores what the remote requests in SDP." (Yutaka)

### What did you expect?

Audio tracks should work in Firefox

### What happened?

No audio

Pion defines: DefaultPayloadTypeOpus = 111
But this 111 should be dynamic.

In the following, NewTrack returns error "codec not found" on Firefox:

```
MediaEngine.PopulateFromSDP(offer) 
pc.NewTrack(webrtc.DefaultPayloadTypeOpus, ...)
```

### Workaround

Manually parse SDP, extract payload type, and use it as first parameter to NewTrack:
````
        var pt uint8
        l := strings.Split(desc.SDP, "\n")                                                               
        for _, v := range l {
                v = strings.TrimSpace(v)                                                                 
                if strings.HasPrefix(v, "a=rtpmap:") &&                                                  
                        strings.HasSuffix(v, " opus/48000/2") {                                          
                        t := strings.TrimPrefix(v, "a=rtpmap:")                                          
                        u := strings.TrimSuffix(t, " opus/48000/2")                                      
                        _pt, err := strconv.Atoi(u)                                                      
                        check(err)
                        pt = uint8(_pt)                                                                  
                }                                                                                        
        }

        m := webrtc.MediaEngine{}
        m.RegisterCodec(webrtc.NewRTPOpusCodec(pt, 48000))                                                                                                
                                                       
        txtrack, err := pc.NewTrack(pt, rand.Uint32(), "audio", "pion1")                          
        check(err)
        _, err = pc.AddTrack(txtrack)
        check(err)

```

**Comment by enobufs** [comment]
Here's a comment by @Sean-Der from the pion Slack channel:

```
You have to do this unfortunately https://github.com/pion/webrtc/blob/master/examples/play-from-disk/main.go#L21-L40
```

@Sean-Der Although this solves for the moment, as some of the RTP payload types are "dynamically" assigned, I think the reassignment of the payload type should happen transparently to the user code. How about changing this issue title to something like "Support dynamic RTP payload type", then close the referencing issues as redundant?

**Comment by chrbsg** [comment]
Won't mediaEngine.PopulateFromSDP(offer) (_"finds all codecs in a session description and adds them to a MediaEngine"_) add support all the codecs that the peer supports, even if we don't? e.g. if the peer supports VP8, but we don't support video, then the mediaEngine will get VP8  codec added?  I don't know the exact impact of that, is it just for runtime checks for payload types in calls to functions like NewTrack()? 

Another issue with the PopulateFromSDP approach is that  the first agument to pc.NewTrack requires the payload type ie. `pc.NewTrack(pt,...)` and DefaultPayloadTypeOpus is now  wrong. The caller would have to iterate over the mediaEngine codecs and find the opus payload type before calling pc.NewTrack.

**Comment by jech** [comment]
Shouldn't you be using `sdp.SessionDescription.Unmarshal` instead of grepping through the SDP yourself?

**Comment by Sean-Der** [comment]
The design right now is unfortunate, lots of sharp edges.

I am prototyping [here](https://github.com/pion/webrtc-v3-api-examples) about what I would like to do to fix all these issues. We need to support both Sender/Receiver side congestion control, and I don't want users to manage PayloadTypes and SSRCes.

If you have time @jech would love your opinion!

**Comment by Sean-Der** [comment]
I am track this in https://github.com/pion/webrtc/projects/17

I am planning on removing PayloadType and SSRC from the public API. This is a sharp edge in the API design, and doesn't hold up at all now that we are working on Simulcast.

I am moving this all into the task board so we can make sure the new API covers all the use cases we care about.

**Comment by jech** [comment]
> I am planning on removing PayloadType and SSRC from the public API.

How will a client send sender/receiver reports if he doesn't know the SSRC?

> doesn't hold up at all now that we are working on Simulcast.

For what it's worth, I've got a working implementation of simulcast in the Unnamed SFU, with no library changes whatsoever.  It's not merged into mainline yet since it's not quite ready for public consumption (I'm currently sending all layers in the client->server direction, not just the ones that some other client needs).

**Comment by Sean-Der** [comment]
@jech 

> How will a client send sender/receiver reports if he doesn't know the SSRC?
What do you think if we make them accessible, but user doesn't have to worry about them? On the `RtpSender` and `RtpReceiver` you can pull the `SSRC`.

I just want users to be able to send RTP packets (and not worry about SSRC/PayloadType). 

> For what it's worth, I've got a working implementation of simulcast in the Unnamed SFU
Nice! What are the most annoying parts to get it working? I have heard from people the lack of proper extmap support is a huge pain. We also have a PR open for it https://github.com/pion/webrtc/pull/1200

**Comment by jech** [comment]
> What do you think if we make them accessible, but user doesn't have to worry about them?

I'm not sure, I'd need to think it over.  I'm currently not rewriting SSRCs, but I might end up having to do that if I fail to implement simulcasting almost entirely on the client side (see below).

> Nice! What are the most annoying parts to get it working?

The most tricky bit is to decide when to switch to a higher layer.  The down direction is easy if you have a proper congestion controller, but the congestion controller doesn't give you accurate information when you're not filling the bottleneck, which is the case when you're on a lower layer.

The most finicky and annoying bit is to get the client to switch layers without too much of an interruption.  I'm hoping I can manage to do that without SSDP munging on the server side.
