### ISSUE TITLE
Turn TCP Relay not working as expected

### ISSUE THREAD

**Issue by nindolabs** [pion/webrtc#1036]
### Your environment.
  - Version: v2.2.0
  - Browser: Chrome 80.0.3987.106

### What did you do?

Set ice server to **turn:192.168.1.27:3478?transport=tcp**

Turn server : coturn

Block UDP Protocol

### What did you expect? / What happened ?

When i block UDP protocol on the client side (chrome), the browser fallbacks to TCP relay as expected.

But when i do the same thing on the server side (pion) it fails to connect.

Logs:

> turnc DEBUG: 17:09:28.499210 client.go:103: resolving 192.168.1.27:3478
turnc DEBUG: 17:09:28.499210 client.go:109: turnServ: 192.168.1.27:3478
turnc TRACE: 17:09:28.499210 client.go:353: start Allocate request transaction nk1NK9cJ8oh9R/pU to 192.168.1.27:3478
turnc TRACE: 17:09:28.500207 client.go:353: start Allocate request transaction oSu9TVp8sl/3fVkG to 192.168.1.27:3478
turnc DEBUG: 17:09:28.501277 conn.go:92: initial lifetime: 600 seconds
turnc DEBUG: 17:09:28.501277 conn.go:107: refreshAllocTimer started
turnc DEBUG: 17:09:28.501277 conn.go:110: refreshPermsTimer started
pc INFO: 2020/02/17 17:09:28 signaling state changed to have-local-offer
pc INFO: 2020/02/17 17:09:28 signaling state changed to stable
ice DEBUG: 17:09:28.576699 agent.go:597: Started agent: isControlling? true, remoteUfrag: "LMFU", remotePwd: "ReKKkiyAlaHJcPDMk7Vi7T4L"
ice INFO: 2020/02/17 17:09:28 Setting new connection state: Checking
ice TRACE: 17:09:28.576699 selection.go:96: pinging all candidates
pc INFO: 2020/02/17 17:09:28 ICE connection state changed: checking
INFO[0005] Connection state changed: checking            Client="192.168.1.43:63644" Func="webrtc_proxy::RTCVideo"
ice TRACE: 17:09:30.576848 selection.go:96: pinging all candidates
ice TRACE: 17:09:32.578049 selection.go:96: pinging all candidates
ice TRACE: 17:09:34.578336 selection.go:96: pinging all candidates
ice TRACE: 17:09:36.576725 selection.go:96: pinging all candidates
ice TRACE: 17:09:38.576700 selection.go:40: check timeout reached and no valid candidate pair found, marking connection as failed
ice INFO: 2020/02/17 17:09:38 Setting new connection state: Failed
ice TRACE: 17:09:38.576700 selection.go:96: pinging all candidates
pc INFO: 2020/02/17 17:09:38 ICE connection state changed: failed
pc INFO: 2020/02/17 17:09:38 peer connection state changed: failed
INFO[0015] Connection state changed: failed              Client="192.168.1.43:63644" Func="webrtc_proxy::RTCVideo"
turnc DEBUG: 17:09:38.576700 conn.go:458: send refresh request (dontWait=true)
turnc TRACE: 17:09:38.576700 client.go:353: start Refresh request transaction zRFofDYsqIZw7mgn to 192.168.1.27:3478
turnc DEBUG: 17:09:38.576700 conn.go:465: refresh request sent
turnc DEBUG: 17:09:38.576700 client.go:174: exiting read loop: read tcp4 192.168.1.64:51373->192.168.1.27:3478: use of closed network connection
ice INFO: 2020/02/17 17:09:38 Setting new connection state: Closed
pc INFO: 2020/02/17 17:09:38 peer connection state changed: closed
pc INFO: 2020/02/17 17:09:38 ICE connection state changed: closed
pc WARNING: 2020/02/17 17:09:38 Failed to start manager: the agent is closed
INFO[0015] Connection state changed: closed              Client="192.168.1.43:63644" Func="webrtc_proxy::RTCVideo"

**Comment by Sean-Der** [comment]
Hey @nindolabs 

I believe this is https://github.com/pion/ice/issues/118. If you do UDP + TCP it will block until all of them connect. We need to properly collect them async. If you do TCP only it should work.

I will be able to grab this in the next few days. Also make sure to enable Trickle ICE (via SettingEngine) otherwise CreateOffer/CreateAnswer blocks forever until everything is gathered. In `/v3` it will be the default.

**Comment by nindolabs** [comment]
Hello @Sean-Der 

Thank you for your reply.

I tested TCP only (blocking UDP on both sides), unfortunately it fails to connect too, i also increased ping timeout + ice trickle but without success.

Logs

> turnc DEBUG: 11:13:49.572868 client.go:103: resolving 192.168.1.27:3478
turnc DEBUG: 11:13:49.572868 client.go:109: turnServ: 192.168.1.27:3478
turnc TRACE: 11:13:49.572868 client.go:353: start Allocate request transaction WDzuNy7mTaqgw235 to 192.168.1.27:3478
turnc TRACE: 11:13:49.573866 client.go:353: start Allocate request transaction BDsB4gxTB0YdfGEL to 192.168.1.27:3478
turnc DEBUG: 11:13:49.574863 conn.go:92: initial lifetime: 600 seconds
turnc DEBUG: 11:13:49.574863 conn.go:107: refreshAllocTimer started
turnc DEBUG: 11:13:49.574863 conn.go:110: refreshPermsTimer started
pc INFO: 2020/02/18 11:13:49 signaling state changed to have-local-offer
pc INFO: 2020/02/18 11:13:49 signaling state changed to stable
ice DEBUG: 11:13:49.649430 agent.go:597: Started agent: isControlling? true, remoteUfrag: "FBSD", remotePwd: "SGev2qbC+znDKrpKSd1VofGT"
ice INFO: 2020/02/18 11:13:49 Setting new connection state: Checking
ice TRACE: 11:13:49.649430 selection.go:96: pinging all candidates
pc INFO: 2020/02/18 11:13:49 ICE connection state changed: checking
INFO[0004] Connection state changed: checking            Client="192.168.1.43:64306" Func="webrtc_proxy::RTCVideo"
ice TRACE: 11:13:51.649505 selection.go:96: pinging all candidates
ice TRACE: 11:13:53.649875 selection.go:96: pinging all candidates
ice TRACE: 11:13:55.649647 selection.go:96: pinging all candidates
ice TRACE: 11:13:57.649659 selection.go:96: pinging all candidates
ice TRACE: 11:13:59.649503 selection.go:96: pinging all candidates
ice TRACE: 11:13:59.649503 selection.go:40: check timeout reached and no valid candidate pair found, marking connection as failed
ice INFO: 2020/02/18 11:13:59 Setting new connection state: Failed
pc INFO: 2020/02/18 11:13:59 ICE connection state changed: failed
pc INFO: 2020/02/18 11:13:59 peer connection state changed: failed
INFO[0014] Connection state changed: failed              Client="192.168.1.43:64306" Func="webrtc_proxy::RTCVideo"
turnc DEBUG: 11:13:59.649503 conn.go:458: send refresh request (dontWait=true)
turnc TRACE: 11:13:59.649503 client.go:353: start Refresh request transaction IEXYCtAKHBRu2ifn to 192.168.1.27:3478
turnc DEBUG: 11:13:59.649503 conn.go:465: refresh request sent
turnc DEBUG: 11:13:59.649503 client.go:174: exiting read loop: read tcp4 192.168.1.64:60705->192.168.1.27:3478: use of closed network connection
ice INFO: 2020/02/18 11:13:59 Setting new connection state: Closed
pc INFO: 2020/02/18 11:13:59 peer connection state changed: closed
pc INFO: 2020/02/18 11:13:59 ICE connection state changed: closed
pc WARNING: 2020/02/18 11:13:59 Failed to start manager: the agent is closed
INFO[0014] Connection state changed: closed              Client="192.168.1.43:64306" Func="webrtc_proxy::RTCVideo"

Offer (from server side - pion)

> v=0
o=- 128496775 1582020829 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 86:C0:4D:71:68:50:05:F2:85:5A:79:45:C9:71:EF:A7:E2:88:CB:4F:A0:BA:90:E1:D5:46:E8:25:FA:6F:39:DE
a=group:BUNDLE 0 1
m=video 9 UDP/TLS/RTP/SAVPF 102
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=ice-ufrag:ORAApFrgEQyYKJPj
a=ice-pwd:ORAApFrgEQyYKJPjpsMWpoUYrmhvHIXx
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:102 nack 
a=rtcp-fb:102 nack pli
a=rtcp-fb:102 nack sli
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 transport-cc 
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=rtcp-fb:102 goog-remb 
a=ssrc:4039455774 cname:cgx
a=ssrc:4039455774 msid:cgx video
a=ssrc:4039455774 mslabel:cgx
a=ssrc:4039455774 label:video
a=msid:cgx video
a=sendrecv
a=candidate:foundation 1 udp 2130706431 192.168.1.64 40381 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.1.64 40381 typ host generation 0
a=candidate:foundation 1 udp 16777215 192.168.1.27 63923 typ relay raddr 192.168.1.64 rport 60705 generation 0
a=candidate:foundation 2 udp 16777215 192.168.1.27 63923 typ relay raddr 192.168.1.64 rport 60705 generation 0
a=end-of-candidates
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:1
a=sendrecv
a=sctpmap:5000 webrtc-datachannel 1024
a=ice-ufrag:ORAApFrgEQyYKJPj
a=ice-pwd:ORAApFrgEQyYKJPjpsMWpoUYrmhvHIXx
a=candidate:foundation 1 udp 2130706431 192.168.1.64 40381 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.1.64 40381 typ host generation 0
a=candidate:foundation 1 udp 16777215 192.168.1.27 63923 typ relay raddr 192.168.1.64 rport 60705 generation 0
a=candidate:foundation 2 udp 16777215 192.168.1.27 63923 typ relay raddr 192.168.1.64 rport 60705 generation 0
a=end-of-candidates

Answer (chrome)

> v=0
o=- 7476886457775158233 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 102
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:FBSD
a=ice-pwd:SGev2qbC+znDKrpKSd1VofGT
a=ice-options:trickle
a=fingerprint:sha-256 43:27:44:F7:89:F4:C8:A5:B9:FA:B4:F3:F1:CB:4B:3E:27:DB:86:40:08:DD:10:61:84:38:DA:13:19:AA:CB:6A
a=setup:active
a=mid:0
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=ice-ufrag:FBSD
a=ice-pwd:SGev2qbC+znDKrpKSd1VofGT
a=ice-options:trickle
a=fingerprint:sha-256 43:27:44:F7:89:F4:C8:A5:B9:FA:B4:F3:F1:CB:4B:3E:27:DB:86:40:08:DD:10:61:84:38:DA:13:19:AA:CB:6A
a=setup:active
a=mid:1
a=sctpmap:5000 webrtc-datachannel 1024

**Comment by Sean-Der** [comment]
It looks the TCP allocation is being generated properly at least!
```
a=candidate:foundation 1 udp 16777215 192.168.1.27 63923 typ relay raddr 192.168.1.64 rport 60705 generation 0
a=candidate:foundation 2 udp 16777215 192.168.1.27 63923 typ relay raddr 192.168.1.64 rport 60705 generation 0
```

Does Chrome have access to `192.168.1.27`? Can you try running `tcpdump -i any udp` on 192.168.1.27  and see if Chrome is properly attempting to send UDP traffic in.

**Comment by Sean-Der** [comment]
I am going to fix https://github.com/pion/ice/issues/118 (which will help the original issue) but I am not sure why things aren't working now :/

**Comment by nindolabs** [comment]
Chrome has access to `192.168.1.27`, i see it in coturn logs.
 I'll try this week using webrtc native api to see if it's related to pion or coturn or something else.

**Comment by Sean-Der** [comment]
Hey @nindolabs 

I have landed all the ICE improvements I have mentioned. If you use the latest master of `pion/webrtc` you will get everything. If you are still having issues please re-open! I would love to help you debug.

thanks

* [TLS and DTLS are now supported](https://github.com/pion/ice/commit/bf81fb51549b1492d3df583ca04ebbe8817b9e47)
* [ICE Gathering is fully async](https://github.com/pion/ice/commit/3e38db1ea52ce21b36f3dcc8895d85ac13d4aa66)
