### ISSUE TITLE
Adding PeerConnection.OnICEGatheringFinish event.

### ISSUE THREAD

**Issue by Jorropo** [pion/webrtc#1051]
## Summary

An event called once ICE gathering is finished.

## Motivation

The idea to be able to safely close the stream used to trickle when there no more ICE candidate to expect (my protocol wait for both nodes to finishing exchange, not only one).

## Describe alternatives you've considered

Registering OnICEGatheringStateChange and checking if state is completed, but that doesn't works or is not safe due to syncronisation issue.
The problem is OnICEGatheringStateChange is executed before OnICECandidate, so the best way I've found is creating a sync.Cond waiting in OnICEGatheringStateChange and broadcasting in OnICECandidate, but Cond are forgetable so if due to lack of enough cpu or context switch at the wrong time OnICECandidate may get executed before OnICEGatheringStateChange.

Its also not possible Lock or channels because Unlock an unlocked locks or closing a close channel panics and the number of OnICECandidate is unkown.

**Comment by Sean-Der** [comment]
I believe this is handled by `OnICECandidate` being called with a `nil` candidate. Taking to #1052 for further discussion.
