### ISSUE TITLE
Forward RTP packets to other tools (e.g. ffmpeg)

### ISSUE THREAD

**Issue by asticode** [pion/webrtc#1061]
Hey guys,

I'm having trouble forwarding RTP packets to ffmpeg and I wonder if you could point me to the right direction.

The whole WebRTC logic works very smoothly (your golang API is really nice btw) but ffmpeg doesn't seem to be able to parse the stream I'm trying to feed it.

I wonder if pion's RTP packets are forwardable at all...

I'm using [gortp](https://github.com/wernerd/GoRTP) to send RTP packets I'm receiving from `pion`.

Here's a sample code

```go
        // Create local addr
	var laddr *net.IPAddr
	if laddr, err = net.ResolveIPAddr("ip", "127.0.0.1"); err != nil {
		err = fmt.Errorf("main: creating local addr failed: %w", err)
		return
	}

	// Create a UDP transport with "local" address and use this for a "local" RTP session
	// The RTP session uses the transport to receive and send RTP packets to the remote peer.
	var tp *rtp.TransportUDP
	if tp, err = rtp.NewTransportUDP(laddr, 5000, ""); err != nil {
		err = fmt.Errorf("main: creating udp transport failed: %w", err)
		return
	}

	// TransportUDP implements TransportWrite and TransportRecv interfaces thus
	// use it to initialize the Session for both interfaces.
	rs := rtp.NewSession(tp, tp)

	// Add address of a remote peer (participant)
	if _, err = rs.AddRemote(&rtp.Address{
		CtrlPort: 5002 + 1,
		DataPort: 5002,
		IPAddr:   laddr.IP,
		Zone:     "",
	}); err != nil {
		err = fmt.Errorf("main: adding remote failed: %w", err)
		return
	}

	// Listen on transport
	if err = rs.ListenOnTransports(); err != nil {
		err = fmt.Errorf("main: listening on transports failed: %w", err)
		return
	}

	// Handle new track
	pc.OnTrack(func(track *webrtc.Track, receiver *webrtc.RTPReceiver) {
		// Send a PLI so that the publisher is pushing a keyframe every 2 seconds
		go func() {
			t := time.NewTicker(2 * time.Second)
			for range t.C {
				// Write rtcp
				if err := pc.WriteRTCP([]rtcp.Packet{&rtcp.PictureLossIndication{MediaSSRC: track.SSRC()}}); err != nil {
					shared.Logger.ErrorC(ctx, fmt.Errorf("main: writing rtcp failed: %w", err))
				}
			}
		}()

		// Loop
		var idx uint32
		var ss *rtp.SsrcStream
		for {
			// Read
			rp, err := track.ReadRTP()
			if err != nil {
				shared.Logger.ErrorC(ctx, fmt.Errorf("main: reading rtp  %s failed: %w", track.Kind(), err))
				return
			}

			// No stream
			if ss == nil {
				// Create a media stream.
				if idx, err = rs.NewSsrcStreamOut(&rtp.Address{
					CtrlPort: 5000 + 1,
					DataPort: 5000,
					IPAddr:   laddr.IP,
					Zone:     "",
				}, rp.SSRC, rp.SequenceNumber); err.Error() != "" {
					shared.Logger.ErrorC(ctx, fmt.Errorf("main: creating ssrc stream failed: %w", err))
					return
				}
				ss = rs.SsrcStreamOutForIndex(idx)
				ss.SetPayloadType(rp.PayloadType)
			}

			// Create packet
			wp := rs.NewDataPacketForStream(idx, rp.Timestamp)
			wp.SetPayload(rp.Payload)

			// Write packet
			if _, err = rs.WriteData(wp); err != nil {
				wp.FreePacket()
				shared.Logger.ErrorC(ctx, fmt.Errorf("main: writing packet failed: %w", err))
				return
			}
			wp.FreePacket()
		}
	})
```

I've tried all sort of `sdp` with `ffmpeg` but no luck. Here's my latest `sdp` if that helps:

```
v=0
o=- 1 1 IN IP4 127.0.0.1
s=Test
c=IN IP4 127.0.0.1
t=0 0
a=recvonly
m=video 5002 RTP 126
a=rtpmap:126 H264/90000
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
```

`ffmpeg` waits forever without doing anything, as if it wasn't receiving any stream at all.

If you have any idea how I can make this work, that would be awesome. Otherwise, if you feel this is not an issue with `pion`, feel free to close this issue.

Thanks in advance.
Cheers

**Comment by Sean-Der** [comment]
Hey @asticode, thanks for checking out Pion!

* Are you sure it is H264 only. Did you create a `MediaEngine` that only allows H264? OnTrack is only firing once?
* I would just forward the raw H264 packets. The following is pseudo code, but should work.
```
buf := make([]byte, 1500)
for {
    n, err := track.Read(buf)
    
    udpTransport.Write(buff[:n])
}
```

* I would try GStreamer, a little easier to debug. Then come back to ffmpeg when this is working.
```
// Pipeline that listens on port 5000, check that are even getting data
gst-launch-1.0 udpsrc port=5000 ! fakesink dump=true

// Are you getting valid H264 packets
gst-launch-1.0 udpsrc port=5000 ! application/x-rtp ! rtph264depay ! fakesink dump=true

// Decode and play them
gst-launch-1.0 udpsrc port=5000 ! application/x-rtp ! rtph264depay ! decodebin ! autovideosink
```

**Comment by Sean-Der** [comment]
@asticode If you are interested, it would also be SUPER helpful to have this an example application! `examples/rtp-forwarder` 

It would forward a single H264 stream, and then we could print out the H264 ffmpeg should use. I am happy to help as well, then would love to share what you built in Slack/Twitter. I bet this is a really common thing people are trying to build :)

**Comment by asticode** [comment]
@Sean-Der thanks a bunch for the suggestions, I managed to make it work by simply UDP forwarding raw packets as you suggested. You're a life saver!

However now I need to find a way to generate automatically the `sdp` I provide `ffmpeg` depending on what the user is sending. Here's how I see things:

- parse the offer which is a `SessionDescription` => is there an exported function to parse the offer `SDP` and get all streams/attributes/payload types/etc. ?
- add an `OnTrack` handler that checks the payload type of the first RTP packet and, based on the offer `SDP` parsed attributes, add the proper stream to the `SDP` I will provide `ffmpeg` => is there an exported function to create an `SDP` from scratch ?

I think that could work. Do you have other suggestions ?

I'm using the code in a private project therefore neither sharable or advertisable. However I'm using the open source [golang encoder](https://github.com/asticode/go-astiencoder) I've built on top of `libav` (`ffmpeg` libs), therefore if I strip all private stuff and create a simple example application, I would love to add a `examples/rtp-forwarder` 🙂 But first I need to fix the `sdp` generation 😄

**Comment by Sean-Der** [comment]
For parsing you could use the SDP library that `pion/webrtc` uses! [Unmarshal](https://pkg.go.dev/github.com/pion/sdp/v2?tab=doc#SessionDescription.Unmarsha)l I think this will be more of a pain though.

I would look at the first RTP packet in `OnTrack` and then generate it by hand. You can use [Marshal](https://pkg.go.dev/github.com/pion/sdp/v2?tab=doc#SessionDescription.Marshal) or just do a string with a bunch of format specifiers.

When you get the SDP generation done I think an example showing this off would be super powerful! 

Also if you need an example on your private project I am happy to help on [Slack](https://pion.ly/slack) or email sean @ pion.ly the more people that use Pion the better it gets :)
