### ISSUE TITLE
Is it possible to add media to a data channel peer connection?

### ISSUE THREAD

**Issue by darwayne** [pion/webrtc#1073]
Hey Guys,
I'm attempting to do the following:

### Flow
1. Setup a data channel that comes from browser
2. Use data channel as signaling
3. Add [perfect negotiation logic](https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/) on both sides.
   - of course can't use the `OnNegotationNeeded` event from the pion side since that isn't supported yet
4. Add an audio track from the browser to the existing peer connection
5. Optionally add additional tracks to existing peer connection from pion to the browser.

## Conclusion
1. I notice that when I get to step 4 track is never retrieved on the pion side.
    - When debugging it seems pion can 'see' that the track was added but discards it
         - maybe this is because I've only registered the ogg audio codec and the browser may have sent another type of audio codec? 🤷‍♂ 
1. So this makes me think I have to setup a separate peer connection for media?

**Comment by Sean-Der** [comment]
Hey @darwayne 

That should be possible! Did you add Transceivers on the receiver side? Every time you want to send something you need to add a Transceivers on the Pion side (or the browser side if Pion is sending)

**Comment by darwayne** [comment]
ahh thanks for the quick response @Sean-Der that may be the problem 🤔 I have an initial transceiver set on the pion side, but browser does not connect with transceiver set it adds it after the fact. think I will dig into this logic some more thanks for the tip!

**Comment by Sean-Der** [comment]
Of course! Always happy to help. I am also available on [Slack](https://pion.ly/slack) and will be faster responding (and you get a lot of other people).

You do need to add the transceiver before you do any signaling, or you can re-signal!

**Comment by Sean-Der** [comment]
I would also check out our `save-to-disk` and `play-from-disk` examples, those might be helpful! I am going to close this for now, but please re-open if there is a bug. 

Also if you have suggestions on how to make the library easier to use I would love to hear! Always trying to make things better.

thanks
