### ISSUE TITLE
pion offer contains "a=rtpmap:111 OPUS" not "a=rtpmap:111 opus"

### ISSUE THREAD

**Issue by chrbsg** [pion/webrtc#1078]
### Your environment.
  - Version: github.com/pion/webrtc/v2 v2.2.3
  - Browser: none
  - Other Information -

### What did you do?
Create an offer in pion

### What did you expect?
Offer to contain `a=rtpmap:111 opus/48000/2`. This was the case in pion-v2.1.19.

### What happened?
Offer had line `a=rtpmap:111 OPUS`.
I'm not sure if using uppercase OPUS is a real bug / incompatible with the specification, but it seems like an odd change, and   [RFC7587](https://tools.ietf.org/html/rfc7587) specifies lowercase:  `The media subtype ("opus") goes in SDP "a=rtpmap" as the encoding name.`

**Comment by Sean-Der** [comment]
This came from 20f2d1899ebbbdb3879444a03a7dc956a3b51126

I can downcase it though if it causing issues! As long as we don't break the case insensitive media matching, I don't care what we put in the SDP.

thanks for reporting, you do a great job of catching stuff :)
