### ISSUE TITLE
module declaration error

### ISSUE THREAD

**Issue by codenoid** [pion/webrtc#1082]
### Your environment.
  - Version: github master
  - Browser: -
  - Go Version: go version go1.14 linux/amd64

### What did you do?
I'm trying to install pion/webrtc with go.mod

### What did you expect?
successful go get

### What happened?

```bash
$ go get -u github.com/pion/webrtc
go: github.com/pion/webrtc upgrade => v1.2.0
go get: github.com/pion/webrtc@v1.2.0: parsing go.mod:
	module declares its path as: github.com/pions/webrtc
	        but was required as: github.com/pion/webrtc

$ go get -u github.com/pion/webrtc@2.2.0
go get github.com/pion/webrtc@2.2.0: github.com/pion/webrtc@2.2.0: invalid version: unknown revision 2.2.0
```

this is so confusing for novice like me, how can i get latest pion/webrtc from `go get` ?

**Comment by Sean-Der** [comment]
Hey @codenoid can you try doing `github.com/pion/webrtc/v2` 

We renamed from `pions` -> `pion` and unfortunately this broke our history. thanks!
