### ISSUE TITLE
How to use gstreamer webrtcdsp for noice,echo cancellation

### ISSUE THREAD

**Issue by pradeep538** [pion/webrtc#1084]
## Summary

One paragraph explanation of the feature.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome? Is this available in other implementations? Can this not be implemented using primitives?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered.

**Comment by Sean-Der** [comment]
Hey @pradeep538 

https://github.com/pion/example-webrtc-applications/tree/master/gstreamer-receive demonstrates how to playback media using GStreamer. You can modify this to insert `webrtcdsp`.

`pion/webrtc` just worries about transport. Media coding isn't something we will ever handle.

thanks for checking out Pion! If you have further questions I am also on [Slack](https://pion.ly/slack) and happy to help.

**Comment by pradeep538** [comment]
Thanks for the replay, 
Unbelievable ! got reply before i write the discription.
But I am novice in gstreamer it would be helpful if you provide an example

Thank You.

**Comment by Sean-Der** [comment]
Do you want to use those elements for sending or receiving? I can get an example together!

**Comment by Sean-Der** [comment]
Oh I see! Didn't noticed you edited the description :)

[webrtcdsp](https://gstreamer.freedesktop.org/documentation/webrtcdsp/webrtcdsp.html?gi-language=c) does have quite a few properties you can set. I don't have advice on what the best things to set are though :/

you can do that like `-audio-src "autoaudiosrc ! webrtcdsp experimental-agc =true"`

Does the microphone sound worse then if you had used your browser?

**Comment by pradeep538** [comment]
@Sean-Der Thanks again for the reply,
i was using gstreamer-send example.
I dint know that i need to use **experimental-agc =true**  I will try your suggestion and Actually am using [respeaker](http://wiki.seeedstudio.com/ReSpeaker_2_Mics_Pi_HAT/) module with a raspberry pi so I have to use pion with GStreamer to send camera feed and mic audio to peer, for peer am using flutter Android/IOS  from peer only audio will come back to pion(raspberry pi)
