### ISSUE TITLE
Setting Data Channel is Open

### ISSUE THREAD

**Issue by newzai** [pion/webrtc#1105]
- in PeerConnection , the data channel now is default open.  some time , I don't datachannel, 

I  want a  api to Close the data channel when CreateOffer or CreateAnswer

**Comment by Sean-Der** [comment]
Hey @newzai thanks for using Pion :)

I might be missing your question, but can you call [Close](https://pkg.go.dev/github.com/pion/webrtc/v2?tab=doc#DataChannel.Close) on the DataChannel?

**Comment by Sean-Der** [comment]
Hey @newzai hopefully this fixed your issue!

If you are still having problems feel free to re-open the issue. I am also available on [Slack](https://pion.ly/slack) if I can be helpful.

thanks
