### ISSUE TITLE
Regression: v2.2.x stuck in CookieWait.

### ISSUE THREAD

**Issue by edwinhayes** [pion/webrtc#1110]
### Your environment.
  - Version: v2.2.4 & v2.2.1 at least.
  - Browser: Safari 13, Chrome 80 

Upgrading from v2.1.0 to v2.2.x breaks my application.  

On Pion WebRTC v2.1.0, the app receives an offer via signalling, adds a single H264 video track, sends the answer back, then finds a connection (either relayed or locally) and starts playing video.

On v2.2.x, it sets up the connection, but then seems to get stuck about here:

```
DEBU[0576] [0xc0000ecdc0] state change: 'Closed' => 'CookieWait'  module=video.webrtc-helper.pion
DEBU[0576] [0xc0000ecdc0] sending INIT                   module=video.webrtc-helper.pion
DEBU[0576] [0xc0000ecdc0] readLoop entered               module=video.webrtc-helper.pion
DEBU[0576] [0xc0000ecdc0] writeLoop entered              module=video.webrtc-helper.pion
``` 

Just seems sending INIT over and offer.

Reverting to v2.1.0 immediately fixes the issue.

**Comment by Sean-Der** [comment]
Hey @edwinhayes 

Can you double check that you are not doing any PeerConnection modification after signaling?

Some applications were broken by re-negotiation. Because they were calling AddTrack/AddTranscevier before SetRemoteDescription. One of our examples had the same bug https://github.com/pion/webrtc/commit/8c7bd6670689d07a11a9893ce3cfc39f11aa8a77

**Comment by Sean-Der** [comment]
That message is for SCTP, so possibly could related! But seems unlikely.

**Comment by edwinhayes** [comment]
Hmm, yes, in both cases I was only adding the track after calling `SetRemoteDescription`, though before creating my answer.  If I change the order around then v2.2.4 works as well.

1. Why does this behaviour change between v2.1 and v2.2?
2. Why is this ordering important?  What does the addition of a track locally have to do with setting the remote description?

**Comment by Sean-Der** [comment]
Sorry missed this!

1.) `v2.2` added re-negotiation. So your list of Transceivers is tightly coupled with last call to the signaling APIs.

2.) So before we kept all our transceivers in a global list. If at anytime you got a new inbound track we would accept it if you had enough receivers. Now we have a list that is only updated for every call to `SetRemoteDescription`.

Please re-open if you think there is something we need to fix! But happy to continue answering questions, sorry for the rough edges :( maybe there is something better we can do here.
