### ISSUE TITLE
[FR] Support gomobile bind

### ISSUE THREAD

**Issue by rostopira** [pion/webrtc#1111]
## Summary

I want to use it in native iOS project as a library, however it seems to not be possible, cause usage of `byte` which is unsupported by gobind: https://github.com/golang/go/issues/31670

## Describe alternatives you've considered

Native WebRTC from chromium - is a total hell to build

## Additional context

Logs?
```
$ gomobile bind -target=ios .
gomobile: darwin-arm: go build -tags ios -buildmode=c-archive -o /var/folders/mm/lnxpsrln3nd4f73sksp2r16w0000gn/T/gomobile-work-629115133/webrtc-arm.a ./gobind failed: exit status 2
go: downloading golang.org/x/mobile v0.0.0-20200329125638-4c31acba0007
go: found github.com/pion/webrtc/v2 in github.com/pion/webrtc/v2 v2.0.0-00010101000000-000000000000
go: downloading github.com/pion/datachannel v1.4.16
go: downloading github.com/pion/sdp/v2 v2.3.4
go: downloading github.com/pion/srtp v1.3.1
go: downloading github.com/pion/rtp v1.3.2
go: downloading github.com/pion/logging v0.2.2
go: downloading github.com/pion/ice v0.7.10
go: downloading github.com/pion/sctp v1.7.6
go: downloading github.com/pion/dtls/v2 v2.0.0-rc.9
go: downloading github.com/pion/transport v0.10.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/pion/rtcp v1.2.1
go: downloading github.com/pion/mdns v0.0.4
go: downloading golang.org/x/net v0.0.0-20200301022130-244492dfa37a
go: downloading github.com/pion/stun v0.3.3
go: downloading github.com/pion/turn/v2 v2.0.3
go: downloading golang.org/x/crypto v0.0.0-20200221231518-2aa609cf4a9d
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: downloading golang.org/x/sys v0.0.0-20190412213103-97732733099d
# gobind/gobind
In file included from Webrtc_darwin.m:9:
gobind/Webrtc.objc.h:442:23: error: unknown type name 'byte'; did you mean 'Byte'?
/Applications/Xcode-11-4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/usr/include/MacTypes.h:687:41: note: 'Byte' declared here
In file included from Webrtc_darwin.m:9:
gobind/Webrtc.objc.h:1211:4: error: expected a type
gobind/Webrtc.objc.h:1631:23: error: unknown type name 'byte'; did you mean 'Byte'?
/Applications/Xcode-11-4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/usr/include/MacTypes.h:687:41: note: 'Byte' declared here
In file included from Webrtc_darwin.m:9:
gobind/Webrtc.objc.h:1668:23: error: unknown type name 'byte'; did you mean 'Byte'?
/Applications/Xcode-11-4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/usr/include/MacTypes.h:687:41: note: 'Byte' declared here
In file included from Webrtc_darwin.m:9:
gobind/Webrtc.objc.h:2289:4: error: expected a type
Webrtc_darwin.m:716:4: error: expected a type
Webrtc_darwin.m:723:34: error: expected a type
Webrtc_darwin.m:719:2: error: unknown type name 'byte'; did you mean 'Byte'?
/Applications/Xcode-11-4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/usr/include/MacTypes.h:687:41: note: 'Byte' declared here
Webrtc_darwin.m:719:14: error: use of undeclared identifier 'byte'
Webrtc_darwin.m:720:9: error: implicit conversion of 'Byte' (aka 'unsigned char') to 'id' is disallowed with ARC
Webrtc_darwin.m:720:9: error: incompatible integer to pointer conversion returning 'Byte' (aka 'unsigned char') from a function with result type 'id' [-Werror,-Wint-conversion]
Webrtc_darwin.m:716:1: error: conflicting return type in implementation of 'iceCandidatePoolSize': 'Byte' (aka 'unsigned char') vs 'id' [-Werror,-Wmismatched-return-types]
gobind/Webrtc.objc.h:442:28: note: previous definition is here
Webrtc_darwin.m:2353:4: error: expected a type
Webrtc_darwin.m:2363:2: error: unknown type name 'byte'; did you mean 'Byte'?
/Applications/Xcode-11-4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/usr/include/MacTypes.h:687:41: note: 'Byte' declared here
Webrtc_darwin.m:2363:17: error: use of undeclared identifier 'byte'
Webrtc_darwin.m:2364:9: error: implicit conversion of 'Byte' (aka 'unsigned char') to 'id' is disallowed with ARC
Webrtc_darwin.m:2364:9: error: incompatible integer to pointer conversion returning 'Byte' (aka 'unsigned char') from a function with result type 'id' [-Werror,-Wint-conversion]
Webrtc_darwin.m:3166:4: error: expected a type
Webrtc_darwin.m:3173:25: error: expected a type
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by Sean-Der** [comment]
Oof that is a pain :/

This sounds like something we should get involved and fix upstream? We pretty extensively use byte across all our packages. Would it be possible to write a shim API on your side, and then we can cast internally?

I have never use gomobile, so not really familiar and don't have a Mac to test myself :( I can get something going in QEMU/VirtualBox though!

**Comment by Sean-Der** [comment]
But this is a use case that is super promising! Especially for DataChannels. There are other users that are doing mobile though, not sure how though?

**Comment by rostopira** [comment]
I'm not familiar with go, actually, just thought it would be easier to build and add some Obj-C code via gobind than build from googlesource.

> Would it be possible to write a shim API on your side, and then we can cast internally?
Yeah, maybe, but I'm not sure it will worth it. I thought, maybe there is an easier solution, will try few ideas

**Comment by alinz** [comment]
I've been using this project inside my side project, and it seems working pretty fine, what I have done to compile it is directly compile it to framework. 

Here's the command that I've been using inside a package that I want build for ios

```
gomobile bind -target=ios -ldflags="-s -w" -v -o WebRTC.framework .
```

**Comment by rostopira** [comment]
@alinz thanks, I think, this closes the issue
Just in case, maybe you know how to create framework for tvOS/watchOS ?

**Comment by shushenghong** [comment]
> @rostopira, I've been using this project inside my side project, and it seems working pretty fine, what I have done to compile it is directly compile it to framework.
> 
> Here's the command that I've been using inside a package that I want build for ios
> 
> ```
> gomobile bind -target=ios -ldflags="-s -w" -v -o WebRTC.framework .
> ```

i tried the lastest pion code and gomobile bind to build android/ios library, it all failed, any help?

**Comment by leonidas002** [comment]
i also get errors when using "gomobile bind -target=ios -ldflags="-s -w" -v -o WebRTC.framework ."

In file included from Webrtc_darwin.m:9:
gobind/Webrtc.objc.h:225:67: error: cannot find protocol definition for 'WebrtcStats' [-Werror]
gobind/Webrtc.objc.h:86:11: note: protocol 'WebrtcStats' has no definition
gobind/Webrtc.objc.h:276:68: error: cannot find protocol definition for 'WebrtcStats' [-Werror]
gobind/Webrtc.objc.h:86:11: note: protocol 'WebrtcStats' has no definition
gobind/Webrtc.objc.h:359:66: error: cannot find protocol definition for 'WebrtcStats' [-Werror]
gobind/Webrtc.objc.h:86:11: note: protocol 'WebrtcStats' has no definition
gobind/Webrtc.objc.h:445:66: error: cannot find protocol definition for 'WebrtcStats' [-Werror]
gobind/Webrtc.objc.h:86:11: note: protocol 'WebrtcStats' has no definition
gobind/Webrtc.objc.h:547:66: error: cannot find protocol definition for 'WebrtcStats' [-Werror]
gobind/Webrtc.objc.h:86:11: note: protocol 'WebrtcStats' has no definition
gobind/Webrtc.objc.h:587:60: error: cannot find protocol definition for 'WebrtcStats' [-Werror]
gobind/Webrtc.objc.h:86:11: note: protocol 'WebrtcStats' has no definition
gobind/Webrtc.objc.h:621:23: error: unknown type name 'byte'; did you mean 'Byte'?
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk/usr/include/MacTypes.h:687:41: note: 'Byte' declared here
In file included from Webrtc_darwin.m:9:
gobind/Webrtc.objc.h:666:23: error: unknown type name 'byte'; did you mean 'Byte'?
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk/usr/include/MacTypes.h:687:41: note: 'Byte' declared here

what is wrong? @rostopira @alinz  thanks!
