### ISSUE TITLE
Question: audio RTP broadcasting breaks safari

### ISSUE THREAD

**Issue by fletcherist** [pion/webrtc#1112]
### Your environment.
  - Version: v2.2.3
  - Browser: Chrome 71, Safari 13.1

### What did you do?
Heya! I'm trying to implement many-to-many open-source voice chat like Discord. My current approach is to broadcast incoming RTP packets to all other clients. Here's an implementation
```golang
for {
	rtpPacket, readErr := remoteTrack.ReadRTP()
	if readErr != nil {
		panic(readErr)
	}
	for _, roomUser := range users {
		// dont send rtp packets to current user
		if roomUser.ID == currentUser.ID {
			continue
		}
                // Track is *webrtc.Track
		if writeErr := roomUser.Track.WriteRTP(rtpPacket); writeErr != nil && writeErr != io.ErrClosedPipe {
			panic(writeErr)
		}
	}
}
```
It works fine in Chrome for many simultaneous connections, however it breaks Safari (no audio, microphone works). Hence I tried yet another approach from [pion reflect example](https://github.com/pion/webrtc/blob/master/examples/reflect/main.go#L96), where rtp.SSRC of the packet is being replaced to receiver's SSRC. Something like this:
```golang
for _, roomUser := range users {
	// dont send rtp packets to current user
	if roomUser.ID == currentUser.ID {
		continue
	}
	rtpPacket.SSRC = roomUser.Track.SSRC()
	if writeErr := roomUser.Track.WriteRTP(rtpPacket); writeErr != nil && writeErr != io.ErrClosedPipe {
		panic(writeErr)
	}
}
```
it seems to be working in Safari, but when it's more than 2 simultaneous connections, it produces some strange bugs (for example, the third client does hear the second, but doesn't hear the first and so on)

Could you please explain me, at what point am I going wrong?
I've also found out, that the thing I'm trying to implement is called [RTP Mixer](http://www.siptutorial.net/RTP/mixer.html) according to spec. Is that really so? Thank you in advance

![mixer](https://user-images.githubusercontent.com/15146860/77919643-1e7f0580-72a6-11ea-83bc-0463b067aca4.gif)

**Comment by at-wat** [comment]
> Hence I tried yet another approach from pion reflect example, where rtp.SSRC of the packet is being replaced to receiver's SSRC. Something like this:

The audio stream is encoded usually by OPUS codec in WebRTC.  Each frame of the stream has specific frame duration for example 20ms.
So, if multiple RTP streams are simply multiplexed using single SSRC like your example, there is too many duration of the audio signal more than realtime. (for example 40ms of the signal arrives per 20ms; it can't be played correctly.)

> I'm trying to implement is called RTP Mixer according to spec. Is that really so?

As the input audio streams are encoded, the mixer can be implemented as decoders for each input (OPUS data to raw audio signal), an audio mixer (sum of multiple raw audio signals), and an encoder (raw audio to OPUS data).
RTP format just only provides CC(CSRC Count) and CSRC fields in RTP header. These fields can embed all (up to 16) original SSRCs into mixed RTP packet. (not mandatory for applications in most case.)
Actual audio mixer is not a feature of RTP protocol; it should be implemented in the application.

**Comment by at-wat** [comment]
FYI, in https://github.com/pion/mediadevices, we use Go wrapper of libopus https://github.com/lherman-cs/opus (fork of https://github.com/hraban/opus).

https://github.com/pion/mediadevices/blob/master/pkg/codec/opus/opus.go
This code only uses the encoder, but using the decoder is also very easy.

**Comment by fletcherist** [comment]
@at-wat thank you for clear explanation! now it's clear to me what's the matter with safari)

By the way, what do you think is it a good idea if i will add/delete new audio tracks dynamically with renegotiation as user join/leave and handle audio mixing on the client side by using Web Audio API?

**Comment by fletcherist** [comment]
> https://github.com/pion/mediadevices/blob/master/pkg/codec/opus/opus.go
This code only uses the encoder, but using the decoder is also very easy.

wow thanks will dive into it right now

**Comment by at-wat** [comment]
> By the way, what do you think is it a good idea if i will add/delete new audio tracks dynamically with renegotiation as user join/leave and handle audio mixing on the client side by using Web Audio API?

I think it depends on your system structure (with server or server-less) and the number of the maximum users.

Mixer implementation is simillar to WebRTC SFU. The simplest implementation may need a server machine (or cloud instance) at somewhere.
(It maybe possible to select one of the participants and make that one server, but the system will be complex and handling on the leaving of host peer is also complicated.)

If the maximum number of users in one room is not so large, client side mixing also makes sense to me. Implementation can be simple compared to the mixer.

**Comment by fletcherist** [comment]
thanks a lot for help! will try implement MCU pattern then. will close this for now!
