### ISSUE TITLE
can not install 

### ISSUE THREAD

**Issue by sorushsaghari** [pion/webrtc#1117]
### Your environment.
  - Version: *Linux 5.3.0-45-generic #37-Ubuntu SMP Thu Mar 26 20:41:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Li
go version go1.14 linux/amd64

*
  - Browser: *include version*
  - Other Information - *go: github.com/pion/webrtc upgrade => v1.2.0
go get: github.com/pion/webrtc@v1.2.0: parsing go.mod:
	module declares its path as: github.com/pions/webrtc
	        but was required as: github.com/pion/webrtc
*

### What did you do?

go get github.com/pion/webrtc
### What did you expect?
package to be installed
### What happened?
go: github.com/pion/webrtc upgrade => v1.2.0
go get: github.com/pion/webrtc@v1.2.0: parsing go.mod:
	module declares its path as: github.com/pions/webrtc
	        but was required as: github.com/pion/webrtc

**Comment by longsleep** [comment]
You probably want v2.

So try `go get github.com/pion/webrtc/v2`

**Comment by sorushsaghari** [comment]
> You probably want v2.
> 
> So try `go get github.com/pion/webrtc/v2`

could you please ad it into documentation
