### ISSUE TITLE
webrtc neteq and bitrate controller

### ISSUE THREAD

**Issue by AVFoundation** [pion/webrtc#1139]
## Summary

the neteq and bitrate controller 

## Motivation

I wanna use the pion to replace the c++ webrtc library, but I don't see any code about the bitrate controller or neteq module. Do you have any plans about that?

**Comment by Sean-Der** [comment]
@AVFoundation Right now users implement it themselves, you can see it in `pion/ion` 

I do have plans to add a JitterBuffer and Congestion Control itself to the library, but we need to make it opt-in. I have started to write about this [here](https://github.com/pion/webrtc/wiki/PlanningV3) and [here](https://github.com/pion/webrtc/wiki/MediaAPI).

For many users bitrate controller doesn't make sense, and we also need to make sure people can have full control of the neteq. I will probably be taking more inspiration from GStreamer vs Google's library. 

If you are interested in contributing we would love your help!

**Comment by AVFoundation** [comment]
thank u
