### ISSUE TITLE
pc.LocalDescription() does not contain "a=candidate"

### ISSUE THREAD

**Issue by enobufs** [pion/webrtc#1143]
### Your environment.
  - Version: v2.2.0 (ice v0.7.8)

### What did you do?
Investigating an issue with connectivity between two pion nodes began occurring after I enabled trickle ICE with pion to avoid pc.CreateOffer() and pc.CreateAnswer() blocking calls.

For compatibility with the remote side (non-trickled) implementaton, actual SDP is not "trickling", but wait for nil from OnICECandidate() callback, then finally generate offer or answer SDP by calling pc.LocalDescription(). 

### What did you expect?
Both answer SDP and offer SDP have correct information including "a=candidate" lines.

### What happened?
The answer SDP returned by pc.LocalCandidate() method after seeing nil from OnICECandidate(), do not contain "a=candidate" lines.

Here's what I am seeing in my log on "answer" side pion:
```
session INFO: 2020/04/16 13:14:51 ICE connection state has changed: checking
session INFO: 2020/04/16 13:14:51 signaling state has changed: stable
session DEBUG: 13:14:51.073970 session.go:1012: onICECandidate: host 10.0.0.135:56086
session DEBUG: 13:14:51.118593 session.go:1012: onICECandidate: srflx 98.207.205.254:65515 related 0.0.0.0:65515
session DEBUG: 13:14:51.158072 session.go:1012: onICECandidate: srflx 2601:646:c202:12d0:a905:8518:475:c66e:65516 related :::65516
session DEBUG: 13:14:51.158141 session.go:1012: onICECandidate: <nil>
signaling DEBUG: 13:14:51.158200 signaling.go:169: signal sent: from=server to=client
signaling DEBUG: 13:14:51.158209 signaling.go:170: signal sent: body={"type":"answer","sdp":"v=0\r\no=- 612196598 1587068091 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 5E:97:A7:95:DE:9D:8E:08:18:05:28:90:C3:2C:AA:EF:F9:08:C8:FE:FD:4A:DE:C2:BA:20:AF:7D:01:18:9A:49\r\na=group:BUNDLE 0\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=setup:passive\r\na=mid:0\r\na=sendrecv\r\na=sctpmap:5000 webrtc-datachannel 1024\r\na=ice-ufrag:vrbfDMmePWHnTbaz\r\na=ice-pwd:QQctwMWemwgzDhfCyHiHCuVRlvbsFpbB\r\n"}
```

Offer side SDP has the candidate lines correct.

**Comment by Sean-Der** [comment]
This is super easy to fix!

https://github.com/pion/webrtc/blob/master/peerconnection.go#L712 just needs to include a call to `populateLocalCandidates` like [this]( https://github.com/pion/webrtc/blob/bd6c5cbc71fc401eac3cd158c97586a79f92d34e/peerconnection.go#L1457)

**Comment by Sean-Der** [comment]
I can fix this tonight! (not on a computer with any Go dev stuff right now) also happy to approve a PR right away :)

**Comment by enobufs** [comment]
Oh great - let me see if I can find time tonight. If so, I will ping you!

**Comment by enobufs** [comment]
@Sean-Der @at-wat 
Let me reopen this issue until the issue I am seeing at the current master head with the above fixes:

With my test, nil pointer dereferencing is happening during the pc.LocalDescription() call:
```
session DEBUG: 15:40:47.065178 session.go:1016: onICECandidate: <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1355edc]

goroutine 114 [running]:
github.com/pion/webrtc/v2.populateLocalCandidates(0xc0002ccf20, 0x0, 0xc0000c8580, 0x3, 0x0)
	/Users/ytakeda/go_ws/pkg/mod/github.com/pion/webrtc/v2@v2.2.6-0.20200418081652-0ab1ac9055fc/sdp.go:181 +0x8c
github.com/pion/webrtc/v2.(*PeerConnection).CurrentLocalDescription(0xc0000a2340, 0x0)
	/Users/ytakeda/go_ws/pkg/mod/github.com/pion/webrtc/v2@v2.2.6-0.20200418081652-0ab1ac9055fc/peerconnection.go:1449 +0x6e
github.com/pion/webrtc/v2.(*PeerConnection).LocalDescription(0xc0000a2340, 0x153c0ed)
	/Users/ytakeda/go_ws/pkg/mod/github.com/pion/webrtc/v2@v2.2.6-0.20200418081652-0ab1ac9055fc/peerconnection.go:712 +0x52
github.com/SpeechGraphics/sgnp-rtc/session.(*Session).onICECandidate(0xc000386000, 0x0)
	/Users/ytakeda/Projects/SpeechGraphics/sgnp-rtc/session/session.go:1018 +0x132
github.com/pion/webrtc/v2.(*ICEGatherer).Gather.func2(0x0, 0x0)
	/Users/ytakeda/go_ws/pkg/mod/github.com/pion/webrtc/v2@v2.2.6-0.20200418081652-0ab1ac9055fc/icegatherer.go:166 +0x271
github.com/pion/ice.(*Agent).gatherCandidates.func1(0xc00043c000)
	/Users/ytakeda/go_ws/pkg/mod/github.com/pion/ice@v0.7.12/gather.go:84 +0x132
created by github.com/pion/ice.(*Agent).gatherCandidates
	/Users/ytakeda/go_ws/pkg/mod/github.com/pion/ice@v0.7.12/gather.go:77 +0xb9
exit status 2
```

As I described in the issue:
* The issue is happening at the answerer.
Trickle ICE is enabled
* Waiting for nil to return from OnICECandidate() callback.
* When it sees OnICECandidate() callback is made with nil candidate, it will call pc.LocalDescription().

**Comment by Sean-Der** [comment]
Merged!
