### ISSUE TITLE
data-channels source problem

### ISSUE THREAD

**Issue by mrostamii** [pion/webrtc#1145]
Environment:
  - Version: go version go1.14.1 windows/amd64

I was going to test the pion data-channel but I realized that the source you mentioned [here](https://github.com/pion/webrtc/tree/master/examples/data-channels) has corrupted.  

I have tried:
```
PS E:\go\src> go get github.com/pion/webrtc/v2/examples/data-channels
package github.com/pion/webrtc/v2/examples/data-channels: cannot find package "github.com/pion/webrtc/v2/examples/data-channels" in any of:
        C:\Go\src\github.com\pion\webrtc\v2\examples\data-channels (from $GOROOT)
        E:\go\src\github.com\pion\webrtc\v2\examples\data-channels (from $GOPATH)
```

After that, I checked "[github.com/pion/webrtc/v2/examples/data-channels](github.com/pion/webrtc/v2/examples/data-channels)" then deduced there is a problem with the source. 

Am I right? Or, there is a problem with my environment?

**Comment by Sean-Der** [comment]
Hey @mrostamii 

I had the same issue until I set `export GO111MODULE=on` then it worked! If you are interested it would be really helpful if you could open a PR and put `GO111MODULE=on go get github.com/pion/webrtc/v2/examples/data-channels` in all the READMEs :)

**Comment by mrostamii** [comment]
Thank you. I got through the problem.  

The `GO111MODULE=on` isn't recognized by PS on windows, however, it has worked on my Linux box.
