### ISSUE TITLE
Question: Get AV data from server

### ISSUE THREAD

**Issue by moneyzmey** [pion/webrtc#1151]
Could you give some advice how to get AV sequence, metadata and audio video packets from server.

**Comment by Sean-Der** [comment]
@moneyzmey You probably want something like `examples/play-from-disk`

What server do you have in mind? In `example-webrtc-applications` we show how to connect to Janus and could add more. `pion/webrtc` is a just a WebRTC implementation, so if you can get an SDP we can pull anything you want.

I would join [Slack](https://pion.ly/slack) if you have more ad-hoc questions! Happy to help there also.
