### ISSUE TITLE
SetRemoteDescription when renegotiation causes deadlock

### ISSUE THREAD

**Issue by cedricfung** [pion/webrtc#1157]
### Your environment.
  - Version: *234a170*
  - Browser: *Firefox 75.0*

### What did you do?

1. Firefox send an offer with an audio track
2. Pion: pc = NewPeerConnection => SetRemote(offer) => OnSignalingStateChange(have-remote-offer)
3. Pion: OnICEConnectionStateChange(checking)
4. Pion: CreateAnswer => SetLocal(answer) => OnSignalingStateChange(stable)
5. Pion: new audio track => pc.AddTrack
6. Pion: CreateOffer => SetLocal(offer) => OnSignalingStateChange(have-local-offer)
7. Firefox: SetRemote(offer) => CreateAnswer
8. Pion: SetRemote(answer) => OnSignalingStateChange(stable)

But the SetRemoteDescription blocks now, won't continue.

Then I read the code and find 
```
	if haveRemoteDescription {
		pc.startRenegotation(currentTransceivers)
```

so it must be startRenegotation blocks. I have removed `pc.startSCTP()` to prevent datachannel lock. If I don't remove the SCTP code, then it will always deadlock, and now it only have random deadlocks. 

### What did you expect?

renegotiate successfully

### What happened?

pc.startRenegotation(currentTransceivers) blocks

**Comment by Sean-Der** [comment]
@cedricfung I will get this fixed today! This is a bug though, we shouldn't create a SCTP Association unless the other side requested it.

**Comment by cedricfung** [comment]
After many tests, there are still deadlocks. The clients has enabled datachannel.

**Comment by cedricfung** [comment]
The deadlock seems occur in this oder:

1. browser offer audio track and datachannel to pion
2. pion answer
3. browser setremote(pion.answer)
4. signal state stable
5. pion offer another audio track to browser
6. browser answer
7. pion setremote(browser.answer)

The pion SetRemoteDescription will block forever now. And in this procedure, no OnTrack event yet. That said, browser offers audio, and signal state stable, no ontrack event yet, then pion offer a new track to browser.

**Comment by Defman21** [comment]
I got it working somehow.

1. browser: addTrack(...), createOffer() => setLocalDescription() => pass to Pion
2. pion: receive offer, setRemoteDescription(offer), createAnswer() => setLocalDescription() => pass to browser
3. browser: accept answer, setRemoteDescription()

Some time passes, a new track appears and it needs to be added, so:

1. pion: peer.AddTrack(...), createOffer() => setLocalDescription() => pass to browser
2. browser: accept offer, setRemoteDescription(offer), createAnswer() => setLocalDescription() => pass to pion
3. pion: accept answer, setRemoteDescription(...)

No deadlocks.

**Comment by Sean-Der** [comment]
Hey @Defman21 

The issue is that we don't allow a second `SetRemoteDesc` until the first one completes. The first one may never complete if connectivity isn't established.

@at-wat What do you think of these two solutions? I haven't thought about it deeply yet though, just realized this was an issue today! 

* Queue `SetRemoteDescription` calls so that the call is non-blocking
* Return an error if another one is in flight
* Cancel previous `SetRemoteDescription` call
* ?


I will add a failing test (and work on fixing)

**Comment by at-wat** [comment]
> The issue is that we don't allow a second `SetRemoteDesc` until the first one completes. The first one may never complete if connectivity isn't established.

How the browsers handle this case?
Doing similar to the browsers would be better.

**Comment by jeremija** [comment]
I'm working on #1191 and I ran into this issue. The webrtc spec says that a RTCPeerConnection should have a an operations chain: https://w3c.github.io/webrtc-pc/#chain-an-asynchronous-operation

So looks like the right thing to do is to queue asynchronous operations.
