### ISSUE TITLE
Is it possible to add tracks on the fly?

### ISSUE THREAD

**Issue by Defman21** [pion/webrtc#1160]
For example, after a client established a peer connection with me, I'd want to add different tracks with different ids but the same label over time (so I'd accept its offer, set it as remote, add a single track, create an answer and send it back to the client, THEN I want to add another track). Looks like I have to somehow fire the `negotiationneeded` event, but I'm not sure how. Or should I just re-send the answer to the client so it would re-establish p2p connection with me?

**Comment by Sean-Der** [comment]
Hey @Defman21!

Yes this is possible, a good example of this is [play-from-disk-renegotation](https://github.com/pion/webrtc/tree/master/examples/play-from-disk-renegotation)

You don't need to fire the `negotiationneeded` you just need to re-signal. That event is just a suggestion that you should re-signal. We do plan on adding it in the future though! https://github.com/pion/webrtc/issues/817

I am also happy to answer questions in [Slack](https://pion.ly/slack) we are trying to build a welcoming/helpful community so happy to answer any other questions you have :)

**Comment by Defman21** [comment]
This example shows a demo when the browser creates an offer. I guess it should be the same if I want to do that from the pion side? So something like this should happen whenever I add a track?

1. pion: Add a track.
2. pion: create an offer.
2.1. pion: set as local description
3. pion: send the offer.
4. web: accept the offer.
4.1. web: set it as remote description.
5. web: create an answer
6. send the answer to pion.
7. pion: accept the answer.
7.1. pion: set it as remote description.

**Comment by Defman21** [comment]
Okay I figured it out, I'm hitting a deadlock as well: #1157

**Comment by Sean-Der** [comment]
@Defman21 I will get that fixed ASAP, sorry about that :( at the latest this weekend it will be done.

For the time being you could do something like [this](https://github.com/peer-calls/peer-calls/blob/baa099c173d10371e5a454c7df15c7a3c905c20b/src/server/wrtc/negotiator/negotiator.go#L89-L93) and handle this outside the PeerConnection.

**Comment by Defman21** [comment]
No worries, thanks for your library! I've found a workaround and described it in #1157 (do not offer any streams immediately, first create a datachannel then offer media and stuff), so I'll wait for the fix.

**Comment by Sean-Der** [comment]
Hi @AndreyMashukov check out https://github.com/pion/webrtc/tree/master/examples/play-from-disk-renegotiation that adds/removes tracks from an already negotiated PeerConnection
