### ISSUE TITLE
RTP streams should be started from SetLocalDescription when an answer is being set (not from SetRemoteDescription when an offer is being set)

### ISSUE THREAD

**Issue by jeremija** [pion/webrtc#1191]
### Your environment.
  - Version: 2.2.9
  - Browser: N/A/

### What did you do?

I tried to add a test for `OnTrack` after renegotiation in my application, but the `OnTrack` callback is sometimes not called because the sender is not added to `track.activeSenders` after renegotiation.

The test case I have in my app is available here: https://github.com/peer-calls/peer-calls/tree/ontrack-test

Link to specific commit in case the branch gets deleted in the future: https://github.com/peer-calls/peer-calls/commit/be3f19159e82f1697b0732b68df00ff1d371900b

Command to run the test:

```sh
git cloone https://github.com/peer-calls/peer-calls
cd peer-calls
PEERCALLS_LOG='-sdp,-pion:*:trace,-pion:*:debug,-pion:*:info,-signaller,negotiator,*' go test ./server -v -run TestSFU_OnTrack -race -count=20
```

The tests fail about 50% of the time, hence the `-count` flag.

**UPDATE: the PR now has a test too**

### What did you expect?

I was expecting the `OnTrack` handler to be called, but sometimes it is not.

### What happened?

In my app this particular peer has to request negotiation from the server after the track is added. The problem occurs when the server sends the offer, and the `pc.startRenegotiation` is called before the `sender.setNegotiated` is called, so the sender is never added to `track.activeSenders`, and thus `track.WriteSample` does not write to the expected sender.

**Comment by sgotti** [comment]
> The problem occurs when the server sends the offer, and the `pc.startRenegotiation` is called before the `sender.setNegotiated` is called, so the sender is never added to `track.activeSenders`, and thus `track.WriteSample` does not write to the expected sender.

@jeremija Sorry but I'm not sure I understand the issue you're describing. If pion is offering then we have to call setRemoteDescription when receiving an answer and so `sender.setNegotiated` has already been called. Instead if we're receiving an offer we can't offer anything else so there's no need to start a sender.
