### ISSUE TITLE
peerconnection stuck at pc.sctpTransport.Start

### ISSUE THREAD

**Issue by cnderrauber** [pion/webrtc#1194]
### Your environment.
  - Version: v2.2.9
  - Browser: ios native
  - Other Information - 
stacktrace:

  Goroutine 103 - User: /home/go/pkg/mod/github.com/pion/sctp@v1.7.6/association.go:220 github.com/pion/sctp.Client (0x61fd3b)
        0  0x0000000000431410 in runtime.gopark
            at /usr/local/go/src/runtime/proc.go:305
        1  0x000000000044025b in runtime.selectgo
            at /usr/local/go/src/runtime/select.go:313
        2  0x000000000061fd3b in github.com/pion/sctp.Client
            at /home/go/pkg/mod/github.com/pion/sctp@v1.7.6/association.go:220
        3  0x00000000007d48ef in github.com/pion/webrtc/v2.(*SCTPTransport).Start
            at /home/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.9/sctptransport.go:95
        4  0x00000000007cafcf in github.com/pion/webrtc/v2.(*PeerConnection).startSCTP
            at /home/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.9/peerconnection.go:992
        5  0x00000000007e22f2 in github.com/pion/webrtc/v2.(*PeerConnection).startTransports.func1
            at /home/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.9/peerconnection.go:1689
        6  0x000000000045c6b1 in runtime.goexit
            at /usr/local/go/src/runtime/asm_amd64.s:1357

Goroutine 139 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x440b27)
        0  0x0000000000431410 in runtime.gopark
            at /usr/local/go/src/runtime/proc.go:305
        1  0x0000000000440dc0 in runtime.goparkunlock
            at /usr/local/go/src/runtime/proc.go:310
        2  0x0000000000440dc0 in runtime.semacquire1
            at /usr/local/go/src/runtime/sema.go:144
        3  0x0000000000440b27 in sync.runtime_SemacquireMutex
            at /usr/local/go/src/runtime/sema.go:71
        4  0x00000000004788fc in sync.(*Mutex).lockSlow
            at /usr/local/go/src/sync/mutex.go:138
        5  0x00000000007cea97 in sync.(*Mutex).Lock
            at /usr/local/go/src/sync/mutex.go:81
        6  0x00000000007cea97 in github.com/pion/webrtc/v2.(*PeerConnection).startRenegotation
            at /home/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.9/peerconnection.go:1694
        7  0x00000000007c92e1 in github.com/pion/webrtc/v2.(*PeerConnection).SetRemoteDescription
            at /home/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.9/peerconnection.go:822
### What did you do?
First ,use ios native webrtc to create offer without datachannel. so there is no m=application sctp in offer sdp.  Then pion's peerconnection create answer sdp and set to pc, the peerconnection will hold pc.negotiationLock, go to startSCTP and wait sctp.Client to complete handshake, then it's stucked because client has no sctp in sdp.(stacktrace Goroutine 103)

Second, client's media track changed, then go to pc.startRengotiation, but pc.negotiationLock is hold by First, then it's stucked, (stacktrace Goroutine 139).

In step First if I add datachannel to client peerconnection, there is no problem.

And in pion@v2.2.3, there is no problem in this situation, because there is no lock in negotiation process. 

### What did you expect?
Pion can work as v2.2.3 when client has no datachannel in sdp.

### What happened?
Renegotiation process stucked, because lock is held to wait sctp.Client handshake complete.

**Comment by Sean-Der** [comment]
Sorry for the delay on this but https://github.com/pion/webrtc/pull/1161 should be the fix for this!

I am going to add tests and merge before the weekend is over.

**Comment by Sean-Der** [comment]
Hey @cnderrauber this is fixed by f78334d9d4cb163b7280be77c848aacca168d0e6

Thanks for using Pion!
