### ISSUE TITLE
How to live stream video from browser to Golang server to Other people?

### ISSUE THREAD

**Issue by cyantarek** [pion/webrtc#1202]
I want to make a system that will monitor and record live streaming videos.

So, I want to start capturing video from browser, browser webrtc will send raw video data to a Golang webrtc backend server and this golang server will record videos to file as well as stream to other subscribed users.

**Comment by r-novel** [comment]
Hey, @cyantarek 

What kind of video do you want to send to the WebRTC server? From a web camera or external source (HLS, DASH, File)?

Anyway, you could follow the examples described below:
https://github.com/pion/webrtc/tree/master/examples/broadcast
https://github.com/pion/example-webrtc-applications/tree/master/save-to-webm
Try to combine them and make what you want.

**Comment by cyantarek** [comment]
Hi, I want like this: user -> browser -> web cam -> webrtc -> sends video data -> backend server -> records/analyzes data -> broadcasts to others

**Comment by Sean-Der** [comment]
@cyantarek I think broadcast does exactly what you are looking for! It allows one person to upload, and then fans out. [Here](https://github.com/pion/webrtc/blob/master/examples/broadcast/main.go#L85) is where we read the video, you could analyze it as you wish.

https://github.com/pion/example-webrtc-applications/tree/master/gocv-receive demonstrates how to use OpenCV with Pion if you want to analyze the video in the same Go process.

**Comment by cyantarek** [comment]
@Sean-Der , when I copy and paste browser session description to golang terminal, I got this error:

`panic: illegal base64 data at input byte 4092`

**Comment by cyantarek** [comment]
Hi @r-novel I have developed something with the help of your link.

What if I want to save to mp4 instead of webm? How can I do this from RTP packet?
