### ISSUE TITLE
Question about Multi-Peer connection(sfu) by pion

### ISSUE THREAD

**Issue by DevRockstarZ** [pion/webrtc#1205]
When client A,B,C is online,
A should receive traffic from B,C.
B should receive traffic from A,C.
C should receive traffic from A,B.

When I assume matching is established by in order A,B,C

When A's matching turn, A doesn't have B,C track so A can't AddTrack() B,C's track.

And B's matching turn, B can AddTrack() A's track because A entered match.

**But, I had already finished offer and answer process,
A.AddTrack() doesn't work.**

How can I make my code to work correctly?

**I want to AddTrack() when Peer Connection is done,**

**All the examples call createAnswer() after AddTrack() so I don't know how to solve this matter.**

Please help me!

**Comment by Sean-Der** [comment]
Hey @DevRockstarZ 

Sorry I missed this, if you get a chance I would ask in [Slack](https://pion.ly/slack) I try to use GitHub as 'long term issue tracking' and just review it when I get a chance.

I would really love for you to use Pion, and I am here to help :) sorry about being slow

**Comment by barkhasikka** [comment]
Is there any solution for this?
