### ISSUE TITLE
Is it possible to access webcam/microphone from golang webrtc, without having to rely on client browser?

### ISSUE THREAD

**Issue by cyantarek** [pion/webrtc#1208]

**Comment by Sean-Der** [comment]
Hey @cyantarek 

You have a few options
* [GStreamer integration](https://github.com/pion/example-webrtc-applications/tree/master/gstreamer-send)
* [mediadevices](https://github.com/pion/mediadevices)

Or you could write your own capture/encode code like [webrtc-remote-screen](https://github.com/rviscarra/webrtc-remote-screen)

This seems to be a really common asked question, adding it to the FAQ would be really helpful! Other developers are probably wondering the same thing. It could be really great if they don't have to ask as well :)

thanks for using Pion!
