### ISSUE TITLE
inconsistent errors when sending on closed track vs closed channel

### ISSUE THREAD

**Issue by josharian** [pion/webrtc#1211]
It's possible I'm misunderstanding something, but...

When you send media to a track with no peers, you get `io.ErrClosedPipe` back. Many of the examples use this to suppress unimportant error messages.

When you send data to a data channel that is closed, you get `data channel not open`.

It would be nice if data channels also returned `io.ErrClosedPipe` in this situation, for consistency.

I guess this is a breaking API change, so maybe it should be considered for v3?

**Comment by Sean-Der** [comment]
:+1: 100% agree with this.

Yea probably `V3` is probably best, great catch :)
