### ISSUE TITLE
pc.AddIceCandidate complains when candidate.Candidate is the empty string

### ISSUE THREAD

**Issue by jech** [pion/webrtc#1212]
[Section 4.8.2 of the spec](https://www.w3.org/TR/webrtc/#rtcpeerconnectioniceevent) has the following to say:

> An RTCIceTransport has finished gathering a generation of candidates, and is providing an end-of-candidates indication as defined by Section 8.2 of [TRICKLE-ICE]. This is indicated by candidate.candidate being set to an empty string. The candidate object should be signaled to the remote peer and passed into addIceCandidate like a typical ICE candidate, in order to provide the end-of-candidates indication to the remote peer.

However, if I pass such a candidate to `pc.AddIceCandidate`, it complains with the error `attribute not long enough to be ICE candidate (0)`.

**Comment by marverix** [comment]
Is there any workaround for now?

**Comment by Sean-Der** [comment]
Not right now, but this would only take ~hour to fix if you are interested!

At this line https://github.com/pion/webrtc/blob/master/peerconnection.go#L1364

```
if candidateValue == "" {
  return nil
}
``

Then you just need to add a test that asserts it doesn't return an error!

**Comment by marverix** [comment]
Thanks for your quick answer. So just from curiosity: So how the library "knows" that there is end-of-candidates?

**Comment by Sean-Der** [comment]
Pion doesn't care about `end-of-candidates` It takes the first connected candidate pair it can get. It waits before taking more expensive candidate pairs though (like TURN and STUN).

You can configure the amount of time you are willing to wait with the [SettingEngine](https://pkg.go.dev/github.com/pion/webrtc/v3?tab=doc#SettingEngine.SetPrflxAcceptanceMinWait)!

**Comment by Sean-Der** [comment]
https://github.com/pion/ice/blob/master/agent_config.go#L23-L33 these are the defaults

**Comment by marverix** [comment]
Thanks @Sean-Der !

**Comment by Sean-Der** [comment]
@jech This happens [here](https://github.com/pion/ice/blob/master/agent.go#L487-L497)

Right now it just does disconnected+failed time.  After 30 seconds of sending connectivity checks it goes to failed. This is a really easy change we could make!

In general `pion/ice` has been really naieve. I wish I could put more time into it, but I feel like we are always missing big parts :(

**Comment by jech** [comment]
I see, thanks.  I've summarised this in https://github.com/pion/ice/issues/271.
