### ISSUE TITLE
having trouble importing with github.com/pions/webrtc

### ISSUE THREAD

**Issue by Sweetkubuni** [pion/webrtc#1218]
The error on go build keeps recurring:

go: brisky.com/m/v2 imports
        github.com/pion/webrtc: github.com/pion/webrtc@v1.2.0: parsing go.mod:
        module declares its path as: github.com/pions/webrtc
                but was required as: github.com/pion/webrtc
I already have GO111MODULE=on and I am using the import path based on your example code
github.com/pion/webrtc/v2

**Comment by Sean-Der** [comment]
Hi @Sweetkubuni 

Double check you are importing ‘pion’ and not ‘pions’. Another possible issue is not importing ‘v2’ the ‘github.com/pion/webrtc’ does not work pre v2

**Comment by Sean-Der** [comment]
@Sweetkubuni If you are still having issues I would be happy to help in the [Pion Slack](https://pion.ly/slack)

I am going to resolve this, but if I am misunderstanding the issue please reopen. thank you!
