### ISSUE TITLE
ICE state switches to failed with unidirectional IPv6 flow

### ISSUE THREAD

**Issue by jech** [pion/webrtc#1221]
Hi,

The Unnamed SFU negotiates unidirectional connections.  In one of my users' networks, Firefox and Pion negotiate the client-to-server connections over IPv6 and the server-to-client connections over IPv4.

The issue I'm having is that the `OnICEConnectionStateChange` callback triggers on the upstream connection with `state` equal to failed after a few seconds.  If the callback is ignored, then the flow continues and everything works.

I'll need to double-check carefully (it's a big packet trace, and the traffic is encrypted), but as far as I can tell, the RTCP traffic in the server-to-client direction gets sent over IPv4, which I find strange -- should it not follow the same ICE pair as the client-to-server traffic?  This might be relevant.

**Comment by Sean-Der** [comment]
@jech I wouldn't be surprised if our IPv6 support was broken. I need to confirm myself, and then update our CI to provide IPv6 candidates (to make sure it doesn't regress)

The `ice.Agent` itself chooses a `selectedPair` and you can keep using it even if you are disconnected. So I assume that the connectivity is good, but we are getting packets back on a different pair.

**Comment by jech** [comment]
> I wouldn't be surprised if our IPv6 support was broken. I need to
> confirm myself, and then update our CI to provide IPv6 candidates (to
> make sure it doesn't regress)

I'll try to reproduce the problem on my side.

I'm now ignoring ICE indications in my code, which means that the user
whose connection fails gets no useful indications about the failure.  Do
you have any suggestions about how to robustly detect that a flow is
failed?

**Comment by jech** [comment]
This turned out to be an issue in my code (I wasn't generating Sender Reports right).  Closing.
