### ISSUE TITLE
Illegal base64 data error from examples/save-to-disk

### ISSUE THREAD

**Issue by somersbmatthews** [pion/webrtc#1226]
### Your environment.
  - SHA: 667941621dd8c895a5dd23b133e1913221b0cf7e
  - Browser: Chrome: 81.0.4044.138 

### What did you do?

`go get github.com/pion/webrtc/v2/examples/save-to-disk` does not work so I used `go get github.com/pion/webrtc` then `go install github.com/pion/webrtc/examples/save-to-disk`

Since I don't have `$BROWSER_SDP` set I used `echo (pasted session description here) > session` then `save-to-disk < session`

### What did you expect?

I expected a session description to be outputed so I could paste it here: https://jsfiddle.net/b3d72av1/

### What happened?

I got this: 
 `pyop@mbp ~/gocode/src/webrtc-forked/examples/save-to-disk : save-to-disk < session`                          

panic: illegal base64 data at input byte 9264

`goroutine 1 [running]:
github.com/pion/webrtc/v2/examples/internal/signal.Decode(0xc0001cc500, 0x2433, 0x13cbd40, 0xc0001921c0)
	/Users/pyop/gocode/src/github.com/pion/webrtc/examples/internal/signal/signal.go:65 +0xcd
main.main()
	/Users/pyop/gocode/src/github.com/pion/webrtc/examples/save-to-disk/main.go:131 +0x559`

On other attempts, the byte offset changes value, in other attempts, there is no error message and, although files are created, they only include the initial header information.

thank you for your time :)

**Comment by Sean-Der** [comment]
Hey @somersbmatthews 

For me on Chromium copying/pasting always ignores the trailing `=` sometimes you might have two. It might be worth switching to something that is more copy/paste resilient :)

Another thing that can happen is stdin length restrictions, `9264` doesn't seem significant but is divisible by two so seems possible :)

**Comment by Sean-Der** [comment]
Resolving for now @somersbmatthews, if you are able to hit a reproducible error please re-open :)

thanks!

**Comment by somersbmatthews** [comment]
@Sean-Der yeah using firefox fixed the copy paste problem, but I'm still getting files with just initial headers and the jsfiddle part just says `failed` and the pion part just says `Connection State has changed failed
Done writing media files` I'm going to try some more things to try to get this jsfiddle working. I am trying to get some sample bytes written by oggwriter so i can write tests for oggreader using the save-to-disk example.
