### ISSUE TITLE
Why SDPMid and SDPMLineIndex isn't set in ICECandidate.ToJSON()?

### ISSUE THREAD

**Issue by juju812** [pion/webrtc#1236]
Hi, there,

In method `ICECandidate.ToJSON()`, `SDPMid` is a nil pointer and value of `SDPMLineIndex` is always 0. So I can't get these info in `PeerConnection.OnICECandidate`. Could anyone kindly clarify why SDPMid and SDPMLineIndex isn't set? Is there any concern?

Thx

**Comment by Sean-Der** [comment]
Hey @juju812 sorry for the delay

`pion/webrtc` always does RTP/RTCP mux, so we don't create ICE candidates per media section. I believe this only matters if you have a PeerConnection that listens on multiple ports.

If there is a change we should make here happy to do it!

thanks

**Comment by Sean-Der** [comment]
Fixed in 6d3633e58923227e00e96ed80ae46e6fa25a39cc

We now always include these entries.
