### ISSUE TITLE
document calling PeerConnection.Close, add to examples

### ISSUE THREAD

**Issue by josharian** [pion/webrtc#1241]
As discussed here:

https://gophers.slack.com/archives/CAK2124AG/p1591453173401600

**Comment by Sean-Der** [comment]
It also would help a lot if we implemented https://github.com/pion/ice/issues/189

The ICE Agent would go to failed, and then all the resources would be freed without user interaction.

**Comment by Sean-Der** [comment]
Duplicate of https://github.com/pion/webrtc/issues/839
