### ISSUE TITLE
improve samplebuilder docs

### ISSUE THREAD

**Issue by josharian** [pion/webrtc#1242]
There's no indication of the units for maxLate.

It's not clear what an rtp.Depacketizer is or what a standard one might look like. What is the byte  slice arg and what byte slice is it returning? The tests only show a `fakeDepacketizer` that is a passthrough. In my testing, a passthrough depacketizer works fine. (Should depacketizer by an option? Should it have type func instead of type interface?)

Are Push and Pop safe for concurrent use? If not, what is the intended use? (If you only Pop after Pushing, then it seems like you might lose packets unnecessarily if there is a delay in inbound packets, but maybe I misunderstand.)

**Comment by tarrencev** [comment]
@josharian can we close this with your PR? or are further improvements necessary?

**Comment by josharian** [comment]
I’m no longer using pion; I’m happy to let you decide about the best path forward for this issue.

**Comment by Sean-Der** [comment]
The SampleBuilder has gone through lots of changes since this issue, don't believe these apply anymore.
