### ISSUE TITLE
ICE Connection state always fails always.

### ISSUE THREAD

**Issue by hiteshjoshi** [pion/webrtc#1253]
Hi Guys,

As a quick hack to try out the desktop side possibilities of this work. I am trying to create a small go lang based client but for some reason I am always stuck on ICE connection state : failed.

Can you someone please guide me on what am I doing wrong? (I am actually trying to replicate the steps involved in the browser side demo(sfu.html) of this example project [sfu-ws](https://github.com/pion/example-webrtc-applications/tree/master/sfu-ws)

so SFU-WS is running as server and this will the client.

Here is what I am doing.

```
package main

import (
	"fmt"
	"log"
	"math/rand"
	"net/url"
	"os"
	"os/signal"
	"time"

	"github.com/gorilla/websocket"
	"github.com/hiteshjoshi/portaudio"
	"github.com/pion/webrtc/v2"
	"gopkg.in/hraban/opus.v2"
)

var m = webrtc.MediaEngine{}

var api *webrtc.API
var broadcastHub = newHub()

const sampleRate = 48000
const channels = 1 // mono; 2 for stereo
var enc *opus.Encoder

const bufferSize = 1000

var addr = "localhost:8443"
var pc *webrtc.PeerConnection
var wsData = make(chan []byte)
var remoteSDP []byte
var remoteSet bool = false

func initMediaEngine() {
	m.RegisterDefaultCodecs()
	s := webrtc.SettingEngine{}
	s.SetTrickle(true)
	api = webrtc.NewAPI(webrtc.WithMediaEngine(m), webrtc.WithSettingEngine(s))

	var peerConnectionConfig = webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
		SDPSemantics: webrtc.SDPSemanticsUnifiedPlanWithFallback,
	}
	peerConnection, err := api.NewPeerConnection(peerConnectionConfig)
	chk(err)
	pc = peerConnection
}
func getSocketMsg(msg string) {

}
func main() {

	u := url.URL{Scheme: "wss", Host: addr, Path: "/ws"}
	c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
	if err != nil {
		log.Fatal("dial:", err)
	}
	defer c.Close()

	initMediaEngine()

	// Create a datachannel with label 'data'
	dataChannel, err := pc.CreateDataChannel("data", nil)
	if err != nil {
		panic(err)
	}

	pc.OnICEConnectionStateChange(func(connectionState webrtc.ICEConnectionState) {
		fmt.Printf("ICE Connection State has changed: %s\n", connectionState.String())
	})

	pc.OnConnectionStateChange(func(p webrtc.PeerConnectionState) {
		fmt.Printf("Peer Connection State has changed: %s\n", p.String())
	})
	pc.OnSignalingStateChange(func(s webrtc.SignalingState) {
		fmt.Printf("Signal State  has changed: %s\n", s.String())
	})

	pc.OnICECandidate(func(f *webrtc.ICECandidate) {

		//fmt.Println(pc.LocalDescription().SDP)

		if f == nil {
			fmt.Println("ICECANDIDATE")
			//SEND WS MSG FROM HERE
			err = c.WriteMessage(websocket.BinaryMessage, []byte(pc.LocalDescription().SDP))
			if err != nil {
				log.Println("write close:", err)
				return
			}
		}

	})

	_, err = pc.AddTransceiver(webrtc.RTPCodecTypeAudio)
	chk(err)

	opustrack, err := pc.NewTrack(webrtc.DefaultPayloadTypeOpus, rand.Uint32(), "audio", "pion1")
	if err != nil {
		chk(err)
	}

	pc.AddTrack(opustrack)
	pc.OnTrack(func(remoteTrack *webrtc.Track, receiver *webrtc.RTPReceiver) {
		fmt.Println("GOT NEW TRACK")
	})

	offer, _ := pc.CreateOffer(nil)
	pc.SetLocalDescription(offer)

	pc.OnDataChannel(func(d *webrtc.DataChannel) {
		fmt.Println("DATA CHANNEL")
		broadcastHub.addListener(d)
	})

	dataChannel.OnOpen(func() {
		fmt.Printf("Data channel '%s'-'%d' open. Random messages will now be sent to any connected DataChannels every 5 seconds\n", dataChannel.Label(), dataChannel.ID())

		for range time.NewTicker(5 * time.Second).C {
			message := "hello"
			fmt.Printf("Sending '%s'\n", message)

			// Send the message as text
			sendTextErr := dataChannel.SendText(message)
			if sendTextErr != nil {
				panic(sendTextErr)
			}
		}
	})
	dataChannel.OnMessage(func(msg webrtc.DataChannelMessage) {
		fmt.Printf("Message from DataChannel '%s': '%s'\n", dataChannel.Label(), string(msg.Data))
	})

	// Send server sdp to publisher

	_, remoteSDP, err = c.ReadMessage()
	if err != nil {
		log.Println("read:", err)
		return
	}

	//chk(ws.WriteMessage(websocket.BinaryMessage, sdp))

	log.Println(pc.SetRemoteDescription(
		webrtc.SessionDescription{
			SDP:  string(remoteSDP),
			Type: webrtc.SDPTypeOffer,
		}))

	// Create answer

	sig := make(chan os.Signal, 1)
	signal.Notify(sig, os.Interrupt, os.Kill)

	enc, err = opus.NewEncoder(sampleRate, channels, opus.AppVoIP)
	if err != nil {
		panic(err)
	}

	portaudio.Initialize()
	defer portaudio.Terminate()
	pcm := make([]int16, 240)
	stream, err := portaudio.OpenDefaultStream(1, 0, sampleRate, len(pcm), pcm)
	chk(err)
	defer stream.Close()

	chk(stream.Start())

	for {
		chk(stream.Read())
		const bufferSize = 2000
		frameSize := len(pcm) // must be interleaved if stereo
		frameSizeMs := float32(frameSize) / channels * bufferSize / sampleRate

		switch frameSizeMs {
		case 2.5, 5, 10, 20, 40, 60:
			data := make([]byte, bufferSize)
			_, err := enc.Encode(pcm, data)
			//data = data[:n]
			_, err = opustrack.Write(data)

			if err != nil {
				fmt.Println(err)
			}
		default:
			fmt.Errorf("Illegal frame size: %d bytes (%f ms)", frameSize, frameSizeMs)
		}

		select {

		case <-sig:
			log.Println("interrupt")
			chk(stream.Stop())
			// Cleanly close the connection by sending a close message and then
			// waiting (with timeout) for the server to close the connection.
			err := c.WriteMessage(websocket.CloseMessage, websocket.FormatCloseMessage(websocket.CloseNormalClosure, ""))
			if err != nil {
				log.Println("write close:", err)
				return
			}
			select {
			case <-time.After(time.Second):
			}

			return
		default:
		}
	}
}

func chk(err error) {
	if err != nil {
		panic(err)
	}
}

```
------------------------------------------------------
The logs

```
Signal State  has changed: have-local-offer
ICECANDIDATE
Signal State  has changed: have-local-offer
2020/06/13 03:32:15 <nil>
ICE Connection State has changed: checking
Peer Connection State has changed: failed
ICE Connection State has changed: failed
```

**Comment by Sean-Der** [comment]
In your `SetRemoteDescription` you seem to be taking an offer? That be causing an issue, I think that needs to be an answer (because you sent an Offer)

Would you be able to share the Pion and Browser SDP? In the browser are you blocking until ICE is fully gathered, if not Pion has no way to contact the browser.

If you don't want to do that you could switch roles and have Pion answer, and the browser could be controlling and you don't have to signal any ICE candidates.

**Comment by hiteshjoshi** [comment]
Also I did a small change to this file here 
https://github.com/pion/webrtc/blob/master/peerconnection.go#L796

For some reasons `pc.RemoteDescription().parsed.MediaDescriptions` was always null and it was throwing exception. I quickly debugged and saw that https://github.com/pion/webrtc/blob/master/peerconnection.go#L781 `desc.parsed` has the MediaDescriptions it is looking for. 

so I chaged the link #796 from `		for _, media := range pc.RemoteDescription().parsed.MediaDescriptions {`
to 

`		for _, media := range desc.parsed.MediaDescriptions {`

I know that might have caused some trouble?

I am sorry, just very new to webrtc in general.

**Comment by hiteshjoshi** [comment]
@Sean-Der WOW! What a waste!!

Thank you so much. It just didnt caught my attention at all.

**Comment by Sean-Der** [comment]
@hiteshjoshi nice! did that work?

**Comment by hiteshjoshi** [comment]
and @Sean-Der Dude! You were really fast.. thanks.
Yup it worked. Nice and clean. Realised that change I did to "TRY" to make it work wasnt required if it was an Answer

**Comment by hiteshjoshi** [comment]
@Sean-Der one last quick one. It now connects but for some reason the Track isnt going forward. Any hint?

**Comment by Sean-Der** [comment]
@hiteshjoshi nice! Always happy to help, excited to see people using Pion :)

Also feel free to shoot me question is [Slack](https://pion.ly/slack)!

----

> Track isnt going forward.
Did you add a Transceiver in the browser as well? You need to explicitly accept tracks (on both sides)

**Comment by barkhasikka** [comment]
I had the exact same issue with connection stated changing to failed, but I could solve it after understanding this comment:

Would you be able to share the Pion and Browser SDP? In the browser are you blocking until ICE is fully gathered, if not Pion has no way to contact the browser.

But I am still not able to see track going forward. I get io.ErrClosedPipe when trying to write rtpBuf to track. Not able to understand why this. Please help.

**Comment by barkhasikka** [comment]
Hi @hiteshjoshi 

Sharing a screenshot of what I’m doing on clientside.. the backend logic follows what is provided in sfu example.. in addition to this I have added to logic for sending and adding ice candidates.. 

![2E31F329-CC3F-4AA8-BFC9-037CE4B0DFD2](https://user-images.githubusercontent.com/11821046/91086868-254f5000-e66d-11ea-8937-6bb19224414b.png)

**Comment by barkhasikka** [comment]
![Screenshot 2020-08-25 at 9 17 41 AM](https://user-images.githubusercontent.com/11821046/91121492-88fd6b80-e6b5-11ea-92a7-15e9a82fb80b.png)

and if it helps this is what is shown in webrtc-internals

**Comment by barkhasikka** [comment]
Is there any way we can have renegotiation inititated from pion since offer is created by browser side.

**Comment by Sean-Der** [comment]
@barkhasikka yes! Either can side can start the renegotiating.

**Comment by Sean-Der** [comment]
Just set `ICERestart` when calling `CreateOffer`

**Comment by Sean-Der** [comment]
Hey @barkhasikka 

If you get a chance [Slack](https://pion.ly/slack) is a better place to ask for support. GitHub issues is more for tracking long term code things we want to fix. I get a lot of email so hard to respond to these quickly.

thanks!

**Comment by barkhasikka** [comment]
Hi! I tried to join the slack channel a lot may times but I am not able to find the channel. If you can guide me on that it would be useful. Since I am using pion for a project and I keep landing into one or the other issues every now and then.

**Comment by barkhasikka** [comment]
> Just set `ICERestart` when calling `CreateOffer`

I am using pion v2 and not able to find ice restart method.
