### ISSUE TITLE
How to broadcast  Audio and Video at once？

### ISSUE THREAD

**Issue by DehaiWang** [pion/webrtc#1260]
I find  broadcast  Audio or broadcast  Video ,but how to broadcast  Audio and Video at once?
build two RTCPeerConnection, one transfer Audio  and the other transfer Video ?
Have better solution?

**Comment by Sean-Der** [comment]
Hey @DehaiWang 

You can use one PeerConnection! [play-from-disk](https://github.com/pion/webrtc/tree/master/examples/play-from-disk) demonstrates how.

**Comment by DehaiWang** [comment]
@Sean-Der 
Hey, 
as [https://github.com/pion/webrtc/blob/master/examples/broadcast/main.go](url)
i remove 
`if _, err = peerConnection.AddTransceiverFromKind(webrtc.RTPCodecTypeVideo); err != nil {
	 	panic(err)
	 }`
and add 
 `videoCodecs := mediaEngine.GetCodecsByKind(webrtc.RTPCodecTypeVideo)
	if len(videoCodecs) == 0 {
		panic("Offer contained no video codecs")
	}

	
	videoTrack, err := peerConnection.NewTrack(videoCodecs[0].PayloadType, rand.Uint32(), "video", "pion")
	if err != nil {
		panic(err)
	}

	
	if _, err = peerConnection.AddTrack(videoTrack); err != nil {
		panic(err)
	}


	audioCodecs := mediaEngine.GetCodecsByKind(webrtc.RTPCodecTypeAudio)
	if len(videoCodecs) == 0 {
		panic("Offer contained no audio codecs")
	}


	audioTrack, err := peerConnection.NewTrack(audioCodecs[0].PayloadType, rand.Uint32(), "audio", "pion")
	if err != nil {
		panic(err)
	}


	if _, err = peerConnection.AddTrack(audioTrack); err != nil {
		panic(err)
	}
`.

And as [https://github.com/pion/webrtc/blob/master/examples/broadcast/jsfiddle/demo.js](url)
i set `video: true, audio: true`.
then  '  Join a Broadcast ', the web video show nothing.

**Comment by DehaiWang** [comment]
@Sean-Der 
Thanks very much.
In the web ,i add 
 `
      pc.addTransceiver('video');
`
`
      pc.addTransceiver('audio')
`
and it work fine.

**Comment by DehaiWang** [comment]
after add 
`pc.addTransceiver('video');`
`pc.addTransceiver('audio')；`
in web js  ,
then web video only play audio;

**Comment by fayfive** [comment]
I can call AddTrack on the PeerConnection as many times as Iwant.But there is a question，different browser has different payload type. For exsample，chrome is 102:h264,but firefox is 126:h264. If set the answer,102:h264,the firefox will not show the video.So is there a solution? Maybe change the payload type before Track.WriteSample ?

**Comment by Sean-Der** [comment]
Hey @fayfive 

This is no longer an issue! In /v3 we internally manage the SSRC/PayloadType for you

**Comment by fayfive** [comment]
And now，how to Achieve One-to-many?  I create a new peer while a new request, but the cpu performance is full.
 Is the function that manage the SSRC/PayloadType in the v3 beta 11?

**Comment by Sean-Der** [comment]
@fayfive How many PeerConnections are you serving when you reach resource exhaustion? Is this on a specific host?

To see an example of fanout we have https://github.com/pion/webrtc/tree/master/examples/broadcast and https://github.com/pion/example-webrtc-applications/tree/master/sfu-ws

**Comment by fayfive** [comment]
@Sean-Der
I download v3 and see the sample.But it dose not work in local network. I usb nginx to see the web.  I set peerConnectionConfig := webrtc.Configuration{}, is there any problem?
