### ISSUE TITLE
ICE AgentConfig does not match what WebRTC Icegatherer expects

### ISSUE THREAD

**Issue by natakug05** [pion/webrtc#1271]
- Version: latest master source
  - Browser: Brave 1.7.92
  - Other Information - icegatherer.go line 93 change ConnectionTimeout to DisconnectTimeout

I simply performed a go get github.com/pion/webrtc and I get the following error:

"github.com/pion/webrtc/icegatherer.go:93:3: unknown field 'ConnectionTimeout' in struct literal of type ice.AgentConfig"

I inspected the ICE project and found a commit as of yesterday moving AgentConfig into its own file. There is no longer a ConnectionTimeout field, only DisconnectTimeout.

**Comment by natakug05** [comment]
Specifically commit 0c308ea365bcc990530bee742fa7c4f330eb957b of the ice project. Looks like this broke on Saturday the 20th.

**Comment by Sean-Der** [comment]
Hey @natakug05 

Are you able to use Go modules? `pion/webrtc@master` and `pion/ice@master` is not going to work for a couple days unfortunately. I moved `pion/ice` to `/v2` and am making breaking changes to support ICE restarts.

Sorry for the breakage :(

**Comment by natakug05** [comment]
Not a problem at all! This is the reason using master source is a "risk". I just went into the ICE project and checked out before that breaking change. I will watch for a change to WebRTC. Since this is known you can close this issue if you'd like.

**Comment by Sean-Der** [comment]
:+1: I will leave in case others hit this also! Will resolve when I finish my `pion/ice` work and all the master branches work together again.

thanks for using Pion :) appreciate you take the time to make bug reports.

**Comment by Sean-Der** [comment]
This is fixed! `pion/webrtc@master` uses `pion/ice@master`
