### ISSUE TITLE
TestPeerConnection_GetStats flaky on windows 10 (v2.2.15, v2.2.16, v2.2.17)

### ISSUE THREAD

**Issue by funvit** [pion/webrtc#1276]
### Your environment.
  - Version: v2.2.15, v2.2.16, v2.2.17
  - Browser: -
  - Other Information: - 
  - Windows: Microsoft Windows [Version 10.0.18363.836]
 - Go ver: go1.14.4 windows/amd64  

### What did you do?

    gotestsum -f dots --  -count 50 -run ^TestPeerConnection_GetStats$ ./...

### What did you expect?

all 50 repeats ok

### What happened?

flaky:

v2.2.15
··xxxx··xx·xxx·xx··xxx··x··xx···xx·xxxx····xx·xxxx
DONE 50 tests, 29 failures in 64.218s

v2.2.16
x··xxx·xxxx·xx·xxxx·xxxxx··xxx··xx··xxx···xx·x·xxx
DONE 50 tests, 33 failures in 44.085s

v2.2.17
·xxx·xxxxx··xx·xx·x·x··xxxxxx·x··xxxxx··xxx·x·xx·x
DONE 50 tests, 33 failures in 55.039s

---

Just reporting, haven't digged.

**Comment by at-wat** [comment]
https://github.com/pion/webrtc/pull/1130
It had been also unstable on Linux, and I added sleep to the test to avoid missing the last packet.
I guess the sleep should be longer due to the timer resolution on Windows.

**Comment by Sean-Der** [comment]
Closed for https://github.com/pion/webrtc/issues/1466
