### ISSUE TITLE
QUIC tests are disabled

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#1277]
We only run the QUIC tests when `-tags quic` are enabled. We should add this functionality back.

**Comment by cryptix** [comment]
Is there more to it then removing the build tag?

**Comment by cryptix** [comment]
Apart from making the tests pass, of course. 

I found some TODOs in the pion/quic wrapper around end-of-stream stuff, currently trying to resolve that.

**Comment by at-wat** [comment]
`pion/quic` is depending on the quite old version of `lucas-clemente/quic-go`.
I think it's better to resolve https://github.com/pion/quic/pull/8 before enabling it by default.

**Comment by cryptix** [comment]
@at-wat yup, I already did that in pion/quic#31 together with some related changes.

**Comment by at-wat** [comment]
oh, that's great!

**Comment by Sean-Der** [comment]
Fixed by 940d6aae86fa13c993460900da7a7f21455bd806
