### ISSUE TITLE
Enqueue logic should take copy of PeerConnection

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#1290]
I am seeing some races in `TestPeerConnection_Renegotiation_AddTrack` where we `AddTrack` after a `SetRemoteDescription`. The test `TestPeerConnection_Renegotiation_AddTrack` is flaking in master a bit. I am able to reproduce by doing `go test -run 'TestPeerConnection_Renegotiation_AddTrack' -count 50 -v`

The `SetRemoteDescription is then processed with the Track that was added BEFORE the call to `SetRemoteDescription`.

**Comment by Sean-Der** [comment]
@jeremija Any quick fixes you can think of? No rush/guilt though! I will work on this tomorrow, just trying to pay down some tech debt before working on next thing :)

**Comment by jeremija** [comment]
I cannot reproduce this on my machine :( Do any of these tests fail or just a one of them:

- TestPeerConnection_Renegotiation_AddTrack
- TestPeerConnection_Renegotiation_AddTrack_Multiple
- TestPeerConnection_Renegotiation_AddTrack_Rename

or just the `^TestPeerConnection_Renegotiation_AddTrack$`?

**Comment by jeremija** [comment]
This is a long shot, but I think the issue might be that we call `getTransceivers()` from the enqueued `pc.startRTP()`, and these get updated when `AddTrack` is called.

Perhaps we can call `getTransceivers()` before enqueuing, and pass them to `pc.startRTP()` as an additional argument via closure?
