### ISSUE TITLE
There is no method to get RemoteAddr/LocalAddr of DataChannel

### ISSUE THREAD

**Issue by hakulat** [pion/webrtc#1292]
### Your environment.
  - Version: v2.2.17

### What did you do?
I want to record the flow of Datachannel, with remote addr and local addr

### What happened?
There is no exported method to get Datachannel or underlayer transport conn info( remote addr and local addr)

**Comment by Sean-Der** [comment]
Hi @hakulat 

I am not sure we will be able to add that, we are implementing [RTCDataChannel](https://w3c.github.io/webrtc-pc/#webidl-1970659251) so we only try add methods/fields that match things in the spec.

Are you trying to get details from the ICE connection? What information are you interested in?

thanks for using Pion!

**Comment by hakulat** [comment]
not details from ICE connection, just remote addr/local addr info of the DataChannel for P2P.
there is *dtls.Conn in `DTLSTransport` and could get DTLSTransport instance by `DataChannel.Transport().Transport()`
could we exposure RemoteAddr/LocalAddr of `*dtls.Conn` in `DTLSTransport`

**Comment by Sean-Der** [comment]
I don't think we can unfortunately. We need to support WASM as well. If we add `Go specific` functionality, it will confuse people when the compile to WASM mode :/

You are able to get the RemoteAddr/LocalAddr right? The API just isn't as friendly?

**Comment by cryptix** [comment]
> You are able to get the RemoteAddr/LocalAddr right? The API just isn't as friendly?

If @hakulat is referring to ICE established transports before https://github.com/pion/ice/pull/222 they were just `nil`. 


@hakulat just to be clear: is there a special reason you want this info from the DataChannels? The address should be the same for all channels on the same transport, no?

**Comment by hakulat** [comment]
@cryptix we have devices with many network card, we want to know which network card is the datachannel exactly used.

**Comment by cryptix** [comment]
@hakulat that makes sense but aren't all DataChannels multiplexed on the same transport and thus on the same card?

**Comment by hakulat** [comment]
@cryptix there no api to get remote/local addr of DataChannel, that's the problem!

grpc could get peer info by 
```golang
import "google.golang.org/grpc/peer"

func xx() {
    thePeer, ok := peer.FromContext(ctx)
}
```
could we consider some api like this?

**Comment by Sean-Der** [comment]
Hey @hakulat 

Sorry I missed this thread, but this API exists today! You just don't find out this information from the DataChannel.

You want to use [OnSelectedCandidatePairChange)(https://pkg.go.dev/github.com/pion/webrtc/v3#ICETransport.OnSelectedCandidatePairChange) this is fired when the Remote/Local addr is set.

This library is implementing an established API [webrtc-pc](https://w3c.github.io/webrtc-pc/) so adding a different API is out of our control unfortunately. 

If this is a problem feel free to re-open this issue, and happy to help :)

**Comment by evedark1** [comment]
@Sean-Der 
I can't find an easy way to set this callback [ICETransport.OnSelectedCandidatePairChange], ICETransport can't get by PeerConnection.
Can you give a example code? thank you very much.
