### ISSUE TITLE
Allow triggering ice gathering in v3

### ISSUE THREAD

**Issue by masterada** [pion/webrtc#1296]
## Summary

In v3, tricke ice is default. We use pion with the `SetNAT1To1IPs` setting, without any stun server, so we don't really benefit from tricke ice. We generate the offer in the browser, and create the answer for it in our pion powered server. In v2 ice candidates are included in the sdp answer. In v3, this is not possible (without the workaround mentioned below), because gathering of candidates is only started in the SetLocalDescription method, which must be called after CreateAnswer. 

## Describe alternatives you've considered

There is a workaround that seems to be working, but is quite ugly and i'm not sure if it will cause any issues:

```
	_ = peerConnection.SetRemoteDescription(remoteOffer)
	answer, _ = peerConnection.CreateAnswer(nil)
	_ = peerConnection.SetLocalDescription(answer)
	<-pion.GatheringCompletePromise(peerConnection)
	answer, _ = peerConnection.CreateAnswer(nil)
	_ = peerConnection.SetLocalDescription(answer)
```

## Suggestion

Would it be possible to add a Gather() method to peerconnection? eg:
```
func (pc *PeerConnection) Gather() error {
	if pc.iceGatherer.State() == ICEGathererStateNew {
		return pc.iceGatherer.Gather()
	}
	
	return nil
} 
```

This would help reproduce the v2 behaviour. This could be updated as well:
https://github.com/pion/webrtc/wiki/Release-WebRTC@v3.0.0#helper-function-to-simulate-non-trickle-ice

**Comment by Sean-Der** [comment]
Yea!

If we expose [ICETransport](https://draft.ortc.org/#rtcicetransport*) we can also expose [ICEGatherer](https://draft.ortc.org/#rtcicegatherer*) directly

**Comment by Sean-Der** [comment]
Hey @masterada I am going to close this for now. 

Users simulate non-trickle ICE in the browser the same way. I think it is better that we stay consistent with the browser.

The helper method `GatheringCompletePromise` works across WASM and Go. I feel a little guilty adding a non-standard API, but I didn't want to break existing users.

**Comment by masterada** [comment]
Ok, the workaround works for now, worst case we will find some other workaround :)

**Comment by masterada** [comment]
In case any1 finds this issue, we now use the following sollution:
```
	_ = peerConnection.SetRemoteDescription(remoteOffer)
	answer, _ = peerConnection.CreateAnswer(nil)
	_ = peerConnection.SetLocalDescription(answer)
	<-pion.GatheringCompletePromise(peerConnection)
	answer = *(peerConnection.CurrentLocalDescription()) // you might want to handle the case if this is nil
```
