### ISSUE TITLE
v2 branch backports

### ISSUE THREAD

**Issue by at-wat** [pion/webrtc#1304]
PRs below are backported to v2 branch.

**Comment by at-wat** [comment]
- Update module pion/sdp/v2 to v2.3.9 #1286 
- Use io.ReadFull in oggreader #1298
- Fix SampleBuilder packet unref #1302

**Comment by at-wat** [comment]
Tagging v2.2.18

**Comment by at-wat** [comment]
- Update module pion/srtp to v1.4.0 #1306 (security fix)

**Comment by at-wat** [comment]
Tagging v2.2.19

**Comment by at-wat** [comment]
- Fix grammatical errors #1295
- Fix randoms #1312
- Fix leak in TestSDPSemantics #1310
- Assert SDPType in setDescription #1313
- Update module pion/rtp to v1.6.0 #1318
- Update module pion/sctp to v1.7.7 #1319 
- Fix JSEP SDP Session ID #1316

**Comment by at-wat** [comment]
Tagging v2.2.20

**Comment by at-wat** [comment]
- Update sctp and datachannel to v1.7.8 and v1.4.19
- Update pion/ice ver to v0.7.18

**Comment by at-wat** [comment]
Tagged v2.2.22

**Comment by at-wat** [comment]
- Update module pion/srtp to v1.5.1 #1351

**Comment by at-wat** [comment]
Tagged v2.2.23

**Comment by Sean-Der** [comment]
* Fix deadlock in OnTrack https://github.com/pion/webrtc/pull/1434

**Comment by Sean-Der** [comment]
tagged v2.2.26

**Comment by Sean-Der** [comment]
v3 has been released :D 

closing! We will be leaving the `v2` branch forever in case anyone needs it.
