### ISSUE TITLE
Generate still image (jpeg/png) from RTP packets (using sampleBuilder?)

### ISSUE THREAD

**Issue by mholbergerNIMBL** [pion/webrtc#1354]
I have adapted code from the RTP-to-webRTC example, using gst-launch-1.0 CLT for testsrcvideo, but I would like to generate an image file on the server using the incoming RTP packets from gstreamer (over UDP into the pion server).

I have cloned the incoming RTP packets and sent to the cloned packets to a sampleBuilder. I am able to pop the media.sample and confirm a keyframe using the code: 
`videoKeyframe := (samplePop.Data[0]&0x1 == 0)`

Now that I have collected the media.sample, how can I generate an image from these bytes?

I have tried using the "golang.org/x/image/vp8" library to decode a VP8 frame as an image.YCbCr, but I was unable to vp8.DecodeFrameHeader from the sample.Data bytes, nor from the incoming RTP packets (payload or raw bytes): 
"ERROR: vp8: invalid format"

I have initialized the sampleBuilder with maxLate of 10, and it consistently collects 9000 samples, with random values for raw, width, and height each time:
`raw := uint(samplePop.Data[6]) | uint(samplePop.Data[7])<<8 | uint(samplePop.Data[8])<<16 | uint(samplePop.Data[9])<<24`
`width := int(raw & 0x3FFF)`
`height := int((raw >> 16) & 0x3FFF)`
(taken from save-to-webm example)

Any suggestions?

**Comment by Sean-Der** [comment]
That all sounds right to me!

If you put that single sample inside an IVF I would be curious if ffmpeg/GStreamer could handle it (helps with your debugging)

When you get this working this would be a really cool example-WebRTC-applications contribution! If you are interested this could really help people not as strong a developer as you.

Thanks

**Comment by mholbergerNIMBL** [comment]
What I am trying now is to extract the VP8 packets from the RTP packet payloads to assemble a whole VP8 frame. Im not well versed in these video/streaming protocols. I am using the RTP packets 'marker' flag to signify the start and end of the VP8 frame.
(The rtpPacket.S flag is ALWAYS set to 0, im not sure if this is a bug)

Once I have the VP8 payloads appended for the entire frame, I will then need to marshal a VP8 header for the frame. I think I can use the pion/rtp/codecs/VP8_packet.Payload() function for this, and assemble into a single []byte. Then try to decode this frame into an Image object using the x/image/vp8 library.

Ill let you know how that goes. Hopefully still on the right track.

**Comment by mholbergerNIMBL** [comment]
I actually got it working using the sampleBuilder! And then decoded the keyframe to image object with golang.org/x/image/vp8, then jpeg.Encode to jpeg. I can maybe pull and add an example, or at least post a blob here later.

**Comment by mholbergerNIMBL** [comment]
Heres the gist of it: 
https://gist.github.com/mholbergerNIMBL/e5d17491a8cad621d53c6ed1b505ab7a

This is a web server coded with go-chi/chi
Im using rs/zerolog for logging.

The 'signal' package must be manually imported from pion/examples/internal.

Im using the pion/webRTC/examples/rtp-to-webRTC example jsfiddle to test:
https://jsfiddle.net/z7ms3u5r/

Im generating a gstreamer video pipeline with the videotestsrc (auto-alt-frames=false):
gst-launch-1.0 videotestsrc ! 'video/x-raw, width=960, height=720, framerate=10/1, format=RGB' ! videoconvert ! vp8enc error-resilient=partitions keyframe-max-dist=10 auto-alt-ref=false cpu-used=5 deadline=1 ! rtpvp8pay ! udpsink host=127.0.0.1 port=5004

I have tested this with with a USB3 Vision camera using aravis plugin for gstreamer and it is working as well.

This gist contains the main web server and 2 http handler functions, one for POST to /startStream with the browser SDP, and one for /snapshot which loads the still frame.

in the POST /startStream JSON body:
{
    "browser_SDP":"eyJ0eXBlIjoib2ZmZXIiLCJ......."
}

which responds with the sesstionToken in json:
{
    "sessionToken": "eyJ0eXBlIjoiYW........."
}

Post the first token as browser_SDP, get the 2nd token and past into jsfiddle 2nd box, then start session
then go to {serviceIP}/snapshot in the browser and it should load the jpeg capture.

**Comment by Sean-Der** [comment]
@mholbergerNIMBL I made your code into an example in https://github.com/pion/example-webrtc-applications

Thank you so much for your contribution :)

**Comment by iammeizu** [comment]
This helps me a lot !
btw, why get a snapshot cost so much (1-2s, maxlate is 10) ?
