### ISSUE TITLE
API's to detect + handle removed tracks

### ISSUE THREAD

**Issue by tarrencev** [pion/webrtc#1360]
Would be nice if pion/webrtc exposed a way to detect when remote has removed a track and handle it. Browsers support a `onremovetrack` on `MediaStream`: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/onremovetrack

Perhaps we could expose an API on `RTPReceiver`? Something like:

```go
pc.OnTrack(func(track *webrtc.Track, recv *webrtc.RTPReceiver) {
    recv.OnRemoveTrack(func(track *webrtc.Track) { ... })
}
```

**Comment by lcodecorex** [comment]
@tarrencev You can solve it through the following methods：
```
rtc.OnTrack = func(track *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) {
    for {
	// Read RTP packets being sent to Pion
	rtp, _, readErr := track.ReadRTP()
	if readErr != nil {
		if readErr == io.EOF {
			return
		}
		panic(readErr)
	}
    }
}
```
