### ISSUE TITLE
add rtx to sdp

### ISSUE THREAD

**Issue by iamRyanChia** [pion/webrtc#1365]
I am new to webrtc. I find no `a=rtpmap:101 rtx/90000` in my sdp. How to add rtx to sdp when creating offer? Thank you.

**Comment by jech** [comment]
Pion does not support RTX right now.  It would be a welcome addition.

**Comment by Sean-Der** [comment]
Hey @iamRyanChia 

Check out https://github.com/pion/webrtc-v3-design/issues/33 we are working on getting this in-tree.

By default Pion will not enable any error correction techniques. We are working on providing an API in `/v3` where uses can opt-in and define their own. I think it is important that we give people flexibility. We have lots of different users with different use cases so we want to support them all. 

I would love your opinion on the new API. I am hoping to start a branch implementing these new ideas in the next few weeks. Implementing it will not be difficult, but breaking the API isn't something we take lightly.

thanks
