### ISSUE TITLE
hope we can push RTMP or RTSP to Pion

### ISSUE THREAD

**Issue by seamanm** [pion/webrtc#1374]
## Summary

One paragraph explanation of the feature.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome? Is this available in other implementations? Can this not be implemented using primitives?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered.

**Comment by Sean-Der** [comment]
Hey @seamanm 

Yes you can! https://github.com/deepch/RTSPtoWebRTC is an example of a popular project that does this.

If you have anymore questions we are available in [Slack](https://pion.ly/slack) thanks!
