### ISSUE TITLE
Testing: turn examples into integration tests

### ISSUE THREAD

**Issue by backkem** [pion/webrtc#139]
Turn examples into integration tests.

Design goals:
- Use the existing examples
- Have minimal impact on the example code E.g.: add event listeners on the existing textareas.
- Use `go test` to run the tests
- Place integration tests behind a build flag to avoid bloating unit tests (E.g.: `go test github.com/pions/webrtc -tags=integration`)
- Communicate test data/results over http in order to minimize use of specialized APIs for test subjects (like a browser, node, ...).

(Moved from #120)

**Comment by netwer** [comment]
@backkem you did not implement the turn server yet?

**Comment by Sean-Der** [comment]
Moved to https://github.com/pion/webrtc/wiki/Big-Ideas

I think this is a great idea, but I don't see it moving anytime soon unfortunately :(
