### ISSUE TITLE
Firefox Simulcast improvements

### ISSUE THREAD

**Issue by r-novel** [pion/webrtc#1390]
### Your environment.
  - Version: Pion WebRTC v3.0.0-beta.1
  - Browser: Firefox 79, 80.0

### What did you do?
Build a Simulcast sample from examples;

### What did you expect?
Three different quality streams in the browser;

### What happened?
Error message: `OnTrack will not be fired. incoming SSRC failed Simulcast probing`

I've tried to skip incoming SSRCes and reproduce Chrome-like behavior, but I getting errors like that: `Incoming unhandled RTCP ssrc(3246989348), OnTrack will not be fired` for each stream.

**Comment by Sean-Der** [comment]
Moved to #1345
