### ISSUE TITLE
Is the server required to support ipV6?

### ISSUE THREAD

**Issue by 270734714** [pion/webrtc#1436]
![image](https://user-images.githubusercontent.com/23243054/93727542-22089f00-fbee-11ea-8f29-1e63b6872a56.png)

**Comment by Sean-Der** [comment]
Hey @270734714 

This is a Pion issue, but something to do with https://caddyserver.com/

I would ask on their GitHub issues and look at the docs around automatic cert generation! You can launch it directly and use the config files [here](https://github.com/pion/ion-app-web/blob/master/configs/caddy/Caddyfile) if that helps.

thanks for using Pion :)
