### ISSUE TITLE
Codec matching during signaling should not be case sensitive

### ISSUE THREAD

**Issue by cnjeffliu** [pion/webrtc#1442]
I use the lib v2.2.25， but there is no audio when browser open the URL, and the video is ok.
It is ok to use v2.2.0， so I research the commit , I found the commit 846257b.
I upcase the opus , It run ok now.
vendor\github.com\pion\webrtc\v2\mediaengine.go:172
Opus = "opus"
to 
Opus = "OPUS"

**Comment by Sean-Der** [comment]
Hey @cnjeffliu 

What browser are you using? Are you offering/answering? Can you reproduce this using `play-from-disk`?

thanks!

**Comment by cnjeffliu** [comment]
I think, the code :
func (m *MediaEngine) getCodecSDP(sdpCodec sdp.Codec) (*RTPCodec, error) {
	for _, codec := range m.codecs {
		if codec.Name == sdpCodec.Name &&
			codec.ClockRate == sdpCodec.ClockRate &&
			(sdpCodec.EncodingParameters == "" ||
				strconv.Itoa(int(codec.Channels)) == sdpCodec.EncodingParameters) &&
			codec.SDPFmtpLine == sdpCodec.Fmtp { // pion/webrtc#43
			return codec, nil
		}
	}
	return nil, ErrCodecNotFound
}
must be fixed to:
func (m *MediaEngine) getCodecSDP(sdpCodec sdp.Codec) (*RTPCodec, error) {
	for _, codec := range m.codecs {
		if strings.EqualFold(codec.Name, sdpCodec.Name) &&
			codec.ClockRate == sdpCodec.ClockRate &&
			(sdpCodec.EncodingParameters == "" ||
				strconv.Itoa(int(codec.Channels)) == sdpCodec.EncodingParameters) &&
			codec.SDPFmtpLine == sdpCodec.Fmtp { // pion/webrtc#43
			return codec, nil
		}
	}
	return nil, ErrCodecNotFound
}

**Comment by Sean-Der** [comment]
@cnjeffliu that diff looks good to me!

If you can submit a PR I would be happy to merge it right away :)

**Comment by Sean-Der** [comment]
@cnjeffliu are you still interested in submitting this PR?

**Comment by rahulnakre** [comment]
I can submit a PR today
