### ISSUE TITLE
data-channels-detach-create does not work

### ISSUE THREAD

**Issue by umbrellary** [pion/webrtc#1473]
Hi

I tried the following sample code, but both V2 and V3 report errors:

https://github.com/pion/webrtc/blob/master/examples/data-channels-detach-create/main.go

LOG
----------------
eyJ0eXBlIjoib2ZmZXIiLCJzZHAiOiJ2PTBcclxubz0tIDM2MTM0MDU3NDQ3MjY0Nzc3NTUgMTYwMjIzNDk5OCBJTiBJUDQgMC4wLjAuMFxyXG5zPS1cclxudD0wIDBcclxuYT1maW5nZXJwcmludDpzaGEtMjU2IDQ3OjYzOkI5OkZBOjMzOjM5OkYxOjRBOjg5OjA1OjVGOkJEOjdGOkYxOjYzOjRGOkRFOkY0OjYxOkRDOjc0OjFCOkM0Ojg2OjMzOjhCOjg2OkEzOjA4OjhFOjcxOkQ3XHJcbmE9Z3JvdXA6QlVORExFIDBcclxubT1hcHBsaWNhdGlvbiA5IERUTFMvU0NUUCA1MDAwXHJcbmM9SU4gSVA0IDAuMC4wLjBcclxuYT1zZXR1cDphY3RwYXNzXHJcbmE9bWlkOjBcclxuYT1zZW5kcmVjdlxyXG5hPXNjdHBtYXA6NTAwMCB3ZWJydGMtZGF0YWNoYW5uZWwgMTAyNFxyXG5hPWljZS11ZnJhZzpKSXZvWHlNUE9SZ1NsT2FjXHJcbmE9aWNlLXB3ZDpzd3hkblROTnFrb3NjYm5OQ291aHN2ZlZLT1N1a0d1SVxyXG5hPWNhbmRpZGF0ZToxMTQ2MTE4OTExIDEgdWRwIDIxMzA3MDY0MzEgMTcyLjE4LjEuOSA0NzE0NSB0eXAgaG9zdFxyXG5hPWNhbmRpZGF0ZToxMTQ2MTE4OTExIDIgdWRwIDIxMzA3MDY0MzEgMTcyLjE4LjEuOSA0NzE0NSB0eXAgaG9zdFxyXG5hPWNhbmRpZGF0ZToyMzM3NjIxMzkgMSB1ZHAgMjEzMDcwNjQzMSAxNzIuMTcuMC4xIDM4MzA1IHR5cCBob3N0XHJcbmE9Y2FuZGlkYXRlOjIzMzc2MjEzOSAyIHVkcCAyMTMwNzA2NDMxIDE3Mi4xNy4wLjEgMzgzMDUgdHlwIGhvc3RcclxuYT1jYW5kaWRhdGU6NTE2MTk0Mjg1IDEgdWRwIDE2OTQ0OTg4MTUgMjE2LjI0LjE4OC4xOTUgMzk5MzggdHlwIHNyZmx4IHJhZGRyIDAuMC4wLjAgcnBvcnQgNDM3MzNcclxuYT1jYW5kaWRhdGU6NTE2MTk0Mjg1IDIgdWRwIDE2OTQ0OTg4MTUgMjE2LjI0LjE4OC4xOTUgMzk5MzggdHlwIHNyZmx4IHJhZGRyIDAuMC4wLjAgcnBvcnQgNDM3MzNcclxuYT1lbmQtb2YtY2FuZGlkYXRlc1xyXG4ifQ==
eyJ0eXBlIjoib2ZmZXIiLCJzZHAiOiJ2PTBcclxubz0tIDYyMjM0MDU1NjIwNTEwMTM3MjYgMTYwMjIzNTAwMSBJTiBJUDQgMC4wLjAuMFxyXG5zPS1cclxudD0wIDBcclxuYT1maW5nZXJwcmludDpzaGEtMjU2IDU5OjhCOjhCOjQ1OkEyOkJBOjFGOjhFOkY0OjFFOjI5OkFBOjBEOjQ3OkU5OjAzOjJBOjE3OjdCOjRFOjIxOkE5OjM2OjYwOjQwOjU2OkY1OjZDOkYzOjRFOkZEOjQ4XHJcbmE9Z3JvdXA6QlVORExFIDBcclxubT1hcHBsaWNhdGlvbiA5IERUTFMvU0NUUCA1MDAwXHJcbmM9SU4gSVA0IDAuMC4wLjBcclxuYT1zZXR1cDphY3RwYXNzXHJcbmE9bWlkOjBcclxuYT1zZW5kcmVjdlxyXG5hPXNjdHBtYXA6NTAwMCB3ZWJydGMtZGF0YWNoYW5uZWwgMTAyNFxyXG5hPWljZS11ZnJhZzpLUWxRTURzQnFCWUttYVFJXHJcbmE9aWNlLXB3ZDpHWm5aTm9OTVJobGh0d29UUXpnRFFOREhIRGdFY2t1alxyXG5hPWNhbmRpZGF0ZToxNDQ3NzY5NTQ5IDEgdWRwIDIxMzA3MDY0MzEgMTcyLjE2LjIxLjEzIDMzMDAwIHR5cCBob3N0XHJcbmE9Y2FuZGlkYXRlOjE0NDc3Njk1NDkgMiB1ZHAgMjEzMDcwNjQzMSAxNzIuMTYuMjEuMTMgMzMwMDAgdHlwIGhvc3RcclxuYT1jYW5kaWRhdGU6MjMzNzYyMTM5IDEgdWRwIDIxMzA3MDY0MzEgMTcyLjE3LjAuMSAzMDcyNyB0eXAgaG9zdFxyXG5hPWNhbmRpZGF0ZToyMzM3NjIxMzkgMiB1ZHAgMjEzMDcwNjQzMSAxNzIuMTcuMC4xIDMwNzI3IHR5cCBob3N0XHJcbmE9Y2FuZGlkYXRlOjExNjQ3MjU0MzkgMSB1ZHAgMTY5NDQ5ODgxNSAyMjEuMjI0LjYzLjI2IDMzMjQ0IHR5cCBzcmZseCByYWRkciAwLjAuMC4wIHJwb3J0IDMzMjQ0XHJcbmE9Y2FuZGlkYXRlOjExNjQ3MjU0MzkgMiB1ZHAgMTY5NDQ5ODgxNSAyMjEuMjI0LjYzLjI2IDMzMjQ0IHR5cCBzcmZseCByYWRkciAwLjAuMC4wIHJwb3J0IDMzMjQ0XHJcbmE9ZW5kLW9mLWNhbmRpZGF0ZXNcclxuIn0=

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x73714a]

goroutine 1 [running]:
github.com/pion/webrtc/v3.(*PeerConnection).SetRemoteDescription(0xc0001016c0, 0x1, 0xc0000ba380, 0x37c, 0x0, 0x4fd, 0x0)
	/opt/gopath/pkg/mod/github.com/pion/webrtc/v3@v3.0.0-beta.7/peerconnection.go:982 +0xb0a
main.main()
	/home/harry/projects/go-ice-tcp/main.go:107 +0x5a5

**Comment by Sean-Der** [comment]
Hey @umbrellary 

I was not able to reproduce this. I ran the example at 7b72d684e541b9a38b66ae4593db366f7b51913d Are you able to share `go-ice-tcp/main.go` ?

Looking at that code I am not able to immediately figure out what is happening. Can you try running your programing with `-race`?

**Comment by Sean-Der** [comment]
@umbrellary if you are still having issues please re-open.

I am not able to reproduce this, but would love to fix if you are still having issues. thanks for using Pion!

**Comment by umbrellary** [comment]
package main

import (
	"fmt"
	"io"
	"time"

	"github.com/pion/webrtc/v3"
)

func main() {

	// Create a SettingEngine and enable Detach
	s := webrtc.SettingEngine{}
	s.DetachDataChannels()
	s.SetEphemeralUDPPortRange(30000, 49999)
	s.SetNetworkTypes([]webrtc.NetworkType{webrtc.NetworkTypeUDP4})

	// Create the API object with the MediaEngine
	API := webrtc.NewAPI(webrtc.WithSettingEngine(s))

	// Prepare the configuration
	config := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	}

	// Create a new RTCPeerConnection using the API object
	peerConnection, err := API.NewPeerConnection(config)
	if err != nil {
		panic(err)
	}

	// Create a datachannel with label 'data'
	dataChannel, err := peerConnection.CreateDataChannel("data", nil)
	if err != nil {
		panic(err)
	}

	// Set the handler for ICE connection state
	// This will notify you when the peer has connected/disconnected
	peerConnection.OnICEConnectionStateChange(func(connectionState webrtc.ICEConnectionState) {
		fmt.Printf("ICE Connection State has changed: %s\n", connectionState.String())
	})

	// Register channel opening handling
	dataChannel.OnOpen(func() {
		fmt.Printf("Data channel '%s'-'%d' open.\n", dataChannel.Label(), dataChannel.ID())

		// Detach the data channel
		raw, dErr := dataChannel.Detach()
		if dErr != nil {
			panic(dErr)
		}

		// Handle reading from the data channel
		go ReadLoop(raw)

		// Handle writing to the data channel
		go WriteLoop(raw)
	})

	// Create an offer to send to the browser
	offer, err := peerConnection.CreateOffer(nil)
	if err != nil {
		panic(err)
	}

	// Create channel that is blocked until ICE Gathering is complete
	gatherComplete := webrtc.GatheringCompletePromise(peerConnection)

	// Sets the LocalDescription, and starts our UDP listeners
	err = peerConnection.SetLocalDescription(offer)
	if err != nil {
		panic(err)
	}

	// Block until ICE Gathering is complete, disabling trickle ICE
	// we do this because we only can exchange one signaling message
	// in a production application you should exchange ICE Candidates via OnICECandidate
	<-gatherComplete

	// Output the offer in base64 so we can paste it in browser
	fmt.Println(Encode(*peerConnection.LocalDescription()))

	// Wait for the answer to be pasted
	answer := webrtc.SessionDescription{}
	Decode(MustReadStdin(), &answer)

	// Apply the answer as the remote description
	err = peerConnection.SetRemoteDescription(answer)
	if err != nil {
		panic(err)
	}

	// Block forever
	select {}
}

// ReadLoop shows how to read from the datachannel directly
func ReadLoop(d io.Reader) {
	for {
		buffer := make([]byte, 15)
		n, err := d.Read(buffer)
		if err != nil {
			fmt.Println("Datachannel closed; Exit the readloop:", err)
			return
		}

		fmt.Printf("Message from DataChannel: %s\n", string(buffer[:n]))
	}
}

// WriteLoop shows how to write to the datachannel directly
func WriteLoop(d io.Writer) {
	counter := 0
	for range time.NewTicker(5 * time.Second).C {
		counter++
		message := fmt.Sprintf("-->%d", counter)
		fmt.Printf("Sending %s \n", message)

		_, err := d.Write([]byte(message))
		if err != nil {
			panic(err)
		}
	}
}

**Comment by umbrellary** [comment]
I will try, thank you very much！
