### ISSUE TITLE
Nack vs slidingWindowDetector

### ISSUE THREAD

**Issue by masterada** [pion/webrtc#1477]
### Your environment.
  - Version: latest master (fdbf5b5c90a8479221cb46c3947db58d04678da3)
  - Browser: chrome

### What did you do?
I started fiddling with NACK, with a browser -> pion stream.

### What did you expect?
Nacked packets to arrive.

### What happened?
Nacked packets did not arrive.

I found out that slidingWindowDetector https://github.com/pion/transport/blob/master/replaydetector/replaydetector.go, which is enabled by default, limits how "old" an arriving packet can be. This can easily cause a resent packet (because of nack) to be dropped.

### Workaround
After calling settingEngine.DisableSRTPReplayProtection(true), the packets arrive as expected.

**Comment by Sean-Der** [comment]
@at-wat what do you think, maybe we can losen the restrictions?

Another thing that people do is have a unique SSRC for NACKs (and then the Payload is the old RTP Packet) that would get you around this!

**Comment by at-wat** [comment]
https://tools.ietf.org/html/rfc3711#section-3.3.2
>  A packet is "replayed" when it is stored by an adversary, and then re-injected into the network. When message authentication is provided, SRTP protects against such attacks through a Replay List. Each SRTP receiver maintains a Replay List, which conceptually contains the indices of all of the packets which have been received and authenticated. In practice, the list can use a "sliding window" approach, so that a fixed amount of storage suffices for replay protection. Packet indices which lag behind the packet index in the context by more than SRTP-WINDOW-SIZE can be assumed to have been received, where SRTP-WINDOW-SIZE is a receiver-side, implementation- dependent parameter and MUST be at least 64, but which MAY be set to a higher value.

The window size is a balance of memory usage vs duration how long can the stream be delayed. And it highly depends on the application. (Current default value is a minimum allowed value in RFC.)

Users can specify the window size by `SettingEngine.SetSRTPReplayProtectionWindow(uint)` and `SettingEngine.SetSRTCPReplayProtectionWindow(uint)`.

**Comment by masterada** [comment]
Thanks for the clarification. I guess i will just leave it turned off for RTP for now as our jitter buffer already handles deduping, and using different SSRC sounds really painful for now (might try it later).

One thing that occured to me after reading into the linked rfc, is that this call: `markAsValid, ok := s.replayDetector.Check(uint64(header.SequenceNumber))` does not seem to account for the ROC. Wouldn't this cause issues at rollovers?

**Comment by at-wat** [comment]
> One thing that occured to me after reading into the linked rfc, is that this call: `markAsValid, ok := s.replayDetector.Check(uint64(header.SequenceNumber))` does not seem to account for the ROC. Wouldn't this cause issues at rollovers?

In the ReplayDetector, wrapping (rollover) of the sequence number is handled. I think it should work correctly on rollover as tested in the following test cases:
https://github.com/pion/transport/blob/7f160b47c670d5b0ada9734010f0a901f7bac443/replaydetector/replaydetector_test.go#L145-L171

> using different SSRC sounds really painful for now

Just for the information, using same SSRC in multiple streams may cause potential security weakness by using same initial vector in encryption. In worst case when using AES-GCM mode, just only a single pair of packets with same IV is required to break authentication.

**Comment by masterada** [comment]
You are right, thanks. 

> Just for the information, using same SSRC in multiple streams may cause potential security weakness by using same initial vector in encryption. In worst case when using AES-GCM mode, just only a single pair of packets with same IV is required to break authentication.

Maybe i misunderstood something, i thought @Sean-Der recommended to use a different SSRC for NACK alone. I use pion on the receiver side, so the stream SSRCs are determined by the browser.

**Comment by jech** [comment]
> Just for the information, using same SSRC in multiple streams may cause potential security weakness

I don't think that masterada is using the same SSRC for multiple tracks.  He's using a single track that is used for both the original data and resent data, which is what causes the issue.

It would be better to use a separate RTX track for the resent data, but I don't know how to achieve that with Pion.

**Comment by masterada** [comment]
Thanks @jech, finally found what you guys are talking about: https://tools.ietf.org/html/rfc4588 . Just when you think you got something working, there is always another rfc behind the corner.
