### ISSUE TITLE
recovered with non-error value: (string) ValueOf: invalid value

### ISSUE THREAD

**Issue by BenLubar** [pion/webrtc#1484]
Caused by this line:

https://github.com/pion/webrtc/blob/7fc6f5435bfb651abb5d609a84e8763579da6105/peerconnection_js.go#L655

should be passed through `stringPointerToValue` before being put into the map

**Comment by Sean-Der** [comment]
Nice catch @BenLubar 

Would you be able to submit a PR (and a test?) I would love to merge them right away :)
