### ISSUE TITLE
OnnegotiationNeeded should get triggered after negotiation is done and still the negotiation is needed.

### ISSUE THREAD

**Issue by sumeet-tiwari-samespace** [pion/webrtc#1491]
### Your environment.
  - Version: Latest
  - Browser: doesn't matter here

### What did you do?
Added a track right after creating answer, but negotiation was not complete yet, but no onNegotiationNeeded is triggered ever , even after negotiation got completed.

### What did you expect?
OnnegotiationNeeded should get triggered once negotiation is completed 

### What happened?
OnnegotiationNeeded was not fired.

It fires only when track is added after negotiation is completed.

**Comment by tarrencev** [comment]
@sumeet-tiwari-samespace thanks for creating this issue. can you provide a test that reproduces this issue?

**Comment by sumeet-tiwari-samespace** [comment]
@tarrencev 
In any example , Lets say in simulcast example. After SetLocalDescription, add another new track. Like this
```
err = peerConnection.SetLocalDescription(answer)
	if err != nil {
		panic(err)
	}

outputTrack, err = peerConnection.NewTrack(videoCodecs[0].PayloadType, randutil.NewMathRandomGenerator().Uint32(), "video_x", "pion_x")
	if err != nil {
		panic(err)
	}
outputTracks["x"] = outputTrack
```
Then OnnegotiationNeeded should trigger after negotiation is done, coz the peerconnection still needs negotiation as the new track was added after creating answer. 
The behaviour is explained here.
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onnegotiationneeded

**Comment by tekig** [comment]
@sumeet-tiwari-samespace you add a track to PeerConnection?

```go
sender, err := peerConnection.AddTrack(outputTrack)
```

**Comment by sumeet-tiwari-samespace** [comment]
yes @tekig

**Comment by tekig** [comment]
@sumeet-tiwari-samespace 
I tried to reproduce the problem but there are no errors.
Earlier, for manual testing, an [example ](https://github.com/pion/webrtc/pull/1359/commits/99a6d98b3555c05f2960432bd5b2b72ecce08ef8) was written that allowed creating/deleting tracks/channels locally/remotely, but it was very confusing and was deleted.
I added a track according to your example, [here](https://github.com/pion/webrtc/pull/1359/commits/99a6d98b3555c05f2960432bd5b2b72ecce08ef8#diff-fc3fbe9fd3b2d64c409a46963ae910c32ec9bace6e70b14cc47daba188d7c6dfR88) I added the addition of a new track as [here](https://github.com/pion/webrtc/pull/1359/commits/99a6d98b3555c05f2960432bd5b2b72ecce08ef8#diff-fc3fbe9fd3b2d64c409a46963ae910c32ec9bace6e70b14cc47daba188d7c6dfR105-R111), but negotiation passed as required. 

I may have misunderstood your problem, can you please attach the full code for testing.

**Comment by Sean-Der** [comment]
Resolving for lack of activity

@sumeet-tiwari-samespace if you are still have this issue/other repro ideas please re-open! thank you
