### ISSUE TITLE
data-channels exapmle not work

### ISSUE THREAD

**Issue by takchichan** [pion/webrtc#1495]
### Environment
  - Version: v3
  - Browser: mozilla firefox 81.0.2

### What I did
open the following url:
**http://localhost:8080/example/js/data-channels/**

### What happened?
console output the following message:
**WebRTC: ICE failed, add a TURN server and see about:webrtc for more details**

**Comment by Sean-Der** [comment]
Hey @takchichan sorry I have been busy.

Did you copy/paste the Session Description messages back and forth?

Are you running FireFox + Go on the same machine?

thanks

**Comment by Sean-Der** [comment]
Hey @takchichan 

I am going to close this for now. I hope you were able to get it working for you.

If you are still having issues please re-open!
