### ISSUE TITLE
Play from play from Disk Renegotation 

### ISSUE THREAD

**Issue by entrehuihui** [pion/webrtc#1497]
First of all, thank the author for his contribution。
I have a project to use Webrtc, I have seen a lot of examples, I think the example of play from Disk Renegotation is in line with my development, the difference is that the example reads the stream from the file, I hope to push the stream against FFMpeg, what should I do, I refer to the example of RTP to WebrTC, but unfortunately, I did not succeed, thank you for any help

**Comment by Sean-Der** [comment]
Hey! Sorry for the delay.

Do you mind sharing with you tried with `rtp-to-webrtc` so far? What files/format are you trying to consume?

thanks

**Comment by Sean-Der** [comment]
Hey @entrehuihui I am closing this for now. I am hoping you were able to get it working.

If you weren't able to make it work please re-open and I am happy to help :)
