### ISSUE TITLE
ICE connection state changes to "Disconnected" 30 seconds after it connected in complex NAT 

### ISSUE THREAD

**Issue by yourchanges** [pion/webrtc#1500]
### Your environment.
  - Version: pion/webrtc v2.2.24
  - Browser: chrome 86.0.4240.111 64bit
  - Other Information 
turn server(gortcd) config

```
peerConnection, err := api.NewPeerConnection(webrtc.Configuration{
			ICEServers: []webrtc.ICEServer{

				{
					URLs: []string{"turn:103.23.11.252:3478"},
					Username: "webrtc",
					Credential:"google",
					CredentialType:webrtc.ICECredentialTypePassword,
				},
			},
		})
```

### What did you do?
I just run the https://github.com/deepch/RTSPtoWebRTC lastest version

deploy it a public ip server, when my browser and RTSPtoWebRTC server in the same LAN, it works normally.

when I open the browser in the other network env, it can open the webrtc vedio stream, the data channel is ok, but it will disconnected in 30 seconds.

### What did you expect?

it works  or  give some tips how to work around.
### What happened?

server side log:
```
2020/10/30 21:51:46 Connection State has changed connected 
2020/10/30 21:51:46 complete
2020/10/30 21:51:46 start stream HQ-3 client 7F5EB57B-2EC8-D515-9BC5-A46E1F4D0CE3
2020/10/30 21:52:17 Client Close Keep-Alive Timer
2020/10/30 21:52:17 Connection State has changed closed 
2020/10/30 21:52:17 complete
2020/10/30 21:52:17 Client Close Exit
2020/10/30 21:52:17 stop stream HQ-3 client 7F5EB57B-2EC8-D515-9BC5-A46E1F4D0CE3

```
chrome browser log:
```
add video Transceiver
checking
1 track is delivered
connected
disconnected
```
chrome webrtc internal

```
Time	Event
2020/10/30 9:51:46	
createLocalDataChannel
2020/10/30 9:51:46	negotiationneeded
2020/10/30 9:51:46	
createOffer
2020/10/30 9:51:46	
createOfferOnSuccess
2020/10/30 9:51:46	
setLocalDescription
2020/10/30 9:51:46	
transceiverModified
2020/10/30 9:51:46	
signalingstatechange
2020/10/30 9:51:46	setLocalDescriptionOnSuccess
2020/10/30 9:51:46	
icegatheringstatechange
2020/10/30 9:51:46	
icecandidateerror
2020/10/30 9:51:46	
icecandidateerror
2020/10/30 9:51:46	
icecandidate (host)
2020/10/30 9:51:46	
icecandidate (host)
2020/10/30 9:51:46	
icecandidate (srflx)
2020/10/30 9:51:46	
icecandidate (srflx)
2020/10/30 9:51:46	
setRemoteDescription
2020/10/30 9:51:46	
iceconnectionstatechange
2020/10/30 9:51:46	
transceiverModified
2020/10/30 9:51:46	
signalingstatechange
2020/10/30 9:51:46	setRemoteDescriptionOnSuccess
2020/10/30 9:51:46	
iceconnectionstatechange (legacy)
2020/10/30 9:51:46	
connectionstatechange
2020/10/30 9:51:46	
icecandidate (relay)
2020/10/30 9:51:46	
icegatheringstatechange
2020/10/30 9:51:46	
iceconnectionstatechange
2020/10/30 9:51:46	
iceconnectionstatechange (legacy)
2020/10/30 9:51:46	
connectionstatechange
2020/10/30 9:52:01	
iceconnectionstatechange (legacy)
completed
2020/10/30 9:52:16	
iceconnectionstatechange
2020/10/30 9:52:16	
iceconnectionstatechange (legacy)
connected
2020/10/30 9:52:16	
iceconnectionstatechange (legacy)
failed
2020/10/30 9:52:16	
connectionstatechange
failed
```

**Comment by yourchanges** [comment]
also see:

https://github.com/deepch/RTSPtoWebRTC/issues/52

**Comment by jech** [comment]
Is this a unidirectional stream?  Are you sending receiver reports?

**Comment by yourchanges** [comment]
The browser side peer, just receive the audio and vedio stream to play, and send a ping msg every second through the data channel, here is code:

```
log('add audio Transceiver')
        pc.addTransceiver('audio', {
          'direction': 'sendrecv'
        })

log('add video Transceiver')
      pc.addTransceiver('video', {
        'direction': 'sendrecv'
      });
      //send ping becouse PION not handle RTCSessionDescription.close()
      sendChannel = pc.createDataChannel('foo');
      sendChannel.onclose = () => console.log('sendChannel has closed');
      sendChannel.onerror = (err) => log(err);
      sendChannel.onopen = () => {
        console.log('sendChannel has opened');
        sendChannel.send('ping');
        setInterval(() => {
          sendChannel.send('ping');
        }, 1000)
      }
      sendChannel.onmessage = e => log(`Message from DataChannel '${sendChannel.label}' payload '${e.data}'`);

...
pc.ontrack = function(event) {
  log(event.streams.length + ' track is delivered')
  var el = document.createElement(event.track.kind)
  el.srcObject = event.streams[0]
  el.muted = true
  el.autoplay = true
  el.controls = true
  el.width = 600
  document.getElementById('remoteVideos').appendChild(el)
}
```

full app.js is here https://github.com/deepch/RTSPtoWebRTC/blob/master/web/static/js/app.js

**Comment by yourchanges** [comment]
> Is this a unidirectional stream? Are you sending receiver reports?

I also try set it like this, but it fails too.
```
pc.addTransceiver('video', {
        'direction': 'recvonly'
      });
```

but I  try rewrite the js client by  ios and android native webrtc sdk, it works without any problem.

**Comment by cedricve** [comment]
@yourchanges i am working with the same repo, and indeed the stream is sometimes hanging and disconnects. Looks like in the golang project it halts while sending the stream. Could we reach out to look into this together @yourchanges ?

**Comment by yourchanges** [comment]
@cedricve  yes, sure.  but I face the problem every time , and I think my problem is a ICE problem (maybe some incorrect ice config on ice sever or webrtc peers). and your stream is sometimes hanging and disconnect, it's another problem.

**Comment by Sean-Der** [comment]
@yourchanges It looks like gortcd was the issue? Switching to coturn fixed everything?

**Comment by yourchanges** [comment]
@Sean-Der  yes, for me it is.

**Comment by Sean-Der** [comment]
Resolving. Looks like we got this fixed up a while ago and just forgot to close :)

If anyone is still having issues please re-open.

**Comment by HidalgoIvan** [comment]
> @yourchanges It looks like gortcd was the issue? Switching to coturn fixed everything?

What do you mean by switching to coturn? I'm currently facing the same problem

**Comment by yourchanges** [comment]
@HidalgoIvan when switched too coturn, my problem just gone.
