### ISSUE TITLE
RTP -> WebRTC Poor audio quality

### ISSUE THREAD

**Issue by regata** [pion/webrtc#1514]
### Your environment.
  - Version: github.com/pion/webrtc/v3 v3.0.0-beta.12
  

### What did you do?

Hello,

I'm trying to send audio to the browser but quality is bad and very choppy. There are many examples how to do it with video but I couldn't anything for audio. I'd be happy to contribute such example here but first need to get it working.

I have the following setup:
* Generate RTP stream using ffmpeg
```sh
ffmpeg -f pulse -i default -c:a libopus -b:a 48000 -ssrc 1 -payload_type 111 -f rtp rtp:/127.0.0.1:5004
```

```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 58.20.100
m=audio 5004 RTP/AVP 111
b=AS:48
a=rtpmap:111 opus/48000/2
a=fmtp:111 sprop-stereo=1
```
* Read RTP stream in Go and write packets to audio track using standard code

```go
...
engine.RegisterCodec(webrtc.NewRTPOpusCodec(webrtc.DefaultPayloadTypeOpus, 48000))
...
// audio ssrc = 1
audioTrack, err := conn.NewTrack(webrtc.DefaultPayloadTypeOpus, 1, "audio", "rapp")
...
conn.AddTransceiverFromTrack(audioTrack, webrtc.RTPTransceiverInit{
    Direction: webrtc.RTPTransceiverDirectionSendonly,
})
...
func (p *Peer) WriteAudioRTP(packet *rtp.Packet) {
    if err := p.audioTrack.WriteRTP(packet); err != nil {
        log.Printf("Failed to WriteRTP: %s\n", err)
    }
}
```

* The browser get the following offer

```
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=ice-ufrag:sRQwbQzElcwkaMpj
a=ice-pwd:VgWqhaAYVFktDlUDzEMCKXCiPZelXlgo
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=ssrc:1 cname:rapp
a=ssrc:1 msid:rapp audio
a=ssrc:1 mslabel:rapp
a=ssrc:1 label:audio
a=msid:rapp audio
a=sendonly
```

### What did you expect?

As I said above I can hear and recognize the sound but the quality is bad.

Any help would be appreciated!

**Comment by Sean-Der** [comment]
That all looks right to me!

In `chrome://webrtc-internals` can you see how much packet loss you are experiencing? 

My guess is that either the audio is bad (re-sampling/bad packetization/$x) OR you are seeing packet loss. If you can rule loss out, I have some debugging ideas.

**Comment by regata** [comment]
AFAIK, no packet loss `Lost: 0`

```
RTP Stats
2f47ecb1

Local: 01:03:39 GMT-0500 (Eastern Standard Time) inbound-rtp SSRC: 1 Received: 10068 packets (373.08 Kb , ~6.6 Kbps) Lost: 0 Jitter: 0.026
```

Not sure if it's related but I noticed some differences between ffmpeg's and pion's codec parameters:
* ffmpeg: `a=fmtp:111 sprop-stereo=1`
* pion: `a=fmtp:111 minptime=10;useinbandfec=1`.

Also pion sets `a=rtcp-mux` but, AFAIK, ffmpeg does not have it

Thank you for your help!

**Comment by regata** [comment]
Here is Chrome debug output for the audio channel https://i.imgur.com/8haT8lT.png

**Comment by jech** [comment]
Interesting.  Packets lost is 0, but concealed samples is on the order of 20%.

Perhaps some samples are dropped before being encapsulated in RTP?

**Comment by regata** [comment]
I validated that RTP stream looks correct by encoding and decoding it locally:

Encoding:
`ffmpeg -f pulse -i default -c:a libopus -b:a 48000 -ssrc 1 -payload_type 111 -f rtp -sdp_file rtp.sdp rtp:/127.0.0.1:5004
9:02`

Decoding:
`ffmpeg -protocol_whitelist rtp,file,udp -i rtp.sdp audio.mp3`

Do you think that Opus codec parameters between ffmpeg and what Pion offers to the browser is the issue?

> * ffmpeg: `a=fmtp:111 sprop-stereo=1`
> * pion: `a=fmtp:111 minptime=10;useinbandfec=1`
> 
> Also pion sets a=rtcp-mux but, AFAIK, ffmpeg does not have it

**Comment by regata** [comment]
I also plotted RTP packet sequence numbers and timestamps. These are the packets i read off the rtp stream produced by ffmpeg. May be it has additional clues?

![](https://i.imgur.com/smxuwig.png)

**Comment by JVillella** [comment]
@Sean-Der and I paired a bit over the #pion Slack channel. The primary issue turned out to be ffmpeg's packetizing. Instead of directly forwarding these packets, we re-packetize them w/ pion.

Instead of,

```go
if err := p.audioTrack.WriteRTP(packet); err != nil {
	log.Printf("Failed to WriteRTP: %v\n", err)
}
```

We did,

```go
if err := p.audioTrack.WriteSample(media.Sample{Data: packet.Payload, Samples: 960 }); err != nil {
	log.Printf("Failed to WriteRTP: %v\n", err)
}
```

That was an enormous improvement to the audio quality. This was the final ffmpeg command we used (bit different than when we started. It also contributed to the final quality improvement),

```bash
ffmpeg -f pulse -i default -c:a libopus -b:a 48000 -sample_fmt s16p -ssrc 1 -payload_type 111 -f rtp -max_delay 0 -application lowdelay rtp:/127.0.0.1:5004
```

**Comment by JVillella** [comment]
[before-after.zip](https://github.com/pion/webrtc/files/5521957/before-after.zip)

Also, here are before and after audio samples ^

**Comment by any1** [comment]
I was having a similar problem and I found out that adding an "adelay" filter with zero delay solved the problem. That's `-af 'adelay=0|0'` for anyone who's curious.

**Comment by patrickcorrigan** [comment]
@any1, that worked! Thank you so much! Any idea why it works?

**Comment by any1** [comment]
@patrickcorrigan, If I remember correctly, the `adelay` filter re-packetizes the stream into even 960 sample intervals.
