### ISSUE TITLE
DataChannel is Closed but PeerConnection.ICEConnectionState is Connected

### ISSUE THREAD

**Issue by txthinking** [pion/webrtc#1518]
I am not sure this is a bug or w3c api is unfriendly.

### Description

Two peers: both pion.webrtc
What I do: create a datachannel and send data each other
Result: everything is ok

But: A accidental problem unable to reproduce. So I write this issue.

### Accidental Problem

DataChannel.ReadyState() is closed but PeerConnection.ICEConnectionState is still connected.

### Question

1. Is this problem standards compliant?
2. Will DataChannel.ReadyState() back to open state?
3. If 2 is no, how to reconnect the datachannel?(looks like DataChannel.OnOpen only be fired on first time, even if ICERestart)

Thank you.

**Comment by Sean-Der** [comment]
Did the remote peer call `DataChannel.Close()`?

The ICEConnection and DataChannel shouldn't interact (but we could have a bug here!). Even after a ICE Restart the DatatChannel should still work, it will just queue data while things aren't connected.

thanks for reporting and using Pion :)

**Comment by txthinking** [comment]
> Did the remote peer call `DataChannel.Close()`?
> 
Yes,
I use ordered, negotiated DataChannel, and MaxRetransmits = 10(but looks like MaxRetransmits only works on in unreliable mode[1] I will remove it).
Set 10s timeout on send, if send error or timeout, the dc.close().

Recently, I am trying when timeout DO NOT dc.close()

> The ICEConnection and DataChannel shouldn't interact (but we could have a bug here!). Even after a ICE Restart the DatatChannel should still work, it will just queue data while things aren't connected.
> 
It looks like if DataChannel.send timeout (or cause rarely error, because it `Data sent before connecting is buffered if possible (or an error occurs if it's not possible), and is also buffered if sent while the connection is closing or closed.`), looks like we can't know the datachannel if works well currently, the only way is recreate peerconnection and rerun all steps, do I understand correct?

Thank you very much.
> thanks for reporting and using Pion :)

1: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createDataChannel

**Comment by Sean-Der** [comment]
@txthinking you can measure how much a DataChannel has queued, and make sure that packets are being ACKed. I think that is the most can do you. [datachannels-flow-control](https://github.com/pion/webrtc/tree/master/examples/data-channels-flow-control)

GetStats might have more info, but I don't know it that well.

**Comment by txthinking** [comment]
Thank you @Sean-Der

**Comment by Sean-Der** [comment]
Thanks for using Pion @txthinking !

I added a test to demonstrate this behavior in 50e49758778f0ba8e3b42708a1c9ab7e333b54f1. Even though the PeerConnections are disconnected and `SendText` returned an error, the next time they reconnect the message is delivered. 

We need to start a FAQ that explains disconnections and shutdowns.
