### ISSUE TITLE
Track V3 Tasks Remaining

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#1526]
These are all the things we need to finish with V3 Track API 

* [x] Re-enable `TestPeerConnection_Media_Closed`
* [x] Rework API so that `Bind` is called in `SetRemoteDescription`
* [x] Write the following tests for new Track API
    - [x] Writing to a un-added Track
    - [x] Write to a track on Closed PeerConnection
    - [x] Write to a track on a disconnected PeerConnection
    - [x] Write to a track with one bad PeerConnection
    - [x] Offer fail when Answerer doesn't support a codec
    - [x] Answer fail when Offerer doesn't support a codec
    - [x] Does sending use the proper Payload type
* [ ] Make `TrackRemote` an interface
* [x] Review Public API for sharp edges.
    - [x] `MimeType` is currently case sensitive. Users will need to do `video/VP8` and `video/vp8`, anything we can do to help?
    - [x] Are we all clear to do all the use cases for Interceptor (NACK, FEC, Congestion Control, Stats)

**Comment by Sean-Der** [comment]
@at-wat @masterada @jeremija ^ following up on the other PR. Add anything else you think is important!

If you agree I would like to merge the other PR and then begin the process of getting this done for `v3.0.0`. We are so close, and really want more people involved :)

**Comment by at-wat** [comment]
> MimeType is currently case sensitive. Users will need to do `video/VP8` and `video/vp8`, anything we can do to help?

https://tools.ietf.org/html/rfc2045#section-2

> All numeric and octet values are given in decimal notation in this set of documents. All media type values, subtype values, and parameter names as defined are case-insensitive.  However, parameter values are case-sensitive unless otherwise specified for the specific parameter.

**Comment by at-wat** [comment]
I think as `TrackLocalStaticRTP` is in the main package, parameters like MTU is better to be configurable by users.
https://github.com/pion/webrtc/pull/1517#discussion_r523729641

**Comment by Sean-Der** [comment]
@at-wat That sounds good to me! If you want to start the `...opt` or doing a configuration struct I am happy with either.

**Comment by Sean-Der** [comment]
@jeremija @OrlandoCo Any interest in splitting/taking on any of these tasks? I am happy to do all of them, just don't want to duplicate work :)

**Comment by Sean-Der** [comment]
@at-wat I tried a few different ways (and failed) to make `TrackRemote` an interface. I might be missing something, but I don't see the value.

* I don't think we should encourage casting in `OnTrack`. Users are going to copy examples and be confused why they don't work.
* I can't think of any use cases that are blocked. Users can just chain `Read` into their own code etc...

**Comment by jeremija** [comment]
@Sean-Der so sorry for a late reply. Last week has been super crazy for me work-wise :frowning_face:. I see you've already implemented all of this (kudos to you!), and I just read your comment about how you ran into issues with the last task (making `TrackRemote` an interface))

**Comment by Sean-Der** [comment]
@jeremija no worries at all :) this all Open Source/for fun!

If you have some time approving https://github.com/pion/webrtc/pull/1546 would be a huge help.

**Comment by Sean-Der** [comment]
These are all merged, we are now just stabilizing `/v3` :partying_face:
