### ISSUE TITLE
Make WithMediaEngine to receive a pointer

### ISSUE THREAD

**Issue by OrlandoCo** [pion/webrtc#1538]
## Summary

Now that mediaengine allow to register and get ext map headers, api sould receive a pointer in order to use the ME outside Pion conext.

## Motivation

On pion-sfu the subscribers starts with not default codecs, once a user share it's media we need to register that media codec to not offer other codecs asside the one shared.

## Describe alternatives you've considered

No alternatives atm.

**Comment by Sean-Der** [comment]
👍 completely missed that, if you open a PR will merge right away.

I will also make a test to confirm that header extension queries work via public API.
