### ISSUE TITLE
About ErrSessionDescriptionConflictingIceUfrag

### ISSUE THREAD

**Issue by kiepluhanh97** [pion/webrtc#1541]
Hi,
I have go server and when I connect from my browser use javascript, everything will be ok.
But when I create a client on python to handle some AI process from webrtc (https://github.com/aiortc/aiortc), in SDP have two different **a=ice-ufrag:** lines when create buffer have **video** and **datachannel**. I got an error **SetRemoteDescription called with multiple conflicting ice-ufrag values**. Can you show me the reason of this error? When I use python as a server, it's ok with two different lines **a=ice-ufrag:**
Thanks,

**Comment by Sean-Der** [comment]
Hey @kiepluhanh97 

pion/webrtc requires that the remote Peer supports bundling. `aiortc` does support it, so I am not sure what the issue is.

One alternative would be to use two PeerConnections. We are not planning on supporting non-bundle in the short term though.

Thanks for using Pion, and happy to answer any other questions.

**Comment by quintenrosseel** [comment]
Hi Sean, thanks for all the great work that you are doing. 

I'm running into this exact same issue when using `aiortc`. I'd appreciate your input for solutions, as this is the only WebRTC library in Python. 

The error is defined under [errors.go](https://github.com/pion/webrtc/blob/271ab556c8a42e21ca49d18e5b046d9031367c86/errors.go#L121). 
```go 
// ErrSessionDescriptionConflictingIceUfrag  indicates SetRemoteDescription was called with a SessionDescription that
// contains multiple conflicting ice-ufrag values
ErrSessionDescriptionConflictingIceUfrag = errors.New(
    "SetRemoteDescription called with multiple conflicting ice-ufrag values"
)
```

It's triggered when setting the remote description,under [sdp.go](https://github.com/pion/webrtc/blob/271ab556c8a42e21ca49d18e5b046d9031367c86/sdp.go#L799).
```go 
for _, m := range remoteUfrags {
  if m != remoteUfrags[0] {
      return "", "", nil, ErrSessionDescriptionConflictingIceUfrag
  }
}
```

Below I attached a SDP example that triggers this error (with some obfuscations), with space/indentation readability. `aiortc` uses the `BUNDLE` expression in the SDP, but doesn't offer direct control over the values of what `ice-ufrag` and `ice-pwd` are. As @kiepluhanh97 mentions, when using the Javascript APIs directly, the `ice-ufrag` and `ice-pwd` are consistent across tracks, and everything works fine. In the SDP example below, the error gets triggered. 

With this context, and knowledge of the current state of the framework, is the only alternative to use one PeerConnection per track? 

```txt
v=0
o=- 3938608397 3938608397 IN IP4 0.0.0.0
s=-
t=0 0

a=group:BUNDLE 0 1
a=msid-semantic:WMS *

m=audio 61547 UDP/TLS/RTP/SAVPF 96 0 8
  c=IN IP6 2a02:a03f:63c3:ab01:8dd:b522:c44e:4c4a
  a=sendrecv
  a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
  a=extmap:2 urn:ietf:params:rtp-hdrext:ssrc-audio-level
  a=mid:0
  a=msid:cb8e4359-9b62-4c55-9e67-c6aafa14cb5e 073e433b-4499-4470-87b9-c823855577b4
  a=rtcp:9 IN IP4 0.0.0.0
  a=rtcp-mux
  a=ssrc:2665274437 cname:2492e33b-7366-49f3-8761-5f1fa9c2c67c
  a=rtpmap:96 opus/48000/2
  a=rtpmap:0 PCMU/8000
  a=rtpmap:8 PCMA/8000
  a=candidate:3d9fb1c05760a5aec3bb63582c0ee75f 1 udp 2130706431 2a02:a03f:63c3:ab01:8dd:b522:c44e:4c4a 61547 typ host
  a=candidate:b3f8102527b52eb84bbce9e970243c72 1 udp 2130706431 2a02:a03f:63c3:ab01:19ae:93db:2f2:7c29 50461 typ host
  a=candidate:7b995085fe42009d6857ed9f99301acb 1 udp 2130706431 192.168.XXX.XX 61487 typ host
  a=candidate:e5bcfe9c71647ac306da9adfe5d02ca8 1 udp 2130706431 192.168.XX.XXX 60962 typ host
  a=candidate:70277552984fbd952854c62500e75a48 1 udp 2130706431 fd82:6bd2:bee9:8cd7:892:8881:c79a:3fa9 61877 typ host
  a=candidate:bf46076bc5b044080f7d76470e336d40 1 udp 16777215 216.39.253.22 59791 typ relay raddr 192.168.129.25 rport 63566
  a=end-of-candidates

a=ice-ufrag:SOc1
a=ice-pwd:3G6gWKQO58pVo3tdBZnxgN
a=fingerprint:sha-256 3E:EE:9E:55:XX:CF:9C:9F:04:68:EB:XX:09:B7:DF:28:69:XX:58:80:8C:42:A1:1E:1C:XX:7A:C8:ED:37:D5:XX
a=setup:actpass

m=application 51010 DTLS/SCTP 5000
  c=IN IP6 2a02:a03f:63c3:ab01:8dd:b522:c44e:4c4a
  a=mid:1
  a=sctpmap:5000 webrtc-datachannel 65535
  a=max-message-size:65536
  a=candidate:3d9fb1c05760a5aec3bb63582c0ee75f 1 udp 2130706431 2a02:a03f:63c3:ab01:8dd:b522:c44e:4c4a 51010 typ host
  a=candidate:b3f8102527b52eb84bbce9e970243c72 1 udp 2130706431 2a02:a03f:63c3:ab01:19ae:93db:2f2:7c29 57433 typ host
  a=candidate:7b995085fe42009d6857ed9f99301acb 1 udp 2130706431 192.168.XXX.XX 64485 typ host
  a=candidate:e5bcfe9c71647ac306da9adfe5d02ca8 1 udp 2130706431 192.168.XX.XX 53464 typ host
  a=candidate:70277552984fbd952854c62500e75a48 1 udp 2130706431 fd82:6bd2:bee9:8cd7:892:8881:c79a:3fa9 57665 typ host
  a=candidate:bf46076bc5b044080f7d76470e336d40 1 udp 16777215 216.XX.XXX.XX 37545 typ relay raddr 192.168.129.25 rport 54827
  a=end-of-candidates

  a=ice-ufrag:1drh
  a=ice-pwd:u6bgmyXf3HzFaNq7blYQZ3
  a=fingerprint:sha-256 3E:EE:9E:55:D0:XX:9C:9F:04:68:EB:0D:09:B7:DF:XX:69:78:58:80:8C:42:A1:1E:1C:XX:7A:C8:ED:37:D5:XX
  a=setup:actpass
```
