### ISSUE TITLE
sdp.go

### ISSUE THREAD

**Issue by Mutronics** [pion/webrtc#1542]
src/github.com/pion/webrtc/v2/sdp.go:625:26: invalid indirect of a.String() (type string)

**Comment by Sean-Der** [comment]
`pion/webrtc` requires you use Go modules to build. Do you have them enabled/how are you building today?

thanks!

**Comment by Mutronics** [comment]
> `pion/webrtc` requires you use Go modules to build. Do you have them enabled/how are you building today?
> 
> thanks!

This error show after this changes: https://github.com/pion/sdp/commit/848fa29661cf2e71c1ab23e343bf22448fb4fd15

**Comment by Sean-Der** [comment]
You need to enable Go modules. The API of different packages will change between different versions.

[Go Modules](https://blog.golang.org/using-go-modules) are mandatory for using Pion WebRTC. So make sure you set `export GO111MODULE=on`, and explicitly specify `/v2` or `/v3` when importing.

**Comment by Sean-Der** [comment]
Hey @Mutronics 

If you are still having issues please reopen, thanks for using Pion!
