### ISSUE TITLE
Improve H264Reader performance

### ISSUE THREAD

**Issue by baiyufei** [pion/webrtc#1559]
### Your environment.
  - Version: 74e790aa115dde28b49ca3fad833bd3ec82e0391

### What did you do?

Use h264reader

### What happened?

https://github.com/pion/webrtc/blob/master/pkg/media/h264reader/h264reader.go#L102

```go
		buffer := make([]byte, 1)
		n, err := reader.stream.Read(buffer)
```

h264reader reads file byte by byte, which is slowly.

It took 216s to parse an 80M h264 file.

**Comment by Sean-Der** [comment]
@baiyufei We do that because of our start code probing `0x00, 0x00, 0x01` vs `0x00, 0x00, 0x00, 0x01` and so we don't have catch if we 'over read' across NAL units.

If you are able to implement optimizations (and provide a benchmark) that would be amazing!

**Comment by baiyufei** [comment]
[benchmark](https://github.com/baiyufei/h264benchmark): Parsing 10M h264 file on Windows 10 (AMD Ryzen 5 2600X).

Current h264reader took **44.61s**:
![current](https://user-images.githubusercontent.com/14902592/100631935-3643e780-3367-11eb-9e9f-ee38920b6497.png)


Optimizations h264reader took **0.06s**:

Read 4096 bytes from the system at one time to the readBuffer.

![new](https://user-images.githubusercontent.com/14902592/100631950-3b089b80-3367-11eb-9ffa-62aa1da30498.png)
