### ISSUE TITLE
Performance regression with context introduction

### ISSUE THREAD

**Issue by OrlandoCo** [pion/webrtc#1564]
### Your environment.
  - Version: latest
  - Browser: n/a
  - Other Information - 
#1560 
https://github.com/pion/transport/pull/116

### What did you do?

Run below bench on commit before and after ctx:

```golang
func Benchmark_TrackLocalStaticRTP_SendOnly_WriteRTP(b *testing.B) {
	offer, answer, err := newPair()
	assert.NoError(b, err)

	track, err := NewTrackLocalStaticRTP(RTPCodecCapability{MimeType: "video/vp8"}, "video", "pion")
	assert.NoError(b, err)

	_, err = offer.AddTrack(track)
	assert.NoError(b, err)

	assert.NoError(b, signalPair(offer, answer))
        ctx:=context.Background()

	buffer := make([]byte, 1000)
	for i := 0; i <= b.N; i++ {
		assert.NoError(b, track.WriteRTP(ctx, &rtp.Packet{Payload: buffer}))
	}

	assert.NoError(b, offer.Close())
	assert.NoError(b, answer.Close())
}
````
The results where:

```bash
# no ctx
Benchmark_TrackLocalStaticRTP_SendOnly_WriteRTP-6   	 1000000	      5021 ns/op
# with ctx
Benchmark_TrackLocalStaticRTP_SendOnly_WriteRTP-6   	  158377	      6653 ns/op
```

The performance loss is in line with the results obtained in https://github.com/pion/transport/pull/116

### Solutions
1- Remove the context commit
2- Add two methods: read/write readCtx/writeCtx

**Comment by Sean-Der** [comment]
@at-wat What do you think is best? I see pro and con for both, so I don't have a clear winner.

* Expose `SetReadDeadline` and `SetWriteDeadline` allowing `TrackLocal` and `TrackRemote` to be cancellable
We can't use `Context` in the future to pass values into `Interceptors` or other interesting use cases.

* Expose `Write/WriteRTP` and `WriteContext/WriteRTPContext` 
We make the API more complicated and we have some ambiguity. 

Is there any possibility that we are using `context` in a non-perfomant way? I personally haven't investigated.

**Comment by at-wat** [comment]
Change in https://github.com/pion/transport/pull/116 makes `Read` behavior strange. (`Read` returns data even after the deadline is exceeded.)
If we decide to accept this behavior, we can also remove `ctx.Done()` check at the beginning of `ReadContext`.

**Comment by Sean-Der** [comment]
These are my numbers when reverting locally.

```
# No Context
Benchmark_TrackLocalStaticRTP_SendOnly_WriteRTP-4         322759             12618 ns/op

# Context
Benchmark_TrackLocalStaticRTP_SendOnly_WriteRTP-4         116152              9672 ns/op
```

**Comment by Sean-Der** [comment]
@OrlandoCo I believe this is fixed! If you are happy with how everything is performing go ahead and resolve.

If there is anything that still needs done I can take it! Also super interesting to see what further optimizations we can do :)

**Comment by jech** [comment]
> We can't use Context in the future to pass values into Interceptors

I would argue that context is the wrong way to pass values into interceptors.

Context does a well defined thing: it carries (nested) request-scoped data and implements (nested) request cancellation.  The inefficiency of context is partly due to its power: the ability to nest contexts relies on context propagation, which is essentially a tree walk.

Pion is essentially asynchronous, and does not have a heavy-weigth notion of request.  While some applications may desire to build request-response protocols over Pion, others prefer to remain asynchronous.  Imposing the cost of context on all users of Pion is, to put it mildly, a misunderstanding.
