### ISSUE TITLE
v3: please export track SSRC and ClockRate

### ISSUE THREAD

**Issue by jech** [pion/webrtc#1575]
There are a number of track properties that were available in v2 but are only available to interceptors in v3.  In particular, there are no equivalents to `track.SSRC` and `track.Codec().ClockRate`.

Interceptors are a neat idea, but they will take some time to be adopted universally, and some applications might want to use a different approach.  For people to be able to move to v3 incrementally, it is important that anything that is easy to do in v2 is still doable in a similar manner in v3.

Please export SSID and ClockRate in v3.

**Comment by Sean-Der** [comment]
@jech I think the best thing to do is embed `TrackLocalStaticRTP`. You can then have your own implementation of `Bind`, you can capture the SSRCes etc.... 

#### Getting the SSRC
* `Track` would need to return `[]uint` and when pulling that list I don't think it would be useful. So we would have to put it on `RTPSender`
* Extending `RTPSender` will break WASM. We are going to make it so you can write some code that does `getUserMedia + addTrack` that works in Go+WASM. If we add too much non-standard stuff it will make it not possible. 

#### Getting the ClockRate
You choose the codec (and ClockRate) when creating the Track. We could add a getter that returns the creation choice!

**Comment by jech** [comment]
> I think the best thing to do is embed TrackLocalStaticRTP. You can then
> have your own implementation of Bind, you can capture the SSRCes etc....

That's a lot of boilerplate just to get the SSRC.  I find it rather
distasteful.

> * Extending RTPSender will break WASM.

I will only break programs that use the unimplemented method.  Document it
that (*RTPSender).SSRC() is not available under WASM, and let the users
decide whether they're willing to pay the price.

> You choose the codec (and ClockRate) when creating the Track. We could add a
> getter that returns the creation choice!

I have no problem keeping track of the ClockRate myself, if that's what
you prefer.  But I find it mildly distasteful: it's needed at a lot of
places (sender and receiver reports, SampleBuilder, jitter estimation,
NACK delay estimation), so I would find it natural if it were readily
available.

-- Juliusz

**Comment by jech** [comment]
ClockRate is already exported for TrackRemote: you can do `track.Codec().ClockRate`.  For some reason, it is not exported for `TrackLocalStaticRTP`.

**Comment by jech** [comment]
This has been closed, but the SSRC issue remains.
