### ISSUE TITLE
Remove QUIC Support

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#1589]
RtcQuicTransport was [removed](https://chromium-review.googlesource.com/c/chromium/src/+/2446019) from Chromium.

I think it is important interoperability that we remove this. It will also reduce test time and reduce maintenace efforts on us.

**Comment by Sean-Der** [comment]
I tried to add everyone that might be interested/would have reasons to push back on this. I have opened a PR and will let it sit for a few days until we get consensus.

**Comment by Sean-Der** [comment]
`Test / Go i386 1.15 (pull_request) Successful in 28s` 🔥 This looks to have a positive impact on total test time in CI!

**Comment by cryptix** [comment]
No pushback from my end. If the transport doesn’t have browser adoption I pretty much don’t care and think it doesn’t have a place in a webrtc stack.

I wouldn’t mind getting a link to some backstory/context. I thought google was just replacing gQUIC with something else but this seems to go further..?

**Comment by Sean-Der** [comment]
@cryptix all the communication has been private unfortunately. https://bugs.chromium.org/p/chromium/issues/detail?id=1131222

My guess is security issues and lack of adoption? https://bugs.chromium.org/p/chromium/issues/detail?id=1108472
