### ISSUE TITLE
how can get candidate info connect to webrtc peer

### ISSUE THREAD

**Issue by seamanm** [pion/webrtc#1608]
### Your environment.
  - Version: *3.0.0*

### What did you do?
i want connect to android webrtc ,but need candidate , but i don't know how can get this.like this 
      "candidate1" : {
         "candidate" : "candidate:2999745851 1 udp 2122260223 192.168.56.1 65195 typ host generation 0 ufrag OLSu network-id 3",
         "sdpMLineIndex" : 0,
         "sdpMid" : "data"
      },
      "candidate2" : {
         "candidate" : "candidate:3573973069 1 udp 2122194687 192.168.0.102 65196 typ host generation 0 ufrag OLSu network-id 4",
         "sdpMLineIndex" : 0,
         "sdpMid" : "data"
      },
      "candidate3" : {
         "candidate" : "candidate:4233069003 1 tcp 1518280447 192.168.56.1 50014 typ host tcptype passive generation 0 ufrag OLSu network-id 3",
         "sdpMLineIndex" : 0,
         "sdpMid" : "data"
      },
      "local_peer_id" : "9001",
      "remote_peer_id" : "3001"
   }

**Comment by Sean-Der** [comment]
Hey @seamanm 

They are exposed via `OnICECandidate` like in the browser. You can also get them for the local session description after they have been gathered. We provide a helper to block until gathering is complete. You read about both options here https://github.com/pion/webrtc/wiki/Release-WebRTC@v3.0.0#after

[sfu-ws](https://github.com/pion/example-webrtc-applications/tree/master/sfu-ws) is a good example of exchange between browser, mobile and Pion.

Thank for using Pion!
