### ISSUE TITLE
Minimizing player on chrome causes video to stop and need to be repaired.

### ISSUE THREAD

**Issue by TroyDota** [pion/webrtc#1614]
When i alt tab or take the player out of visibility for a while (causing no Animation Frames to run) the player stops and needs to be reloaded to work again. Is there a way programmatically to fix this without severing the webrtc connection? or am i doing something wrong?

**Comment by Sean-Der** [comment]
Hey @TroyDota 

Where are you getting the frames from? What is your keyframe interval/are you responding to NACKs?

**Comment by Sean-Der** [comment]
Hi @TroyDota 

Hopefully you were able to fix this. If you are still having problems please re-open, thanks for using Pion!
