### ISSUE TITLE
examples/simulcast should read mediaSessions from SDP or PeerConnection.GetReceivers().Tracks()

### ISSUE THREAD

**Issue by cameronelliott** [pion/webrtc#1621]
The simulcast example at examples/simulcast is great!
But, one small gotcha, it magically knows the names of the Rids that appear in the SDP from the browser.

It would be nice if the example iterated through the Rids and created the 'f','h','q' tracks by iterating either
through sdp.SessionDescription or PeerConnection.GetReceivers().Tracks()
Instead of magically knowing how many tracks+the names of the tracks in the SDP are.

The downside of using sdp.SessionDescription, is that the simulcast stuff isn't fully parsed out like it is in PeerConnection.GetReceivers().Tracks()

But, the info in PeerConnection.GetReceivers().Tracks() cannot be used in the example, because isn't isn't parsed out until the connection is made, and the example code needs to use the tracks info to call PC.AddTrack() to setup the simulcast tracks.
**in my mind it would be fantastic if the example could use PeerConnection.GetReceivers().Tracks() to create it's tracks.
That would mean PC.GetReceivers().Tracks()  is available after a single call to peerConnection.SetRemoteDescription(),
without the matching call to peerConnection.SetLocalDescription()**
Probably impossible for a bunch structural reasons I don't grok, but I am throwing it out there.

This is not a big deal, or the end of the world, more like a small nit, or feedback about how `simulcast` really wants (more than needs) fully parsed out rid structs/stuff in order to setup simulcast tracks for productions situations.

So, just consider this some feedback that I hope is helpful in thinking about simulcast usage situations.

The example uses hardcoded rids, f/h/q in the code, but should read them from the SDP or from 
PeerConnection.GetReceivers().Tracks():
https://github.com/pion/webrtc/blob/921608c26b93fdc72ef34c59c1df1916d1d2a565/examples/simulcast/main.go#L40

**Comment by Sean-Der** [comment]
Moved to https://github.com/pion/webrtc/issues/1345
