### ISSUE TITLE
h264reader appears to not read/pass the first keyframe it receives

### ISSUE THREAD

**Issue by chrisuehlinger** [pion/webrtc#1625]
### Your environment.
  - Version: *v3.0.3*
  - Browser: *Chrome 87.0.4280.88*
  - Other Information - *[reduced test case](https://github.com/chrisuehlinger/pion-h264-repro)*

### What did you do?

I'm building a tool that involves using ffmpeg to pipe a video stream into pion, which then reads the stream (as if reading from a file) and sends it to a client in Chrome. This is most similar to the `play-from-disk` example.

For various (mostly performance) reasons, I'd like to switch from VP8 to H264, but doing so introduces a weird several second lag that appears to be caused by a missing keyframe at the beginning of the stream (even though ffmpeg *does* seem to be writing one).

### What did you expect?

When reading VP8 video from a file descriptor and sending it to a client over WebRTC, the video starts instantly.

### What happened?

When reading H264 video from a file descriptor and sending it to a client over WebRTC, the video doesn't start for 8 seconds (and starts 8 seconds in).

I've assembled a [reduced test case](https://github.com/chrisuehlinger/pion-h264-repro) with instructions on how to reproduce the issue.

**Comment by Sean-Der** [comment]
This is one of the best bug reports I have ever seen! Thank you so much @chrisuehlinger will check it out ASAP :)

I usually don’t get much Pion time until the weekends :(

**Comment by baiyufei** [comment]
When sps and pps are in two separate rtp packets, [Chrome does not treat packets as a keyframe](https://source.chromium.org/chromium/chromium/src/+/93789ecf59c3afe3c5aa7125950744e6869c97fd:third_party/webrtc/modules/video_coding/packet_buffer.cc;l=301;bpv=1;bpt=1). First sps and pps  were discarded by Chrome.
Enable webrtc log of Chrome, will see warning like this:
```log
[18520:18608:0106/221557.568:WARNING:rtp_seq_num_only_ref_finder.cc(66)] Generic frame with packet range [18746, 18746] has no GoP, dropping frame.
[18520:18608:0106/221557.568:WARNING:rtp_seq_num_only_ref_finder.cc(66)] Generic frame with packet range [18745, 18745] has no GoP, dropping frame.
```
Sending sps and pps in one STAP-A rtp packet may solve this.

**Comment by chrisuehlinger** [comment]
@Sean-Der Thanks! I also wanted to make sure I wasn’t messing anything up or using the reader wrong. Once this gets resolved, I’m down to build a play-h264-from-disk example (since there aren’t any examples yet that use H.264)

@baiyufei I had never heard that Chrome had anything besides webrtc-internals, this is huge, thanks. WRT this issue, is there a change I could make to my ffmpeg incantation to combine the packets?

**Comment by baiyufei** [comment]
@chrisuehlinger I created a [PR](https://github.com/pion/rtp/pull/112) to solve this. You can try https://github.com/baiyufei/pion-h264-repro for test.

**Comment by chrisuehlinger** [comment]
@baiyufei Thanks! I'll get to checking it out in a bit. On my end, I was able to mitigate my issue by increasing keyframe frequency so the initial lag is decreased, but it'll be good to have an actual solution to the problem.
