### ISSUE TITLE
how to change datachannel protocol to "UDP"

### ISSUE THREAD

**Issue by seamanm** [pion/webrtc#1626]
## Summary

i want use datachannel and udp protocol transfer some file,but don't know how to modify

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome? Is this available in other implementations? Can this not be implemented using primitives?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered.

**Comment by Sean-Der** [comment]
The Datachannel runs over the ICE Agent. You can’t control UDP/TCP and the Datachannel level. No matter UDP or TCP a Datachannel is reliable so you will not lose messages.

ICE is usually over UDP. Unless you use TCP TURN. You can force TCP TURN via the PeerConnection configuration.

**Comment by Sean-Der** [comment]
If you have anymore questions feel free to ask here or in [Slack](https://pion.ly/slack)
