### ISSUE TITLE
curl: (7) Failed to connect to localhost port 8080: Connection refused

### ISSUE THREAD

**Issue by NielsDom** [pion/webrtc#1632]
Hello,

Project looks exciting, but I am not even able to launch it.

When I try: curl localhost:8080/sdp -d "YOUR SDP",
I got  "curl: (7) Failed to connect to localhost port 8080: Connection refused".

Thanks

**Comment by Sean-Der** [comment]
Hey @NielsDom 

Sorry about the issues you are running into! Would you mind trying `reflect` or `datachannels` first. They are a little less involved, it will help if you can see all the moving parts. 

When you get back to trying the broadcast example did you `go run main.go` in `webrtc/examples/broadcast`? Are you running `curl` on the same machine that you ran broadcast?

**Comment by NielsDom** [comment]
@Sean-Der Thank you.
I can run examples localhost following instructions: https://github.com/pion/webrtc/tree/master/examples. 
I run curl on same machine that runs examples.
But I cannot get Golang base64 Session Description. If I understand well I have to generate it from command: curl localhost:8080/sdp -d "Browser SDP". (which "browser SDP" = Browser base64 Session Description, right?)

I try to follow instructions on this issue: https://github.com/pion/webrtc/issues/1019

I still not understand, I am too noob, is there any video tutorial? Thanks

**Comment by Sean-Der** [comment]
Hey @NielsDom 

Sorry for the delay been really busy lately. I would suggest starting with [data-channels](https://github.com/pion/webrtc/tree/master/examples/data-channels) 

`$BROWSER_SDP` is the base64 message from your browser. 

If you are still having issues mind opening a discussion! This could be a good thing for others debugging in the future :) 

thanks for using Pion

**Comment by peerasan** [comment]
First time with Pion. I try reflect, data-channel, broadcast, simulcast and I face the issues too.

**Comment by Sean-Der** [comment]
Hey @peerasan what issues are you having?

Did you 
  * Copy ` Browser base64 Session Description` from the browser on the jsfiddle page?
  * Did you echo that value into Pion `echo VALUE_YOU_COPIED | go run *.go`
  * Did you copy the value that Pion echoed back into the browser?

Would you mind joining [Slack](https://pion.ly/slack) for help? I am also happy to respond to GitHub discussions. thanks!

**Comment by NielsDom** [comment]
@Sean-Der I small video tutorial about launching a basic example would be very helpful :)

**Comment by Uukins** [comment]
maybe i ma so noob,but i also think the tutorial  is not enought detail,

i don't understand why the tutorial make us to use  `echo &SDP|data-channels`  ,

and it output `data-channels: command not found`, maybe i missed a step?

and @Sean-Der you say use  `curl localhost:8080/sdp -d "SDP"` ,

it makes me wonder ....

**Comment by batousaj** [comment]
the $BROWSER_SDP mean the String on text area in Browser base64 Session Description. We just only copy the String and run the command on the Terminal (Linux) echo "String on text area" | go run main.go
I make the video step by step to make all of us can be easy to use the Example data-channels on Pion.
[](https://www.youtube.com/watch?v=SXFiZosIZ68)

**Comment by Yecccccc** [comment]
I had this problem before too.
when I run this:
`curl localhost:8080/sdp -d "$SDP"`
I get 404 and there were nothing in my shell.
The main reason is that the port 8088 is  occupied.
Go to examples/internet/signal/http.go line 13, you can see the port 8088.
You can change the port by using `go run main.go -port=8081`
then you can `curl localhost:8081/sdp -d "$SDP"` and the result is "done"
