### ISSUE TITLE
samplebuilder.Pop(), only nil comes out.

### ISSUE THREAD

**Issue by thsdmfwns** [pion/webrtc#1644]
### Your environment.
  - Version: Release
  - Browser: ION-SFU
  - Other Information - elementary OS 5.1.7 Hera, ~18.04.1-Ubuntu

### What did you do?
  Builder := samplebuilder.New(10, &codecs.H264Packet{}, 90000)
  for {
            inboundVideoPacket := make([]byte, 1500)
            v, _, err := Listener.ReadFromUDP(inboundVideoPacket)
            if err != nil {
	            log.Fatalf("Listener.ReadFromUDP Error %s", err.Error())
            }
            
            Packet = &rtp.Packet{}
            err = Packet.Unmarshal(inboundVideoPacket[:v])
            if err != nil {
	            log.Fatalf("Pakcet.Unmarshal Error %s", err.Error())
            }
            log.Println("Packet : ", Packet.SequenceNumber)
            Builder.Push(Packet)
            log.Println(Builder.Pop())
            // writesample(Builder, Track)
  }

the output is
2021/01/21 15:17:03 Packet :  24795
2021/01/21 15:17:03 nil
2021/01/21 15:17:03 Packet :  24796
2021/01/21 15:17:03 nil
2021/01/21 15:17:03 Packet :  24797
2021/01/21 15:17:03 nil
2021/01/21 15:17:03 Packet :  24798
2021/01/21 15:17:03 <il
2021/01/21 15:17:03 Packet :  24799
2021/01/21 15:17:03 nil
2021/01/21 15:17:03 Packet :  24800
2021/01/21 15:17:03 nil
2021/01/21 15:17:03 Packet :  24801
2021/01/21 15:17:03 nil
2021/01/21 15:17:03 Packet :  24802
2021/01/21 15:17:03 nil
2021/01/21 15:17:03 Packet :  24803
2021/01/21 15:17:03 nil

### What did you expect?
The packet should have come out.
### What happened?
i don't know :(

**Comment by Sean-Der** [comment]
Hey @thsdmfwns 

If you are sending very large frames and/or have packet loss that should be expected! Can you share the command you are using to generate the input?

You can also skip the SampleBuilder and send packets directly. This was changed in 9439d820c594cc3bf0de3c63a22be98c22eef081 because some programs (ffmpeg) were generating invalid RTP packets. 

I am going to make the SampleBuilder a CLI flag. Then in the README give people an option to forward RTP, or use the SampleBuilder. If you are interested in contributing that would be a really great PR! Otherwise I will get to it in about two weeks.

thanks

**Comment by thsdmfwns** [comment]
the input command is 
/usr/bin/ffmpeg -re -i rtmp://localhost:1935/$app/$name -vn -acodec libopus -f rtp rtp://localhost:6000 -vcodec copy -an -f rtp rtp:localhost:5000 -sdp_file video.sdp;

i'm using the nginx-rtmp-module

I can't use Go very well because this is my first Go project.
so please give me the example about Pop in a for loop.

sorry about my english skill

**Comment by Sean-Der** [comment]
I will test out your solution tomorrow! That does look ok to me.

If you re-encode to VP8 does it work with the SampleBuilder? 

Can you try the non-samplebuilder example also? https://github.com/pion/webrtc/blob/52249252fb14005473242599074abbdfd8fc8077/examples/rtp-forwarder/main.go#L120

**Comment by thsdmfwns** [comment]
i changed my input command like 
            exec_push /usr/bin/ffmpeg -re -i rtmp://localhost:1935/tc/stream -vn -c:a libopus -b:a 48000 -ssrc 1 -payload_type 111 -f rtp rtp://localhost:6000 -an -vcodec libvpx -qmin 0 -qmax 10 -deadline 1 -g 10 -error-resilient 1 -auto-alt-ref 1 -f rtp rtp:localhost:5000;

but output is same :(

**Comment by Sean-Der** [comment]
Did you try not using the SampleBuilder like in the commit I linked? I am curious if the video is viewable without it.

Would you be able to share a pcap of the RTP traffic. I can debug/fix locally then!

Thanks

**Comment by Sean-Der** [comment]
Hey @thsdmfwns glad you got it working! What did you end up doing?

thanks

**Comment by thsdmfwns** [comment]
Actually, I changed the server to Janus. I thought this would be easier.

**Comment by Sean-Der** [comment]
No worries! Sorry about the frustration.

I added an example so shows `rtmp-to-webrtc` so future users don't hit this frustration :( https://github.com/pion/example-webrtc-applications/tree/master/rtmp-to-webrtc
