### ISSUE TITLE
SetRemoteDescription called with multiple conflicting ice-ufrag values

### ISSUE THREAD

**Issue by jech** [pion/webrtc#1659]
After applying #1658, the scenario described in #1656 results in the following error:
```
SetRemoteDescription called with multiple conflicting ice-ufrag values
```
The answer sent by the browser looks like this:
```
v=0
o=- 6191044200071977403 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS
m=audio 46952 UDP/TLS/RTP/SAVPF 111
c=IN IP4 192.168.3.100
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:1904234453 1 udp 2122262783 2a01:xxx 40971 typ host generation 0 network-id 2 network-cost 10
a=candidate:2782741380 1 udp 2122197247 2a01:yyy 59384 typ host generation 0 network-id 3 network-cost 10
a=candidate:4051717925 1 udp 2122129151 192.168.3.100 46952 typ host generation 0 network-id 1 network-cost 10
a=ice-ufrag:AOWb
a=ice-pwd:uYdWPIsrUyvQ7s2gIdPDb2aa
a=ice-options:trickle
a=fingerprint:sha-256 8B:7F:E7:31:C6:DA:52:E4:EF:3C:E5:8C:86:99:34:75:39:07:90:07:3F:D2:B2:38:3E:2B:0E:A5:4D:0A:9B:9A
a=setup:active
a=mid:0
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
m=video 0 UDP/TLS/RTP/SAVPF 0
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:8mIV
a=ice-pwd:n0X4qJS0S2NsfFg5ahCz24Yv
a=ice-options:trickle
a=fingerprint:sha-256 8B:7F:E7:31:C6:DA:52:E4:EF:3C:E5:8C:86:99:34:75:39:07:90:07:3F:D2:B2:38:3E:2B:0E:A5:4D:0A:9B:9A
a=setup:active
a=mid:1
a=inactive
```

**Comment by Sean-Der** [comment]
It looks like the browser thinks Pion supports non-bundle (which it doesn't) so it creating two DTLSTransports.

Thanks for checking this before it got merged! I will make sure to confirm with a browser before anything gets merged

**Comment by jech** [comment]
The second track is `a=inactive`, which is probably a consequence of a different issue (probably in my code), the weird media track (no `a=` lines, just the `m=` line).  I still find it weird — `a=inactive` doesn't prevent RTCP, so it would make sense to include it in the BUNDLE group.

**Comment by jech** [comment]
Ok, I found it.  I'll describe the root issue in #1656, and let you decide whether to close this report.

**Comment by Sean-Der** [comment]
Thanks! Yea will close for now.

In the future I do think we will want to support non-bundle. It will be a pretty big challenge, so will need to evaluate all the trade-offs. I worry about the complexity it brings vs amount of users.
