### ISSUE TITLE
Please provide a way to check whether all PCs are closed

### ISSUE THREAD

**Issue by jech** [pion/webrtc#1664]
## Summary

I often wish it were possible to query Pion about the number of PeerConnections that are open.

## Motivation

A common bug is to forget to call `Close` on a PeerConnection.  I wish I could check at program shutdown that all PCs are closed, and print a warning if that's not the case.

## Describe alternatives you've considered

I'm currently testing by generating a backtrace and find whether there are any reader/writer goroutings hanging around.

## Additional context

(I hate this template.)

**Comment by Sean-Der** [comment]
Hey @jech, feel free to ignore the template it is more guardrails for new people :) 

I am not sure if doing this is a good idea. I don't want to add extend `webrtc-pc` and stop people from switching to webrtc-rs, aiortc etc...

I do something like this in sfu-ws. I just excluded all the locking/error handling to keep code short. 
```go

peerConnections = append(peerConnections, peerConnectionState{peerConnection, c})
peerConnection.OnConnectionStateChange(func(p webrtc.PeerConnectionState) {
    switch p {
    case webrtc.PeerConnectionStateFailed:
        peerConnection.Close()
    case webrtc.PeerConnectionStateClosed:
        for i := range peerConnections {
            if peerConnections[i].peerConnection.ConnectionState() == webrtc.PeerConnectionStateClosed {
                peerConnections = append(peerConnections[:i], peerConnections[i+1:]...)
        }
    }
})
```

**Comment by jech** [comment]
> I don't want to add extend webrtc-pc and stop people from switching to webrtc-rs, aiortc etc...

Not sure I agree, but ok.
