### ISSUE TITLE
Export newICECandidateFromICE

### ISSUE THREAD

**Issue by kev-the-dev** [pion/webrtc#1665]
## Summary

The function `newIceCandidateFromICE` converts the `pion/ice.Candidate` type to `pion/webrtc.ICECanidate` type. The `ice.Candidate` type is more easily formed by a user in application code, as `pion/ice` contains utilities to generate this type for common use cases such as Srflx/Prflx/Host candidates. But if `ice.Candidate` is used in user-level code, for example to implement a custom ICE candidate generation scheme, it cannot be converted into the `pion/webrtc` type for use in `pion/webrtc.PeerConnection.AddICECandidate`. 

Exporting this function introduces a slight API refactor/upgrade burden, as there is a new exported function to maintain. However, as these types are more or less dictated by the WebRTC spec, they are unlikely to change. And if they do, both structs will likely change simultaneously. 

## Motivation
Enabling custom ICE candidate generators in application code, such as having a server add ICE Candidates for a the resolved IPs for a hostname it knows it is indexed by, or hitting a database. Admittedly, these are non-standard use cases, but the exposure of `AddICECandidate` suggests there is some intention of supporting these custom use cases.

## Describe alternatives you've considered

Attempting to fill webrtc.ICECandidate fields manually within my application (essentially reimplementing pion/ice)

Removing `webrtc.ICECandidate`, having all uses by of `ice.Candidate`, with a function to convert to `webrtc.ICECandidateInit` JSON. This is a more invasive change and is not backwards compatible.

## Additional context

Happy to submit a PR to do this, just wanted a sign off from maintainers if this export would be acceptable

**Comment by Sean-Der** [comment]
Hey @kev-the-dev 

Thanks for opening this :) Where are you getting the other ICE Candidates from? Is it possible they are a ICECandidateInit?

We have a demo of trickle-ice in sfu-ws [here](https://github.com/pion/example-webrtc-applications/blob/master/sfu-ws/main.go#L323-L332) does that not work with the remote agent you are interacting with?

[pion-to-pion](https://github.com/pion/webrtc/tree/master/examples/pion-to-pion) does trickle between two WebRTC Agents that might be helpful. 

We can totally export this if it is helpful, but I am hoping other APIs can cover this.

**Comment by kev-the-dev** [comment]
Thanks for getting back to me Sean. The examples you link seem to involve decoding a candidate from one already generated by a remote peer. 

I'm trying to do something similar to what is provided by `webrtc.SetNAT1To1IPs`, but with a dynamic set of ips resolved from a hostname. I want my application to periodically resolve `mywebrtcapp.example.com`, and add the IPs resolved there as Srflx candidates to any new PeerConnections. I'm trying to utilize the apriori knowledge that my app can be externally reached at these addresses to avoid having to gather with STUN.

The simplest way to do that seems to be to add each as an `pion/ice.NewCandidateServerReflexive`, then convert them to `pion/webrtc.ICECandidate` and call `pion/webrtc.PeerConnection.AddCandidate`.

The important bit is that I'm generating these candidates "from scratch", and wish to make use of the existing API in `pion/ice` to do so.

**Comment by kev-the-dev** [comment]
Perhaps you could give me some context on why `webrtc.ICECandidate` is not simply a re-export of `pion/ice.ICECandidate`?

**Comment by Sean-Der** [comment]
> Perhaps you could give me some context on why `webrtc.ICECandidate` is not simply a re-export of `pion/ice.Candidate`?

I think it was just an accident. I don't ever remember making that decision consciously. I have been moving more logic into `pion/ice` since people are using that directly. Stuff like 2155a7d70305e06d31e59102c82136531039ed4a.

It might make more sense to just `fmt.Sprintf(...)` then you can just pass in `ICECandidateInit{candidate...`

If you are able to make it work with a type alias I am all for deleting code! We just can't break the public API :( if you are interested in doing this in a year (or so) I would be happy to make it a `/v4` thing.

> IPs resolved there as Srflx candidates to any new PeerConnections.

Would supporting hostnames in a srflx candidate help? This may be supported by WebRTC. It would be great for geoip load balancing.

**Comment by kev-the-dev** [comment]
Cool, sounds like the consideration of the duplicate types has outgrown this issue, so I made an #1669 for that.


> Would supporting hostnames in a srflx candidate help? This may be supported by WebRTC. It would be great for geoip load balancing.

I've seen mixed information about hostnames being supported directly in ICE candidates sent in signaling. I've seen it brought up as a security concern (leaking DNS server info), and have not seen evidence that browsers support this.

For my use case, I'd be prefer to resolve them myself and send the IPs to the peer, for better security and compatibility. This approach unfortunately would not work for a geo-based load balancer, where transmitting the hostname and having the peer resolve it is ideal.

It seems there are many different custom use cases for adding ICE candidates, so keeping good support for `AddICECandidate` boots this to application code.

> It might make more sense to just fmt.Sprintf(...) then you can just pass in ICECandidateInit{candidate...

I'm not sure what you mean here. What would I be passing in to `Sprintf`? Ideally I'd like to avoid forming my own candidate/SDPMid strings, as this would be a reimplementation of code in `pion/ice/CandidatePeerReflexive`.

**Comment by Sean-Der** [comment]
I spent some time prototyping this. I think it makes more sense to keep things as is. I am going to close and if anyone disagrees please re-open!

### WASM in pion/ice

pion/webrtc has a few places where we support both WASM+Go. We could move these into pion/ice but it feels a tad messy. I would rather keep that complexity in pion/webrtc.

### pion/webrtc is a standard, pion/ice isn't

I would like to keep the flexibility we have with pion/ice. Right now I can add features/APIs as a please (as long as they don't block pion/webrtc). Then we can get at those features via the SettingEngine.

If we start providing pion/ice as the pion/webrtc API we need to match the W3C API.

IMO this is a case where `A little copying is better than a little dependency`

**Comment by robbie-anam** [comment]
@kev-the-dev 

Did you have example code to manually add that ICE candidate? I have a similar use case.   Appreciate the tradeoff @Sean-Der so just looking for a way to easily add my own dynamically allocated public IP to the candidates.

**Comment by xianqiliu** [comment]
@robbie-anam hey, do you have any update idea about manually add that ICE candaidate? i have a similiar use case too...
