### ISSUE TITLE
Replace ICE types with pion/ice types (v4)

### ISSUE THREAD

**Issue by kev-the-dev** [pion/webrtc#1669]
## Summary

`pion/webrtc` implements the following types which are duplicates or near duplicates of those in `pion/ice`. This is a request to remove these types in `pion/webrtc` and replace all usage of it with the corresponding types in `pion/ice`, with slight modifications if needed to preserve the full feature set.

* [ ] `pion/webrtc.ICECandidate` -> `pion/ice.Candidate`
* [ ] `pion/webrtc.ICECandidateStats` -> `pion/ice.CandidateStats`
* [ ] `pion/webrtc.ICECandidatePairStats` -> `pion/ice.CandidatePairStats`
* [ ] `pion/webrtc.ICEGathererState` -> `pion/ice.GatherState` (webrtc version has additional `closed` field which can be added to `ice` package)
* Likely others that I have not yet documented

This could either be done in a tick-tock deprecation strategy, with the original types being marked deprecated and both supported in v3, or wait to begin work on this until v4.

## Motivation

1. Reduce confusion over API and reduce maintenance  burden of having these duplicates.
1. Reduce complexity in `pion/webrtc` from converting between these two types
1. Allow `pion/webrtc` to focus on only the high-level PeerConnection API (separation of concerns)
1.  Allow users of `pion/webrtc` to benefit from the richer feature set in `pion/ice` (see #1665 for an example)

## Describe alternatives you've considered

Exporting methods to convert between the two types. This gives us (4) above but not (1-3). It is however a quicker change without API breakage considerations (only new methods are being introduced).

## Additional context

`pion/webrtc `already depends on `pion/ice`, so this represents so additional dependencies.

**Comment by Sean-Der** [comment]
I spent some time prototyping this. I think it makes more sense to keep things as is. I am going to close and if anyone disagrees please re-open!

### WASM in pion/ice

pion/webrtc has a few places where we support both WASM+Go. We could move these into pion/ice but it feels a tad messy. I would rather keep that complexity in pion/webrtc.

### pion/webrtc is a standard, pion/ice isn't

I would like to keep the flexibility we have with pion/ice. Right now I can add features/APIs as a please (as long as they don't block pion/webrtc). Then we can get at those features via the SettingEngine.

If we start providing pion/ice as the pion/webrtc API we need to match the W3C API.

IMO this is a case where `A little copying is better than a little dependency`
