### ISSUE TITLE
I need an interface to send the FIR/PLI/SLI of rtcp to the sender

### ISSUE THREAD

**Issue by pig-peppa** [pion/webrtc#1688]
## Summary

I am developing a media server based on pion. If every subscriber of a new stream is added, the sender needs to generate a key frame, so I need this interface.

## Describe alternatives you've considered
I considered an alternative, caching keyframes, but I don't think it is a good idea, because the gop size mabe much big.

can anyone help?

**Comment by Sean-Der** [comment]
Hey @pig-peppa you can do this today!

`PeerConection` has `WriteRTCP`. You can see an example [here](https://github.com/pion/webrtc/blob/master/examples/save-to-disk/main.go#L100-L103) of writing a PLI on an interval.

I am going to resolve, but if you have more questions I am here to help! I am also on [Slack](https://pion.ly/slack)
