### ISSUE TITLE
"Failed to set remote offer sdp" on renegotiation, sometimes

### ISSUE THREAD

**Issue by s4y** [pion/webrtc#1694]
### Your environment.
  - Version: v3.0.12 (but I believe I have observed the problem since v3 stable)
  - Browser: Chrome 89.0.4389.72

### What did you do?
I'm trying to migrate my multiparty video chat project (https://github.com/s4y/space) from `v3.0.0-beta.10` to `v3.0.12`.

You can find a snapshot of my project with the issue [here](https://github.com/s4y/space/commit/c398ea22bff439bf0143bfe089c49b5b0d27a8d4). You can demo it by typing `make run` and then visiting http://127.0.0.1:8031/test/meta.html, which will display four client iframes which all try to connect to each other. Check the console for errors.

### What did you expect?
Successful negotiation.

### What happened?
I keep ending up with errors like the following in Chrome when trying to `setRemoteDescription` on an offer from the server:

> DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set up demuxing for m-section with mid='8'.
> onerror @ rtc.html:276

If I set the clients up to reconnect on error, they all eventually stabilize (until something triggers renegotiation).

I also noticed that chunks of lines like the following in the offer SDP:

```
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:2 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
```

…are changing into:

```
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:2 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
```

…in the first failing offer.

I tried sorting the lines with no luck. I asked about this on Slack, and Patryk Rogalski [suggested stripping those lines from the offer](https://gophers.slack.com/archives/CAK2124AG/p1614785006465700), which seems to resolve the issue completely.

**Comment by Sean-Der** [comment]
Hey @s4y 

Sorry about the headache. I believe the issue is from registering those header values. Can you try removing 

https://github.com/s4y/space/commit/c398ea22bff439bf0143bfe089c49b5b0d27a8d4#diff-21fdbb2de08f79a16b8f6805ad3720115b874d7e36decbb2ae4e9188069aab3aR65-R75

https://github.com/s4y/space/commit/c398ea22bff439bf0143bfe089c49b5b0d27a8d4#diff-21fdbb2de08f79a16b8f6805ad3720115b874d7e36decbb2ae4e9188069aab3aR95-R103

**Comment by s4y** [comment]
Ah, yep, you nailed it. I copied those values from an older version of [mediaengine.go](https://github.com/pion/webrtc/blob/22eea024a224d426b31b2f66ace08a4c0e7fdc13/mediaengine.go#L194-L202) and it looks like they’ve been removed since then. Thanks so much for catching it.
