### ISSUE TITLE
can't handle the retransmission RTP packet

### ISSUE THREAD

**Issue by pig-peppa** [pion/webrtc#1697]
### Your environment.
  - Version: v3.0.12
  - Browser: chrome M88 (newest)
  - Other Information - web publish steam(audio,video, datachannel) to pion.

### What did you do?
When the first nack triggers the sender to retransmit, a new stream will be called back up in PeerConnection.undecaredMediaProcessor(), and pc.api.mediaEngine.negotiatedHeaderExtensions is nil in handleUndeclaredSSRC() function, so you can got a error report: "pc ERROR: 1999/10/14 09:14:23 Incoming unhandled RTP ssrc(1184720791), OnTrack will not be fired. mid RTP Extensions required for Simulcast"

### What did you expect?
did i miss some? should i create mediaEngine add to peerconnection?

**Comment by Sean-Der** [comment]
Hey @pig-peppa 

Thanks for a report, this is a known issue #1675. It would be great if someone offered to take it! I am currently working on WebRTC for the Curious for a few weeks.

thanks
