### ISSUE TITLE
InvalidModificationError: invalid proposed signaling state transition: stable->SetRemote(answer)->stable

### ISSUE THREAD

**Issue by HaoRan98** [pion/webrtc#1703]
checkError(peerconntion.SetRemoteDescription(
			webrtc.SessionDescription{
				Type: webrtc.SDPTypeAnswer,
				SDP:  s["sdp"].(string)
			}))

setRemoteDesciption can't analysis "answer" ???

**Comment by Sean-Der** [comment]
Hi @HaoRan98 

Would you mind posting a minimal code example?

My guess is that you are calling `SetRemoteDescription` before calling `SetLocalDescription`. You also need to do a `CreateOffer/SetLocalDescription` before every offer.

**Comment by Sean-Der** [comment]
Hey @HaoRan98 

Hopefully your issue was just a signaling mistake! I am going to close, but please re-open if you are still having issues.

Thanks for using Pion :)
