### ISSUE TITLE
Codec negotiation fails for Firefox

### ISSUE THREAD

**Issue by at-wat** [pion/webrtc#1711]
Codec negotiation logic has been changed by https://github.com/pion/webrtc/commit/e5c8c659caa915041dd6dbcaacbb85fe28733820#diff-8b596789ae952f46740e3dabb4df2a5391953429f8f84da7f58820feb5838ae3R111-R114.
It requires that `SDPFmtpLine` should be empty to be partially matched.

For example, Firefox's fmtp line for OPUS codec is `maxplaybackrate=48000;stereo=1;useinbandfec=1`
and pion/webrtc's default fmtp line for OPUS codec is `minptime=10;useinbandfec=1`
https://github.com/pion/webrtc/blob/545613dcdeb5dedb01cce94175f40bcbe045df2e/mediaengine.go#L68
So, OPUS codec won't be negotiated between Firefox and pion/webrtc>=v3.0.13. (unless registering custom codec to `MediaEngine`)

## Possible solutions
1. Make `SDPFmtpLine` of default OPUS codec empty
    - Make them partially matched on the current negotiation logic.
    - User may enable/disable inband FEC, so setting `useinbandfec=1` by default seems wrong.
2. Fix `codecParametersFuzzySearch`
    - For this Firefox case, it is natural to treat `minptime=10;useinbandfec=1` and `maxplaybackrate=48000;stereo=1;useinbandfec=1` are partially matched.
    - Parse contents of `SDPFmtpLine` and treat as partially-matched if two `SDPFmtpLine`s are not incompatible.

**Comment by Sean-Der** [comment]
Thanks for fixing this FireFox issues @at-wat and @jsmouret. I am sorry I haven't been more present I am taking a few weeks off to work on https://webrtcforthecurious.com. If any emergencies come up I am here to help though!

I added @jsmouret to the GitHub org so you can approve each other PRs. Sorry for the breakage :(

**Comment by at-wat** [comment]
Another problem is that when browser requests
- mime=`audio/opus` fmtp=`minptime=10;useinbandfec=1`
- mime=`audio/G722`
and pion requests
- mime=`audio/opus`
- mime=`audio/G722`
, G722 will be always selected.

I think most user expect that `audio/opus` is selected by first priority.
(Before https://github.com/pion/webrtc/commit/e5c8c659caa915041dd6dbcaacbb85fe28733820#diff-8b596789ae952f46740e3dabb4df2a5391953429f8f84da7f58820feb5838ae3R111-R114, opus was selected in this case.)

**Comment by at-wat** [comment]
https://github.com/pion/webrtc/blob/07d7403cca7ee34f5c1717479686d243d93e4ca8/rtpcodec.go#L88-L99
It might be better to calculate distance between two fmtps and select closest one.

**Comment by Sean-Der** [comment]
Hey @at-wat with all the PRs merged is this better now, or still need work?

thanks!

**Comment by at-wat** [comment]
It seems working as expected in our app.
Please reopen or create a new issue if there are unexpected cases of codec negotiation.
