### ISSUE TITLE
Support getSelectedCandidatePair on ICETransport

### ISSUE THREAD

**Issue by debiandebiandebian** [pion/webrtc#1713]
## Summary

The same as the title.

## Motivation

As per [the standard](https://www.w3.org/TR/webrtc/#webidl-744203390), the selected pair should be accessible through `RTCIceTransport.getSelectedCandidatePair`. [`ICETransport`](https://github.com/pion/webrtc/blob/master/icetransport.go#L19) on `Pion` has not implemented this method yet. 

## Describe alternatives you've considered

None.

## Additional context

None.

**Comment by Sean-Der** [comment]
I am in support of this @debiandebiandebian and would be happy to merge right away!

* Export [getSelectedPair](https://github.com/pion/ice/blob/c578160cc82c9a86c4cd2deca397f7b865ba961f/agent.go#L1125) from pion/ice.
* call `getSelectedCandidatePair` from your new `GetSelectedCandidatePair` function. 
* Use [newICECandidateFromICE](https://github.com/pion/webrtc/blob/master/icecandidate.go#L40) to convert them to a `pion/webrtc.ICECandidate` . 
*  Use [NewICECandidatePair](https://github.com/pion/webrtc/blob/master/icecandidatepair.go#L22) as the return value from `ICETransport.GetSelectedCandidatePair`.

**Comment by debiandebiandebian** [comment]
That's very considerate. You give me no choice but to contribute! I wish production environment were this good.

**Comment by Sean-Der** [comment]
Hey @debiandebiandebian 

I have some time this weekend and can implement this! If you have already started would rather take your PR :)

thanks

**Comment by debiandebiandebian** [comment]
@Sean-Der 
Sorry. I've been preoccupied with other things. ='(
