### ISSUE TITLE
A series of problems that lead to missing ontrack event

### ISSUE THREAD

**Issue by pascal-ace** [pion/webrtc#1715]
After having succeeded in making work all the environment of janus with the library, I manage to make calls (creation of an offer, addition of the answer, and I make calls of several minutes).
But when I receive a call, my SDP is detected with a lot of errors, and at each correction, new errors, until there are no more errors, but never ontrack. 

Here are the problems list: 
1. `remoteDescription contained media section without mid value`
Solution: add a `a=mid:0` to audio media part (inactive audio part)
2. `Incoming unhandled RTP ssrc(0), OnTrack will not be fired. mid RTP Extensions required for Simulcast`
Solution: cut the end of the sdp, to have only one media part (just to have the audio opus)
3. `Incoming unhandled RTP ssrc(0), OnTrack will not be fired. single media section has an explicit SSRC`
Solution: remove all line with `ssrc`

I put below, the original SDP. What is surprising is that it has `a=inactive`, that should not be managed, right? 

```
offer v=0
o=FreeSWITCH 1616059163 1616059164 IN IP4 192.168.1.66
s=FreeSWITCH
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS janus
m=audio 9 UDP/TLS/RTP/SAVPF 102 9 0 8 105 106 101 13
c=IN IP4 192.168.1.66
a=sendrecv
a=mid:audio
a=rtcp-mux
a=ice-ufrag:vWx3
a=ice-pwd:VB48NkttHZLX7oGLlNf2i+
a=ice-options:trickle
a=fingerprint:sha-256 95:2F:CF:B4:F4:0D:2E:76:E2:37:C4:1B:EF:2E:E1:E3:07:5B:21:CE:D7:16:C4:84:C7:9B:EB:65:F7:E5:C9:B0
a=setup:actpass
a=rtpmap:102 opus/48000/2
a=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:105 telephone-event/48000
a=fmtp:105 0-16
a=rtpmap:106 CN/48000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtpmap:13 CN/8000
a=ptime:20
a=msid:janus janusa0
a=ssrc:882197165 cname:janus
a=ssrc:882197165 msid:janus janusa0
a=ssrc:882197165 mslabel:janus
a=ssrc:882197165 label:janusa0
a=candidate:1 1 udp 2013266431 192.168.1.66 40419 typ host
a=end-of-candidates
m=audio 0 UDP/TLS/RTP/SAVPF 0
c=IN IP4 192.168.1.66
a=inactive
m=video 9 UDP/TLS/RTP/SAVPF 103 104
c=IN IP4 192.168.1.66
b=AS:1024
a=inactive
a=mid:video
a=rtcp-mux
a=ice-ufrag:vWx3
a=ice-pwd:VB48NkttHZLX7oGLlNf2i+
a=ice-options:trickle
a=fingerprint:sha-256 95:2F:CF:B4:F4:0D:2E:76:E2:37:C4:1B:EF:2E:E1:E3:07:5B:21:CE:D7:16:C4:84:C7:9B:EB:65:F7:E5:C9:B0
a=setup:actpass
a=rtpmap:103 H264/90000
a=rtcp-fb:103 ccm fir
a=rtcp-fb:103 ccm tmmbr
a=rtcp-fb:103 nack
a=rtcp-fb:103 nack pli
a=rtpmap:104 rtx/90000
a=fmtp:104 apt=103
a=msid:janus janusv0
a=ssrc:4282870267 cname:janus
a=ssrc:4282870267 msid:janus janusv0
a=ssrc:4282870267 mslabel:janus
a=ssrc:4282870267 label:janusv0
a=ssrc:566197871 cname:janus
a=ssrc:566197871 msid:janus janusv0
a=ssrc:566197871 mslabel:janus
a=ssrc:566197871 label:janusv0
a=candidate:1 1 udp 2013266431 192.168.1.66 40419 typ host
a=end-of-candidates
```

### Your environment.
  - Version: latest (v3.0.15)
  - Browser: No browser (go & janus & freeswitch)
  - Other Information - Build on windows, janus and FS in vm.

### What happened?
either errors or no ontrack

**Comment by Sean-Der** [comment]
Sorry I have been so slow! I really want to help with this, the amount of work has just really caught up with me lately. Will be back on this ASAP :)

**Comment by pascal-ace** [comment]
no worries, I continue without this function. 
What's strange, and maybe it's Janus's fault, but in the first version of Janus that I had installed, I could receive calls, but I took an older version, because I had the some errors after a minute.
I use Janus v0.10.9, no problem with janus on master (except errors), error with ICE in v0.10.10 (missing implementation)

**Comment by pascal-ace** [comment]
For information:
So, after a little investigation, I suspected that the problem came from freeswitch/fusionpbx, it was him who sent several `m=audio || video`, janus added the `inactive`. I don't know why. But then, we arrived at this stage, with a SDP that should work but that nobody has foreseen this case. 

In any case, I solved my problem, I am not blocked anymore, I can make calls in OPUS Audio and in H264 with SIP and fusionpbx and Janus. To solve my problem, I simply put fusionpbx back to its initial state. (because I had modified a lot of parameters to make my tests and correct the previous problems I had with janus).

I let you close the ticket if you wish, or close it once you have managed the `inactive `media in the SDP. 

With a default fusionpbx (and freeswitch), I have this SDP which works perfectly: 


```
offer v=0
o=FreeSWITCH 1614651400 1614651401 IN IP4 192.168.1.66
s=FreeSWITCH
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS janus
m=audio 9 UDP/TLS/RTP/SAVPF 102 9 0 8 104 105 101 13
c=IN IP4 192.168.1.66
a=sendrecv
a=mid:audio
a=rtcp-mux
a=ice-ufrag:6dsP
a=ice-pwd:H8kJMao8taP7CxqAf0Bks1
a=ice-options:trickle
a=fingerprint:sha-256 36:83:9A:9C:49:CA:A7:E5:B6:47:CC:10:2F:4F:AF:C3:60:A8:D0:D9:82:A7:37:85:23:CC:98:28:08:4B:BF:11
a=setup:actpass
a=rtpmap:102 opus/48000/2
a=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:104 telephone-event/48000
a=fmtp:104 0-16
a=rtpmap:105 CN/48000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtpmap:13 CN/8000
a=ptime:20
a=msid:janus janusa0
a=ssrc:3836882962 cname:janus
a=ssrc:3836882962 msid:janus janusa0
a=ssrc:3836882962 mslabel:janus
a=ssrc:3836882962 label:janusa0
a=candidate:1 1 udp 2013266431 192.168.1.66 34305 typ host
a=end-of-candidates
m=video 9 UDP/TLS/RTP/SAVPF 103 104
c=IN IP4 192.168.1.66
b=AS:1024
a=inactive
a=mid:video
a=rtcp-mux
a=ice-ufrag:6dsP
a=ice-pwd:H8kJMao8taP7CxqAf0Bks1
a=ice-options:trickle
a=fingerprint:sha-256 36:83:9A:9C:49:CA:A7:E5:B6:47:CC:10:2F:4F:AF:C3:60:A8:D0:D9:82:A7:37:85:23:CC:98:28:08:4B:BF:11
a=setup:actpass
a=rtpmap:103 H264/90000
a=rtcp-fb:103 ccm fir
a=rtcp-fb:103 ccm tmmbr
a=rtcp-fb:103 nack
a=rtcp-fb:103 nack pli
a=rtpmap:104 rtx/90000
a=fmtp:104 apt=103
a=msid:janus janusv0
a=ssrc:3751164564 cname:janus
a=ssrc:3751164564 msid:janus janusv0
a=ssrc:3751164564 mslabel:janus
a=ssrc:3751164564 label:janusv0
a=ssrc:4180992514 cname:janus
a=ssrc:4180992514 msid:janus janusv0
a=ssrc:4180992514 mslabel:janus
a=ssrc:4180992514 label:janusv0
a=candidate:1 1 udp 2013266431 192.168.1.66 34305 typ host
a=end-of-candidates
```

**Comment by Sean-Der** [comment]
I think everything is working as expected here!

IME being more permissive with mid is the wrong way to go. If we have complicated SDP logic we will end up allowing broken things/have unexpected behavior. 

If anyone thinks we can do more please re-open!
