### ISSUE TITLE
Bring back reverted commit "Fixes MediaEngine: codec apt negotiation"

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#1785]
Our `broadcast` example stopped working after this commit with the following error

```
Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Failed to set remote video description send parameters for m-section with mid='0'.
```

I reverted eeb67e1c5398f1c214f874c1917fd27df8a11845 and should have some time to investigate this weekend. @cnderrauber if you have the bandwidth would love your help, thanks!

**Comment by cnderrauber** [comment]
@Sean-Der  Ok, I will find the reason about this problem.

**Comment by cnderrauber** [comment]
Add a test case for partial match codec with rtx. Broadcast example tested in my mac with browser edge.
