### ISSUE TITLE
Use open ports

### ISSUE THREAD

**Issue by makeworld-the-better-one** [pion/webrtc#1786]
## Summary

It'd be nice if I could give the library a known external address, like a public IP and UDP port, and then have that be part of the SDP / ICE candidates.

## Motivation

My main interest in WebRTC is in NAT traversal, using it as a generic P2P transport. It's also nice that it can work in the browser. But outside of the browser there are some existing techniques for NAT traversal like UPnP and NAT-PMP. These standards allow for opening a port on the router. There already existing Go libraries for this, like [huin/goupnp](https://github.com/huin/goupnp) and [jackpal/go-nat-pmp](https://github.com/jackpal/go-nat-pmp). I don't think Pion should integrate these libs, but it'd be nice if on a desktop I could call them, get an address, and then give it to Pion to try and use when establishing the WebRTC connection. This will make for faster connection setup, and can create direct connections in places where STUN doesn't work.

## Describe alternatives you've considered

Not sure of anything that can do this. Maybe it's already available in the library and I just don't know about it. Maybe just by adding an SDP line before sending it? If that's possible I'd appreciate if someone could share some code.

**Comment by Sean-Der** [comment]
Hey @makeworld-the-better-one 

This does exist today! Check out [SetNAT1To1IPs](https://pkg.go.dev/github.com/pion/webrtc/v3#SettingEngine. SetNAT1To1IPs). When you do implement you should write a blog post! I have never seen any numbers, but I am personally curious about the success rate of STUN vs nat-pmp.
