### ISSUE TITLE
Single Port mode(NewICEUDPMux) and AWS(SetNAT1To1IPs)

### ISSUE THREAD

**Issue by sampleref** [pion/webrtc#1791]
Hi, 

I am trying to use single-port mode on AWS, so using below configuration options:

For example:
_AWS External IP: 13.125.134.27
AWS Internal IP: 10.0.0.78
ICEUDPMux: 50501_

And 
```
singlePortUdpListener, err := net.ListenUDP("udp", &net.UDPAddr{
		IP:   net.IP{0, 0, 0, 0},
		Port: 50501,
	})
settingEngine.SetICEUDPMux(webrtc.NewICEUDPMux(nil, singlePortUdpListener))
```

1. With `settingEngine.SetNAT1To1IPs("13.125.134.27", webrtc.ICECandidateTypeSrflx) `

    ice candidates are generated as below:

   
 ```
    candidate:271088779 1 udp 2130706431 10.0.0.78 50501 typ host
    candidate:233762139 1 udp 2130706431 172.17.0.1 50501 typ host
    candidate:33487147 1 udp 1694498815 13.125.134.27 50536 typ srflx raddr 0.0.0.0 rport 50536 
```

    Ice candidate is generated but UDPMux port(50501) is not chosen but some random port for srflx as 50536 where ice connection fails

2. With `settingEngine.SetNAT1To1IPs("13.125.134.27", webrtc.ICECandidateTypeHost)`

     ice candidates are generated as below:
    
    ` candidate:80214168 1 udp 2130706431 13.125.134.27 50501 typ host`

      No ice candidate is generated with type srflx where ice connection setup is failing

I would like to know if this **single-port mode(SetICEUDPMux) + SetNAT1To1IPs( AWS External IP )** is right way if I have to deploy on AWS with single incoming UDP connection open?

Please let know if any additional config is needed here or any better way to achieve this

Thanks

**Comment by Sean-Der** [comment]
@davidzhao fixed this with https://github.com/pion/ice/pull/363/files case 2 should now work. I am not sure about how it fixes it though.

I think there is a bug where we are generating listeners other then UDPMux? IMO If you use UDPMux you shouldn't gather any other candidates. The intent of the user is they want to just use a single port.

I will make sure to get this fixed ASAP. I have been slowing down David :(

**Comment by davidzhao** [comment]
Fixed in c4d5d1c67026994a9d53e54574798c98fd5cfdb0

**Comment by Sean-Der** [comment]
@sampleref this should be fixed in WebRTC master now! Thanks for the issue :)

**Comment by sampleref** [comment]
I tried with WebRTC master and as along with ice v2.1.6, its looks to be giving out same behavior,

For same AWS setup as above,
AWS External IP: 13.125.134.27
AWS Internal IP: 10.0.0.78
ICEUDPMux: 50501

candidate:271088779 1 udp 2130706431 10.0.0.78 50501 typ host
candidate:33487147 1 udp 1694498815 13.125.134.27 55886 typ srflx raddr 0.0.0.0 rport 55886

Just curious that may be the UDPMux conn is not verified when generating srflx candidate types, in https://github.com/pion/ice/blob/v2.1.6/gather.go   

But if there is something else I am missing please let know

**Comment by davidzhao** [comment]
@sampleref you'll need to enable NAT address mapping with `SetNAT1To1IPs` on AWS nodes. srflx does not require the mux as those ports are essentially considered "outbound" traffic.

**Comment by sampleref** [comment]
so for AWS EC2 with :
External IP: 13.125.134.27
Internal IP: 10.0.0.78

 is it that I should create NAT address mapping from 13.125.134.27 to 10.0.0.78 on AWS node? I am not fully aware of AWS features so, please let know if I am missing something here or any quick reference will be helpful

**Comment by davidzhao** [comment]
so what you'd want to do is:

1. `SetNat1To1IPs(["13.125.134.27"])`
2. Configure UDPMux to listen on <fixedport>
3. Open security group to allow UDP <fixedport> to go through

The rest should be handled automatically by PIon.

Single port will *NOT* be used for srflx candidates; they do not need to be forwarded. srflx candidates are used with STUN and are able to hole punch through NAT.

**Comment by sampleref** [comment]
Yes This worked,

1. SetNat1To1IPs(["13.125.134.27"], webrtc.ICECandidateTypeHost)
2. Configure UDPMux to listen on fixedport
3. Configure security group to allow inbound UDP on fixedport to go through

Thanks @davidzhao for the support

**Comment by davidzhao** [comment]
Thanks for the update, I'm glad to hear that!
