### ISSUE TITLE
Long time with multiple network interfaces

### ISSUE THREAD

**Issue by mlgarrido** [pion/webrtc#1798]
With the "Broadcast" example, when I use my PC with two network interfaces, It takes 40 seconds or more to connect, I think the GatheringCompletePromise are the cause of the delay. 

I think this is a bug, but i'm not sure if there is another way to avoid it.

If it can be avoided. What can I do to prevent that?

Thanks.

**Comment by zyxar** [comment]
for v3 with trickle-ice enabled, you don't need _GatheringCompletePromise_ (a helper function to simulate non-trickle ICE) if you are able to migrate to the _trickle_ way.
check [sfu-ws](https://github.com/pion/example-webrtc-applications/blob/master/sfu-ws/main.go) for example.

**Comment by mlgarrido** [comment]
WORKING!!! thanks!
