### ISSUE TITLE
Potential deadlock : createoffer when ice connection state changing

### ISSUE THREAD

**Issue by cnderrauber** [pion/webrtc#1809]
### Your environment.
  - Version: fork from v3.0.26
  - Browser:  client use pion
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

```
goroutine 1
5574     2  0x00000000009382e5 in github.com/pion/ice/v2.(*Agent).run
5575         at /home/luog/go/pkg/mod/github.com/pion/ice/v2@v2.1.6/agent.go:177
5576     3  0x000000000093c0f9 in github.com/pion/ice/v2.(*Agent).GetLocalUserCredentials
5577         at /home/luog/go/pkg/mod/github.com/pion/ice/v2@v2.1.6/agent.go:859
5578     4  0x000000000096dc8a in github.com/pion/webrtc/v3.(*ICEGatherer).GetLocalParameters
5579         at /home/luog/go/pkg/mod/github.com/cnderrauber/webrtc/v3@v3.0.24/icegatherer.go:200
5580     5  0x0000000000985d3d in github.com/pion/webrtc/v3.(*PeerConnection).generateMatchedSDP
5581         at /home/luog/go/pkg/mod/github.com/cnderrauber/webrtc/v3@v3.0.24/peerconnection.go:2216
5582     6  0x000000000097a21f in github.com/pion/webrtc/v3.(*PeerConnection).CreateOffer

goroutine 2
5517     3  0x0000000000951405 in github.com/pion/ice/v2.(*Agent).updateConnectionState.func1
5518         at /home/luog/go/pkg/mod/github.com/pion/ice/v2@v2.1.6/agent.go:559
5519     4  0x0000000000950719 in github.com/pion/ice/v2.(*Agent).taskLoop.func1
5520         at /home/luog/go/pkg/mod/github.com/pion/ice/v2@v2.1.6/agent.go:196
5521     5  0x0000000000938485 in github.com/pion/ice/v2.(*Agent).taskLoop
5522         at /home/luog/go/pkg/mod/github.com/pion/ice/v2@v2.1.6/agent.go:225


goroutine 3
5551      7  0x000000000097919a in github.com/pion/webrtc/v3.(*PeerConnection).onICEConnectionStateChange
5552          at /home/luog/go/pkg/mod/github.com/cnderrauber/webrtc/v3@v3.0.24/peerconnection.go:467
5553      8  0x00000000009a36d7 in github.com/pion/webrtc/v3.(*PeerConnection).createICETransport.func1
5554          at /home/luog/go/pkg/mod/github.com/cnderrauber/webrtc/v3@v3.0.24/peerconnection.go:781
5555      9  0x000000000096fdf4 in github.com/pion/webrtc/v3.(*ICETransport).onConnectionStateChange
5556          at /home/luog/go/pkg/mod/github.com/cnderrauber/webrtc/v3@v3.0.24/icetransport.go:224
5557     10  0x00000000009a2d95 in github.com/pion/webrtc/v3.(*ICETransport).Start.func1
```

### What did you do?

I call pc.CreateOffer when ice is connecting, means there is ice connctions state is changing. Then peerconnection is deadlock. 

In stacktrace above, goroutine1 : CreateOffer hold pc.mu, and call GetLocalParameters -> agent.run(...) then wait at agent.go:180 
```

	select {
	case <-ctx.Done():
		return ctx.Err()
	case a.chanTask <- task{t, done}:
		<-done
		return nil
	}
```

But in goroutine 2 at agent.go:225, agent taskloop may call onConnectionStatechange, and wait at agent.go:559
```

		a.afterRun(func(ctx context.Context) {
			a.chanState <- newState
		})

```

Then in goroutine3 at agent.go 424, the recv from chanState my block in onConnectionStateChange, because it try to lock pc.mu, and the mutex is hold by goroutine1.  (agent.onConnectionStateChange -> icetransport.onConnectionStateChange -> peerconnection.onIceConnectionStateChange).

```

	pc.mu.Lock()
	pc.iceConnectionState = cs
	handler := pc.onICEConnectionStateChangeHandler
	pc.mu.Unlock()

	pc.log.Infof("ICE connection state changed: %s", cs)
	if handler != nil {
		go handler(cs)
	}

```

### What did you expect?
No deadlock.

### What happened?
Deadlock in peerconnection if call CreateOffer when ice is connecting. (occasional)

I found that because Agent's chanState has no buffer, should we use a buffered channel to avoid deadlock?

Although we can require user of pion don't call createoffer when ice is not connected, but I think avoid deadlock in library is better.

**Comment by zyxar** [comment]
I fixed a similar deadlock some time before. Better to resolve the potential race in pion/ice, maybe.

**Comment by cnderrauber** [comment]
Yes I see your pull request about the deadlock. I think you are right.  The problem is from pion/ice

**Comment by Sean-Der** [comment]
Nice catch @cnderrauber 

Could we make `iceConnectionState` and `onICEConnectionStateChangeHandler` an atomic? That way `onICEConnectionStateChange` doesn't need to take the lock.

Neither seemed to be used in a transaction, so it would be ok if either were changed at anytime.

**Comment by cnderrauber** [comment]
> Nice catch @cnderrauber 
> 
> Could we make `iceConnectionState` and `onICEConnectionStateChangeHandler` an atomic? That way `onICEConnectionStateChange` doesn't need to take the lock.
> 
> Neither seemed to be used in a transaction, so it would be ok if either were changed at anytime.

Yes, I think it will work.
 I want to know why the channel in agent are all unbuffered,does it is by design?

**Comment by Sean-Der** [comment]
I didn't make a decision to do unbuffered/buffered. I just did the default of unbuffered. 

If you want to open a PR to add a buffer I think that would be ok! I worry it wouldn't fix the root issue though, I would have the follow questions.

* How did you pick the buffer size? It would have to be an arbitrary decision.
* Could we still hit the deadlock if we don't read fast enough?

The nice thing about the atomic change is that it fixes the root cause.

**Comment by cnderrauber** [comment]
Yes, I agree to you about the atomic

**Comment by digitalix** [comment]
I've just hit the problem, is there anything being done about this issue?
