### ISSUE TITLE
i can't find that about 'x-google-max-bitrate' & 'x-google-min-bitrate' in process sdp moudle,  is there any other way to control bitrate?

### ISSUE THREAD

**Issue by legal-username** [pion/webrtc#1826]
## Summary

i can't find that about 'x-google-max-bitrate' & 'x-google-min-bitrate' in process sdp moudle,  is there any other way to control bitrate?

**Comment by Sean-Der** [comment]
Hey @legal-username 

Pion WebRTC only handles media transport. We don't provide an encoder so those two values will not have an effect. In your application you can parse the SDP and perform behavior however you like.
