### ISSUE TITLE
Generate RemoteDescription from only (IceCandidates, Pwd and UFrag, FingerPrints)

### ISSUE THREAD

**Issue by Laky-64** [pion/webrtc#1859]
It's possible to generate RemoteDescription from just this values?
Because Telegram use this, i need to pass before to telegram the (Fingerprint, Hash, Setup, Pwd and UFrag, Audio Source value)
And then i get (IceCandidates, Pwd and UFrag, FingerPrints), from this i need to generate the RemoteDescription

Thanks in advance

**Comment by Sean-Der** [comment]
Hey @Laky-64 

Unfortunately nothing like that exists in the WebRTC spec. I think the best thing you can do is use https://github.com/pion/sdp to parse/generate values.

If you have questions about what values matter, or the right place to put them (global or media level) happy to help here or on [Slack](https://pion.ly/slack)
