### ISSUE TITLE
Samplebuilder packet loss on RTP sequence number wrap

### ISSUE THREAD

**Issue by kevindejong** [pion/webrtc#1870]
### Your environment.
  - Version: v3.0.30
  - Browser: N/A
  - Other Information -

### What did you do?

I have pion-to-pion connection which is streaming VP8 video and using the `samplebuilder` to reconstruct the samples.  The sender uses an unaltered `VP8Payloader`, `rtp.Packetizer`, and `rtp.RandomSequencer` though it does set the RTP timestamp in the RTP header using a custom heuristic.

### What did you expect?

During testing over a connection on a local network, I expected the `samplebuilder` not to experience loss when reconstructing samples.  For the most part this is working correctly, however I have noticed that the `samplebuilder` consistently reports packet loss when the RTP sequence number wraps.  

### What happened?

After the sequence number hits 65535, I see it wrap to 0 however I don't see any more samples emitted until it reaches a sequence number of 100 (the configured `maxLate`) after which it emits a sample which reports `PrevDroppedPackets` > 0.  (As an aside, it seems that when the sequence number wraps it can take more than `maxLate` packets for the sample to be emitted as it will be emitted on `maxLate` packets after 0, but this does not include the number of packets received before the wrap.)

As an example, here are some (filtered) logs from my application, `packet` is the RTP header timestamp and `seq` is the RTP sequence number 

```
TRAC[0048] received rtp packet                           codec=video/VP8 len=794 packet=2597305381 seq=65529
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=65530
TRAC[0048] assembled sample                               codec=video/vp8 dropped=0 duration=66.666666ms length=10262 packet=2597305381 timestamp="2021-07-05 19:49:19.599995363 +0000 UTC"      
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=65531
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=65532
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=65533
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=65534
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=65535
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=0
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=1
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=2
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=3
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=4
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597311381 seq=5
TRAC[0048] received rtp packet                           codec=video/VP8 len=1040 packet=2597311381 seq=6
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597317381 seq=7

...

TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597365382 seq=100
TRAC[0048] assembled sample                               codec=video/vp8 dropped=13 duration=66.666666ms length=13031 packet=2597317381 timestamp="2021-07-05 19:49:19.733327363 +0000 UTC"
TRAC[0048] received rtp packet                           codec=video/VP8 len=1188 packet=2597365382 seq=101
```

The sample which is lost (2597311381) is the sample which falls on the sequence number wrap.  The sample for the subsequent timestamp (2597317381) correctly reports 13 dropped packets however it appears that all 13 packets were received in-order (seq 65530-65535 and 0-6).

**Comment by jech** [comment]
Please let me know if you have the same issues with https://github.com/jech/samplebuilder
