### ISSUE TITLE
Can support aac codes, which payloadtype=104?

### ISSUE THREAD

**Issue by yourchanges** [pion/webrtc#1888]
I test on a Hik camera, but can't get the audio works, so please support the aac codecs, thank you!

here is the stream info:

```
Input #0, rtsp, from 'rtsp://xxx:xxxk@xxxxxx:40052/Streaming/Channels/701':
  Metadata:
    title           : HIK Media Server V4.30.210
    comment         : HIK Media Server Session Description : standard
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp

```

the original audio stream is:  " Stream #0:1: Audio: aac, 16000 Hz, mono, fltp"
it seems not h264 standard aac codecs, it will work on webrtc ?

I use pion v2.2.26, it only has
```
	DefaultPayloadTypePCMU = 0
	DefaultPayloadTypePCMA = 8
	DefaultPayloadTypeG722 = 9
	DefaultPayloadTypeOpus = 111
	DefaultPayloadTypeVP8  = 96
	DefaultPayloadTypeVP9  = 98
	DefaultPayloadTypeH264 = 102
```
and my HIK media server's audio acc payloadtype is 104, here is rtsp despcrtion
```
m=audio 0 RTP/AVP 104
 i=Audio Media
a=rtpmap:104 MPEG4-GENERIC/16000/1
a=control:trackID=audio
a=fmtp:104 profile-level-id=15; streamtype=5; mode=AAC-hbr; config=1408;SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;
b=AS:10
a=Media_header:MEDIAINFO=494D4B48020100000400000101200210401F00000000000000000000000000000000000000000000;
a=appversion:1.0
```

**Comment by yourchanges** [comment]
the number "104" seems is dynamic, but it can be identify by "MPEG4-GENERIC"

**Comment by Sean-Der** [comment]
Hey @yourchanges 

WebRTC doesn't support AAC unfortunately. You will have to transcode to Opus or PCM.

We could add support to `github.com/pion/rtp` or maybe add a library that makes transcoding easier, but we can't play AAC in the browser.

**Comment by yourchanges** [comment]
Get it，Thank you very much！

Sean DuBois ***@***.***>于2021年7月16日 周五23:15写道：

**Comment by yourchanges** [comment]
@Sean-Der 

Could you add support to github.com/pion/rtp or maybe add a library that makes transcoding (aac->pcm) easier?

**Comment by AngellusMortis** [comment]
> WebRTC doesn't support AAC unfortunately. You will have to transcode to Opus or PCM.

Do you have a source on WebRTC not support AAC? I have seen that in a lot of places, but as far as I can tell, AAC support for WebRTC is 100% up to the browser and not required to be supported. Likely because it is not an open codec.

[MDN](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/WebRTC_codecs) actually says multiple times that the docs they list are only the _required_ ones and that browsers can choose to add more.

> This guide reviews the codecs that browsers are required to implement as well as other codecs that some or all browsers support for WebRTC.

> The list above indicates the minimum required set of codecs that all WebRTC-compatible endpoints are required to implement. A given browser may also support other codecs; however, cross-platform and cross-device compatibility may be at risk if you use other codecs without carefully ensuring that support exists in all browsers your users might choose.

You can also see on [MDN's page for AAC](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#aac_advanced_audio_coding) or [caniuse](https://caniuse.com/aac) that AAC is supported in nearly every browser.

**Comment by Sean-Der** [comment]
Hey @AngellusMortis 

[rfc7874](https://datatracker.ietf.org/doc/html/rfc7874#section-3) has Opus, PCMA/PCMU and CN  as REQUIRED.

Nothing is stopping WebRTC agents from supporting AAC. However libwebrtc the implementation used in every web browser [does not have AAC](https://source.chromium.org/search?q=AAC&sq=&ss=chromium%2Fchromium%2Fsrc:third_party%2Fwebrtc%2F) 

If you want to do Pion <-> Pion you can specify AAC in the MediaEngine and send the packets.

**Comment by AngellusMortis** [comment]
@Sean-Der thanks for the response. That really helps me fill in the part I was missing. One of my co-workers who knows a bit more about WebRTC also pointed the same thing out.

Browser's WebRTC implementation is 100% separate from their own media implementations so it cannot reuse system codecs and/or other codecs supported from elsewhere. That definitely seems maddeningly annoying.

**Comment by Sean-Der** [comment]
@AngellusMortis best of luck on what you are building! I have seen users do `AAC -> Opus` using cgo, nothing in Pure Go that I know of unfortunately. 

If you want to chat/throw ideas my way I am always around in [Slack](https://pion.ly/slack). Best of luck with your project :)

**Comment by cedricve** [comment]
@Sean-Der  Is there any example to transcode an audio channel (AAC) to OPUS/PCM?
