### ISSUE TITLE
Enable Transport Wide Congestion Control by default

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#1907]
Transport Wide Congestion Control is available in pion/interceptor. We should enable it by default.

**Comment by jech** [comment]
It's only the feedback part, right?  I cannot find the actual congestion controller (the sender-side part).

**Comment by mengelbart** [comment]
Right, the current implementation in pion/interceptor includes only interceptors to add a header extension at sender side and to produce the feedback at receiver side, no actual congestion controller to do bandwidth estimation.

I didn't read the discussion on the mailing list, Sean and I were talking about implementing a congestion controller based on TWCC next, but I think we could add REMB, too. I can't say much about which is best to enable by default though.

**Comment by Sean-Der** [comment]
@jech It will be behind `RegisterDefaultInterceptors` we still will not send any RTCP (or perform actions on incoming). My plan is that we will keep it that way forever. The use cases of Pion are just too varied to force anything.
