### ISSUE TITLE
examples/play-from-disk failed in challenging signature of ivf file

### ISSUE THREAD

**Issue by http600** [pion/webrtc#1924]
### Your environment.
  - Version: f7f760f8c6e2f1aba1bf7c544fdd84d70f6e05b6
  - Browser: Chrome(Windows) Version 92.0.4515.131 (Official Build) (64-bit)
  - Golang(Windows): 1.16.5
  - Windows: 10
  - ffmpeg(running in Ubuntu): 4.2.4-1ubuntu0.1

### What did you do?

1. Prepare output.ivf and output.ogg files
    1. run `ffmpeg -i amazing.mp4 -g 30 output.ivf`
    2. run `ffmpeg -i amazing.mp4 -c:a libopus -page_duration 20000 -vn output.ogg`
2. Run play-from-disk
    1. copy ivf and ogg to right place
    2. run play-from-disk

### What did you expect?
Should not report error, should do something, like playing
### What happened?
It says: 

> panic: IVF signature mismatch
> 
> goroutine 12 [running]:
> main.main.func2(0x97b160, 0xc00004de80, 0xc0000dd170)
> 	D:/workspace/pion/webrtc/examples/play-from-disk/main.go:82 +0x35c
> created by main.main
> 	D:/workspace/pion/webrtc/examples/play-from-disk/main.go:73 +0x949
> 
> Process finished with the exit code 2

It leads to https://github.com/pion/webrtc/blob/0735efd344a71601a4a51d45686667029358ce22/pkg/media/ivfreader/ivfreader.go#L137 asking `DKIF` as signature, but what I have the 4 bytes are `00000020` representing in hex.

How to prepare correct ivf file or is there something else wrong?

**Comment by Twometer** [comment]
If the signature doesn't match, it probably is not a valid ivf file. What was the output from the ivf ffmpeg command?

**Comment by http600** [comment]
oh, yes, actually the processing of `ffmpeg from mp4 to ivf` failed, but i did not notice the error info
