### ISSUE TITLE
Missing packets in rtp forwarding for higher quality videos

### ISSUE THREAD

**Issue by marlocarlo** [pion/webrtc#1938]
Hi,
When I send HD video from a peer to the rtp-forwarder and use ffmpeg to stream, I get this error :

[sdp @ 0x55a64b1aca00] max delay reached. need to consume packet
[sdp @ 0x55a64b1aca00] RTP: missed 43 packets
[sdp @ 0x55a64b1aca00] max delay reached. need to consume packet
[sdp @ 0x55a64b1aca00] RTP: missed 20 packets

In addition to that, the video is fully pixelated and garbled. Please advise.

Thanks.

_Originally posted by @marlocarlo in https://github.com/pion/webrtc/discussions/1935_

**Comment by Sean-Der** [comment]
Hey @marlocarlo 

I am going to close this and use #1935. This isn't a specific issue with pion/webrtc, but will be useful information for others!
