### ISSUE TITLE
Self-signed certificate generation input should match libwebrtc (NotBefore/NotAfter/IsCA/Subject)

### ISSUE THREAD

**Issue by adriancable** [pion/webrtc#1940]
### Environment
  - Version: *pion-webrtc v3.0.32*
  - OS: *macOS 11.5.2*
  - Go: *1.17 darwin/amd64*

### What I'm trying to do
I have a camera that produces a WebRTC video/audio stream that I want to receive (H264/OPUS RTP packets) in pion-webrtc.

In Chromium/JavaScript getting the stream 'just works' ... I set up offer/answer, RTCPeerConnection, add the stream to an HTML video element when the stream appears and it's all hunky dory.

I am now trying to set things up in pion-webrtc. Starting point is more or less the save-to-disk example (which works fine when sending it video from a browser, as per the demo), except the server side (i.e. pion-webrtc) is creating the offer and the camera is giving me back the answer. Offer/answer look fine (very similar to what Chromium produces - attached for completeness but I don't think the issue is here), but pion-webrtc breaks during the DTLS handshake (before OnTrack is fired). I am not sure if this is 'operator error' or an issue with pion-webrtc but I am out of ideas at this point. Any help would be very much appreciated!

### The log
Here's the log from pion-webrtc, with the uninteresting bits cut out.

pc INFO: 2021/08/31 08:02:49 signaling state changed to stable
ice DEBUG: 08:02:49.913860 agent.go:451: Started agent: isControlling? true, remoteUfrag: "W6HPCIBDBEYIH1NM", remotePwd: "MWGYIL4TM+RYJWQXFUI6IIFR"
ice INFO: 2021/08/31 08:02:49 Setting new connection state: Checking
pc INFO: 2021/08/31 08:02:49 ICE connection state changed: checking
ice TRACE: 08:02:49.914018 agent.go:593: pinging all candidates
ice TRACE: 08:02:49.914086 agent.go:953: ping STUN from udp4 host 10.0.0.22:52440 to udp4 host 74.125.197.127:19305
ice TRACE: 08:02:49.914163 agent.go:953: ping STUN from udp4 srflx 73.189.212.170:57092 related 0.0.0.0:57092 to udp4 host 74.125.197.127:19305
...
ice TRACE: 08:02:50.361480 selection.go:140: Found valid candidate pair: prio 9079301926608164607 (local, prio 2130706431) udp6 host 2601:646:c500:1487:14d2:2b3:f56f:fb0a:60848 <-> udp6 host 2607:f8b0:400e:c03::7f:19305 (remote, prio 2113939711)
ice TRACE: 08:02:50.361499 agent.go:565: Set selected candidate pair: prio 9079301926608164607 (local, prio 2130706431) udp6 host 2601:646:c500:1487:14d2:2b3:f56f:fb0a:60848 <-> udp6 host 2607:f8b0:400e:c03::7f:19305 (remote, prio 2113939711)
ice INFO: 2021/08/31 08:02:50 Setting new connection state: Connected
pc INFO: 2021/08/31 08:02:50 ICE connection state changed: connected
dtls TRACE: 08:02:50.361733 handshaker.go:163: [handshake:client] Flight 1: Preparing
dtls TRACE: 08:02:50.361796 handshaker.go:163: [handshake:client] Flight 1: Sending
dtls TRACE: 08:02:50.361824 conn.go:379: [handshake:client] -> ClientHello (epoch: 0, seq: 0)
dtls TRACE: 08:02:50.361903 handshaker.go:163: [handshake:client] Flight 1: Waiting
dtls TRACE: 08:02:50.406946 flight3handler.go:93: [handshake] use cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
dtls TRACE: 08:02:50.407174 handshaker.go:279: [handshake:client] Flight 1 -> Flight 5
dtls TRACE: 08:02:50.407192 handshaker.go:163: [handshake:client] Flight 5: Preparing
dtls TRACE: 08:02:50.407668 handshaker.go:231: [handshake:client] -> changeCipherSpec (epoch: 1)
dtls TRACE: 08:02:50.407686 handshaker.go:163: [handshake:client] Flight 5: Sending
dtls TRACE: 08:02:50.407695 conn.go:379: [handshake:client] -> TypeCertificate (epoch: 0, seq: 1)
dtls TRACE: 08:02:50.407706 conn.go:379: [handshake:client] -> ClientKeyExchange (epoch: 0, seq: 2)
dtls TRACE: 08:02:50.407714 conn.go:379: [handshake:client] -> CertificateVerify (epoch: 0, seq: 3)
dtls TRACE: 08:02:50.407723 conn.go:379: [handshake:client] -> Finished (epoch: 1, seq: 4)
dtls TRACE: 08:02:50.407839 handshaker.go:163: [handshake:client] Flight 5: Waiting
**dtls TRACE: 08:02:50.444225 conn.go:716: client: <- Alert Fatal: UnknownCA
pc INFO: 2021/08/31 08:02:50 peer connection state changed: failed
pc WARNING: 2021/08/31 08:02:50 Failed to start manager: handshake error: alert: Alert Fatal: UnknownCA
pc WARNING: 2021/08/31 08:02:50 RTPReceiver Receive failed the DTLS transport has not started yet**

[sdp_offer_from_pion.txt](https://github.com/pion/webrtc/files/7085087/sdp_offer_from_pion.txt)
[sdp_answer_from_device_to_pion.txt](https://github.com/pion/webrtc/files/7085086/sdp_answer_from_device_to_pion.txt)

**Comment by Sean-Der** [comment]
We debugging this on Slack and it turns out the remote host is asserting attributes of the self signed certificate. I believe certificate lifetime?

@adriancable (or myself) will be opening a PR soon to update Pion's self signed certificate generation to match libwebrtc's
