### ISSUE TITLE
DataChannel and PeerConnection already close, but the memory not erase

### ISSUE THREAD

**Issue by leeliliang** [pion/webrtc#1951]

**Comment by leeliliang** [comment]
this is the example
package dataChannel

import (
	"encoding/json"
	"fmt"
	"net"
	"net/url"

	frame "UdpSignal/src/Frame"
	"UdpSignal/src/config"
	"UdpSignal/src/util"
	"UdpSignal/src/util/logger"

	"github.com/pion/webrtc/v3"

	"go.uber.org/zap"
)

var api *webrtc.API
var WssUrl url.URL

const (
	FuncIceListen = "IceListen"
	FuncDCConnect = "DCConnect"
)

func IceListen(publicIp string, privateIp string, port string) {

	host := fmt.Sprintf("%s:%s", privateIp, port)
	udpaddr, err := net.ResolveUDPAddr("udp4", host)
	udpListener, err := net.ListenUDP("udp", udpaddr)
	if err != nil {
		panic(err)
	}

	logger.Logger.Warn(FuncIceListen, zap.String("Listening for WebRTC traffic at: ", udpListener.LocalAddr().String()))

	settingEngine := webrtc.SettingEngine{}

	if publicIp != "" {
		ips := []string{publicIp}
		settingEngine.SetNAT1To1IPs(ips, webrtc.ICECandidateTypeHost)
	}

	settingEngine.SetICEUDPMux(webrtc.NewICEUDPMux(nil, udpListener))

	api = webrtc.NewAPI(webrtc.WithSettingEngine(settingEngine))
}

type DataChannelClient struct {
	Uid string
	DC  *webrtc.DataChannel
	PC  *webrtc.PeerConnection
	FC     *frame.FrameControl
	RMAddr string
}

func (dataChannelClient *DataChannelClient) Erase() {

}

func (dataChannelClient *DataChannelClient) DCConnect(offer *webrtc.SessionDescription) (*webrtc.SessionDescription, error) {

	dataChannelClient.FC = &frame.FrameControl{}
	dataChannelClient.FC.Init()

	pc, err := api.NewPeerConnection(webrtc.Configuration{})
	if err != nil {
		logger.Logger.Error(FuncDCConnect, zap.String(util.Msg, err.Error()))
		return nil, err
	}

	pc.OnICEConnectionStateChange(func(connectionState webrtc.ICEConnectionState) {
		logger.Logger.Info(FuncDCConnect, zap.String(util.State, connectionState.String()), zap.String(util.RemoteAddr, dataChannelClient.RMAddr))
		if connectionState.String() == "disconnected" || connectionState.String() == "failed" {

			dataChannelClient.Close()
		}
	})

	pc.OnDataChannel(func(dc *webrtc.DataChannel) {

		dc.OnOpen(func() {

			logger.Logger.Info(FuncDCConnect, zap.String(util.State, util.Open), zap.String(util.RemoteAddr, dataChannelClient.RMAddr))

		})

		dc.OnMessage(func(msg webrtc.DataChannelMessage) {
			result := msg.Data
			if string(msg.Data)[0] == []byte("1")[0] {
				sendData := string(msg.Data)[1:len(msg.Data)]
				logger.Logger.Debug(FuncDCConnect, zap.String(util.Data, sendData))
				recvData := websocketClient.UdpFrame{}
				err := json.Unmarshal([]byte(sendData), &recvData)
				if err != nil {
					logger.Logger.Error(FuncDCConnect, zap.String(util.Data, sendData), zap.String(util.Msg, err.Error()))
				}
				result = dataChannelClient.FC.ProcessFrame(&recvData)
			}
			logger.Logger.Debug(FuncDCConnect, zap.String(util.Data, string(result)))

		})

		dc.OnClose(func() {
			logger.Logger.Warn(FuncDCConnect, zap.String(util.RemoteAddr, dataChannelClient.RMAddr), zap.String(util.Info, util.Close))

		})

		dc.OnError(func(err error) {
			logger.Logger.Error(FuncDCConnect, zap.String(util.RemoteAddr, dataChannelClient.RMAddr), zap.String(util.Info, util.Error))


		})
		dataChannelClient.DC = dc
	})

	logger.Logger.Debug(FuncDCConnect, zap.String(util.Offer, offer.SDP))
	if err = pc.SetRemoteDescription(*offer); err != nil {
		logger.Logger.Error(FuncDCConnect, zap.String(util.Msg, err.Error()))
		return nil, err
	}

	gatherComplete := webrtc.GatheringCompletePromise(pc)

	answer, err := pc.CreateAnswer(nil)
	if err != nil {
		logger.Logger.Error(FuncDCConnect, zap.String(util.Msg, err.Error()))
		return nil, err
	} else if err = pc.SetLocalDescription(answer); err != nil {
		logger.Logger.Error(FuncDCConnect, zap.String(util.Msg, err.Error()))
		return nil, err
	}

	<-gatherComplete
	response := pc.LocalDescription()
	dataChannelClient.PC = pc
	return response, nil
}

func (dataChannelClient *DataChannelClient) Close() {
	if (dataChannelClient.DC != nil) && (dataChannelClient.DC.ReadyState() != webrtc.DataChannelStateClosed) {
		logger.Logger.Warn(FuncDCConnect, zap.String(util.RemoteAddr, dataChannelClient.RMAddr), zap.String(util.Info, util.Close))
		dataChannelClient.DC.Close()
	}

	if dataChannelClient.PC != nil {
		state := dataChannelClient.PC.SignalingState()
		if int(state) != int(webrtc.PeerConnectionStateClosed) {
			logger.Logger.Warn(FuncDCConnect, zap.String(util.RemoteAddr, dataChannelClient.RMAddr), zap.String(util.Info, util.Close))
			dataChannelClient.PC.Close()
		}
	}

	if dataChannelClient.FC != nil {
		logger.Logger.Warn(FuncDCConnect, zap.String(util.RemoteAddr, dataChannelClient.RMAddr), zap.String(util.Info, util.Close))
		dataChannelClient.FC.Erase()
	}
}

**Comment by wargebitebane** [comment]
How did you fix it? I'm getting same problem.

**Comment by Sean-Der** [comment]
Hi @wargebitebane 

Are you making sure to call `PeerConnection.Close()`? If you do that all memory/goroutines should be freed.

Can you share a memory profile if that doesn't help?

**Comment by leeliliang** [comment]
> How did you fix it? I'm getting same problem.
func DCRelease() {
	logger.Logger.Warn("DCRelease start FreeOSMemory")
	debug.FreeOSMemory()
	//runtime.GC()
	//TraceMemStats()
}
try this every minutes
