### ISSUE TITLE
Enabling Transport Wide Congestion Control breaks Simulcast

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#1957]
If I enable TWCC `examples/simulcast` now breaks with 

```
pc ERROR: 2021/09/14 14:44:34 Incoming unhandled RTP ssrc(1780109122), OnTrack will not be fired. incoming SSRC failed Simulcast probing
```

**Comment by Sean-Der** [comment]
@mengelbart This one is suprising, you see anything around this before? I am looking into it now.

I am getting RTP packets without rid/mid headers, will keep investigating.

**Comment by Sean-Der** [comment]
Without rid/mid headers is a red herring!

Tracks aren't getting enabled with TWCC enabled because the BWE is stuck at the floor.

**Comment by jech** [comment]
I suspect that's due to negotiating `urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id`.  I'm not seeing the issue in Galene (which is not negotiating said extension).

**Comment by Sean-Der** [comment]
@jech Yes it was because of RTX stream. Even if I removed `repaired-rtp-stream-id` Chrome would still emit a RTX. Only when I removed support from the MediaEngine did it start working.

With TWCC Chrome seems to be re-sending packets if we mark them as lost in TWCC. If we ignored RTX we would lose the RTX, and it would just spiral from there. We have the HeaderExtension + RTX enabled in the examples, so things would break if we turned on TWCC by default.

What we really need to do is expose RTX to users. Either as a distinct stream in the RemoteTrack OR unpack the packets for users and copy them into the original stream. Then things would be processed properly, instead of us having to read the streams that we don't expose to users.

**Comment by jech** [comment]
What do you mean « I removed support from the MediaEngine » ?  Support for what?

If that's what happening, then it is very bad: without NACK, WebRTC video is essentially unusable over WiFi.  If we're dropping all NACKed packets, then Pion is essentially broken for video.

**Comment by Sean-Der** [comment]
We support NACKs, but not with a distinct SSRC for the RTX.

We have https://github.com/pion/webrtc/issues/1675 for that. I don't think the implementation will be hard, it just an API question. It needs to cover FEC and a RTX.

I would love to make this a priority. Just need some feedback on the API. I re-think and come up with a proposal today!

**Comment by jech** [comment]
Ok, but what shall we do for 3.1.0?

1. Disable TWCC by default in 3.1.0 and document that TWCC should not be enabled with simulcast?
2. Add some hackish code to disable TWCC when simulcast is enabled?
3. ???
