### ISSUE TITLE
Efficiency of multithread syncrhonsations

### ISSUE THREAD

**Issue by Vadiml1024** [pion/webrtc#1966]
Looking at rtpsender.go i think that various mutex protected set/get functions will be MUCHmore efficient
using function form sync/atomic than mutexes

**Comment by Sean-Der** [comment]
Hey @Vadiml1024 

That would be great! I am open to accepting any PRs that use atomics and don't complicate the code. It would also be great if we could measure things and prove the changes actually improve performance :)

If you are interested I would love to add you to the Pion organization and you can make branches/PRs in any way that works for you. thanks!

**Comment by Sean-Der** [comment]
I would love to see performance optimizations in the future. AFAIK lock contention isn't an issue at this time.

Some contributors have been focused on this area and nothing has come up yet. We will work on getting some automated tooling, until then nothing actionable on this.
