### ISSUE TITLE
gstreamer-send to gstreamer-recv, VPX preprocessing error: unsupported bitstream

### ISSUE THREAD

**Issue by wattanakorn495** [pion/webrtc#197]
I combined gstreamer-send and gstreamer-recv into pion-pion-video.go
code here: https://github.com/wattanakorn495/pion-pion-video

Connection State of both sender and receiver have changed to Connected 
Track has started, of type 96: VP8 

but receiver did not show received video stream 
and it has this gstreamer debug massage

> creating caps event video/x-vp8, framerate=(fraction)0/1, height=(int)1080, width=(int)5975, profile=(string)2
> 0:00:12.854395448 15639 0x7f7568002cf0 WARN                  vpxdec gstvpxdec.c:582:gst_vpx_dec_open_codec:<vp8dec0> VPX preprocessing error: unsupported bitstream

height and width are random every loop

**Comment by wattanakorn495** [comment]
I changed decodebin to avdec_vp8 then got message "Header size larger than data provided "
and i found  
RTP packet Marshaled = gstreamer buffer(sender) + 23 bytes 
but 
RTP packet UnMarshaled = gstreamer buffer(receiver) + 10 bytes

Does it relate to header size ?

**Comment by Sean-Der** [comment]
Hey @wattanakorn495 sorry this took so long
I forked https://github.com/wattanakorn495/pion-pion-video and it worked perfectly for me! Is there something I should be changing/debugging?

RTP header is 12 bytes, so maybe an off-by-one but `23 -> 10` is almost right :)

```
sean@SeanLaptop:~$ gst-launch-1.0 --version
gst-launch-1.0 version 1.14.4
GStreamer 1.14.4
http://packages.qa.debian.org/gstreamer1.0

sean@SeanLaptop:~$ go version
go version go1.10.4 linux/amd64
```

**Comment by wattanakorn495** [comment]
I changed this line in gstsend/gst.go for displaying sender side 
```
case webrtc.VP8:
		pipelineStr = "videotestsrc ! tee name=t ! queue ! vp8enc ! " + pipelineStr + " t. ! queue ! videoconvert ! autovideosink "
```
so if it work correctly, it should show 2 video windows.

**Comment by wattanakorn495** [comment]
It works, if disabled SRTP encrypt/decrypt

`
//stream.XORKeyStream(packet.Payload, packet.Payload)
`

**Comment by Sean-Der** [comment]
Hey @wattanakorn495 really sorry for the delay :( I got sucked into replacing OpenSSL (but it is finally done!)

This is the same issue as #261 (which should have a PR posted soon) I will update/close the ticket when it lands! Again really sorry for the delay

**Comment by Sean-Der** [comment]
Hey would you mind trying master again? With the merge of #261 this should be fixed!
