### ISSUE TITLE
webrtc/examples/ice-restart and ice-single-port examples are broken

### ISSUE THREAD

**Issue by rainliu** [pion/webrtc#1970]
### Your environment.
  - Version: v3.0.32
  - Browser: Chrome
  - Other Information - SyntaxError: Unexpected token p in JSON at position 4

### What did you do?
cd webrtc/example/ice-restart or ice-single-port
go run ice-restart
click http://localhost:8080 

### What did you expect?
no error

### What happened?
browse says:
 SyntaxError: Unexpected token p in JSON at position 4

**Comment by Sean-Der** [comment]
Hey @rainliu!

I was able to use both examples in FireFox+Chrome. What was the message that the server is returning via websocket (that is failing to parse)

**Comment by rainliu** [comment]
@Sean-Der, thanks for the check.

After reboot my computer, the examples work fine now. Looks like old process occupied http://localhost:8080.

Close the task.
