### ISSUE TITLE
"a=group:BUNDLE video audio" makes Pion sulk.

### ISSUE THREAD

**Issue by steely-glint** [pion/webrtc#2011]
### Your environment.
  - Version: pion/sdp/v3 v3.0.4 and pion/webrtc/v3 v3.1.0-beta.6 (galene)
  - Browser: https://github.com/pipe/whipi
  - Other Information - I get TypeError: offer SDP semantics does not match configuration

### What did you do?
Pointing whipi at a WHIP supporting instance of galene - sending the following SDP
` {type:"offer", sdp:"v=0\r\no=- 4648475892259889561 3 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE video audio\r\na=candidate:2847938860 1 udp 659138 2003:ec:df17:8d00:bcdd:1d88:72db:603e 46264 typ host generation 0\r\na=candidate:443052812 1 udp 659078 192.168.178.97 63698 typ host generation 0\r\na=candidate:4259310722 1 udp 322278 84.140.139.170 63698 typ srflx generation 0 raddr 192.168.178.97 rport 63698\r\na=ice-ufrag:1hhfzwf0ijpzm\r\na=ice-pwd:jm5puo2ab1op3vs59ca53bdk7s\r\na=fingerprint:sha-256 40:42:FB:47:87:52:BF:CB:EC:3A:DF:EB:06:DA:2D:B7:2F:59:42:10:23:7B:9D:4C:C9:58:DD:FF:A2:8F:17:67\r\nm=video 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=setup:passive\r\na=mid:video\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:96 H264/90000\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 goog-remb\r\na=fmtp:96 packetization-mode=1;profile-level-id=42e01f\r\na=ssrc:1505338584 cname:10000000b5810aac\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=setup:passive\r\na=mid:audio\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=ssrc:697641945 cname:10000000b5810aac\r\n"}`

### What did you expect?
SDP would be accepted: 
### What happened?
 fails with
TypeError: offer SDP semantics does not match configuration

### Work around

Replace the audio and video mid: with 1 and 2 e.g.

a=group:BUNDLE 1 2

This works - but I'm not clear that it should be necessary

**Comment by Sean-Der** [comment]
I can confirm this is a problem. The current heuristics check for `audio` and `video`. You could enable Plan-B fallback to get around this today. I am not sure what the right answer going forward is.

```
func TestOfferWithAudioVideoMediaSection(t *testing.T) {
    pc, err := NewPeerConnection(Configuration{SDPSemantics: SDPSemanticsUnifiedPlanWithFallback})
    assert.NoError(t, err)

    msg := "v=0\r\no=- 4648475892259889561 3 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE video audio\r\na=candidate:2847938860 1 udp 659138 2003:ec:df17:8d00:bcdd:1d88:72db:603e 46264 typ host generation 0\r\na=candidate:443052812 1 udp 659078 192.168.178.97 63698
typ host generation 0\r\na=candidate:4259310722 1 udp 322278 84.140.139.170 63698 typ srflx generation 0 raddr 192.168.178.97 rport 63698\r\na=ice-ufrag:1hhfzwf0ijpzm\r\na=ice-pwd:jm5puo2ab1op3vs59ca53bdk7s\r\na=fingerprint:sha-256 40:42:FB:47:87:52:BF:CB:EC:3A:DF:EB:06:DA:2D:B7:2F:59:42:10:23:7B:9D:4C:C9:58:DD:FF:A2:8F:17:67\r\nm=video 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=setup:passive\r\na=mid:video\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:96 H264/90000\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 goog-remb\r\na=fmtp:96 packetization-mode=1;profile-level-id=42e01f\r\na=ssrc:1505338584 cname:10000000b5810aac\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=setup:passive\r\na=mid:audio\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=ssrc:697641945 cname:10000000b5810aac\r\n"
    assert.NoError(t, pc.SetRemoteDescription(SessionDescription{
        Type: SDPTypeOffer,
        SDP:  msg,
    }))

    _, err := pc.CreateAnswer(nil)
    assert.NoError(t, err)
}

```

**Comment by steely-glint** [comment]
It is an easy fix if one controls the Mid names in the SDP offer, or can re-write them.
Perhaps it is enough to expand the error message to include a hint of a fix,
`warning: mid names "audio" and "video" detected, assuming Plan B semantics`
or something similar. Otherwise it isn't obvious what is wrong, even to SDP sages.

**Comment by Sean-Der** [comment]
@steely-glint great! I can improve the error messages that is a zero cost fix :)

I am worried about loosening the audio/video check. It has done us well so far. I will resolve this with a better error message today
