### ISSUE TITLE
Does rtp-to-webrtc support h264

### ISSUE THREAD

**Issue by patrickcorrigan** [pion/webrtc#2021]
I've been using Pion to successfully realtime steam VP8 Video using the example https://github.com/pion/webrtc/tree/master/examples/rtp-to-webrtc

I'd like to try using h264 for the hardware acceleration but the stream starts but them seems to stop after a few seconds

I've been using this ffmpeg command succesfully for capturing the rtp stream for VP8

`# ffmpeg -re  -f  x11grab -draw_mouse 0 -framerate 60 -video_size 640x480 -i :0+642,340 -vcodec libvpx -crf 10 -b:v 3M -cpu-used 8 -deadline 1 -g 10 -error-resilient 1 -auto-alt-ref 1 -an -f rtp rtp://127.0.0.1:5004?pkt_size=1200 &`

and it works well

I've tried a few different command for h264 but none of them last more than a few seconds.

`ffmpeg -re  -f  x11grab -draw_mouse 0 -framerate 60 -video_size 640x480 -i :0+642,340 -c:v libx264 -bsf:v h264_mp4toannexb -b:v 2M -max_delay 0 -bf 0   -an -f rtp rtp://127.0.0.1:5004?pkt_size=1200 &`

Is it a keyframe issue?

**Comment by patrickcorrigan** [comment]
Got it working using `ffmpeg -re -f lavfi -i testsrc=size=640x480:rate=30 -pix_fmt yuv420p -c:v libx264 -bsf:v h264_mp4toannexb -cpu-used 5 -deadline 1 -g 10 -error-resilient 1 -auto-alt-ref 1 -f rtp rtp://127.0.0.1:5004?pkt_size=1200`

Found here https://github.com/pion/webrtc/issues/1652#issuecomment-927018681

**Comment by Sean-Der** [comment]
Hey @patrickcorrigan 

also make sure to do baseline constrained. You can see the appropriate settings in [gstreamer-src](https://github.com/pion/example-webrtc-applications/blob/master/internal/gstreamer-src/gst.go#L58)

It would be great if you could open a PR with the proper H264 settings in the README!
