### ISSUE TITLE
How to get access to RTCP Receiver report generated by remote end?

### ISSUE THREAD

**Issue by sajal** [pion/webrtc#2027]
My context is pion sending video to remote end via WebRTC PeerConnection. The receiving end is Google Chrome.

I can see RTCP Receiver report being sent from browser using wireshark, however I cant get to it using my code for further processing. This is what I tried so far.

```go
type RTCPInterceptor struct {
	*interceptor.NoOp
}

func (i *RTCPInterceptor) BindRTCPReader(reader interceptor.RTCPReader) interceptor.RTCPReader {
	fmt.Println("======reader======", reader) #This line logs
	return interceptor.RTCPReaderFunc(func(in []byte, _ interceptor.Attributes) (int, interceptor.Attributes, error) {
		fmt.Println("=========", in) #This line never logs
		return len(in), nil, nil
	})
}

type MyFactory struct{}

func (mf *MyFactory) NewInterceptor(id string) (interceptor.Interceptor, error) {
	return &RTCPInterceptor{&interceptor.NoOp{}}, nil
}

func main(){
        /* snipped */
	reg := &interceptor.Registry{}
	reg.Add(&MyFactory{})
        api := webrtc.NewAPI(webrtc.WithMediaEngine(mediaEngine), webrtc.WithSettingEngine(*settingEngine), webrtc.WithInterceptorRegistry(reg))
       peer, err = api.NewPeerConnection(config)
       /* snipped */
}

```

Is there a working example that can print RTCP Receiver Report as sent from client to a pion-based sender?

Edit: Is this related to pion/interceptor#20 ?

**Comment by mengelbart** [comment]
It may be related to the issue you linked. Can you try to add a goroutine that reads RTCP from the RTP reader like in this [example](https://github.com/pion/webrtc/blob/master/examples/reflect/main.go#L76)?

**Comment by sajal** [comment]
Thanks. I did not realize that I could read incoming RTCP packets from `RTPSender`, for my application, that's a better place for me to read them than interceptors.

**Comment by Sean-Der** [comment]
Hey @sajal I just added a `rtcp-processing`  example in https://github.com/pion/webrtc/commit/fa72a9529fbc8c9581ca3c0463d6327807e824bf

Would you mind trying it out? Do you think that would have made learning Pion easier? Anything I missed?

**Comment by shandafu** [comment]
> It may be related to the issue you linked. Can you try to add a goroutine that reads RTCP from the RTP reader like in this [example](https://github.com/pion/webrtc/blob/master/examples/reflect/main.go#L76)?
I have the same problem, did you solve it?

**Comment by mengelbart** [comment]
Hi @shandafu did you try calling `ReadRTCP` like the [RTCP processing example](https://github.com/pion/webrtc/tree/master/examples/rtcp-processing) does?
