### ISSUE TITLE
Bandwidth going triple when restarted ice between pion and pion peer

### ISSUE THREAD

**Issue by lamhai1401** [pion/webrtc#2028]
### Your environment.
  - Version: pion webrtc v3.1.9
  - Browser: Chrome newest version
  - Other Information - Bandwithd will going triple (2mb -> 6mb) when restarted ice and decrease to 2mb after few minute (~10mins)

### What did you do?
I'm building a livestreaming project and has a peer between chrome and pion (server).
In my test case, i'm using ChromeA to peer and pushing video data to pionA, after that i forward data from pionA to pionB and pionB forward to ChromeB

### What happened?

In the img below
ChromeA set default video bandwidth 2mb so everything is fine (case1).
To add one more video track (which does not have any data yet), i have to restart ice between pionA and pionB (case2).
suddenly the bandwidth going `triple` in a few minute.
I added a feature `ReceiverEstimatedMaximumBitrate` to limit but its not work.

<img width="745" alt="Screen Shot 2021-11-18 at 16 13 09" src="https://user-images.githubusercontent.com/31619361/142388007-4cf775a1-a637-4bca-a2f4-afd5be1d4797.png">

### What did you expect?
The bandwidth between pion A and pion B should always ~2mb (because the data from Chrome A always around 2mb)

**Comment by Sean-Der** [comment]
Hey @lamhai1401 

I am not sure where the excess traffic is coming from. These would be my guesses

* Media is being double (or triple) sent
* Interceptors are sending excess traffic (Sender Reports, Transport Wide Congestion Control)
* SCTP is sending excess traffic
* DTLS is sending excess traffic

 It would be helpful to debug the following points.

* If you disable forwarding media do you see a large amount of traffic still?
* If you disable interceptors do you see this behavior still?
* Are you able to get a shareable/minimal reproduce?

**Comment by lamhai1401** [comment]
> Hey @lamhai1401
> 
> I am not sure where the excess traffic is coming from. These would be my guesses
> 
> * Media is being double (or triple) sent
> * Interceptors are sending excess traffic (Sender Reports, Transport Wide Congestion Control)
> * SCTP is sending excess traffic
> * DTLS is sending excess traffic
> 
> It would be helpful to debug the following points.
> 
> * If you disable forwarding media do you see a large amount of traffic still?
> * If you disable interceptors do you see this behavior still?
> * Are you able to get a shareable/minimal reproduce?

Thanks for your quick response.
The issue cause by the `interceptors `.
After i comment these lines `ConfigureNack` func and the bandwidth being normal, nomore bug happen.

<img width="811" alt="Screen Shot 2021-11-19 at 14 01 11" src="https://user-images.githubusercontent.com/31619361/142579284-1eebdf70-23f6-440d-a33b-e528bc6273c5.png">

**Comment by Sean-Der** [comment]
That’s great info! Does PionB see a big jump in RTP Sequence Numbers and send NACKs for all them?

We should assume that a gap of N and we should start over. Let me investigate and can have a patch today. Thank you so much for the report

**Comment by lamhai1401** [comment]
> That’s great info! Does PionB see a big jump in RTP Sequence Numbers and send NACKs for all them?
> 
> We should assume that a gap of N and we should start over. Let me investigate and can have a patch today. Thank you so much for the report

i did not check the Sequence Numbers but when i disable forwarding media (stop writing RTP pkg) , the bandwidth being normal.
Bug happen `only` when i try to `writeRTP` package between pionA and pionB and its not happen between pion and chrome after restarted ice.

You guys make a great repo, keep going. I really really like pion so much. Can wait to use the next version.

**Comment by Sean-Der** [comment]
Hey @lamhai1401 

Would you mind trying `v3.1.11` ?

We reduced the NACK buffer size so during interruption you shouldn't see it attempting to re-send so many packets. Thank you @boks1971 for fixing this!

**Comment by lamhai1401** [comment]
Hi! @boks1971 @Sean-Der , i still got this issue with newest version [v3.1.41]
