### ISSUE TITLE
Adding more than one track to peer connection not changing SDP

### ISSUE THREAD

**Issue by C-monC** [pion/webrtc#2038]
### Your environment.
  - Version: github.com/pion/webrtc/v3 v3.1.11

### What did you do?
I add one track to a new peer connection. I receive an incoming SDP. I set this as the remote description and generate an answer.
I add the track before generating the answer so no renegotiating is necessary (i think).
This works as I expect. The answer with one camera with track id 30 and stream id 30:

> {"type":"answer","sdp":"v=0
> o=- 335683819051561308 1638353159 IN IP4 0.0.0.0
> s=-
> t=0 0
> a=fingerprint:sha-256 B0:B0:3F:4F:0B:09:02:37:C7:A1:C3:E8:81:A9:5C:DB:C0:19:7C:A5:F3:3D:C4:CF:75:21:DB:9D:43:BD:DB:A6
> a=group:BUNDLE 0 1 2
> m=audio 9 UDP/TLS/RTP/SAVPF 111 9 0 8
> c=IN IP4 0.0.0.0
> a=setup:active
> a=mid:0
> a=ice-ufrag:sXHkNIFKmfaLayws
> a=ice-pwd:AszrkCamYNfrRBesYhvCdfZZFuXpulLO
> a=rtcp-mux
> a=rtcp-rsize
> a=rtpmap:111 opus/48000/2
> a=fmtp:111 minptime=10;useinbandfec=1
> a=rtcp-fb:111 transport-cc 
> a=rtpmap:9 G722/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=sendonly
> m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 125 127
> c=IN IP4 0.0.0.0
> a=setup:active
> a=mid:1
> a=ice-ufrag:sXHkNIFKmfaLayws
> a=ice-pwd:AszrkCamYNfrRBesYhvCdfZZFuXpulLO
> a=rtcp-mux
> a=rtcp-rsize
> a=rtpmap:96 VP8/90000
> a=rtcp-fb:96 goog-remb 
> a=rtcp-fb:96 transport-cc 
> a=rtcp-fb:96 ccm fir
> a=rtcp-fb:96 nack 
> a=rtcp-fb:96 nack pli
> a=rtpmap:97 rtx/90000
> a=fmtp:97 apt=96
> a=rtpmap:98 VP9/90000
> a=rtcp-fb:98 goog-remb 
> a=rtcp-fb:98 transport-cc 
> a=rtcp-fb:98 ccm fir
> a=rtcp-fb:98 nack 
> a=rtcp-fb:98 nack pli
> a=rtpmap:99 rtx/90000
> a=fmtp:99 apt=98
> a=rtpmap:125 H264/90000
> a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
> a=rtcp-fb:125 goog-remb 
> a=rtcp-fb:125 transport-cc 
> a=rtcp-fb:125 ccm fir
> a=rtcp-fb:125 nack 
> a=rtcp-fb:125 nack pli
> a=rtpmap:127 ulpfec/90000
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=ssrc:3165229882 cname:30
> a=ssrc:3165229882 msid:30 30
> a=ssrc:3165229882 mslabel:30
> a=ssrc:3165229882 label:30
> a=msid:30 30
> a=sendonly
> m=application 9 UDP/DTLS/SCTP webrtc-datachannel
> c=IN IP4 0.0.0.0
> a=setup:active
> a=mid:2
> a=sendrecv
> a=sctp-port:5000
> a=ice-ufrag:sXHkNIFKmfaLayws
> a=ice-pwd:AszrkCamYNfrRBesYhvCdfZZFuXpulLO
> "}

Adding the other stream by itself also works.
Adding multiple tracks like below. Does not work.
```
//track 0
	track := GlobalStreams.RtspStreams[0].Track // stream id 30 track id 30
	_, err := ThisPeer.RTCPeerConnection.AddTrack(track)
//track 1
	track2 := GlobalStreams.RtspStreams[1].Track //stream id 33 track id 33
	_, err2 := ThisPeer.RTCPeerConnection.AddTrack(track2)
```
If I add multiple tracks and then generate the answer only one track is shown.

> {"type":"answer","sdp":"v=0
> o=- 4654924821333478278 1638353514 IN IP4 0.0.0.0
> s=-
> t=0 0
> a=fingerprint:sha-256 F9:AF:C0:20:9C:E1:B7:AE:61:37:10:83:D2:4A:91:02:30:CA:08:66:A3:73:18:0B:9B:18:D6:A5:C1:9D:47:65
> a=group:BUNDLE 0 1 2
> m=audio 9 UDP/TLS/RTP/SAVPF 111 9 0 8
> c=IN IP4 0.0.0.0
> a=setup:active
> a=mid:0
> a=ice-ufrag:QWARwmieXHYbzZYN
> a=ice-pwd:wINeKfxqdQmlPEHiwNDhhRNaGFBVDQZC
> a=rtcp-mux
> a=rtcp-rsize
> a=rtpmap:111 opus/48000/2
> a=fmtp:111 minptime=10;useinbandfec=1
> a=rtcp-fb:111 transport-cc 
> a=rtpmap:9 G722/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=sendonly
> m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 125 127
> c=IN IP4 0.0.0.0
> a=setup:active
> a=mid:1
> a=ice-ufrag:QWARwmieXHYbzZYN
> a=ice-pwd:wINeKfxqdQmlPEHiwNDhhRNaGFBVDQZC
> a=rtcp-mux
> a=rtcp-rsize
> a=rtpmap:96 VP8/90000
> a=rtcp-fb:96 goog-remb 
> a=rtcp-fb:96 transport-cc 
> a=rtcp-fb:96 ccm fir
> a=rtcp-fb:96 nack 
> a=rtcp-fb:96 nack pli
> a=rtpmap:97 rtx/90000
> a=fmtp:97 apt=96
> a=rtpmap:98 VP9/90000
> a=rtcp-fb:98 goog-remb 
> a=rtcp-fb:98 transport-cc 
> a=rtcp-fb:98 ccm fir
> a=rtcp-fb:98 nack 
> a=rtcp-fb:98 nack pli
> a=rtpmap:99 rtx/90000
> a=fmtp:99 apt=98
> a=rtpmap:125 H264/90000
> a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
> a=rtcp-fb:125 goog-remb 
> a=rtcp-fb:125 transport-cc 
> a=rtcp-fb:125 ccm fir
> a=rtcp-fb:125 nack 
> a=rtcp-fb:125 nack pli
> a=rtpmap:127 ulpfec/90000
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=ssrc:2634581783 cname:30
> a=ssrc:2634581783 msid:30 30
> a=ssrc:2634581783 mslabel:30
> a=ssrc:2634581783 label:30
> a=msid:30 30
> a=sendonly
> m=application 9 UDP/DTLS/SCTP webrtc-datachannel
> c=IN IP4 0.0.0.0
> a=setup:active
> a=mid:2
> a=sendrecv
> a=sctp-port:5000
> a=ice-ufrag:QWARwmieXHYbzZYN
> a=ice-pwd:wINeKfxqdQmlPEHiwNDhhRNaGFBVDQZC
> "}

However printing the ID's of the tracks connected to the peer connection indicates that there are two unique tracks:
```
			fmt.Println(RTCPeerConnection.GetSenders()[0].Track().ID()) -> 30
			fmt.Println(RTCPeerConnection.GetSenders()[1].Track().ID()) -> 33
```

### What did you expect?
The client should be able to access two tracks and the sdp should've changed

### What happened?
The client can only access one track which is always the first in the senders list. There is no indication of a second track in the SDP.

**Comment by Sean-Der** [comment]
Hey @C-monC

Can you share the Offer as well? I am not exactly sure what the issue is, but my guess is that the offerer isn't able to accept more.

An answerer can only add as many tracks as the Offerer is willing to receive. You need to add another `sendrecv` or `recvonly` transceiver to the offerer. This is a WebRTC design, so nothing that Pion can do unfortunately. 

We could add debug/verbose logs if that would be helpful!

**Comment by C-monC** [comment]
Hi @Sean-Der, sorry I typed the answer and did not press send.

Adding the tracks into a single stream works. Which is probably related to your 3rd paragraph.
Thanks
