### ISSUE TITLE
Using ice-single-port can not connect successfully and just have request stun packets

### ISSUE THREAD

**Issue by ChenMoGe2** [pion/webrtc#2040]
### Your environment.
  - Version: v3.1.11
  - Browser: Android 10

### What did you do?
 I study example [ice-single-port](https://github.com/pion/webrtc/blob/master/examples/ice-single-port) and use it to make my own program.but it can't trig OnICEConnectionStateChange success.I bind port 50501 and use Wireshark to hook the packets just have request stun like this
![image](https://user-images.githubusercontent.com/32083531/144430662-dc862581-7689-4a38-9635-1abbcd661231.png)

this is the code:
```
package service

import (
	"fmt"
	"github.com/pion/sdp/v3"
	"github.com/pion/webrtc/v3"
	"gittelex.com/telex/telex-webrtc/app/log"
	"go.uber.org/zap"
	"net"
	"time"
)

type GroupCallRoom struct {
	peerConnection	*webrtc.PeerConnection
	udpConn			*net.UDPConn
	api				*webrtc.API
}

func NewGroupCallRoom() (*GroupCallRoom, error) {
	udpConn, err := net.ListenUDP("udp", &net.UDPAddr{
		IP:   net.IP{0, 0, 0, 0},
		Port: 50501,
	})
	if err != nil {
		return nil, err
	}

	settingEngine := webrtc.SettingEngine{}
	settingEngine.SetICEUDPMux(webrtc.NewICEUDPMux(nil, udpConn))

	api := webrtc.NewAPI(webrtc.WithSettingEngine(settingEngine))
	return &GroupCallRoom{udpConn: udpConn, api: api}, nil
}

func (g *GroupCallRoom) Join(offer webrtc.SessionDescription) (*sdp.SessionDescription, error) {
	peerConnection, err := g.api.NewPeerConnection(webrtc.Configuration{})
	if err != nil {
		log.Log().Error("NewPeerConnection failed", zap.Error(err))
		return nil, err
	}

	peerConnection.OnICEConnectionStateChange(func(connectionState webrtc.ICEConnectionState) {
		fmt.Println("ICE Connection State has changed:", connectionState.String())
	})

	peerConnection.OnDataChannel(func(d *webrtc.DataChannel) {
		d.OnOpen(func() {
			for range time.Tick(time.Second * 3) {
				if err = d.SendText(time.Now().String()); err != nil {
					panic(err)
				}
			}
		})
	})

	err = peerConnection.SetRemoteDescription(offer)
	if err != nil {
		log.Log().Error("SetRemoteDescription failed", zap.Error(err))
		return nil, err
	}

	gatherComplete := webrtc.GatheringCompletePromise(peerConnection)

	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		log.Log().Error("CreateAnswer failed", zap.Error(err))
		return nil, err
	}

	err = peerConnection.SetLocalDescription(answer)
	if err != nil {
		log.Log().Error("SetLocalDescription failed", zap.Error(err))
		return nil, err
	}

	<-gatherComplete

	g.peerConnection = peerConnection

	answerDescription, err := peerConnection.LocalDescription().Unmarshal()
	if err != nil {
		log.Log().Error("Unmarshal failed", zap.Error(err))
		return nil, err
	}

	return answerDescription, nil
}
```

### What did you expect?
I expect the code can execute the function OnICEConnectionStateChange and the state is success.And the packets in the Wireshark have both request stun and response stun like this.
![image](https://user-images.githubusercontent.com/32083531/144431511-626b73d1-87e5-4c65-81d2-883288afe342.png)

Thank you

**Comment by ChenMoGe2** [comment]
Addition:The server have public IP.

**Comment by Sean-Der** [comment]
Hi @ChenMoGe2

Is the server behind a NAT? Does the generated answer contain the public IP address? You also need to use [SetNAT1To1IPs](https://pkg.go.dev/github.com/pion/webrtc/v3#SettingEngine.SetNAT1To1IPs) if behind a NAT.

If you run [ice-single-port](https://github.com/pion/webrtc/blob/master/examples/ice-single-port/main.go) on your server with the Public IP does it work?

Does your example application work in Chrome? Are you only having issues with Android?

**Comment by ChenMoGe2** [comment]
@Sean-Der Hello,Thank you for your reply
The server is not behind any NAT and it has its own public IP address,so I don't use SetNAT1To1IPs
I can run https://github.com/pion/webrtc/tree/master/examples/ice-single-port successfully using chrome and server program on the server

But I embed the code into my own signal server and the webrtc in android application using the signal can not connect into the server,which the stun packet on wireshark just have request

**Comment by ChenMoGe2** [comment]
@Sean-Der this is my Android code fatal,thank you very much
