### ISSUE TITLE
webrtc dynamic fps

### ISSUE THREAD

**Issue by xiaoshengduan** [pion/webrtc#2041]
When the encoding server uses a dynamic frame rate, such as 3fps for a while and 30fps for a while, there will be a significant delay in the image displayed by the browser, which causes me to switch to a fixed frame rate. Is the buffer too large? Caused? What should I do in this situation?

**Comment by ashellunts** [comment]
Hi @xiaoshengduan , when you use WriteSample, do you adjust Duration depending on your frame rate?

**Comment by xiaoshengduan** [comment]
I don't know the current frame rate, because it changes every moment. How do I calculate it? Is it the interval between the previous frames? If Duration or V2's Samples is set, how can it be set without delay?

**Comment by xiaoshengduan** [comment]
if strings.ToLower(protobufObj.Frame.Type.String()) == "kh264"{
				if s.track != nil{
					s.track.WriteSample(media.Sample{
						Data:    protobufObj.Frame.Data,
						Samples: 1,
					})
				}
			}
			if strings.ToLower(protobufObj.Frame.Type.String()) == "kopus"{
				if s.atrack != nil{
					sampleDurationSeconds := float64(20)/1000  //20ms
					clockRate  := float64(48000)             
					Samples := sampleDurationSeconds * clockRate  
					s.atrack.WriteSample(media.Sample{
						Data:    protobufObj.Frame.Data,
						Samples: uint32(Samples),
					})
				}
			}

**Comment by xiaoshengduan** [comment]
The above is my code, how do I set the Video Samples parameter

**Comment by xiaoshengduan** [comment]
@ashellunts

**Comment by jsmouret** [comment]
You can do something like:

```go
last := time.Now()

// ...
now := time.Now()
duration := now.Sub(last)
last = now

s.track.WriteSample(media.Sample{
	Data:    protobufObj.Frame.Data,
	Duration: duration,
})
```

**Comment by Sean-Der** [comment]
Hey @xiaoshengduan 

If you still have questions please re-open! Thanks for using Pion :)

Thank you so much @jsmouret and @ashellunts for answering :fire:
