### ISSUE TITLE
track.Read([]byte) result not equals with wireshark

### ISSUE THREAD

**Issue by ChenMoGe2** [pion/webrtc#2042]
### Your environment.
  - Version: v3.1.11
  - Browser: Android 9

### What did you do?
I read from track using track.Read([]byte) and the result of []byte not equals with wireshark
buffer:b06f1d44b51de5a24f0221bebede000231000122cc7efa000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000032

wireshark:b06f1d44b51de5a24f0221bebede000231000122cc7efa003e0f8dbe4d0de86cbf3615d6c4373da0977063890630deee8f37bcd1f885cb560e3e6e679134f03d8b7c736e49c995b291ec6259125d20652c4ade61dee294354a23

### What did you expect?
I expect the results are same

**Comment by ChenMoGe2** [comment]
@Sean-Der Thank you very much.I have no problem of this issue

**Comment by yujian-syj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
