### ISSUE TITLE
pion webrtc server ice use ice-lite mode，webrtc client exits abnormally, the webrtc server not detected by the client disconnected

### ISSUE THREAD

**Issue by xianchuhan** [pion/webrtc#2045]
My environment.
  - Version: github.com/pion/webrtc/v2
  - client and server: pion/webrtc/v2 
  - Other Information : webrtc the server will not function with ice-lite mode, the client disconnected exception, the server can be detected to end disconnected
  
webrtc client log:
![image](https://user-images.githubusercontent.com/82028984/145396821-43042261-2700-4dff-8a03-2ee64dbb2f29.png)
webrt server log:
![image](https://user-images.githubusercontent.com/82028984/145397211-001f808e-88c5-4b4d-8a68-f16457e6bea6.png)

Otherwise, I want to know if the V3 version has to solve the problem.

**Comment by Sean-Der** [comment]
Hey @xianchuhan 

I believe this is fixed in `v3`. Here is a test that connects an ICE-Lite and Full ICE PeerConnection. The test ends when ICE-Lite detects disconnected.

```
package webrtc

import (
    "context"
    "testing"

    "github.com/stretchr/testify/require"
)

func TestICELiteDisconnect(t *testing.T) {
    fullICEPeerConnection, err := NewAPI().NewPeerConnection(Configuration{})
    require.NoError(t, err)

    s := SettingEngine{}
    s.SetLite(true)
    iceLitePC, err := NewAPI(WithSettingEngine(s)).NewPeerConnection(Configuration{})
    require.NoError(t, err)

    require.NoError(t, signalPair(fullICEPeerConnection, iceLitePC))

    iceConnectedCtx, iceConnectedCtxCancel := context.WithCancel(context.TODO())
    iceDisconnectedCtx, iceDisconnectedCtxCancel := context.WithCancel(context.TODO())

    iceLitePC.OnICEConnectionStateChange(func(iceState ICEConnectionState) {
        if iceState == ICEConnectionStateConnected {
            iceConnectedCtxCancel()
        } else if iceState == ICEConnectionStateDisconnected {
            iceDisconnectedCtxCancel()
        }
    })

    <-iceConnectedCtx.Done()
    require.NoError(t, fullICEPeerConnection.Close())

    <-iceDisconnectedCtx.Done()
    require.NoError(t, iceLitePC.Close())
}
```

**Comment by xianchuhan** [comment]
Hey@Sean-Der 
Thanks a million. When I go to work tomorrow under the test as you see. In addition, I want to periodically check whether the peer sends RTCP packets to determine whether the peer is disconnected or abnormal. In most cases, the peer sends RTCP packets periodically.

**Comment by Sean-Der** [comment]
@xianchuhan You can use `Read` and `ReadRTCP` on `RTPSender` and `RTPReceiver` to get access to any incoming RTCP packets.

If you need access to all RTCP packages you could write an interceptor that gets access to each stream (and a callback is fired each time a packet is ready)

**Comment by xianchuhan** [comment]
@Sean-Der Thank you very much for your advice. I'll take it into practice.
