### ISSUE TITLE
pion's answer direction sets recvonly when got offer message with a=inactive

### ISSUE THREAD

**Issue by lenaky** [pion/webrtc#2050]
### Your environment.
  - Version: latest
  - Browser: firefox 95.0
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

in some cases, firefox's createOffer() returns sdp with `a=invalid`.

ie)
```javascript
const pc = new RTCPeerConnection();
const sender = pc.addTrack(track);
....
pc.createOffer();
pc.removeTrack(sender);
```
When pion gets offerSDP, local direction sets RecvOnly as default.
https://github.com/pion/webrtc/blob/8a10f67d5a36905d08875d2c9eeec97a455c8cdf/peerconnection.go#L1058-L1060

### What did you expect?

media direction on answer SDP is marked `invalid` and peerConnection is established.

### What happened?

media direction on Answer SDP is marked `recvonly` and peerConnection is not established.
firefox sent `invalid` media but answer peer tells `ready to recvonly`. I think this makes firefox is broken.

So I fixed simply, 
```go
localDirection := RTPTransceiverDirectionRecvonly 
if direction == RTPTransceiverDirectionRecvonly { 
    localDirection = RTPTransceiverDirectionSendonly 
} else if direction == RTPTransceiverDirectionInactive {
    localDirection = RTPTransceiverDirectionInactive
}
```
then peerConnection is established.

**Comment by Sean-Der** [comment]
Thanks for finding/reporting this @lenaky 

Would you be interested in making a PR? Always looking for more people to get involved :) if not I can do it myself also.

thanks!

**Comment by lenaky** [comment]
Thanks, I will try :) @Sean-Der

**Comment by Sean-Der** [comment]
Hey @lenaky!

No rush, but are you interested in opening a PR? If not I can do it :)

I am just excited to get people involved in Open Source (if they are interested)

**Comment by lenaky** [comment]
sorry for delay.
I'll open PR in a couple of days.  @Sean-Der
