### ISSUE TITLE
How to deal remote ssrc-group SIM with FID

### ISSUE THREAD

**Issue by ChenMoGe2** [pion/webrtc#2053]
### Your environment.
  - Version: v3.1.11
  - Browser: Android 9

### What did you do?
I want implement a sfu-server with Pion.Pion is offer and remote android is answer.Using once signal request.The android peer using simulcast with 3 ssrc(and there is no rid in any track).And each simulcast ssrc has two FID ssrcs.And the android SDP is about below format
```
...
a=rid:1748680504 send
a=rid:1748680506 send
a=rid:1748680508 send
a=simulcast:send 1748680504;1748680506;1748680508
...
a=ssrc-group FID 1748680504 1748680505 
a=ssrc:1748680504 cname:pion_1_0
a=ssrc:1748680504 msid:pion_1_0 sim_1_0
a=ssrc:1748680504 mslabel:pion_1_0
a=ssrc:1748680504 label:sim_1_0
a=ssrc:1748680505 cname:pion_1_1
a=ssrc:1748680505 msid:pion_1_1 sim_1_1
a=ssrc:1748680505 mslabel:pion_1_1
a=ssrc:1748680505 label:sim_1_1
...
a=ssrc-group FID 1748680506 1748680507 
a=ssrc:1748680506 cname:pion_2_0
a=ssrc:1748680506 msid:pion_2_0 sim_2_0
a=ssrc:1748680506 mslabel:pion_2_0
a=ssrc:1748680506 label:sim_2_0
a=ssrc:1748680507 cname:pion_2_1
a=ssrc:1748680507 msid:pion_2_1 sim_2_1
a=ssrc:1748680507 mslabel:pion_2_1
a=ssrc:1748680507 label:sim_2_1
...
a=ssrc-group FID 1748680508 1748680509 
a=ssrc:1748680508 cname:pion_3_0
a=ssrc:1748680508 msid:pion_3_0 sim_3_0
a=ssrc:1748680508 mslabel:pion_3_0
a=ssrc:1748680508 label:sim_3_0
a=ssrc:1748680509 cname:pion_3_1
a=ssrc:1748680509 msid:pion_3_1 sim_3_1
a=ssrc:1748680509 mslabel:pion_3_1
a=ssrc:1748680509 label:sim_3_1
...
```

### What did you expect?
I hope the ssrc in FID can be handled(1748680505 1748680507 1748680509).Now it just deal ssrc in SIM.

### What happened?
Incoming unhandled RTP ssrc(1748680505)
Incoming unhandled RTP ssrc(1748680507)
Incoming unhandled RTP ssrc(1748680509)

**Comment by Sean-Der** [comment]
Hi @ChenMoGe2 

What version of WebRTC are you using with Android?

Can you try with commit 0180ee38051dec890fdfa6220a532984d685555f ? This may have regressed with ef285fbe0917d83e69898fae4bcc68eab221eba4

**Comment by ChenMoGe2** [comment]
@Sean-Der 
Thank you,I will try it

**Comment by Sean-Der** [comment]
Hi @ChenMoGe2 

I believe this has been resolved. If you are still having issues reach out and would love to help :)
