### ISSUE TITLE
'http: panic' when using SetNAT1To1IPs

### ISSUE THREAD

**Issue by Lanceback** [pion/webrtc#2060]
### Your environment.
  - Version: Go 1.17.3 linux/amd64, Pion WebRTC V3
  - Browser: Chrome - Version 96.0.4664.110 (Official Build) snap (64-bit)

### What did you do?
To replicate this error, use [rtsp-bench](https://github.com/pion/rtsp-bench)  server as a template, and enable the Setting Engine SetNAT1ToIPs with a public IP and candidate type svflx.

Something like this:

```
func doSignaling(w http.ResponseWriter, r *http.Request) {
	// Initialize settings engine
	var settings = webrtc.SettingEngine{}
	// Enable 'hardcoded' public IP address as a srflx candidate
	settings.SetNAT1To1IPs([]string{"PUBLIC IP HERE"}, webrtc.ICECandidateTypeSrflx)
	var api = webrtc.NewAPI(webrtc.WithSettingEngine(settings))
	// Change 'webrtc' to 'api'
	peerConnection, err := api.NewPeerConnection(webrtc.Configuration{})
	if err != nil {
		panic(err)
	}
```

### What did you expect?
Expected to be able to get video stream through the public IP address that is passed to the Pion SetNAT1To1IPs call.

### What happened?
With the Pion Setting Engine we get the below error from the main.go script. 
Without the Pion Setting Engine, it works fine (on the internal network).
At the very least, this is probably not the correct error message for the event triggering it.

On the server side--
```
http: panic serving 192.168.16.5:59730: unable to start track, codec is not supported by remote
```

The error appears to originate from line 94:

```
answer, err := peerConnection.CreateAnswer(nil)
if err != nil {
	panic(err)
} else if err = peerConnection.SetLocalDescription(answer); err != nil {
	panic(err)    <--- Here
}
```

**Comment by Sean-Der** [comment]
Hi @Lanceback 

The `API` object by default comes with an empty MediaEngine. When you call `SetLocalDescription` you have zero available and hit the error case.

Try following [this]( https://github.com/pion/webrtc/blob/080d7b8427bc0123e002a314a7461eb8ac40bdd8/examples/simulcast/main.go#L31-L34) and create a MediaEngine and RegisterDefaultCodecs against it. Then use that with your API like [this](https://github.com/pion/webrtc/blob/080d7b8427bc0123e002a314a7461eb8ac40bdd8/examples/simulcast/main.go#L57 )

Thanks for using Pion!

**Comment by Lanceback** [comment]
That makes sense. I'll try it out.

**Comment by Sean-Der** [comment]
Great @Lanceback :)

If you are still having issues please re-open! I am also available on [Slack](https://pion.ly/slack) if you need help.

**Comment by 3mmanu3lmois3s** [comment]
Thank you @Sean-Der PION , for your GREAT work.
