### ISSUE TITLE
Save audio to .wav file

### ISSUE THREAD

**Issue by edwardsPaul421** [pion/webrtc#2073]
## Summary
I researched and noticed the example of the oggwriter.
I would like to do the same thing, but to write the RTP packets (gotten in OPUS format), to a wav file. 
It might include a decode from OPUS to PCM in order to write raw bytes to wav file. 
## Motivation
Trying to save audio to a wav file

**Comment by kevmo314** [comment]
Given that this requires transcoding, it would probably be easiest to use something like [gstreamer-receive](https://github.com/pion/example-webrtc-applications/tree/master/gstreamer-receive) to save the file. Even with the depayloader and payloader, the transcoding layer is missing so it would be a lot of work for a pure golang solution.

A sample pipeline might be:

```
appsrc ... ! rtpopusdepay ! decodebin ! audioresample ! audioconvert ! wavenc ! filesink location=out.wav
```
