### ISSUE TITLE
Interceptor Memory Leak

### ISSUE THREAD

**Issue by lamhai1401** [pion/webrtc#2097]
### Your environment.
  - Version: pionWebrtc v3.1.17, interceptor v0.1.5 and above 
  - Browser: *Chrome newest version*
  - Other Information - Using simulcast feature with 16 video/audio tracks source
 
### What did you do?

I'm building a livestreaming project and has a peer between chrome and pion (server), it was running by pm2.
In my test case, i'm using ChromeA to peer and pushing video data to pionA, after that i forward data from pionA to pionB and pionB forward to ChromeB

<img width="441" alt="Screen Shot 2022-01-24 at 18 14 20" src="https://user-images.githubusercontent.com/31619361/150772913-7bbf3216-7660-4ffd-8230-fdebd9a0f757.png">

PionA & PionB has only 1 `simulcast peer`, PionA is forwarding 16 video/audio data to PionB
PionB is forwarding that data to ~100 ChromeB Clients.

In the img below, I checked my instance Mem between 2 version of pion interceptor, process running about 2mins ago.
The Mem in v0.1.4 is stable and increase very low.
But in v0.1.5 and above,  it keep increasing too much and seem like never stop.
It will get over ~30GB after 10mins

 interceptor v0.1.4
<img width="452" alt="Screen Shot 2022-01-24 at 16 00 46" src="https://user-images.githubusercontent.com/31619361/150771344-cbf18c83-f6f2-4741-9897-36d6c1036916.png">

 interceptor v0.1.5 and above 
<img width="460" alt="Screen Shot 2022-01-24 at 16 08 54" src="https://user-images.githubusercontent.com/31619361/150771360-0669b9b4-9eab-46d1-a797-d87b06923aca.png">

### What did you expect?
The Mem  should like interceptor v0.1.4

### What happened?
Memory keep increasing in simulcast.

**Comment by at-wat** [comment]
Could you take a memory profile by pprof?

I also have memory usage problem on interceptor v0.1.5 (without simulcast) which is due to https://github.com/pion/interceptor/pull/92.
NACK generator interceptor now deep copies RTP packets for each local track, so if you create local track for each client (for 100 clients), memory usage will be x100.

Memory profile in my case:
interceptor v0.1.5 | beforehand
--- | ---
![image](https://user-images.githubusercontent.com/8390204/150776564-eaaec51c-c47e-492e-bfe4-b4be02f83b06.png) | ![image](https://user-images.githubusercontent.com/8390204/150776920-f3abc04c-7bc3-4604-b57c-f87db7fa7c5f.png)

**Comment by Sean-Der** [comment]
If the memory usage is causing upgrade issues would be good to disable for now. Don’t want people sticking in old version

**Comment by at-wat** [comment]
@Sean-Der I was going to copy the old implementation to my source tree for now.
In my use case, RTP packet source never reuse memory (due to a backend library), so storing pointers are the best solution.
If pion/interceptor will have option not to copy packets, it would be better for me.

**Comment by davidzhao** [comment]
@at-wat it makes sense to have it be an option for use case like yours. I'll take a look.

@lamhai1401 I'd be interested in seeing a profile as well for the leak scenario you are seeing. It's likely related to the same change.

**Comment by Sean-Der** [comment]
@at-wat Would it work for you if we add a option to `DisableCopy`? I would love to have you on the latest version.

Copying by default is the safest thing we can do I think. Then if users know what they are doing/want to opt out. Some open points of discussion for me.

* Should we disable NACK by default? Users should opt-in, is the memory usage too excessive by default?
* Should we add a Option struct (or vaarg) to `RegisterDefaultInterceptors` so that users can set these options easier? vaarg is a little harder to do in this case since we aren't modifying something ?

@lamhai1401 Unfortunately the old behavior meant that NACKs probably weren't working. Since we didn't copy when we get a NACK we sent the latest RTP Packet (instead of the actual one requested)

**Comment by at-wat** [comment]
@Sean-Der @davidzhao something like `DisableCopy` option should work for me.

Additional point of discussion:
- Is the current default buffer size of the packets reasonable?

The default seems be 8192 and in the worst case, memory usage will be 1.5kb (MTU) * 8129 = 12MB for each NACK responder interceptor.
8192 packets are around 2.5 min in my case, but actually required buffer would be a few to 10 seconds I guess. (But the packet count depends the video bitrate)


> Should we add a Option struct (or vaarg) to `RegisterDefaultInterceptors` so that users can set these options easier? vaarg is a little harder to do in this case since we aren't modifying something ?

I think `RegisterDefaultInterceptors` is better to be static and 
https://github.com/pion/webrtc/blob/08ab8d27002021d67ee0d0ef8bab68f0aca5af29/interceptor.go#L18-L19
It would be better to mention that `RegisterDefaultInterceptors` is mainly for examples and recommended to configure them by yourself especially in product applications.


> Should we disable NACK by default? Users should opt-in, is the memory usage too excessive by default?

In my feeling, NACK is almost essential as there are always some packet losses on real networks.
(Before pion/interceptor, I had another NACK implementation in my product code.)
So, the options would be

- Minimize buffer size and keep it default
- Remove from default

**Comment by lamhai1401** [comment]
This is my report when i have done a test today, process running in 7mins with ~100 clients.
 interceptor v0.1.5

<img width="463" alt="Screen Shot 2022-01-25 at 14 33 09" src="https://user-images.githubusercontent.com/31619361/150939951-02afc7c8-56bd-4de1-bece-736ffd624727.png">

<img width="832" alt="Screen Shot 2022-01-25 at 14 33 17" src="https://user-images.githubusercontent.com/31619361/150939839-66afc5ba-1605-475b-94a8-3f1ed970bd56.png">


@davidzhao Here is my Mem profile
<img width="825" alt="Screen Shot 2022-01-25 at 15 19 42" src="https://user-images.githubusercontent.com/31619361/150938563-c0305531-0f55-489c-a133-c79bac3f82e2.png">

You guys can see full here.
[cgraph.pdf](https://github.com/pion/webrtc/files/7931779/cgraph.pdf)

@at-wat  Sorry to bother you but i saw the `MTU` var in your formula [` 1.5kb (MTU) * 8129 = 12MB `].
I also got this issue:
`mux: ending readLoop dispatch error packetio.Buffer is full, discarding write`

<img width="576" alt="Screen Shot 2022-01-25 at 15 40 33" src="https://user-images.githubusercontent.com/31619361/150941837-9cc516cf-f43b-4d4e-bd81-15f95dac9de5.png">

The buffersize depend on `MTU` and can set in `mediaengine`, i found the default `MTU = 1460` so try to x2 default and set it in `SetReceiveMTU` func, but still got that error.

Could you tell me What's happen when i continuing got this error for long run process

@Sean-Der I still got this error but i think you guys fixed it in previous version.
` Incoming unhandled RTP ssrc(1353327085), OnTrack will not be fired. mid RTP Extensions required for Simulcast`

**Comment by at-wat** [comment]
@lamhai1401 

> - Is the current default buffer size of the packets reasonable?

meant to change default value at https://github.com/pion/interceptor/blob/075cb2c32613c9328c52870e3695672027cbc50c/pkg/nack/responder_interceptor.go#L20.
Maximum MTU is limited by Ethernet frame size, so usually you can't increase MTU.

**Comment by lamhai1401** [comment]
> @lamhai1401
> 
> > * Is the current default buffer size of the packets reasonable?
> 
> meant to change default value at https://github.com/pion/interceptor/blob/075cb2c32613c9328c52870e3695672027cbc50c/pkg/nack/responder_interceptor.go#L20. Maximum MTU is limited by Ethernet frame size, so usually you can't increase MTU.

Thanks you for your quick response. So `discarding write` what does it mean, in this case the buffer will be freed or not

This is my stdout when i running process with v0.1.4 interceptor, the mem keep increasing very low but still get over the limit for long running process (~1h30mins so far)

<img width="464" alt="Screen Shot 2022-01-25 at 17 44 25" src="https://user-images.githubusercontent.com/31619361/150962350-b161b3de-abc4-4207-99fe-cbc633339847.png">


<img width="850" alt="Screen Shot 2022-01-25 at 17 38 29" src="https://user-images.githubusercontent.com/31619361/150961402-c746977a-fd04-4281-b14d-cb0dd2ef33ac.png">

**Comment by at-wat** [comment]
@lamhai1401 what Go version and OS do you use?
Go between 1.12 and 1.15 on Linux don't return GC-ed memory to OS unless system runs out of memory and need to set `GODEBUG=madvdontneed=1` environment variable.

**Comment by lamhai1401** [comment]
> @lamhai1401 what Go version and OS do you use?
> Go between 1.12 and 1.15 on Linux don't return GC-ed memory to OS unless system runs out of memory and need to set `GODEBUG=madvdontneed=1` environment variable.

Sorry my fault!
I'm using go 1.17 & Ubuntu 20.04.3 LTS (Focal Fossa) and i did not set any env about GC.

**Comment by at-wat** [comment]
@lamhai1401 I think there are some independent problems mixed.

`mux: ending readLoop dispatch error packetio.Buffer is full, discarding write`
This error is from:
https://github.com/pion/webrtc/blob/22bd93fd7be1a2ff8937b4c045a3b9b449e63485/internal/mux/mux.go#L122
https://github.com/pion/transport/blob/094566eaf23dbd80059743aaf375ee3908254939/packetio/buffer.go#L99
It basically means, there were too many incoming packets from remote peer and couldn't process fast enough.
The buffer is referenced as `webrtc.PeerConnection` -> `webrtc.ICETransport` -> `mux.Mux` -> `packetio.Buffer`, so it is designed to be freed by GC after PeerConnection is closed and unreferenced.
It seems independent of the interceptor memory usage problem.

`Incoming unhandled RTP ssrc(1353327085), OnTrack will not be fired. mid RTP Extensions required for Simulcast`
Seems also not a part of the interceptor memory usage problem as well.

I think it would be nice to open separate issues or discussions for them.

**Comment by lamhai1401** [comment]
@at-wat  I saw this comment `the packet size is limited to 65536 bytes` so `discarding write` mean drop all data at that time and i have to resend it ?
Because i use `DC` (datachannel) for `simulcast peer` handshaking (send/receive SDP, candidate). Randomly the msg disappear.
SDP with 50 video/audio profile about ~72kb so i have to split and send it one by one.
Here is the issue of this, i would reopen it
https://github.com/pion/webrtc/issues/2072
Buffer being hang and cannot release.

**Comment by at-wat** [comment]
@lamhai1401 
> I saw this comment the packet size is limited to 65536 bytes so discarding write mean drop all data at that time and i have to resend it ?

The packet size can't be larger than the Ethernet frame size (1500 bytes on the Internet or 9000 bytes jumbo frame on local), so you'll never reach 65536 bytes packet size limit.

**Comment by at-wat** [comment]
@Sean-Der @davidzhao I switched to use old NackInterceptor in my product for now. I'll switch back to the latest once it supports no-copy mode.

**Comment by lamhai1401** [comment]
> @lamhai1401
> 
> > I saw this comment the packet size is limited to 65536 bytes so discarding write mean drop all data at that time and i have to resend it ?
> 
> The packet size can't be larger than the Ethernet frame size (1500 bytes on the Internet or 9000 bytes jumbo frame on local), so you'll never reach 65536 bytes packet size limit.

Which interceptor version you mean `old NackInterceptor`, may i have that, i'm using it in my product too.

**Comment by at-wat** [comment]
NackInterceptor on https://github.com/pion/interceptor/tree/36d6df80197310a2da2fc8dc626ae43998da1535 this commit (one before https://github.com/pion/interceptor/tree/ec82d5387a9c4adb724f06440ae5bb2a6589fabe)

**Comment by davidzhao** [comment]
I'll take a look at this PR this week. apologies for the delays here.

**Comment by lamhai1401** [comment]
@at-wat  sorry to bother you, but could you tell me did you have memory usage after apply commit above

**Comment by gabridego** [comment]
@Sean-Der @at-wat @davidzhao
I am sorry to reopen this issue. I am running the last version of Pion (webrtc v3.1.47 and interceptor v0.1.12) and experiencing very similar memory issues in nack NewInterceptor.

![pprof](https://user-images.githubusercontent.com/41424282/196874062-a79c4b3c-0326-42c9-87bc-1c17d3fa3e0f.png)

I see https://github.com/pion/interceptor/pull/102 introduced a DisableCopy option that would fit my use case, but it is not clear to me how to enable it when importing the full Pion webrtc package. How could I do it?
Thank you in advance!

**Comment by ogsts** [comment]
Hi
I am using application with Pion for video streaming to browser. 
Application uses:
* github.com/pion/webrtc/v3 v3.1.50
* github.com/pion/interceptor v0.1.11
and after several hours of streaming with multiple streams per connection
application RSS grows to > 2 Gb. Profiler shows:

![image](https://user-images.githubusercontent.com/5054117/208965266-97402087-60f8-4549-9ec9-75d2b44b8402.png)

Any advice on how to resolve this memory growth ?

**Comment by ogsts** [comment]
ok, checked that need to use
`responder, err := nack.NewResponderInterceptor(nack.DisableCopy())`
to get rid of memory growth
