### ISSUE TITLE
Support password authentication for TURN servers in JS

### ISSUE THREAD

**Issue by bigfarts** [pion/webrtc#2140]
## Summary

Support password authentication for TURN servers in JS

## Motivation

Currently there's no way to use TURN servers in JS, as they require a credential, but pion/webrtc doesn't ever pass the password credential to JS.

## Describe alternatives you've considered

No alternative available.

**Comment by Sean-Der** [comment]
Hi @bigfarts 

Thanks for reporting this. I just pushed `v3.1.30` that fixes this.

**Comment by bigfarts** [comment]
Thanks!
