### ISSUE TITLE
Video bugy using UDPMux

### ISSUE THREAD

**Issue by EmrysMyrddin** [pion/webrtc#2158]
### Your environment.
  - Version: 3.1.24 + PR #1812 merge
  - Browser: Firefox 99.0b3

### What did you do?
We have a working server allowing to forward a incoming video track to multiple outgoing video tracks.
It works well, but for firewall workarounds, we would like to have a unique udp port opened.
So we used code from `ice-single-port` to add an UDPMux to our config. 

### What did you expect?

I didn't except any difference in behaviour between default ephemeral udp listener and custom UDPMux

### What happened?

The connection establishes as expected but the video is totally broken. It seems we are receiving data (key frames + few following frames are displayed correctly) but something disturb the video feed and sends wrong data the codec can't decode.

### What else ?

I don't really which information you need to further investigate this issue, please ask me for any details.

**Comment by davidzhao** [comment]
Are you handling NACKs?

Can you reproduce this issue without using UDPMux? (i.e. using a fixed UDP port range)

**Comment by EmrysMyrddin** [comment]
No, I'm not handling it, we only handle PLI.

The problem is not reproduced with ephemeral udp, but I can't really test with a single port. Ephemeral udp opens a new port for each connections, meaning it can't allocate the same port for tow connections.

I have tried the other way around : allocating a new port for each connections with an UDPMux. I have exactly the same problem. So the problem really appear when using UDPMux instead of the default EphemeralUdp

**Comment by davidzhao** [comment]
How much data are you sending through when this happened? You might need to increase the kernel buffer sizes as all of the incoming/outgoing data is going into a single kernel buffer. See [this section](https://docs.livekit.io/deploy/test-monitor#kernel-parameters) on tuning kernel params.

**Comment by EmrysMyrddin** [comment]
I found the problem: it was a bug in the code forwarding the packet from one track to another. The sequence number was incremented for each incoming packet, without taking care of the packet order.

I still doesn't understand why it was working with Ephemeral UDP but not with UDPMux.
