### ISSUE TITLE
The best way to extract rtpmap from a SessionDescription

### ISSUE THREAD

**Issue by asticode** [pion/webrtc#2171]
Hey guys,

I'm trying to extract the `rtpmap` from a `SessionDescription` so that I know which payload types have been chosen in the answer and the only way I see is looping through `MediaDescriptions` then `Attributes`, looking for key `rtpmap` and parse its value.

Is there a better way to do this?

Cheers
Quentin

**Comment by Sean-Der** [comment]
Hey @asticode!

Great to see you here, huge fan of your work :)

You can get the negotiated codecs (and the PayloadTypes they are using) by calling [RTPSender.GetParameters](https://pkg.go.dev/github.com/pion/webrtc/v3#RTPSender.GetParameters) and [RTPReceiver.GetParamaters](https://pkg.go.dev/github.com/pion/webrtc/v3#RTPReceiver.GetParameters). 

This gives you access to [RTPParameters](https://pkg.go.dev/github.com/pion/webrtc/v3#RTPCodecParameters) and you can scan through for the `Codec.MimeType` and when you find it you can get they value from the `PayloadType` member.

You can get the RTPSenders and RTPReceivers by calling `GetSenders` and `GetReceivers` on the `PeerConnection`.

**Comment by asticode** [comment]
Hey @Sean-Der,

Thanks, I'm also really impressed by the amazing work you've been able to pull off with the Pion ecosystem ❤️ I'm hoping to switch all our webrtc use cases to Pion in the near future!

Thanks a bunch for the elegant solution, that's way better than what I had in mind 👍 

Cheers
