### ISSUE TITLE
oggreader errors don't indicate to users that only Opus is supported

### ISSUE THREAD

**Issue by OptimisticLock** [pion/webrtc#2181]
### Your environment.

Intel MacOS Monterey
github.com/pion/webrtc/v3 v3.1.28

### What did you do?

I haven't been able to read any ogg file.

Example:

`curl https://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg > a.ogg`

```
package main

import (
	"fmt"
	"github.com/pion/webrtc/v3/pkg/media/oggreader"
	"os"
)

func main() {
	file, _ := os.Open("a.ogg")
	_, _, err := oggreader.NewWith(file)
	fmt.Println(err)
}
```

### What happened?

`err` is `payload for id page must be 19 bytes`

**Comment by Sean-Der** [comment]
Hey @OptimisticLock 

The ogg reader unfortunately only supports Opus. If you can transcode that to Opus does it work?

`ffmpeg -i a.ogg -c:a libopus -page_duration 20000 -vn output.ogg`

**Comment by OptimisticLock** [comment]
Wow, thank you for a fast response! Worked like a charm. Now am surprised I haven't seen this issue mentioned by anyone else online. Perhaps the error message could be made a bit more informative, too?

**Comment by Sean-Der** [comment]
@OptimisticLock That could be really helpful!

I am not sure exactly what we would do. Maybe if that check fails we run an additional check for Vorbis and return a specific error message?

**Comment by OptimisticLock** [comment]
I wouldn't know. But seriously, this project has 9K stars, and no one has ever tried it on Mac and posted about it? Confused.

**Comment by Sean-Der** [comment]
This issue isn't Mac specific. The `oggreader` only supports the Opus Codec.

We also don't have any reason to support Vorbis. WebRTC doesn't support it and Opus is the successor of Vorbis.

**Comment by Sean-Der** [comment]
Closing for now.

If anyone is interested in adding more heuristics to the oggreader I would love to accept the contribution. I don't see a way we can bound/define this issue as users could pass us so many different codecs.
