### ISSUE TITLE
"valid" unified plan sdp considered as planB by pion

### ISSUE THREAD

**Issue by Philippe-Torrelli-Ale** [pion/webrtc#2193]
### Your environment.
  - Version: *v3.1.25*
  - Browser: *not relevant*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

Hi, i have a problem related to plan-b and pion.

I use pion in a bot that is connected to a webrtc gateway.

Previously this gateway didn't support unified plan, and i had no issue with connecting pion and it, but with google withdrawing support of planb from their satck, the authors reworked the gateway, and now it supports unfied plan.

What this gateway does is handle sip calls and make them available through a webrtc client.
In this scenario my "bot" is the client, and relies on pion for webrtc matters.

The signaling between the bot and the gateway  is negotiated over xmpp through a jingle session:

Here is what happens:

The gateway sends a propose to my pion bot:
```
<message xmlns="jabber:client" xml:lang="en" to="83ddc5e30d9d4908be03bd652f47d1a7@openrainbow.net" from="mp_rvcp_cce750bce746486c8f17d39b753eeab6@openrainbow.net/mediapillar">
   <propose xmlns="urn:xmpp:jingle-message:0" id="c9j6s308hpfda453sao0">
      <description xmlns="urn:xmpp:jingle:apps:rtp:1" media="audio" />
      <mediapillar xmlns="urn:xmpp:janus:1">
         <callernumber>+33999981002</callernumber>
         <callId>48D8265E-62666E0C00085A20-5F7FE700_tpcc_pbx-1</callId>
      </mediapillar>
      <unifiedplan xmlns="urn:xmpp:jingle:apps:jsep:1" />
   </propose>
</message>
```
->nothing very interesting here except the ```<unifiedplan xmlns="urn:xmpp:jingle:apps:jsep:1" />```  which means that it is an unified plan session, so in Pion I create a peerConnection with ```  config.SDPSemantics = webrtc.SDPSemanticsPlanB```

Then the bot sends "proceed" jingle packet meaning he accepts the session (nothing of consequence on pion here so won't detail that more)..

Then the gateway sends its offer in a "session-initiate" packet.

```
<iq xmlns="jabber:client" xml:lang="en" to="xx" from="yy" type="set" >
   <jingle xmlns="urn:xmpp:jingle:1" action="session-initiate" initiator="mp_rvcp_cce750bce746486c8f17d39b753eeab6@openrainbow.net" responder="83ddc5e30d9d4908be03bd652f47d1a7@openrainbow.net/gomock_196210f0-bd38-4f89-ace2-1bd3b4fa37a8" sid="c9j6s308hpfda453sao0">
      <content creator="initiator" name="audio" senders="both">
         <description xmlns="urn:xmpp:jingle:apps:rtp:1" media="audio">
            <payload-type channels="1" clockrate="8000" id="8" name="PCMA" />
            <payload-type channels="1" clockrate="8000" id="0" name="PCMU" />
            <payload-type channels="1" clockrate="48000" id="96" name="opus" />
            <payload-type channels="1" clockrate="48000" id="97" name="telephone-event" />
            <payload-type channels="1" clockrate="8000" id="101" name="telephone-event" />
            <rtcp-mux />
         </description>
         <transport xmlns="urn:xmpp:jingle:transports:ice-udp:1" pwd="qYe1EBozQG1FD8EORLFzbDO72l" ufrag="uJRDCFb0">
            <fingerprint xmlns="urn:xmpp:jingle:apps:dtls:0" hash="sha-256" setup="actpass">55:20:49:E2:F0:CD:82:96:64:45:F5:F3:32:AA:44:FB:FC:C0:1B:AF:CB:D1:E9:83:3E:A0:FD:F2:FB:70:30:F2</fingerprint>
            <candidate component="1" foundation="TwJ090uYNRcf6dG0" generation="0" id="c9j6s308h" ip="5.135.97.99" network="1" port="39192" priority="2130706431" protocol="UDP" type="host" />
         </transport>
      </content>
   </jingle>
</iq>
```

Translated into SDP, this becomes:
```
v=0
o=- 1923518516 2 IN IP4 0.0.0.0
s=-
t=0 0
m=audio 1 RTP/SAVPF 8 0 96 97 101
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:uJRDCFb0
a=ice-pwd:qYe1EBozQG1FD8EORLFzbDO72l
a=ice-options:trickle
a=fingerprint:sha-256 55:20:49:E2:F0:CD:82:96:64:45:F5:F3:32:AA:44:FB:FC:C0:1B:AF:CB:D1:E9:83:3E:A0:FD:F2:FB:70:30:F2
a=setup:actpass
a=candidate:TwJ090uYNRcf6dG0 1 UDP 2130706431 5.135.97.99 39192 typ host generation 0 network-id 1 ufrag uJRDCFb0 pwd qYe1EBozQG1FD8EORLFzbDO72l
a=sendrecv
a=mid:audio
a=rtcp-mux
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:96 opus/48000
a=rtpmap:97 telephone-event/48000
a=rtpmap:101 telephone-event/8000
```

The bot calls pc.SetRemoteDescription with this SDP, 
and then pc.CreateAnswer()

### What did you expect?
create answer returns an answer and i can send it to the gateway.

### What happened?

createAnswer returns the following error: 
```
remote SessionDescription semantics does not match configuration: Expected UnifiedPlan, but RemoteDescription is PlanB
```
### What the problem could be...
Apparently the same sdp works on every other stacks they tested.. mostly browsers / libwebrtc based apps.
From my understanding, pion considers the sdp offer to be planB because of  the id "audio" in the line a=mid:audio ..

So  I think I have five options here:

1. would be to fork pion, to remove this test (obviously i don't want to do that)
2. would be to change the transcoding from jingle to sdp to generate a=mid:0 instead of the original a=mid:audio line..
But from my understanding this "audio" label is used in extensions to the rtp headers and by the stack to find the right transceiver/track .. and i would have issues then with the media (so i don't want to do that too)
3. would be to use another sdp semantics: stick to planB or maybe SDPSemanticsUnifiedPlanWithFallback and, having only one media, it should be compatible..
But from what I read in the roadmap, planB is planned to be removed from pion in upcoming versions
4. would be to make the people in charge of the gateway fix the SDP and encode it in pion friendly way, (or valid way ?) but I would need a good justification for that to happen (considering it works with other stacks, and they think it's a valid sdp)
I'm struggling with the draft, and cannot find a place where it forbids them to use "audio" "video" or "data" for their mid
5. or maybe they are right, and pion should accept this SDP ?

Can you help me with that ? What do you think ?

Thanks in advance

**Comment by fippo** [comment]
unrelated, would you please let the authors of that gateway know that they are not supposed to make up non-standard extensions in the `urn:xmpp` xml namespace? The change controller for that is the XMPP Standards foundation. They are free to use their own namespace, including http:// urls.

**Comment by Philippe-Torrelli-Ale** [comment]
> unrelated, would you please let the authors of that gateway know that they are not supposed to make up non-standard extensions in the `urn:xmpp` xml namespace? The change controller for that is the XMPP Standards foundation. They are free to use their own namespace, including http:// urls.

I will. Thanks.

**Comment by Philippe-Torrelli-Ale** [comment]
Update: I tried using the two other sdp semantics. In this case pion accepts to create an answer and negociation goes well, up to onICEConnectionStateChanged that goes to connected.
with the webrtc.SDPSemanticsUnifiedPlanWithFallback semantics, pion issues a log "Plan-B Offer detected; responding with Plan-B Answer"

But when i do so,  onTrack is never called  so the "option" 3 doesn't work for me.

**Comment by atoppi** [comment]
Working with the `0.x` branch of Janus (the one before the support for multistream), I'm being hit by the same issue.

```
v=0
o=- 1653053144451578 1 IN IP4 192.168.1.174
s=VideoRoom 1
t=0 0
a=group:BUNDLE audio video
a=extmap-allow-mixed
a=msid-semantic: WMS janus
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 192.168.1.174
a=sendonly
a=mid:audio
a=rtcp-mux
a=ice-ufrag:jNqK
a=ice-pwd:uWAE4E8Ff3551RKOQ6uyqb
a=ice-options:trickle
a=fingerprint:sha-256 B1:18:4A:CB:40:F7:A1:57:65:60:40:EE:9A:C6:E3:3B:61:46:C1:73:1E:86:AA:6A:8B:16:13:30:E2:D7:ED:76
a=setup:actpass
a=rtpmap:111 opus/48000/2
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtcp-fb:111 transport-cc
a=msid:janus janusa0
a=ssrc:3228063102 cname:janus
a=ssrc:3228063102 msid:janus janusa0
a=ssrc:3228063102 mslabel:janus
a=ssrc:3228063102 label:janusa0
a=candidate:1 1 udp 2015363327 192.168.1.174 49090 typ host
a=candidate:2 1 udp 2015363583 192.168.1.170 40630 typ host
a=end-of-candidates
m=video 9 UDP/TLS/RTP/SAVPF 96 97
c=IN IP4 192.168.1.174
a=sendonly
a=mid:video
a=rtcp-mux
a=ice-ufrag:jNqK
a=ice-pwd:uWAE4E8Ff3551RKOQ6uyqb
a=ice-options:trickle
a=fingerprint:sha-256 B1:18:4A:CB:40:F7:A1:57:65:60:40:EE:9A:C6:E3:3B:61:46:C1:73:1E:86:AA:6A:8B:16:13:30:E2:D7:ED:76
a=setup:actpass
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=msid:janus janusv0
a=ssrc:466645072 cname:janus
a=ssrc:466645072 msid:janus janusv0
a=ssrc:466645072 mslabel:janus
a=ssrc:466645072 label:janusv0
a=candidate:1 1 udp 2015363327 192.168.1.174 49090 typ host
a=candidate:2 1 udp 2015363583 192.168.1.170 40630 typ host
a=end-of-candidates
```

**Comment by Sean-Der** [comment]
Sorry I haven't addressed this sooner!

I am going to push a fix now that instead of looking at the Media Section name it looks at the count of SSRCes with distinct `msid`

**Comment by Sean-Der** [comment]
Hey @atoppi and @Philippe-Torrelli-Ale I have made the default checks for Plan-B harder to trip. Mind testing with https://github.com/pion/webrtc/pull/2231 if that passes either of your use cases I will merge! This is the new behavior

```
Before a SessionDescription was assumed to be Plan-B if it contained a
MediaName of audio or video. This PR Changes that behavior.

If SDPSemantics is UnifiedPlan the SessionDescription must contain a
MediaDescription with two SSRCes.

If SDPSemantics is PlanB or UnifiedPlanWithFallback it maintains the
existing behavior.
```

**Comment by atoppi** [comment]
@Sean-Der testing with `github.com/pion/webrtc/v3 v3.1.41-0.20220523012042-e985fab1428b` was successful.
Now it works as expected.

**Comment by Philippe-Torrelli-Ale** [comment]
Hi Sean, it works for me now with your fix, thanks a lot !

**Comment by Philippe-Torrelli-Ale** [comment]
Hi Sean, sorry for the late response.
I updated my dependencies and tried again, and now the problem is gone.
Thanks a lot for this :)
