### ISSUE TITLE
add support for embed.FS for ogg

### ISSUE THREAD

**Issue by mohammadne** [pion/webrtc#2247]
## Summary

In my case I prefer to use `embed.FS` for reading ogg track, so it would be awesome to add support for `embed.FS` in `ogg` package.

## Motivation

Appropriate for reading small ogg files, also to cleanup copying the static files manually into containers in build time.  

## Additional context

None.

**Comment by Sean-Der** [comment]
Hi @mohammadne 

I believe you can do this today! `oggreader` takes a `io.Reader`.

You could do something like this then 

```
//go:embed file.opus
var opus []byte

NewWith(bytes.NewReader(opus))
```

Please re-open if that doesn't work! Thanks for using Pion :)
