### ISSUE TITLE
Failed to handle DCEP: invalid Message Type

### ISSUE THREAD

**Issue by dafapro** [pion/webrtc#2258]
### Your environment.
  - Version: master--589d67e5abbb717be775d1709ebcdc8f93e646ad
  - Browser: chrome
  - Other Information - related issue: https://github.com/pion/datachannel/issues/125

### What did you do?
create and close datachannels frequently, use those datachannels for short time communications.

### What did you expect?
create data channel successfully
### What happened?
datachannel ERROR: 2022/06/14 07:59:50 Failed to handle DCEP: invalid Message Type &{0 0 0 [103 97 116 101 119 97 121 45 105 79 83 45 49 54 53 53 49 57 51 53 56 57 46 54 54 54 52 51 54] []}

**Comment by vyloy** [comment]
After studying the code, I guess it is about missing implementation of reusing data channel.

**Comment by dafapro** [comment]
After studying the code, I guess it is about missing implementation of reusing data channel.

**Comment by shynome** [comment]
```go
params := &webrtc.DataChannelParameters{
	ID: &a, // set id will it working
}
```
