### ISSUE TITLE
How can I receive or deal the RTX packet?

### ISSUE THREAD

**Issue by ChenMoGe2** [pion/webrtc#2272]
Your environment.
Version: 3.1.42

**Comment by alexpokotilo** [comment]
It looks like rtx packets not supported by default and it is strange why rtx declared in 
func (m *MediaEngine) RegisterDefaultCodecs()
Please see  https://github.com/pion/webrtc/issues/1675 for details.
I removed rtx and back to NACK. NACK works.
May be I missed something. I'm new with pion

**Comment by Sean-Der** [comment]
Hi!

We currently don't support RTX as a distinct SSRC. We do support NACK + RTX though, you can see the implementation [here](https://github.com/pion/interceptor/tree/master/pkg/nack)

**Comment by ChenMoGe2** [comment]
> Hi!
> 
> We currently don't support RTX as a distinct SSRC. We do support NACK + RTX though, you can see the implementation [here](https://github.com/pion/interceptor/tree/master/pkg/nack)

Hello,Thank you for your reply.If I want support RTX as a distinct SSRC,how do I do?I see your reply in issue [https://github.com/pion/webrtc/issues/1675](url),but I try to do it but I failed.Could you give a more complete plan？Thank you!

**Comment by alexpokotilo** [comment]
Hi @ChenMoGe2,
why do you need RTX with distinct SSRC ? NACK works fine and as far as I understand do the same as RTX+distinct SSRC.
Please explain your considerations as I'm newbie too.

**Comment by ChenMoGe2** [comment]
> Hi @ChenMoGe2, why do you need RTX with distinct SSRC ? NACK works fine and as far as I understand do the same as RTX+distinct SSRC. Please explain your considerations as I'm newbie too.

Hello.I use RTX with distinct SSRC because for packet loss statistics.If you just use NACK,the packet loss statistics maybe a negative number.RTX distinct SSRC is designed for it.The packet resend on the RTX ssrc and the packet loss statistics will be correct

**Comment by alexpokotilo** [comment]
Hi @ChenMoGe2,
could you please give me something to read about this statistics measurement problem?
Besides statistics re-transmission works the same, right ?

**Comment by Sean-Der** [comment]
This has been implemented!

If a remote Peer sends a RTX with a distinct SSRC Pion now returns in via the `Read`. You can see a test for it [here](https://github.com/pion/webrtc/blob/master/rtpreceiver_go_test.go#L86)
