### ISSUE TITLE
Add interface to disable DTLS SRTP

### ISSUE THREAD

**Issue by CaptainNeil** [pion/webrtc#2273]
## Summary
As the title describes, I would like to have an interface to disable DTLS SRTP, just like the `enable_dtls_srtp` defined in C++

## Motivation
To analyze RTP payload.

## Describe alternatives you've considered

I'm working on rtmp 2 webrtc, the workflow is as follow：
- rtmp receive origin aac data
- decode aac to pcm
- slice pcm to 10ms pcm list (the opus encoder requires)
- encode pcm to opus
- pack opus as an rtp package
- send rtp package to TrackLocalStaticRTP

Unfortunately, the received sound on the other end is noisy.
I saved the opus data before sending it to the RTPSender, and it sounded fine.

So I wanted to use Wireshark to see what happened, but the rtp payload was encrypted.

By searching at code，I could'n find a way to turn it off.

@Sean-Der

**Comment by CaptainNeil** [comment]
The problem is similar as [#2090](https://github.com/pion/webrtc/issues/2090)

**Comment by zjzhang-cn** [comment]
agreed

**Comment by yyyar** [comment]
@CaptainNeil did you managed to solve the issue? 
I have the same similar problem doing the same thing (aac->opus->webrtc) I've got choppy audio as described in #2090. I noticed 0 lost packets in webrtc-internals in chrome, but lots of concealedSamples and insertedSamplesForDeceleration.

**Comment by CaptainNeil** [comment]
> @CaptainNeil did you managed to solve the issue? I have similar problem doing the same thing (aac->opus->webrtc) I've got choppy audio as described in #2090. I noticed 0 lost packets in webrtc-internals in chrome, but lots of concealedSamples and insertedSamplesForDeceleration.
@yyyar 
I have solved this problem.
My problem is the noise caused by the rtp timestamp.
When I pack OPUS into an RTP package, I did not increase the timestamp according to the audio size. Therefore, noise will be generated when webRTC rendering

**Comment by GodKingGitHub** [comment]
absolutely agreed

**Comment by Sean-Der** [comment]
I am in support of this!

What someone should do is add support for the NULL cipher to `pion/srtp`. Then via the SettingEngine both sides can request it.

As long as this requires the developer explicitly requesting it (via the SettingEngine) it would be great to have.

**Comment by sirzooro** [comment]
I am working on some changes to srtp module now. I will add NULL cipher there too.
