### ISSUE TITLE
How to deal packet loss？

### ISSUE THREAD

**Issue by ChenMoGe2** [pion/webrtc#2291]
I use pion webrtc to develop a media server and the video quality is low(I use simulcast) and video loss frame frequently.I send rtcp from server to client using below code in example/simulcast:
```
// Start reading from all the streams and sending them to the related output track
rid := track.RID()
go func() {
    ticker := time.NewTicker(3 * time.Second)
    for range ticker.C {
	fmt.Printf("Sending pli for stream with rid: %q, ssrc: %d\n", track.RID(), track.SSRC())
	if writeErr := peerConnection.WriteRTCP([]rtcp.Packet{&rtcp.PictureLossIndication{MediaSSRC: uint32(track.SSRC())}}); writeErr != nil {
		fmt.Println(writeErr)
	}
    }
}()
```
but the video quality still low and the packet still loss(increment by I doing nothing)
How can I sovle it and I have two question.
1.Is there some perfect example or project to deal with packet loss.
2.How can I deal Rtcp packet from sender(client).If I must handle rtcp packets in code or the pion can handle it automaticly
Thank you

**Comment by ChenMoGe2** [comment]
> I use pion webrtc to develop a SFU server and the video quality is low(I use simulcast) and video loss frame frequently.I send rtcp from server to client using below code in example/simulcast:
> 
> ```
> // Start reading from all the streams and sending them to the related output track
> rid := track.RID()
> go func() {
>     ticker := time.NewTicker(3 * time.Second)
>     for range ticker.C {
> 	fmt.Printf("Sending pli for stream with rid: %q, ssrc: %d\n", track.RID(), track.SSRC())
> 	if writeErr := peerConnection.WriteRTCP([]rtcp.Packet{&rtcp.PictureLossIndication{MediaSSRC: uint32(track.SSRC())}}); writeErr != nil {
> 		fmt.Println(writeErr)
> 	}
>     }
> }()
> ```
> 
> but the video quality still low and the packet still loss(increment by I doing nothing) 
How can I sovle it and I have two question.
1.Is there some perfect example or project to deal with packet loss.
2.How can I deal Rtcp packet from sender(client).If I must handle rtcp packets in code or the pion can handle it automaticly
Thank you

**Comment by rajivg91** [comment]
Hi @ChenMoGe2 
I'm having the same issue, were you able to solve it

**Comment by alexpokotilo** [comment]
please take a look at https://github.com/pion/webrtc/discussions/2254

**Comment by Tekunalogy** [comment]
Running into severe packet loss on windows 10/11 with this example (rtp-to-webrtc):
https://github.com/pion/webrtc/tree/master/examples/rtp-to-webrtc

however, no issues with the same code on ubuntu 22. Same machine specs, same router/network conditions.

**Comment by Sean-Der** [comment]
Good news! Packet loss is now handled by default with Pion.

We provide NACK Interceptors to send NACKs and respond to them appropriately. They are enabled by default and you can see that [here](https://github.com/pion/webrtc/blob/master/interceptor.go#L58)

Low bitrate from the browser is caused by lack of receiver feedback. By default we enable TWCC [here](https://github.com/pion/webrtc/blob/master/interceptor.go#L97) so you should get the best experience possible by default.

If anyone has questions/concerns I am happy to help further. Thanks for using Pion!
