### ISSUE TITLE
Support FQDN ICE candidates

### ISSUE THREAD

**Issue by i-sergienko** [pion/webrtc#2300]
## Summary

Add support for FQDN ICE candidates in addition to the already supported IP candidates.

## Motivation

FQDN candidates are a valid option as per the RFC, and they are supported in other major WebRTC implementations (such as browser ones).
This feature will allow the users to use Pion to connect to peers that only expose FQDN candidates, which is somewhat tricky to achieve without direct library support.

## Describe alternatives you've considered

A hypothetical alternative would be to post-process incoming ICE candidates, resolving any FQDNs to concrete IP addresses on the client side before passing them to the library. That adds implementation overhead to the user, and requires them to know the implementation details of the WebRTC stack instead of just using the library as a black box.

## Additional context

@Sean-Der mentioned in the Slack channel that this feature has [potential privacy implications](https://medium.com/tenable-techblog/turning-signal-app-into-a-coarse-tracking-device-643eb4298447).

**Comment by stv0g** [comment]
@i-sergienko Can we close this issue here in favor of this one: https://github.com/pion/ice/issues/512 ?

**Comment by i-sergienko** [comment]
@stv0g Sounds good to me, closing it.
