### ISSUE TITLE
GatheringCompletePromise is never triggered when there is no network

### ISSUE THREAD

**Issue by MI-Class** [pion/webrtc#2304]
### Your environment.
  - Version: *Release or SHA*
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*
  webrtc: v3.1.42
  go:1.8
### What happened?
Calling this method in the absence of an extranet will never result in channel closure

**Comment by Sean-Der** [comment]
Hey @MI-Class 

I am not able to reproduce this. What OS are you on? Do you have no interfaces at all?

thanks!

**Comment by MI-Class** [comment]
> 嘿
> 
> 我无法重现这一点。您使用什么操作系统？你根本没有接口吗？
> 
> 谢谢！

抱歉,我是用了其他的项目里使用了这个库,webrtc.GatheringCompletePromise   是这个方法等待时间太长了,因为stun服务器地址链接超时了,是其他项目的问题
