### ISSUE TITLE
Screen sharing gets stuck while lock screen.

### ISSUE THREAD

**Issue by AamanPhale** [pion/webrtc#2318]
Hi I just wanted to know when the screen sharing is going on  while the screen gets auto locked, after end user unlocking it the screen sharing get stuck. Is there any way where we can resume the screen sharing after unlock event happens?

We are using Opus and H264 codec here..

**Comment by Sean-Der** [comment]
Hey @AamanPhale 

Sorry I didn't respond to this sooner. Unfortunately nothing you can really do with Pion here. You can detect when RTP packets have stopped flowing, but you can't really know why the remote machine has pushed them.

If you discovered anything more while working on this I would love to know! Would be great to help others. Thanks @AamanPhale
