### ISSUE TITLE
Error in save-to-disk example in demo.js file.

### ISSUE THREAD

**Issue by zaargham** [pion/webrtc#2324]
### Your environment.
  - Browser: *firefox 104 linux*
  - Other Information - file:-demo.js line no 36 
  - suggestions-RTCsessionDescription is deprecated use RTCSessionDescriptionInit, 
links [click](https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescription/RTCSessionDescription)

### What did you do?

![Screenshot from 2022-10-07 11-51-19](https://user-images.githubusercontent.com/48851583/194481240-368dec8e-16e3-4f43-aa3b-fccc7ca27927.png)

**Comment by Sean-Der** [comment]
Thank you for reporting this @zaargham !

If you need any other help with Pion I am always available in [Pion Slack](https://pion.ly/slack)
