### ISSUE TITLE
I'm looking for SNI configuration support for DTLS, using webRTC

### ISSUE THREAD

**Issue by RaniRaven** [pion/webrtc#2325]
Hi,

I understand there is SNI extension support for TLS, and that it was also extended for the DTLS, even though it is not in the standard or in any ietf draft.
I fail, however, to understand if this needs to be configured over the peer connection in some way, or it is the default.
Which kind of configuration is supposed to enable this, so that i'll be able to test it ?

If somebody has some snippet of code for checking it with the examples via Janus-Gateway for example, that would be great

**Comment by Sean-Der** [comment]
Hi @RaniRaven 

It is enabled by default! You can see the tests for it [here](https://github.com/pion/dtls/blob/master/conn_test.go#L2133)

In the context of WebRTC I don't believe we can do SNI. DTLS is running over an ICE Connection (which can connect to multiple remote peers). Which remote host would the SNI be?

You also have Peer Reflexive Candidates. So if the remote host creates a Peer Reflexive candidate do we create the SNI for that?

-----

I am going to resolve this as 'Not possible to implement'. We could possibly add a feature to the `SettingEngine` to force a SNI. I worry that could have a negative impact though. What are you trying to implement. Maybe it could be done a different way?

Thanks for using pion @RaniRaven and sorry this isn't an easy fix :/
