### ISSUE TITLE
Midsession Reoffer

### ISSUE THREAD

**Issue by gbfarah** [pion/webrtc#2334]
### Discussed in https://github.com/pion/webrtc/discussions/2333

<div type='discussions-op-text'>

<sup>Originally posted by **gbfarah** October 17, 2022</sup>
Hi,
I'm tackling an issue that I would appreciate feedback on...
Issue is pretty simple.  When using pion to communicate to a browser I need to address maintaining a webrtc connection being resilient to a page refresh.

Conceptually I've tried two solution and both have failed . Solution 1 is most ideal but I understand if their is a WebRTC limitation I'm missing.

**Solution 1**

1- Server create a WebRTC offer.... The SDP for this offer is cached by signalling app
2-Browser answers the offer and remote SDP is communicated back to server .. WebRTC connection successfully established
3- Browser refreshes. The original offer in 1 is given again to the browser and answered. Remote SDP passed back to the server
4. No connection established

In the above conceptually I can't see why using an old server offer to a new browser doesn't work . From a crypto perspective all required info is known by each of the browsers

**Solution 2**
1- Server create a WebRTC offer.... The SDP for this offer is cached by signalling app
2-Browser answers the offer and remote SDP is communicated back to server .. WebRTC connection successfully established
3- Browser refreshes. Server is asked to reoffer
4- New Browser presents the answer
5. No connection established

I'm a little confused by neither of these solutions works and prefer not to destroy and recreate peer connections

Many thanks in advance

</div>

**Comment by Sean-Der** [comment]
Hi @gbfarah 

Sorry for taking so long to respond to this out. I have been taking a break from pion/webrtc.

Will respond in your question thread now!
