### ISSUE TITLE
How can I specify more than one codec when I invoke NewTrackLocalStaticRTP

### ISSUE THREAD

**Issue by ChenMoGe2** [pion/webrtc#2335]

**Comment by Sean-Der** [comment]
Hi @ChenMoGe2 

That isn't possible today. What are you trying to implement? 

We could modify it to make your use case work, or maybe it is possible to implement your idea another way.

**Comment by ChenMoGe2** [comment]
> Hi @ChenMoGe2
> 
> That isn't possible today. What are you trying to implement?
> 
> We could modify it to make your use case work, or maybe it is possible to implement your idea another way.

Thanks for you reply.I want do this because the sender sends video codec either h264 or vp8.

Maybe I already resovle it.I create two video track to distinguish different video codec

**Comment by ChenMoGe2** [comment]
> Hi @ChenMoGe2
> 
> That isn't possible today. What are you trying to implement?
> 
> We could modify it to make your use case work, or maybe it is possible to implement your idea another way.

Hello,I made an SFU server and use different client to connect it.One client sends video using H264 and the other sends video using VP8.

**Comment by Sean-Der** [comment]
Hi @ChenMoGe2 

Sorry I never got around to responding to this. This is possible with `pion/webrtc@v3` now! `TrackLocal` is an interface so as long as you satisfy it you can send w/e codec you want.

Here is an example of the pattern you are requesting in Broadcast box [trackMultiCodec](https://github.com/Glimesh/broadcast-box/blob/24fdb2d6569cb7486952e1690b49d929fc3d867d/internal/webrtc/track_multi_codec.go) allows the caller to switch between H264/VP8/VP9/AV1 at anytime.

I think it would make sense to add this pattern to Pion itself! Make `TrackLocalDynamicRTP` and `TrackLocalDynamicSample` it would require some thought around the API design/error handling though!
