### ISSUE TITLE
pion/webrtc: forward live h264 stream to pion/webrtc and play in browser, the stream play abnormally。

### ISSUE THREAD

**Issue by sureone** [pion/webrtc#2337]
I am trying to ise this libaray to  implement forwarding live stream to webrtc for playing in browser. Work is based on project: https://github.com/aler9/rtsp-simple-server, below my code for write h264 nalus sample to webrtc,

1. pull h264 data from ringbuffer
2. write h264 nalus to webrtc video track
```
func (c *webrtcSession) runRead(ctx context.Context) error {
        c.ringBuffer, _ = ringbuffer.New(uint64(c.readBufferCount))
        h264FrameDuration := time.Millisecond * 33
        for {
            item, ok := c.ringBuffer.Pull()
            data := item.(*data)
            if c.videoTrack != nil && data.trackID == c.videoTrackID 
            {
                if data.h264NALUs == nil {
                    continue
                }
                outBuf := []byte{}
                for _, nalu := range data.h264NALUs {
                    outBuf = append(outBuf, []byte{0x00, 0x00, 0x00, 0x01}...)
                    outBuf = append(outBuf, nalu...)
                }
                c.videoTrack.WriteSample(media.Sample{Data: outBuf, Duration:time.Duration(h264FrameDuration)})
            }
        }
    }
```

here is the screen recording for the problem :https://youtu.be/twyiU9rF8AY

**Comment by Sean-Der** [comment]
Hi @sureone 

My guess would be the source has B Frames? Chrome doesn't have a concept of DTS so it will stutter as the timestamps are out of order.

Can you try re-encoding with `tune=zerolatency` (will disable b-frames and some other features that Chrome/OpenH264 have issues handling)

If that doesn't work please re-open this issue and happy to help :)

**Comment by sureone** [comment]
@Sean-Der Thanks for your help! Issue fixed after disable B frames in encoding.
