### ISSUE TITLE
Improper transceiver reuse in peerConnection.AddTrack

### ISSUE THREAD

**Issue by peffis** [pion/webrtc#2342]
### Your environment.
  - Version: github.com/pion/webrtc/v3 v3.1.44
  - Browser: Firefox 106.0.1 (but any Firefox really)
  - Other Information - [CollectSenders](https://www.w3.org/TR/webrtc/#dfn-collectsenders)

### What did you do?
1) A user1 has published a track - say audio - to the SFU by sending an offer with a sendonly track to the SFU. The SFU sets up a peerConnection with a recvonly transceiver to receive this track. All is working fine. Track and RTP is received on SFU

2) User1 gets a notification that someone else - say user2 - has published a track. User1 therefore adds a recvonly transceiver to its browser peerconnection, sends a new offer which now has its previous sendonly track and its new recvonly track info. 

3) The SFU adds a sendonly transceiver to user1's SFU peerConnection (which only had a recvonly transceiver before this), adds the localtrack of user2, adds the new offer from the client and creates the answer. 

4) Instead of, in AddTrack, adding an rtpSender to the newly added free sendonly transceiver, the AddTrack will find the recvonly transceiver (the published stream) and change its direction to sendrecv instead. This results in that the answer sent back will now specify sendrecv on the track where the offerer specified sendonly. This is, strictly speaking, not allowed and Firefox will, when you add the remote description (SetRemoteDescription) throw an exception: "Unhandled Rejection (InvalidAccessError): Answer tried to set send when offer did not set recv". Other browsers, like Chrome, is less formal regarding this and will not care. 

### What did you expect?
The expected result is that the new, free sendonly trasceiver was used when adding the localtrack rather than modifying the existing recvonly transceiver. This would have also created a proper answer with one sendonly track and one recvonly track. 

Also, the code in AddTrack is broken in another way also: If you want to add a track and before add a sendonly transceiver in order to send this track on, this sendonly transceiver will actually NEVER be picked up by the loop in AddTrack. Instead it will always fall back to the base case on line 1786 https://github.com/pion/webrtc/blob/9c47fea3f2514dc6021323e66e628a3b99f6911e/peerconnection.go#L1786 where it will always add a new sendrecv transceiver. So the call to add a sendonly trasceiver is useless as that transceiver will never be used. It will however show up in the answer and cause the SDP to grow over time when you add more and more tracks to the peer connection. 

### What happened?
https://github.com/pion/webrtc/blob/9c47fea3f2514dc6021323e66e628a3b99f6911e/peerconnection.go#L1764-L1767 refers to https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-addtrack for why it looks the way it does, but the code does not really implement it that way. I believe that the main difference here is that the code will loop through all available transceivers and will therefore find this recvonly transceiver which also has a nil sender (obviously), but the specification on https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-addtrack will actually first do [CollectSenders](https://www.w3.org/TR/webrtc/#dfn-collectsenders) and then find the associated transceiver with the senders, so in the specification's sender reuse it would never even consider this recvonly transceiver as it is not associated with any sender (its sender is nil)

**Comment by cnderrauber** [comment]
@jeremija  Can you post a test case of your failed case? We can check the detail of that and how to make it pass.

**Comment by cnderrauber** [comment]
@jeremija Created #2393 to fix your test-case, can you verify it works in your product?
@peffis I'm not sure your case is same as @jeremija 's , can you verify the fix pr work for you too? Or you can provide a test case if it is not work.

**Comment by Sean-Der** [comment]
This seems to be fixed! If you are still seeing issues @jeremija or @peffis tell me and happy to dig into this :)
