### ISSUE TITLE
SRT for production streaming from jvc production camera’s 

### ISSUE THREAD

**Issue by gedw99** [pion/webrtc#2343]
https://www.haivision.com/products/srt-secure-reliable-transport/

They have a golang lib too !

https://github.com/Haivision/srtgo

seems there are a few golang projects using it:

https://github.com/Haivision/srtgo/network/dependents

But if you want to get production cameras to stream to a mixing booth that is remote is SRT the best way ?

Either digital or hardware mixing cloud I mean

**Comment by Sean-Der** [comment]
Hi @gedw99 

I have been working on this lately! Check out https://github.com/flavioribeiro/donut

It is a MPEG-TS over SRT -> WebRTC bridge. Should be a good jumping off point for anyone interested
