### ISSUE TITLE
No connection on local device even though Local and Remote description are set and candidates exist

### ISSUE THREAD

**Issue by peredwardsson** [pion/webrtc#2345]
I run two programs based on the `pion-to-pion` business, although I use Firebase rather than a HTTP server for signalling. I am unable to get it to work. The offerer creates an offer, sets the local description, sends it to the answerer, who sets it as remote description, creates an answer and sends its answer off which is again set as the remote description of the offerer. In the background, buffer ICE candidates and send the candidates once remote description has been set. I make a data channel before creating the offer and add `OnDataChannel` callbacks on answerer. The offerer reports the data channel opening, even though the answerer does not. `OnConnectionStateChange` callbacks are never triggered, but `OnICEGatheringState` callbacks do.

In the end, both clients have a local description and a remote description, and they look to have been transmitted correctly.

I just can't figure it out. It really seems like it should work. How do I go about troubleshooting an issue like this? Any logs I can provide?

**Comment by ashellunts** [comment]
Hi @peredwardsson,

Take a look here for debugging:
https://github.com/pion/webrtc/wiki/Debugging-WebRTC

**Comment by ashellunts** [comment]
I am not sure.

I would suggest to compare logs of pion-to-pion example running locally and logs of your setup.

**Comment by peredwardsson** [comment]
pion-to-pion had the same errors, so that seems kosher. It works now. Turned out that I had made a struct carrying a `webrtc.PeerConnection` instead of a `*webrtc.PeerConnection`, so I got a connection established but on another object than I was adding callbacks too maybe. That's what I get for learning go, webrtc and pion at the same time. Thanks for your super fast response and helpful tips.
