### ISSUE TITLE
RTPSender causes panic when an offer to receive audio / video is created without adding tracks and subscribing to OnNegotiationNeeded

### ISSUE THREAD

**Issue by InnovativeUS** [pion/webrtc#2349]
Using the trickle ICE example

Change the client to offerToReceiveAudio on line 59 of index.html

      pc.createOffer({offerToReceiveAudio: true,}).then(offer => {
        pc.setLocalDescription(offer)
        socket.send(JSON.stringify(offer))
      })

Change the server to subscribe to OnNegotiationNeeded on line 57 of main.go

	peerConnection.OnNegotiationNeeded(func() {
		fmt.Printf("Renegotiation needed %s\n", peerConnection.SignalingState())
	})

Increase the size of the websocket buffer to allow the increased size of SDP to be received

	buf := make([]byte, 5000)

When the client / server negotiation is complete this causes a panic after negotiation is complete

Open http://localhost:8080 to access this demo
ICE Connection State has changed: checking
ICE Connection State has changed: connected

github.com/pion/webrtc/v3.(*RTPSender).Track(0x14000288320?)
dev/pion-replicate-error/rtpsender.go:215 +0x24
github.com/pion/webrtc/v3.(*PeerConnection).checkNegotiationNeeded(0x140002d6000)
dev/pion-replicate-error/peerconnection.go:394 +0x1208
github.com/pion/webrtc/v3.(*PeerConnection).negotiationNeededOp(0x140002d6000)
dev/pion-replicate-error/peerconnection.go:338 +0xe8
github.com/pion/webrtc/v3.(*operations).start(0x140002d20a8)
dev/pion-replicate-error/operations.go:90 +0x5c
created by github.com/pion/webrtc/v3.(*operations).Enqueue
dev/pion-replicate-error/operations.go:38 +0x268

### Your environment.
  - Version: 3.1.47
  - Browser: Chrome
  - Go: 1.19.3

**Comment by InnovativeUS** [comment]
Is there anything we can do to help fix this? This is a potential Denial of Service issue if a client requests audioOnly.

**Comment by Sean-Der** [comment]
Hi @InnovativeUS 

I will write and test and fix this today. Sorry for the delay!

**Comment by yurifedoseev** [comment]
@Sean-Der Hi! Any updates for the issue? Encountered to the same problem today

**Comment by yurifedoseev** [comment]
@Sean-Der I can do PR. Is it enough to check `r == nil` in `func (r *RTPSender) Track() TrackLocal` method?

**Comment by yurifedoseev** [comment]
There is an existing PR for fixing this issue https://github.com/pion/webrtc/pull/2376

**Comment by Sean-Der** [comment]
Fixed with 777e03ca3ce94d383db8e29dc5d7d242a1f59684 and tagged as `v3.1.58`
