### ISSUE TITLE
v3 & STUN - 2 party data channel always fails to negotiate a connection if one host is behind NAT.

### ISSUE THREAD

**Issue by alexanderyoung** [pion/webrtc#2388]
Hi, thanks for taking a look at this.  I mentioned in the slack channel and @jech helpfully suggested filing this issue.

Let me know how I can help, I'd like to get this resolved so I can start using v3.

Cheers!

### Your environment.
  - Version: v3 (all tested builds) fails to establish connection.  v2 (all builds) works without issue.
  - Browser: N/A.  Tested configuration is pion to pion

### What did you do?
Built a small data channel to data channel test program: https://go.dev/play/p/3g9Qmx9Kmkc

_Usage:_

**Machine 1**
1. ./data-channel
2. Copy SDP - Use below for machine 2
3. Paste SDP from machine 2
4. Send messages

**Machine 2**
1. ./data-channel {SDP_FROM_MACHINE_1}
2. Copy SDP - Use above for machine 1
3. Send messages

I started looking at pion as a nice native go way to build UDP hole punching connections, but discovered the above mentioned problem when trying to implement anything across NAT.

At first I thought it was my particular network, but then I tried it on several others and found the same thing.

I’ve seen all of the advice to just build a TURN server, but I wanted to make sure STUN was working first, and I know the theory works well, and I was able to get working connections from STUN servers through other implementations, so I suspected there is a problem in pion itself.

Through trial and error, I discovered that pion v2 works with just STUN, and works very well for my needs.

I’ve tried to isolate using a debugger, but I’m a little lost honestly.

Here’s a toy example loosely based on a couple of the data channel examples:  https://go.dev/play/p/3g9Qmx9Kmkc
I’ve had problems building v2.0.21 and above, but if I run go get -u [golang.org/x/sys](http://golang.org/x/sys) that clears things up.  Any build with v3 compiles but never establishes an ICE connection.

### What did you expect?
Data channels would connect across NAT using just STUN.

### What happened?
Connections failed to establish 100% of the time using webrtc v3.
Connections worked 100% of the time using webrtc v2.

**Comment by jech** [comment]
You're not sending ICE candidates, so you need to disable Tricke ICE.  See the example at <https://pkg.go.dev/github.com/pion/webrtc/v3#example-GatheringCompletePromise>.

(This has changed since v2: in v2, there was an explicit flag to disable Trickle.  In v3, you need to do the GatheringCompletePromise dance on your own.)

**Comment by alexanderyoung** [comment]
@jech Thank you for pointing this out.  I was able to successfully connect using v3 after adding the GatheringCompletePromise dance.

Much appreciated!
