### ISSUE TITLE
Fix repair ssrcs detection in track details extraction

### ISSUE THREAD

**Issue by BluePenNeto** [pion/webrtc#2459]
I have used the Pion webrtc to make a client of a SFU. After inspecting the output of the function **trackDetailsFromSDP**, I noticed that the field **repairSsrc** is not been filled when I think it should be (when there are rtx ssrcs). Then I manually changed the position of the **ssrc-group** lines in SDP offer from the SFU, puting them before the **ssrcs** lines. After that the field **repairSsrc** was filled correctly.

After checking the function source code, it appears that the function does not impose order on attribute processing.

**Comment by Sean-Der** [comment]
Hey @BluePenNeto 

Thanks for the report! Sorry it has taken a year to look at :/ 

I wrote a test and wasn't able to make it file. Mind looking at my PR and see if I actually captured what you described?

thank you for using Pion!
