### ISSUE TITLE
How to properly handle PeerConnection OnTrack event.

### ISSUE THREAD

**Issue by tubzby** [pion/webrtc#2470]
For example:

```go
	m := &webrtc.MediaEngine{}
	if err := m.RegisterDefaultCodecs(); err != nil {
		return nil, err
	}
	api := webrtc.NewAPI(webrtc.WithMediaEngine(m))
	pc, err := api.NewPeerConnection(conf)
	if err != nil {
		return nil, err
	}

	pc.OnTrack(func(track *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) {
		bs := make([]byte, 1600)
		for {
			n, _, err := track.Read(bs)
			if err != nil {
				log.Err(err).Msg("Read, reset demuxer")
				// IS IT SAFE to return here?
				return
			}
			//handle bytes
		}
	})

```

If *track.Read* returns any kind of error, it will break the loop and return, the question is: if the stream resumes, will the *OnTrack* hook fire again?

According to my test, it will, but not sure about that, or is there any specific error I can handle instead of quitting the loop?

**Comment by Sean-Der** [comment]
Hi @tubzby 

It is safe to return! This can happen if the Remote has closed the Track or the PeerConnection is closed.

You should have some error handling the manage the state of the entire PeerConnection though. Maybe in `OnICEConnectionState` check that you have gone to Failed/Closed (like in the examples)

It also would be fine to call `pc.Close()` before the return! If you only have one incoming track and if the read fails you are done with that PeerConnection.

Thanks for using Pion, hopefully you are still using it and enjoying it :)
