### ISSUE TITLE
RTSP and gstreamer

### ISSUE THREAD

**Issue by projetoarduino** [pion/webrtc#2502]
Hello everyone I'm trying but without success to add an RTSP url and convert to vp8

`videoSrc := flag.String("rtspsrc", `location="rtsp://admin:admin@192.168.1.7:554/Streaming/Channels/102/" ! rtph264depay ! h264parse ! avdec_h264`, "GStreamer video src")`

can anyone give any suggestions?

**Comment by Sean-Der** [comment]
Hi @projetoarduino 

Hopefully you got this working! Instead of using GStreamer directly for RTSP I would suggest https://github.com/AlexxIT/go2rtc

Best of luck with your project, and if you have any further questions I will make sure to respond faster. thanks!
