### ISSUE TITLE
Setup peerconn without ICE

### ISSUE THREAD

**Issue by lisay-yan** [pion/webrtc#2503]
## Summary

Based on RFC 8445, https://datatracker.ietf.org/doc/html/rfc8445
ICE is the solution for Network Address Translator (NAT) Traversal, for network side webRTC, no NAT, can peerconn/udp/datachannel established without ICE?

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome? Is this available in other implementations? Can this not be implemented using primitives?

Network, core network, no NAT.
Can make ICE optional? And support peerconn based on Host IP directly?

## Describe alternatives you've considered

NA

## Additional context

Support webrtc for core network side, without NAT.

**Comment by Sean-Der** [comment]
Hi @lisay-yan 

Unfortunately ICE is required for WebRTC. If we don't use/require it then we wouldn't interoperate with other WebRTC implementations. Pion doesn't attempt NAT traversal by default. Only if you pass a STUN server in the `Configuration` to `NewPeerConnection`.

Pion's `SettingEngine` gives you a lot of control over the ICE Agent.

* gather on certain interfaces [SetInterfaceFilter](https://pkg.go.dev/github.com/pion/webrtc/v3#SettingEngine.SetInterfaceFilter)
* select the ports you listen on [SetEphemeralUDPPortRange](https://pkg.go.dev/github.com/pion/webrtc/v3#SettingEngine.SetEphemeralUDPPortRange)
* Set pre-defined ICE Cred [SetICECredentials](https://pkg.go.dev/github.com/pion/webrtc/v3#SettingEngine.SetICECredentials)

**Comment by lisay-yan** [comment]
@Sean-Der 

Would you like share any standard or information for why ICE is always required for WebRTC? Thanks so much.

**Comment by Sean-Der** [comment]
[RFC 8835](https://www.rfc-editor.org/rfc/rfc8835.html) is a good starting point. If you don't want ICE it is possible to use the parts of Pion independently

* pion/sdp (signaling)
* pion/rtp and pion/rtcp (media)
* pion/interceptor (congestion control and error correction)
* pion/srtp and pion/dtls (encryption)

```
ICE [[RFC8445](https://www.rfc-editor.org/rfc/rfc8835.html#RFC8445)] MUST be supported. The implementation MUST be a full ICE implementation, not ICE-Lite. A full ICE implementation allows interworking with both ICE and ICE-Lite implementations when they are deployed appropriately.
```

**Comment by lisay-yan** [comment]
@Sean-Der 

Thanks Sean. These words is under "[3.4. ](https://www.rfc-editor.org/rfc/rfc8835.html#section-3.4)[Middlebox-Related Functions](https://www.rfc-editor.org/rfc/rfc8835.html#name-middlebox-related-functions)"

ICE only is "MUST" for TURN or NAT (Middlebox-Related) cases.

**Comment by lisay-yan** [comment]
@Sean-Der 

Would you like accept contribution to disable ICE for no NAT cases?
It will be controllable by PeerConn config and by default off. 
The general design idea is to reuse ICE transport and disable stun steps. UDP conn is based on c line IP and m line port.

Thanks.
