### ISSUE TITLE
insertable-streams example gaps

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [pion/webrtc#2504]
Some questions:
1) the example shows only how to [transform](https://github.com/pion/webrtc/blob/master/examples/insertable-streams/main.go#L97-L99) sended stream frames in golang code, not so clear how to setup custom transformation routine on the reciver side;
2) also not so clear why the golang code has no any specific stuff to instruct the reciver that the sender is using insertable streams, means that code wich encrypts frames has the only difference (in comparison with others examples) in lines mentioned above.
@Sean-Der could you please comment on this?

**Comment by Sean-Der** [comment]
Hi @UladzimirTrehubenka 

1.) The transformation on the client side is [here](https://github.com/pion/webrtc/blob/master/examples/insertable-streams/jsfiddle/demo.js#L33-L37)

2.) I don't believe WebRTC has a mechanism for that unfortunately. Nothing in the protocol lets you say 'This frame was modified with insertable streams'. 

I am going to resolve but feel free to ask more questions here or on [Slack](https://pion.ly/slack) thanks!

**Comment by UladzimirTrehubenka** [comment]
JS code has
```
insertableStreams = transceiver.receiver.createEncodedVideoStreams()
const reader = insertableStreams.readable.getReader()
const writer = insertableStreams.writable.getWriter()
```
But golang implementation has no appropriate calls for obtain
reader/writer from receiver object in OnTrack callback function
```
rtcConn.OnTrack(func(track *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) {...})
```

**Comment by UladzimirTrehubenka** [comment]
[Insertable streams golang example, both audio/video publisher/subscriber](https://github.com/user-attachments/files/17840828/insertable_streams.txt)
Don't ask me how I came up with this specific video frame processing, it was hard...
