### ISSUE TITLE
Add `SetDTLSCustomCipherSuite` to `SettingEngine`

### ISSUE THREAD

**Issue by jikard0** [pion/webrtc#2512]
## Summary

Is it possible to disable encryption for DataChannel.

## Motivation

Need for testing purposes. Improve performance of applications with hundreds of webrtc datachannels when encryption is not needed, for example protected environments.

**Comment by Sean-Der** [comment]
This could be implemented easily today! If you don't mind making a PR, should only be 5 minutes of work :)

pion/dtls allows you to provide a custom cipher suite [here](https://github.com/pion/dtls/blob/master/config.go#L34-L37). I would add an option to Pion WebRTC's SettingEngine `SetDTLSCustomCipherSuite`. Then you can can do w/e you want encryption wise on both sides.

Unfortunately we will never be able to provide a 'disable encryption' out of the box. It wouldn't work against other WebRTC clients
