### ISSUE TITLE
webrtc.NewAPI is inherently confusing and frustrating

### ISSUE THREAD

**Issue by ForestJohnson** [pion/webrtc#2516]
I get it that Pion WebRTC is a highly technical thing and we are supposed to be "smart" and "Able to Read"  in order to use it...  But please hear me out. 

## Summary

I think `webrtc.NewAPI` docstring needs needs an **ALL CAPS BOLD WARNING TEXT**  and a link to an example of how to set it up to so that the resulting `webrtc.NewPeerConnection()`s will behave exactly the same as the ones you get from the default `webrtc.NewPeerConnection()`.

## Motivation

https://gophers.slack.com/archives/CAK2124AG/p1690162030755169

When you call `webrtc.NewAPI()` and then create a new `PeerConnection` with it, it behaves radically differently from the default  `PeerConnection` that you get from `webrtc.NewPeerConnection()`, and the developer has no way of being informed why this is the case or how to "fix" it. Specifically, they have no way of easily getting their `webrtc.NewAPI()` to reach "feature parity" with the default from the `webrtc` package, they have no easy way of being assured that their `PeerConnection` should work roughly the same as the "normal" one.

## Describe alternatives you've considered

I considered asking for `webrtc.NewAPI()` to come fully pre-configured by default.  But I thought there's gotta be a reason why it wasn't done that way, it probably would be even more confusing in a lot of cases.

## Additional context

Just look at the slack thread to see my despair live. 

EDIT:   OMFG :facepalm:   I can't believe I missed this;  the exact example I was looking for is... right where you would expect it, in the body of the `webrtc.NewPeerConnection()` function.

**Comment by edaniels** [comment]
Closing with merging of https://github.com/pion/webrtc/pull/2517
