### ISSUE TITLE
Rtp to webrtc example, missing audio track

### ISSUE THREAD

**Issue by 549869500** [pion/webrtc#2524]
The rtp to webrtc example lacks a audio track. 

I ran the rtp to webrtc example, which only has video tracks and no audio tracks. 

Please add the audio track function of rtp to webrtc, Thanks.

**Comment by Sean-Der** [comment]
Hi @549869500 

Would you mind explaining more. In the README it explains [here](https://github.com/pion/webrtc/blob/master/examples/rtp-to-webrtc/README.md?plain=1#L41) how to do audio instead.

**Comment by 549869500** [comment]
The link you sent will open a blank page
Now I'm doing the function of rtmp to webrtc, which has realized the function of rtmp Comparison of video converters to webrtc video. 
However, since rtp to webrtc does not realize the conversion of audio track, it is uncertain whether it can realize the function of transferring rtmp voice to webrtc. 
If Pion can implement the OPUS type audio in the RTMP stream and convert it to webRTC playback in the future?

**Comment by 549869500** [comment]
> Hi @549869500
> 
> Would you mind explaining more. In the README it explains [here](https://github.com/pion/webrtc/blob/master/examples/rtp-to-webrtc/README.md?plain=1#L41) how to do audio instead.



> Hi @549869500
> 
> Would you mind explaining more. In the README it explains [here](https://github.com/pion/webrtc/blob/master/examples/rtp-to-webrtc/README.md?plain=1#L41) how to do audio instead.

The link you sent will open a blank page
Now I'm doing the function of rtmp to webrtc, which has realized the function of rtmp Comparison of video converters to webrtc video.
However, since rtp to webrtc does not realize the conversion of audio track, it is uncertain whether it can realize the function of transferring rtmp voice to webrtc.
If Pion can implement the OPUS type audio in the RTMP stream and convert it to webRTC playback in the future?

**Comment by 549869500** [comment]
> Hi @549869500
> 
> Would you mind explaining more. In the README it explains [here](https://github.com/pion/webrtc/blob/master/examples/rtp-to-webrtc/README.md?plain=1#L41) how to do audio instead.

The link you sent will open a blank page
Now I'm doing the function of rtmp to webrtc, which has realized the function of rtmp Comparison of video converters to webrtc video.
However, since rtp to webrtc does not realize the conversion of audio track, it is uncertain whether it can realize the function of transferring rtmp voice to webrtc.
If Pion can implement the OPUS type audio in the RTMP stream and convert it to webRTC playback in the future?

**Comment by heshouyong** [comment]
Hi @549869500 
rtmp to webrtc 
https://github.com/pion/example-webrtc-applications/tree/master/rtmp-to-webrtc

**Comment by Sean-Der** [comment]
You can also do rtmp-to-webrtc using this example I made [here](https://github.com/Sean-Der/rtmp-to-webrtc)

For doing general protocol bridging [go2rtc](https://github.com/AlexxIT/go2rtc) is a really great project
