### ISSUE TITLE
Use pion as a WebRTC consumer

### ISSUE THREAD

**Issue by framesteel** [pion/webrtc#2532]
Let me preface this with the fact that I am very new to WebRTC.

With that being said, I would like to use Pion to consume an audio/video stream from a nest camera. I want to do additional analysis on the video stream, and store the video for later use.

https://developers.google.com/nest/device-access/api/camera-battery#access_a_live_stream

Reading the docs, it tells me the offer SDP generated must specify the opus audio codec, and a video format. However, I cannot figure out how to do this using Pion. Specifying audio/video codecs only seems possible through the media engine, but as far as I can tell this is only for defining what the server can produce, not what the client can consume. The createoffer function only offers a tiny set of options too.

Is this something that is possible with Pion? If so, can someone steer me in the right direction? If not, is there another library or tool that might suit my needs? Should I just use gstreamer?

**Comment by Sean-Der** [comment]
Hi @framesteel 

Yes this is totally possible. I have worked with two companies that are doing this today!

`MediaEngine` just defines what codecs you support. When you make an Offer (or Answer) only codecs in the MediaEngine will be included. By default Opus is enabled via [RegisterDefaultCodecs](https://github.com/pion/webrtc/blob/64533460747de610cd9e5076c0fdb5e94be51de3/mediaengine.go#L81)

I think Pion is the right tool for the job! I am heavily biased though :) 

If you have any further questions please ask away here or on [Slack](https://pion.ly/slack)
