### ISSUE TITLE
webrtc v3.2.15 has a breaking change

### ISSUE THREAD

**Issue by hansgylling** [pion/webrtc#2533]
### Your environment.
  - Version: v3.2.15
  - Browser: N/A
  - Other Information: See below for my suggested fix.

### What did you do?

I updated to the latest version of webrtc (v3.2.15) in our program, which uses the struct field webrtc.ICECandidateStats.NetworkType, and then tried to build it. There were build errors like this:

```
r.local.NetworkType.String undefined (type string has no field or method String)
```

### What did you expect?

No breaking changes in a patch release.

### What happened?

Version 3.2.15 of webrtc has a breaking change where the type of the struct field webrtc.ICECandidateStats.NetworkType has been changed from NetworkType to string.

The breaking change was made in this commit: https://github.com/pion/webrtc/commit/2926b99173b44266550855079501ae1cd7d89a92

The line that was changed in a breaking way can be viewed here: https://github.com/pion/webrtc/commit/2926b99173b44266550855079501ae1cd7d89a92#diff-9f6cddeabc26d57e3837fe66df90a6288f56e8a0e898cb6004d098da521583aeL1393

My understanding of how Go modules is supposed to work is that if the major version is 1 or higher and you want to do breaking changes, you need to increase the major version. It looks to me that webrtc v3.2.15 isn't following that contract.

### Discussion ###

If you want to change the type of the NetworkType field and follow the contract of Go modules, you need to do that in webrtc v4.0.0.

Since  RTCIceCandidateStats.networkType is removed from the latest version of the Identifiers for WebRTC's Statistics API specification, I guess it makes more sense to just remove the NetworkType field than change the type (unless you want to continue to support old specs). If you want to change the type or remove the struct field is up to you, but both choices are breaking changes.

### Suggested changes ###

My suggested fix is that you revert the breaking change in webrtc.ICECandidateStats and then retract version 3.2.15 in the go.mod file. https://go.dev/ref/mod#go-mod-file-retract

### References ###

Links to the RTCIceCandidateStats dictionary in the Identifiers for WebRTC's Statistics API specification.
- Latest version: https://www.w3.org/TR/webrtc-stats/#icecandidate-dict*
- First version where the networkType member was removed: https://www.w3.org/TR/2020/CR-webrtc-stats-20200114/#icecandidate-dict*
- Last version where the networkType member was present: https://www.w3.org/TR/2018/CR-webrtc-stats-20180703/#icecandidate-dict*

**Comment by Sean-Der** [comment]
Hey @hansgylling 

Totally agree. Would you mind making a PR for this? I can merge right now. I don't have access to a desktop though, just my phone.

I would like to see this fixed ASAP though! Before it effects others.

**Comment by hansgylling** [comment]
I suggested to add a retract directive in the go.mod file, but I see now that is supported from Go version 1.16 and the current Go version in the go.mod file is 1.13.

Do you want me to increase the Go version in the go.mod file or to skip the retract directive?

**Comment by Sean-Der** [comment]
@hansgylling I would skip the retract directive. Thanks for working on this!

**Comment by hansgylling** [comment]
OK, then I think I'm done. PR coming soon.

**Comment by hansgylling** [comment]
PR created in #2535.

I'm leaving work now and will only be able to view Github on my phone for a while.
