### ISSUE TITLE
cannot use &nopReplayDetector{} as replaydetector.ReplayDetector value

### ISSUE THREAD

**Issue by yangyile1990** [pion/webrtc#2544]
I'm use 
```
github.com/pion/webrtc/v3 v3.2.17
```

the bug is:

/Users/admin/Documents/work/go/pkg/mod/github.com/pion/srtp/v2@v2.0.16/option.go:37:11: cannot use &nopReplayDetector{} (value of type *nopReplayDetector) as replaydetector.ReplayDetector value in return statement: *nopReplayDetector does not implement replaydetector.ReplayDetector (wrong type for method Check)
		have Check(uint64) (func(), bool)
		want Check(uint64) (func() bool, bool)

after I execute the 
```
go get github.com/pion/srtp/v2@master
```
it's ok. and  the ok mod is:
```
github.com/pion/srtp/v2 v2.0.17-0.20230901060821-d22e8677f7e0
```

**Comment by hansgylling** [comment]
The build problem is because of a breaking change in the pion/transport package v2.2.2. I've filed a bug about that: https://github.com/pion/transport/issues/264

**Comment by yangyile1990** [comment]
OK.

**Comment by yangyile1990** [comment]
done

**Comment by Sean-Der** [comment]
Thanks for reporting this @yangyile1990 ot should be fixed now!

we are also adding tooling to ensure it doesn’t happen again
