### ISSUE TITLE
EOF on TrackRemote.Read

### ISSUE THREAD

**Issue by benyamin218118** [pion/webrtc#2580]
hello,
im randomly experiencing an issue
im using pion to create a conferencing app and i face EOF on TrackRemote.Read sometimes while the peerConnection is not disconnected and the app is still receiving the other tracks from the same peerConnection with no problem so only one track.Read returned EOF

can you help me with this please?

**Comment by Sean-Der** [comment]
Hopefully this works for you @benyamin218118!

If you are still having issues please re-open. I am also available on [Slack](https://pion.ly/slack) to debug

**Comment by benyamin218118** [comment]
hi @Sean-Der
im using `v3.2.12` version of pion webrtc
it happens sometimes when im testing ( not always but sometimes )
what do you mean by :
> Have you done a re-negotation/any other changes
i have renegotiations when a track is removed or added from the caller side

**Comment by Sean-Der** [comment]
Things are behaving as expected then! When the remote removes a track you will get a `EOF`

**Comment by benyamin218118** [comment]
thats the problem. remote didnt removed a track :/

**Comment by benyamin218118** [comment]
@Sean-Der any opinion??
