### ISSUE TITLE
Datachannel has a race in handleOpen

### ISSUE THREAD

**Issue by sukunrt** [pion/webrtc#2586]
### Your environment.
  - Version: v3.2.20
  - Other Information - triggered while working on libp2p-webrtc implementation: https://github.com/libp2p/go-libp2p/actions/runs/6283700827/job/17064424760?pr=2576

### What did you do?
The race is straightforward, the two fields onBufferedAmountLow and onBufferedAmountLowThreshold are protected by the mutex and should only be accessed with the lock held. 
https://github.com/pion/webrtc/blob/master/datachannel.go#L315

**Comment by Sean-Der** [comment]
Fixed by @sukunrt in https://github.com/pion/webrtc/pull/2587

thank you!
