### ISSUE TITLE
use of internal package github.com/pion/webrtc/v3/examples/internal/signal not allowed

### ISSUE THREAD

**Issue by Chuvvi** [pion/webrtc#2600]
### Your environment.
  - Version: v3.2.21

### What did you do?
I was trying to implement the "reflect" example and I came across this bug

**Comment by Sean-Der** [comment]
Hi @Chuvvi 

Sorry I didn't respond to this sooner. This is by design, `examples/internal` isn't a public API, so we put it inside the `internal` folder so users can't import it.

If you want to use that code you can copy it into your new project!

thanks for using Pion
