### ISSUE TITLE
onTrack accept a trackremote with no valid codec

### ISSUE THREAD

**Issue by vipcxj** [pion/webrtc#2610]
### Your environment.
  - Version: v4.0.0-beta.6
  - Browser: chrome 117.0.5938.150
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?
```go
		peer.OnTrack(func(tr *webrtc.TrackRemote, r *webrtc.RTPReceiver) {
			if tr.Codec().MimeType == "" {
				panic(errors.FatalError("This is impossible")) // trigger here.
			}
                }
```

### What did you expect?
ontrack return a track with valid codec or provide a listerner to get a track with valid codec

**Comment by Sean-Der** [comment]
Thank you for the report @vipcxj!

This has been solved by https://github.com/pion/webrtc/commit/6deb47d3bf148db556cf3df905f236770a15b24d

A PayloadType with value of 0 is valid, but we would improperly interpret that as unset. This is now fixed and has a test
