### ISSUE TITLE
"IVF signature mismatch" if fed with GStreamer VP8 stream 

### ISSUE THREAD

**Issue by neilyoung** [pion/webrtc#2622]
### Your environment.
  - Version: livekit-server, livekit-client
  - Browser: Chrome latest
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

See https://github.com/livekit/livekit-cli/issues/251

### What did you expect?

Should work with VP8 input as it works with H.264

### What happened?

I'm using livekit-server/livekit-cli and GStreamer. Publishing a H.264 stream into the room works fine, VP8 not. I suppose the a.m. and described error comes out of your code, since live-xxx relies on that.

As seen here

https://github.com/pion/webrtc/blob/eed2bb2d3b9f204f9de1cd7e1046ca5d652778d2/pkg/media/ivfreader/ivfreader.go#L25

and here

https://github.com/pion/webrtc/blob/eed2bb2d3b9f204f9de1cd7e1046ca5d652778d2/pkg/media/ivfreader/ivfreader.go#L140C25-L140C47

the code expects some head in the VP8 payload. I'm not sure how to produce that using GStreamer. Any hint?

**Comment by neilyoung** [comment]
The strange thing is: I can see the expected DKIF header, if I use an `udpsink`:

<img width="787" alt="image" src="https://github.com/pion/webrtc/assets/731020/bc4dedc3-8493-49d1-80fa-ae7183e5400b">

But not with a tcpserversink...

**Comment by Todilo** [comment]
Any progress on this. I face similar issue. I have tried two different vp9 encoded videos. One encoded myself using ffmpeg:
>ffmpeg -i file_example_MP4_640_3MG.mp4 -c:v libvpx -b:v 1M output.webm

and one from example online:
https://base-n.de/webm/VP9%20Sample.html

**Comment by neilyoung** [comment]
In my case it was sufficient to add the `avmux_ivf` element to the pipeline before feeding PION:

`... vp8enc deadline=1 ! avmux_ivf ...`

**Comment by Todilo** [comment]
Is this from gstreamer or where does that piping occur? I use the example "play-from-disk" which uses the ivfreader.NewWith which crashes

**Comment by neilyoung** [comment]
Yes. Gstreamer

**Comment by neilyoung** [comment]
That being said, this is not an issue anymore for me and I'm going to close that.
