### ISSUE TITLE
gomobile build broken

### ISSUE THREAD

**Issue by kevmo314** [pion/webrtc#2626]
### Your environment.
  - Version: *Release or SHA*
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

Running `gomobile bind .` no longer seems to work. `git bisect` reported this commit: https://github.com/pion/webrtc/commit/7edfb701e09e89258d4b3235cded99befc8058fd

I'm not actually sure why, perhaps it has to do with exposing an interface as an API? I will do some research and see if I can figure it out.

**Comment by suutaku** [comment]
maybe show more error message?

**Comment by Sean-Der** [comment]
Thanks for sharing how you fixed it @kevmo314! Would it be worth putting shims in a public repo, or do you think it’s better to do it per project?

I don’t think we should change pion/webrtc for this. Unless the changes are simple I don’t want to negatively impact others users not doing mobile.

**Comment by kevmo314** [comment]
> Thanks for sharing how you fixed it @kevmo314! Would it be worth putting shims in a public repo, or do you think it’s better to do it per project?
> 
> I don’t think we should change pion/webrtc for this. Unless the changes are simple I don’t want to negatively impact others users not doing mobile.

It is unfortunately quite hard to fix, so we likely can't fix it directly. I think the shims are actually better per project since you can add logic into the shim which is what I'm doing and that cleans up the calling site.

That being said probably some documentation or examples might be worthwhile.
