### ISSUE TITLE
Why SampleBuilder.buffer and SampleBuilder.preparedSamples so big

### ISSUE THREAD

**Issue by vipcxj** [pion/webrtc#2627]
https://github.com/pion/webrtc/blob/eed2bb2d3b9f204f9de1cd7e1046ca5d652778d2/pkg/media/samplebuilder/samplebuilder.go#L19

https://github.com/pion/webrtc/blob/eed2bb2d3b9f204f9de1cd7e1046ca5d652778d2/pkg/media/samplebuilder/samplebuilder.go#L20

It seems that a empty SampleBuilder cost about 1M

**Comment by Sean-Der** [comment]
Hi @vipcxj this has been fixed!

@thatsnotright refactored the JitterBuffer and moved it into the interceptor. It also dynamically grows so no more large allocations up front!

Thanks for using Pion. If you have feedback/ideas about other things we should fix I would love to hear.

**Comment by vipcxj** [comment]
@Sean-Der I'm currently using a custom SampleBuilder which is jech's implementation (include some bug fix), does that mean that's not necessary now?

**Comment by Sean-Der** [comment]
@vipcxj correct! If you are de-jittering RTP packets you can use [JitterBuffer](https://github.com/pion/interceptor/tree/master/pkg/jitterbuffer) directly.

We will continue to make the SampleBuilder simpler and make bug fixes. Would love your help testing and improving it!

@thatsnotright anything I am missing?
