### ISSUE TITLE
How to compile this project into a dynamic library for Android?

### ISSUE THREAD

**Issue by itpan8067** [pion/webrtc#2638]
How to compile this project into a dynamic library and then reference the dynamic library(.so) in Android JNI?

**Comment by Sean-Der** [comment]
Hi @itpan8067 see https://github.com/pion/example-webrtc-applications/tree/master/c-data-channels

That shows how to build a shared object and call in/out of Go code.

You can use that like any library on Android then

**Comment by Sean-Der** [comment]
If you have any other questions happy to help on here or [Slack](https://pion.ly/slack) thanks for using Pion!
