### ISSUE TITLE
Trickle ICE not working properly

### ISSUE THREAD

**Issue by hoainam10th123** [pion/webrtc#2678]
# Trickle ICE not working properly. 
I have registered for a few turn servers
Here's an example I used
```
relay1.expressturn.com:3478
Username: efBUE9E50T5TQBUF1U
Password: FWr3VMwpYCQ6nJud
```
But when testing on [trickle-ice](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)
It all shows error 701, I tried [openrelay](https://www.metered.ca/tools/openrelay/)
but they all don't work. Is Trickle ICE not running properly or is it because the turn server I registered with is not working well

**Comment by Sean-Der** [comment]
Hi @hoainam10th123 

Sorry your TURN servers aren't working. You can try to deploy [pion/turn](https://github.com/pion/turn) yourself and have a working setup.

I think you will have a hard time finding free and dependable TURN servers, someone has to pay for the bandwidth and CPU you are expending!
