### ISSUE TITLE
OnTrack will not be fired

### ISSUE THREAD

**Issue by yangxingyu** [pion/webrtc#2680]
### Your environment.
  - Version: *v3.2.24 v3.2.28 v4.0.0.beta9*
  - Browser: *Chrome 122.0.6261.70 x64*
  - Other Information - *os: windows 10*

### What did you do?

build example-webrtc-applications/sfu-ws and run demo on Chrome 122.0.6261.70

### What did you expect?
OnTrack fired

### What happened?
i got this error "Incoming unhandled RTP ssrc(XXXXXXX), OnTrack will not be fired. incoming SSRC failed Simulcast probing" with version 3.x
i tried v4.0.0.beta9 then i got  "Incoming unhandled RTP ssrc(XXXXXXX), OnTrack will not be fired, EOF"

**Comment by Gbcards** [comment]
I have the same error ;(, the offer is being cycled

**Comment by macoeshka** [comment]
Same problem.

**Comment by shsma** [comment]
Same issue here.

I've got this error `Incoming unhandled RTP ssrc(xxxxxxx), OnTrack will not be fired. mid RTP Extensions required for Simulcast` with version 3.x.

Then I tried to update to version 4.x and now I'm getting
`Incoming unhandled RTP ssrc(xxxxxxxxx), OnTrack will not be fired. EOF`

**Comment by shsma** [comment]
I added a server per protocol and it fixed the problem in the backend. Now the frontend is struggeling with getting the trackID.
```
	webrtcCfg := webrtc.Configuration{
		SDPSemantics: webrtc.SDPSemanticsUnifiedPlanWithFallback,
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{
					"stun:stun.l.google.com:19302",
				},
			},
			{
				URLs: []string{
					"stun:stun.l.google.com:443?transport=udp",
					"stun:stun.l.google.com:443?transport=tcp",
				},
			},
		}}
```

**Comment by Sean-Der** [comment]
I will investigate tonight. Chrome has changed behavior in the latest release.

Pion might have an existing bug that is getting exposed. I will share more when I have answers

**Comment by shsma** [comment]
True that. I started seeing this problem after updating chrome.

**Comment by yangxingyu** [comment]
This is a great project.
I have been studying the code recently and I appreciate your work.

**Comment by shsma** [comment]
@Sean-Der Any updates!

**Comment by Sean-Der** [comment]
This has been fixed with https://github.com/pion/webrtc/commit/92df4bf0ec6d401827a6dbaa5b8be6d4d4a6a3d3

Please update to v4.0.0-beta.15 or v3.2.32. A workaround exists and was added to Pion. See https://issues.chromium.org/u/1/issues/328522463?pli=1

**Comment by yangxingyu** [comment]
Thanks very much.
