### ISSUE TITLE
rtp-to-webrtc H264 via gstreamer issue

### ISSUE THREAD

**Issue by Sean-Zeo** [pion/webrtc#2703]
Hi, was h264 ever fixed? I am trying to send a nvh264enc stream of desktop.
Thanks!

**Comment by Sean-Der** [comment]
Hey @Sean-Zeo 

H264 has no issues that I am aware of! Make sure you have properly configured your encoder. Try [gstreamer-send](https://github.com/pion/example-webrtc-applications/tree/master/gstreamer-send) it's a good place to start.

**Comment by Sean-Zeo** [comment]
Hi, when using a commandline similar to;
`gst-launch-1.0 d3d11screencapturesrc ! videoconvert ! queue max-size-bytes=0 max-size-time=0 ! x264enc speed-preset=ultrafast tune=zerolatency bitrate=5000 ! video/x-h264, framerate=(fraction)60/1, stream-format=byte-stream ! rtph264pay mtu=1200 ! udpsink host=127.0.0.1 port=5004`
It takes a significantly long time for video to appear, sometimes not at all.

**Comment by Sean-Der** [comment]
Can you share the command line you are using?

**Comment by Sean-Zeo** [comment]
Hi, apologies, the command is the one I'm using above.
