### ISSUE TITLE
Testing: Recreate TestRTCPeerConnection_OnDataChannelSync

### ISSUE THREAD

**Issue by backkem** [pion/webrtc#271]
Recreate `TestRTCPeerConnection_OnDataChannelSync` which was lost in 09b0c78d3d27dee5ac19b2b974814301f5ba215b.

**Comment by Sean-Der** [comment]
The purpose of this test is to make sure nothing is lost when setting up a DataChannel and it's callbacks.
￼￼￼￼￼
We need to assert that the user has a chance to add the OnMessage callback before any messages are received.
