### ISSUE TITLE
Specific port to automatically open?

### ISSUE THREAD

**Issue by ZeoWorks** [pion/webrtc#2753]
Hi, for cloud virtual machines, sometimes we're behind only a select amount of ports.
Is it possible to have webrtc to open only on a specific port?

**Comment by Sean-Der** [comment]
Hi @ZeoWorks 

You probably want https://pkg.go.dev/github.com/pion/webrtc/v4#SettingEngine.SetEphemeralUDPPortRange

also check out https://github.com/pion/webrtc/tree/master/examples/ice-single-port

Best of luck on your project! Happy to answer more questions on here or [Slack](pion.ly/slack)
