### ISSUE TITLE
Chrome: Warn: Discard message from (x.x.x.x), integrity check failed

### ISSUE THREAD

**Issue by BertoldVdb** [pion/webrtc#2776]
**I am not sure this is a Pion bug, I don't know enought about WebRTC internals to tell**

### Your environment.
  - Version: v4.0.0-beta.19  
  - Browser: Google-Chrome on Linux 125.0.6422.112 (other versions also trigger issue, Firefox, Safari, iPhone, Android works)

### What did you do?
I have a WebRTC application (browser produces offer, Pion answers) that generally works well. However when talking to a Chrome peer the connection sometimes fails to establish. I have traced this to verifying the integrity of the initial ICE probing STUN packets. We send the STUN Request to chrome and fail to validate the response.

Pion properly decodes the RemotePwd/Ufrag and other info, and tries to verify the signature. The expected signature and buffer to calculate it on match the packet as decoded by wireshark. Yet the calculated signature does not match. 

Verifying incoming requests from Chrome with our LocalPwd works, and the answer is accepted according to chrome webrtc stats. I can provided packet traces if this is useful.

This is the function that is failing: https://github.com/pion/stun/blob/master/integrity.go#L95 . To verify I have removed the check by always returning nil. The connection then establishes 100% of the time (did around 1000 runs).

I have tried to invert the flow where Pion makes the offer and Chrome answers. This also works 100% of the time.

I think it is possible this is a bug in Chrome, unless the Pion answer or ICE candidates can change chromes idea of the RemotePwd?

### What did you expect?
Connection establishes properly every time, no integrity check errors.

### What happened?
See above

**Comment by Sean-Der** [comment]
Hi @BertoldVdb 

Sorry I missed this. Did you make any progress on this. I would love to help you debug if it's still a problem.

thanks
