### ISSUE TITLE
Can receiver check whether the buffer is full？

### ISSUE THREAD

**Issue by bug45** [pion/webrtc#2787]
thanks for your excellent work！May I ask if Pion can obtain the buffer occupancy situation on the receiver side during WebRTC communication? I encountered an issue where the frame content was incomplete, and I want to confirm if it's caused by packet loss due to a full buffer

**Comment by Sean-Der** [comment]
Sorry for the slow response @bug45 

A sender doesn’t have that information. You do have access to timing/loss information on packets sent. You can use that to detect loss or slow packets. Look at receiver reports and TWCC feedback. 

Check out this chapter in WebRTC for the Curious it should be helpful.  https://webrtcforthecurious.com/docs/06-media-communication/

**Comment by bug45** [comment]
Thanks for your reply! I will check it




咸鱼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pion/webrtc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月4日(星期天) 凌晨1:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pion/webrtc] Can receiver check whether the buffer is full？ (Issue #2787)





 
Sorry for the slow response @bug45
 
A sender doesn’t have that information. You do have access to timing/loss information on packets sent. You can use that to detect loss or slow packets. Look at receiver reports and TWCC feedback.
 
Check out this chapter in WebRTC for the Curious it should be helpful.  https://webrtcforthecurious.com/docs/06-media-communication/
