### ISSUE TITLE
 Issues with Audio Transmission via PortAudio and OPUS Encoding

### ISSUE THREAD

**Issue by Josepavese** [pion/webrtc#2789]
Hello,
I am facing issues with a Go-based WebRTC application utilizing the GO/PION library. The application is designed to capture a video stream and make it available over a WebRTC connection, while also receiving audio via WebRTC and playing it through the system speakers. I am currently implementing the final module, which involves sending audio to the WebRTC connection. The system should capture the microphone stream using github.com/gordonklaus/portaudio, encode it in OPUS using gopkg.in/hraban/opus.v2, and write it to the output track added to the WebRTC connection.

**Problem**
The audio is not being heard on the other end of the WebRTC connection, despite the audio track being received correctly. On the receiving end (using JavaScript and HTML), there is mostly silence with occasional brief noises occurring at regular intervals. These noises do not appear when the connection is not established, indicating that data is being sent but may be improperly encoded or not following an appropriate bitrate.

**Environment**
- Golang version: 1.22.4
- PION/webrtc version: v4.0.0
- PortAudio version: Latest
- OPUS version: v2
- Operating System: Ubuntu 22.04

**Code Excerpt**
`import (
	"github.com/gordonklaus/portaudio"
	"github.com/hajimehoshi/oto"
	"github.com/pion/webrtc/v4"
	"github.com/pion/webrtc/v4/pkg/media"
	"gopkg.in/hraban/opus.v2"
	"github.com/pion/rtp"
	"log"
	"runtime"
	"time")`
`

	func main() {
		runtime.GOMAXPROCS(runtime.NumCPU()) // Utilize all available CPU cores

		outboundAudioTrack, err := webrtc.NewTrackLocalStaticRTP(webrtc.RTPCodecCapability{
			MimeType: webrtc.MimeTypeOpus,
		}, "audio", "pion")
		if err != nil {
			log.Fatalf("Failed to create audio track: %s", err)
		}

		// Initialize PortAudio
		if err := portaudio.Initialize(); err != nil {
			log.Fatalf("Failed to initialize PortAudio: %s", err)
		}
		defer portaudio.Terminate()

		go StartMicrophoneStream(outboundAudioTrack)
	}

	func StartMicrophoneStream(outboundAudioTrack *webrtc.TrackLocalStaticRTP) {
		// Open default microphone device
		stream, err := portaudio.OpenDefaultStream(1, 0, sampleRate, frameSize, readAudio)
		if err != nil {
			log.Fatalf("Failed to open default stream: %s", err)
		}
		defer stream.Close()

		// Start the audio stream
		if err := stream.Start(); err != nil {
			log.Fatalf("Failed to start stream: %s", err)
		}
		defer stream.Stop()

		log.Println("Microphone streaming started")

		// Keep the stream open
		select {}
	}

	func readAudio(in []int16) {
		// Log input buffer
		// log.Printf("Captured audio data: %v", inputBuffer)

		// Create Opus encoder
		encoder, err := opus.NewEncoder(sampleRate, channels, opus.AppVoIP)
		if err != nil {
			log.Fatalf("Failed to create Opus encoder: %s", err)
		}

		// Encode PCM to Opus
		packet := make([]byte, 4000) // Adjust size as needed
		n, err := encoder.Encode(in, packet)
		if err != nil {
			log.Printf("Error encoding PCM to Opus: %s", err)
			return
		}

		// Log encoded packet size
		// log.Printf("Encoded audio packet size: %d", n)

		// Create RTP packet
		rtpPacket := &rtp.Packet{
			Header: rtp.Header{
				Version:        2,
				PayloadType:    111,                           // Dynamic payload type for Opus
				SequenceNumber: uint16(time.Now().UnixNano()), // Use a more appropriate sequence number generator
				Timestamp:      uint32(time.Now().UnixNano() / int64(time.Millisecond)),
				SSRC:           12345,
			},
			Payload: packet[:n],
		}

		// Marshal RTP packet to bytes
		rawPacket, err := rtpPacket.Marshal()
		if err != nil
`

**Comment by Sean-Der** [comment]
Hi @Josepavese 

Sorry I didn't help with this sooner, time really got away from me. Did you get this working?

If you have code on GitHub I would love to help debug! When you get it working I think this would be great for https://github.com/pion/example-webrtc-applications

**Comment by Sean-Der** [comment]
I am going to close for now (since it isn't a Pion bug) but I would love to help with this if you are still on it.

thanks
