### ISSUE TITLE
Is there a example to forward the RTSP stream of the ip camera to the Pion node

### ISSUE THREAD

**Issue by autoexpect** [pion/webrtc#2796]
## Summary

Forward the RTSP stream of the ip camera to the Pion node.

## Motivation

I have an IPC whose SDP in RTSP does not meet the requirements of WebRTC. I am trying to convert the SDP, but all my attempts have failed.

**Comment by Sean-Der** [comment]
Hi @autoexpect 

https://github.com/AlexxIT/go2rtc is the easiest way to do this. You can also build this yourself, but will take more time! Happy to explain how/help you write anything

Help is also available in [Slack][https://pion.ly/slack)

**Comment by autoexpect** [comment]
Thanks! I'll give it a try.
