### ISSUE TITLE
Undefined iteration order when parsing SDP RID ids

### ISSUE THREAD

**Issue by j1elo** [pion/webrtc#2838]
Hi,

I've been observing a strange behavior in my WebRTC application, due to the fact that some times the simulcast layers are provided by Pion in a different order than the one in SDP messages.

After quite a bunch of debugging and printfs, ended up finding this line:

https://github.com/pion/webrtc/blob/2364173cedda65030a8a5f2110416387deb0083e/sdp.go#L197-L207

`getRids` returned a `map[string]*simulcastRid`, and then it gets traversed so the RIDs get appended into `simulcastTrack.rids`.

However, a big problem that I think is what I'm observing, is that Go does not guarantee any ordering on map traversal:

> 3. The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next.

[Source](https://go.dev/ref/spec#For_range)

**Concrete example**

This is the relevant part of an SDP Offer that is received:

```
a=rid:0 send
a=rid:1 send
a=rid:2 send
a=simulcast:send 0;1;2
a=sendonly
```

If then we add a printf of `incomingTrack.rids` right before this line: https://github.com/pion/webrtc/blob/v3.2.50/peerconnection.go#L1414
What *some* times we get is this: `[1 2 0]`.

So I believe that to respect the same ordering as given in the SDP's `a=simulcast` line, a different method of construction should be used that avoids unspecified orderings.

What do you think?

**Comment by Sean-Der** [comment]
@j1elo That definitely is broken! You interested in taking this on or want me to take it?

thanks for reporting :)

**Comment by j1elo** [comment]
I'm fine doing it, just wanted to first confirm that you also see a problem in that code.
So, I'll shortly put a PR and we can review my approach to solving it.
