### ISSUE TITLE
CI doesn't run tests on stable `v3` branch

### ISSUE THREAD

**Issue by j1elo** [pion/webrtc#2841]
## Summary

This is an improvement idea for the CI systems of the project. Arguably it could also be considered a bug in CI.

One can see in the commits view of the [`master` branch](https://github.com/pion/webrtc/commits/master/) that each one passes through currently 10 or 11 tests (not sure of why the difference, but it doesn't matter for this issue report).

However, commits on the [`v3` branch](https://github.com/pion/webrtc/commits/v3) do not pass any testing at all (or at least not reported by GitHub in the commits page).

I believe this should be considered as a mistake and "ci bug", more than a mere improvement chance; tests should also be passed on commits in other branches, even more so in the stable branches than in current development ones.

## Motivation

I had been using tag `v3.2.40` i.e. commit `7cad104` (*Update module github.com/pion/ice/v2 to v2.3.24*), and was very confused to see that the tests didn't pass with `go test -v -count=1 .` due to some failures in testing RTX stuff.

Then after inspecting the history I saw that the next commit was `1778f7f` (*Fix tests for simulcast rtx on v3*) and realized all this about missing tests.

On [this page](https://github.com/pion/webrtc/commits/v3?after=2364173cedda65030a8a5f2110416387deb0083e+34) of the commits page we can see how up to the point where `v3` was created at `ea23dec` (*Update module transport, srtp, ice and turn*) all commits had 10/11 tests, then on the next one they had no tests.

## Describe alternatives you've considered

I believe that tests should also run on the `v3` branch. In fact tests should run *especially* in the branches which are considered stable, and their tagged commits, which hold the final releases that end users will receive.

**Comment by Sean-Der** [comment]
Fixed! Thanks for filing this @j1elo :)
