### ISSUE TITLE
I don't know why my project warn "undefined: webrtc (typecheck)" and I don't know how to solve.

### ISSUE THREAD

**Issue by yangyile1990** [pion/webrtc#2866]
```
admin@lele-de-MacBook-Pro uvdemo % golangci-lint run
```

main_webrtc/pion_webrtc_demo0/main.go:124:51: undefined: webrtc (typecheck)
func newWebrtcSessionDescription(sdpInput string) webrtc.SessionDescription {
                                                  ^
main_webrtc/pion_webrtc_demo0/main.go:58:15: undefined: webrtc (typecheck)
        conn, err := webrtc.NewPeerConnection(webrtc.Configuration{
                     ^
main_webrtc/pion_webrtc_demo0/main.go:59:17: undefined: webrtc (typecheck)
                ICEServers: []webrtc.ICEServer{
                              ^
```
admin@lele-de-MacBook-Pro uvdemo % go get -u github.com/pion/webrtc/v3
```

go: github.com/gortc/stun@v1.23.0: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/gortc/stun
        trying github.com/gortc/stun@v1.22.2
go: github.com/pion/stun@v1.23.0: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.22.2
go: github.com/gortc/stun@v1.22.2: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/gortc/stun
        trying github.com/gortc/stun@v1.22.1
go: github.com/pion/stun@v1.22.2: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.22.1
go: github.com/gortc/stun@v1.22.1: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/gortc/stun
        trying github.com/gortc/stun@v1.22.0
go: github.com/pion/stun@v1.22.1: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.22.0
go: github.com/gortc/stun@v1.22.0: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/gortc/stun
        trying github.com/gortc/stun@v1.21.1
go: github.com/pion/stun@v1.22.0: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.21.1
go: github.com/gortc/stun@v1.21.1: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/gortc/stun
        trying github.com/gortc/stun@v1.21.0
go: github.com/pion/stun@v1.21.1: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.21.0
go: github.com/gortc/stun@v1.21.0: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/gortc/stun
        restoring github.com/gortc/stun@v1.20.0
go: github.com/pion/stun@v1.21.0: parsing go.mod:
        module declares its path as: gortc.io/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.20.0
go: github.com/pion/stun@v1.20.0: parsing go.mod:
        module declares its path as: github.com/gortc/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.19.0
go: github.com/pion/stun@v1.19.0: parsing go.mod:
        module declares its path as: github.com/gortc/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.18.5
go: github.com/pion/stun@v1.18.5: parsing go.mod:
        module declares its path as: github.com/gortc/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.18.4
go: github.com/pion/stun@v1.18.4: parsing go.mod:
        module declares its path as: github.com/gortc/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.18.3
go: github.com/pion/stun@v1.18.3: parsing go.mod:
        module declares its path as: github.com/gortc/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.18.2
go: github.com/pion/stun@v1.18.2: parsing go.mod:
        module declares its path as: github.com/gortc/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.18.1
go: github.com/pion/stun@v1.18.1: parsing go.mod:
        module declares its path as: github.com/gortc/stun
                but was required as: github.com/pion/stun
        trying github.com/pion/stun@v1.18.0
go: github.com/pion/stun@v1.18.0: parsing go.mod:
        module declares its path as: github.com/gortc/stun
                but was required as: github.com/pion/stun
        restoring github.com/pion/stun@v1.17.3

**Comment by Sean-Der** [comment]
Hi @yangyile1990 

Can you share some code? My guess is your import statement or `go.mod` is incorrect
