### ISSUE TITLE
Release v3.3.0

### ISSUE THREAD

**Issue by sukunrt** [pion/webrtc#2873]
I've created a draft release v3.3.0 with the `OnClose` callback on SCTP implemented by this PR: https://github.com/pion/webrtc/pull/2861

@edaniels @Sean-Der Should I go ahead and publish it?

**Comment by Sean-Der** [comment]
@sukunrt go for it! Feel free to publish patch releases at anytime

**Comment by edaniels** [comment]
You're asking the guy who never asks for permission :). Of course haha

**Comment by sukunrt** [comment]
Thanks @edaniels @Sean-Der. I've published [v3.3.0](https://github.com/pion/webrtc/releases/tag/v3.3.0)
