### ISSUE TITLE
Help! cannot use pion in delivering audio

### ISSUE THREAD

**Issue by Eggrolling-hu** [pion/webrtc#2883]
### Code
package main

import (
	"flag"
	"fmt"
	"log"
	"regexp"
	"strconv"
	"sync"
	"time"

	"github.com/gordonklaus/portaudio"
	"github.com/hraban/opus"
	"github.com/pion/example-webrtc-applications/v3/sip-to-webrtc/softphone"
	"github.com/pion/rtp"
	"github.com/pion/sdp/v2"
	"github.com/pion/webrtc/v3"
	"github.com/pion/webrtc/v3/pkg/media/oggwriter"
)

var (
	username  = flag.String("username", "1008", "Extension you wish to register as")
	password  = flag.String("password", "1234", "Password for the extension you wish to register as")
	extension = flag.String("extension", "1000", "Extension you wish to call")
	host      = flag.String("host", "192.168.0.106", "Host that websocket is available on")
	port      = flag.String("port", "5066", "Port that websocket is available on")
)

var (
	audioDataFromMic     = make([][]byte, 0)
	dataMutex            sync.Mutex
	oggFile              *oggwriter.OggWriter
	encoder              *opus.Encoder
	gotAnswer            = false
	senderSSRC           uint32
	senderTimestamp      uint32
	senderSequenceNumber uint16
)

func main() {
	flag.Parse()

	if *host == "" || *port == "" || *password == "" {
		panic("-host -port and -password are required")
	}

	conn := softphone.NewSoftPhone(softphone.SIPInfoResponse{
		Username:        *username,
		AuthorizationID: *username,
		Password:        *password,
		Domain:          *host,
		Transport:       "ws",
		OutboundProxy:   *host + ":" + *port,
	})

	pc, err := webrtc.NewPeerConnection(webrtc.Configuration{})
	if err != nil {
		panic(err)
	}

	// create echo audio back to the caller
	// micTrack, err := webrtc.NewTrackLocalStaticSample(
	// 	webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeOpus}, "audio", "pion")

	micTrack, err := webrtc.NewTrackLocalStaticRTP(
		webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeOpus}, "audio", "pion")

	if err != nil {
		panic(err)
	}

	// log the echo track's codec
	fmt.Printf("Echo track codec: %s\n", micTrack.Codec().MimeType)

	if _, err = pc.AddTrack(micTrack); err != nil {
		panic(err)
	}

	// Create an Opus encoder
	encoder, err = opus.NewEncoder(48000, 1, opus.AppVoIP)
	if err != nil {
		log.Fatalf("Failed to create Opus encoder: %v", err)
	}

	// Create an Ogg file to save the received audio
	oggFile, err = oggwriter.New("output.ogg", 48000, 1)
	if err != nil {
		panic(err)
	}

	// Initialize PortAudio
	portaudio.Initialize()
	defer portaudio.Terminate()
	stream, err := portaudio.OpenDefaultStream(1, 0, 48000, 960, micCallback)

	if err != nil {
		log.Fatalf("Failed to open PortAudio stream: %v", err)
	}
	defer stream.Close()
	defer stream.Stop()

	pc.OnICEConnectionStateChange(func(connectionState webrtc.ICEConnectionState) {
		fmt.Printf("Connection State has changed %s \n", connectionState.String())
	})

	pc.OnTrack(func(track *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) {
		fmt.Println("Got Opus track, saving to disk as output.ogg")

		for {
			rtpPacket, _, readErr := track.ReadRTP()
			if readErr != nil {
				panic(readErr)
			}

			_ = rtpPacket

		}
	})

	// 强制使用 Opus 编解码器
	for _, transceiver := range pc.GetTransceivers() {
		if transceiver.Mid() == "0" || transceiver.Mid() == "1" {
			codecParams := []webrtc.RTPCodecParameters{
				{
					RTPCodecCapability: webrtc.RTPCodecCapability{
						MimeType: webrtc.MimeTypeOpus,
						Channels: 1,
					},
					PayloadType: 111,
				},
			}
			if err := transceiver.SetCodecPreferences(codecParams); err != nil {
				panic(err)
			}
		}
	}

	offer, err := pc.CreateOffer(nil)
	if err != nil {
		panic(err)
	}

	fmt.Println("Generated SDP Offer:", offer.SDP)
	re := regexp.MustCompile(`a=ssrc:(\d+)`)
	matches := re.FindStringSubmatch(offer.SDP)
	if len(matches) > 1 {
		ssrc, err := strconv.ParseUint(matches[1], 10, 32)
		if err != nil {
			fmt.Println("Error converting SSRC:", err)
			return
		}
		senderSSRC = uint32(ssrc)
		fmt.Printf("Found SSRC: %d\n", senderSSRC)
	} else {
		fmt.Println("No SSRC found in SDP")
	}

	if err := pc.SetLocalDescription(offer); err != nil {
		panic(err)
	}

	conn.OnOK(func(okBody string) {
		if gotAnswer {
			return
		}
		gotAnswer = true

		// Start the PortAudio stream
		if err := stream.Start(); err != nil {
			log.Fatalf("Failed to start PortAudio stream: %v", err)
		}

		// log the answer
		fmt.Printf("Answer from FreeSWITCH: %s\n", okBody)

		okBody += "a=mid:0\r\n"
		if err := pc.SetRemoteDescription(webrtc.SessionDescription{Type: webrtc.SDPTypeAnswer, SDP: okBody}); err != nil {
			panic(err)
		}
	})

	conn.Invite(*extension, rewriteSDP(offer.SDP))

	// Create a ticker to send audio samples
	go func() {
		ticker := time.NewTicker(time.Millisecond * 20)
		defer ticker.Stop()

		initTimestamp := false

		for {
			<-ticker.C

			// 如果没有收到应答，不发送音频
			if !gotAnswer {
				continue
			}

			if !initTimestamp {
				senderTimestamp = uint32(time.Now().UnixNano() / 1000)
				initTimestamp = true
			}

			dataMutex.Lock()
			if len(audioDataFromMic) == 0 {
				dataMutex.Unlock()
				continue
			}
			payload := audioDataFromMic[0]
			audioDataFromMic = audioDataFromMic[1:]
			dataMutex.Unlock()

			rtpPacket := &rtp.Packet{
				Header: rtp.Header{
					Version:        2,
					PayloadOffset:  12,
					SequenceNumber: senderSequenceNumber,
					Timestamp:      senderTimestamp,
					SSRC:           senderSSRC,
				},
				Payload: payload,
			}

			if readErr := oggFile.WriteRTP(rtpPacket); readErr != nil {
				panic(readErr)
			}

			err := micTrack.WriteRTP(rtpPacket)

			// 创建并发送音频样本
			// err := micTrack.WriteSample(media.Sample{
			// 	Data:     payload,
			// 	Duration: time.Millisecond * 20,
			// })

			if err != nil {
				panic(err)
			}

			senderTimestamp += 960
			senderSequenceNumber++
		}
	}()

	select {}
}

// Apply the following transformations for FreeSWITCH
// * Add fake srflx candidate to each media section
// * Add msid to each media section
// * Make bundle first attribute at session level.
func rewriteSDP(in string) string {
	parsed := &sdp.SessionDescription{}
	if err := parsed.Unmarshal([]byte(in)); err != nil {
		panic(err)
	}

	// Reverse global attributes
	for i, j := 0, len(parsed.Attributes)-1; i < j; i, j = i+1, j-1 {
		parsed.Attributes[i], parsed.Attributes[j] = parsed.Attributes[j], parsed.Attributes[i]
	}

	// Remove all extmap lines to disable RTP header extensions
	for _, media := range parsed.MediaDescriptions {
		var newAttributes []sdp.Attribute
		for _, attr := range media.Attributes {
			if attr.Key != "extmap" {
				newAttributes = append(newAttributes, attr)
			}
		}
		media.Attributes = newAttributes
	}

	parsed.MediaDescriptions[0].Attributes = append(parsed.MediaDescriptions[0].Attributes, sdp.Attribute{
		Key:   "candidate",
		Value: "79019993 1 udp 1686052607 1.1.1.1 9 typ srflx",
	})

	out, err := parsed.Marshal()
	if err != nil {
		panic(err)
	}

	return string(out)
}

func micCallback(in []int16) {
	dataMutex.Lock()
	defer dataMutex.Unlock()

	encodedData := make([]byte, 4000)
	n, err := encoder.Encode(in, encodedData)
	if err != nil {
		fmt.Printf("Failed to encode to Opus: %v\n", err)
		return
	}

	payload := encodedData[:n]

	audioDataFromMic = append(audioDataFromMic, payload)
}

### What did you expect?
can anyone give me some suggestion about how to solve it
### What happened?
I want use pion to build a sip phone. but it cannot deliver the audio. output.ogg is working well, so hardware is Ok.

**Comment by Sean-Der** [comment]
Hi @Eggrolling-hu 

Were you able to make this work? If not I would love to help!

Sorry for the delay. I am also available on [Slack](https://pion.ly/slack)

**Comment by Eggrolling-hu** [comment]
Thank you so much for your kindness. I just use the PJSIP.
