### ISSUE TITLE
who can help me create connection

### ISSUE THREAD

**Issue by qidailove** [pion/webrtc#2886]
I established two peer-to-peer connections in the same program and saw that candidate information was added to each other, but the callback function for the connection status has not been triggered yet

**Comment by Sean-Der** [comment]
Hey @qidailove 

I would check out the examples [pion-to-pion](https://github.com/pion/webrtc/tree/master/examples/pion-to-pion) I think is what you want.

If you have more questions I am faster to respond on [Slack](https://pion.ly/slack), thanks for using Pion!
