### ISSUE TITLE
How to solve this issue?

### ISSUE THREAD

**Issue by udhayNuk** [pion/webrtc#2902]
root@user-Standard-PC-i440FX-PIIX-1996:/home/user/P2PCAM/turnsetup/turn# ./simple-turn-linux-amd64 
2024/09/10 10:55:05 unable to handle SEND-INDICATION from 103.183.46.180:55183: Unable to handle send-indication, no permission added: 192.168.6.112:37234
Packet unhandled in relay src 59.92.235.60:1163 
Packet unhandled in relay src 59.92.235.60:1163 
Packet unhandled in relay src 59.92.235.60:1163 
Packet unhandled in relay src 59.92.235.60:1163 
Packet unhandled in relay src 59.92.235.60:1163 
Packet unhandled in relay src 59.92.235.60:1163 
Packet unhandled in relay src 59.92.235.60:1163 
Packet unhandled in relay src 59.92.235.60:1163 
Packet unhandled in relay src 59.92.235.60:1163

**Comment by Sean-Der** [comment]
Hey @udhayNuk sorry I didn't respond sooner.

Are you running Pion on a i440FX? That is really cool if you are!

Can you share more about your setup. Are you signaling candidates between both hosts?

Hopefully you figured the problem out. If not I am available here to answer questions or or [Slack](https://pion.ly/slack)

thanks for using Pion :)
