### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by Kesha005** [pion/webrtc#2908]
does anyone have a pdf docs or website that can provide good information about this package

**Comment by Sean-Der** [comment]
Hey @Kesha005 

I would recommend starting with the [examples directory](https://github.com/pion/webrtc/tree/master/examples) those are a good start to common projects.

For more knowledge on how WebRTC itself works check out https://webrtcforthecurious.com

If you still need help I am always available on [Slack](https://pion.ly/slack) to answer questions!

Best of luck with your project :)
