### ISSUE TITLE
"short buffer" error when the incoming RTP has 1460 payload length.

### ISSUE THREAD

**Issue by braveyao** [pion/webrtc#2927]
Hi,

I'm working on Livekit to bridge H264 stream into a conference room and noticed some interesting situations in webrtc.

The packages involved are:
- livekit/server-sdk-go v2.1.1, pion/webrtc v3.2.38
- livekit/livekit v1.6.2, pion/webrtc v3.2.40, pion/transport v2.2.5

I noticed that when I feed the H264 stream from a MP4 file to livekit, FFmpeg and GStreamer do the packetizing differently. 
- FFmpeg intends to send packets with payload size as 1460.
- GStreamer on the other hand will keep the payload size below MTU, i.e. 1388 at most.
As result, the test with GStreamer works as expected, but fails with FFmpeg as no packets delivered to livekit SFU, with the below error logs
```
2024-10-11T14:17:49.467-0700    ERROR   livekit.transport.pion.mux      mux/mux.go:117  mux: failed to read from packetio.Buffer short buffer%!(EXTRA string=bufferSize:, int=1460, string=readSize, int=1460)  {"room": "my-first-room", "roomID": "RM_pebRMUdCTAar", "participant": "participant_demo_bypass", "pID": "PA_HzMSEx56hE6F", "remote": false, "transport": "PUBLISHER"}
github.com/pion/webrtc/v3/internal/mux.(*Mux).readLoop
```

So I added some logs at both sending and receiving side to see what's going on.
At sending side, [server-sdk-go>localtrack.go#WriteRTP()](https://github.com/livekit/server-sdk-go/blob/76007e61480f5da5f34ee9697c8fa03a66345706/localtrack.go#L340), I logged the packet size, payload size and sequence number before it's passed on to [webrtc/track_local_static.go#WriteRTP()](https://github.com/pion/webrtc/blob/3f1622a2f406433f90671ea059ab04119a402883/track_local_static.go#L152):
```
	fmt.Println("LocalTrack.WriteRTP:  packetSize", p.MarshalSize(), ", payloadSize", len(p.Payload), ", sequenceNbr", p.SequenceNumber)
	return s.rtpTrack.WriteRTP(p)
```
And the first and last lines after the negotiation look like below:
```
LocalTrack.WriteRTP:  packetSize 1480 , payloadSize 1460 , sequenceNbr 838
LocalTrack.WriteRTP:  packetSize 1480 , payloadSize 1460 , sequenceNbr 839
LocalTrack.WriteRTP:  packetSize 69 , payloadSize 49 , sequenceNbr 840
LocalTrack.WriteRTP:  packetSize 1472 , payloadSize 1460 , sequenceNbr 841
LocalTrack.WriteRTP:  packetSize 1472 , payloadSize 1460 , sequenceNbr 842
.
.
.
.
LocalTrack.WriteRTP:  packetSize 1472 , payloadSize 1460 , sequenceNbr 1078
LocalTrack.WriteRTP:  packetSize 61 , payloadSize 49 , sequenceNbr 1079
LocalTrack.WriteRTP:  packetSize 1472 , payloadSize 1460 , sequenceNbr 1080
LocalTrack.WriteRTP:  packetSize 1472 , payloadSize 1460 , sequenceNbr 1081
LocalTrack.WriteRTP:  packetSize 1115 , payloadSize 1103 , sequenceNbr 1082
```

Then at the receiving side, I found the place where io.ErrShortBuffer is returned at [transport>packetio>buffer.go#Read()](https://github.com/pion/transport/blob/538047e56b04b46dce5388536827b350054f8c9f/packetio/buffer.go#L244) and checked what the 'copied' and 'count' are.
```
buffer.Read: read count  1496 , copied 1460 
or
buffer.Read: read count  1488 , copied 1460 
```
It looks like the 'count' is either 1496 or 1488 when problem happens, which matches to the packet size 1480 or 1472 at the sending side.
The 'copied' 1460 is because in [webrtc>internal>mux>mux.go#readLoop](https://github.com/pion/webrtc/blob/3f1622a2f406433f90671ea059ab04119a402883/internal/mux/mux.go#L121) it tried to read data into the 'buf' which has size 1460.

As experiments, I enlarged the buffer size in mux.go to 1496 by resetting the [receiveMTU in constants.go](https://github.com/pion/webrtc/blob/3f1622a2f406433f90671ea059ab04119a402883/constants.go#L10). Then things just work fine as livekit>sfu>downtrack.go start to send packets to its clients(see the matching sequence numbers as the sending side logs).
```
DownTrack.WriteRTP: payloadSize  1460 , sequenceNbr 1078
DownTrack.WriteRTP: payloadSize  49 , sequenceNbr 1079
DownTrack.WriteRTP: payloadSize  1460 , sequenceNbr 1080
DownTrack.WriteRTP: payloadSize  1460 , sequenceNbr 1081
DownTrack.WriteRTP: payloadSize  1103 , sequenceNbr 1082
```

Apparently this is a problem that MTU is handled differently in each part. Given that [WebRTC has default MTU as 1500](https://webrtc.googlesource.com/src/+/refs/heads/main/call/rtp_video_sender.cc#91), maybe pion should do same? Or reject packets over 1460 at sending side?

PS: what's the extra 16 bytes in the buffer of packetio? The minimum buffer size that works is 1488, given the most packet with 1460 payload has a size 1472. (Also 1472 is another common UDP MTU)

**Comment by Sean-Der** [comment]
@braveyao lets raise to 1500! I don’t believe the impact will be noticed, it’s a better default. If you make a PR I can merge now.

We should also expose via SettingEngine, if someone really wants it lower they can. I don’t think that needs to be done now though.

honored you are looking at Pion code! I have read lots of your WebRTC code :)

**Comment by braveyao** [comment]
@Sean-Der, lately I also noticed that the receiveMTU can be set via SettingEngine in Livekit to solve the problem. Anyway, 1500 is a better default. I'll raise it soon.

BTW: I still didn't figure out what is the 16 extra bytes in the packetio(the 'count' is 1496 to a 1480-size packet). Any idea?
