### ISSUE TITLE
Enable user to register custom codec implementation

### ISSUE THREAD

**Issue by LeeTeng2001** [pion/webrtc#2928]
## Summary

Allow user to register custom codec implementation other than provided one.

## Motivation

Right now we have a way to register custom codec via MediaEngine.RegisterCodec, but it'll throw "the requested codec does not have a payloader" error when the codec implementation is not found. I would like to bind a custom codec to a particular mime type. The matching of codec is private and couldn't be modified by user

```
func payloaderForCodec(codec RTPCodecCapability) (rtp.Payloader, error) {
	switch strings.ToLower(codec.MimeType) {
	case strings.ToLower(MimeTypeH264):
		return &codecs.H264Payloader{}, nil
	case strings.ToLower(MimeTypeOpus):
		return &codecs.OpusPayloader{}, nil
	case strings.ToLower(MimeTypeVP8):
		return &codecs.VP8Payloader{
			EnablePictureID: true,
		}, nil
	case strings.ToLower(MimeTypeVP9):
		return &codecs.VP9Payloader{}, nil
	case strings.ToLower(MimeTypeAV1):
		return &codecs.AV1Payloader{}, nil
	case strings.ToLower(MimeTypeG722):
		return &codecs.G722Payloader{}, nil
	case strings.ToLower(MimeTypePCMU), strings.ToLower(MimeTypePCMA):
		return &codecs.G711Payloader{}, nil
	default:
		return nil, ErrNoPayloaderForCodec
	}
}
```
In the above code, pion should try to match a custom user implemented codec before throwing an error

**Comment by LeeTeng2001** [comment]
on a side note, can someone pinpoint me an alternative solution to my problem? I have a specific use case where I want to ensure I receive data for a specific codec and I do not care about decoding the content. By exposing user implemented codec, I could create a dummy codec and bind it to the codec mime type

**Comment by Sean-Der** [comment]
@LeeTeng2001 Would love to support!

Can you add a method to register a payloader for mimetype to the MediaEngine?

**Comment by LeeTeng2001** [comment]
sure thing, I'll submit a pr!

**Comment by LeeTeng2001** [comment]
Did I merge it to the wrong branch? Should I merge it to v3?
