### ISSUE TITLE
Pion implements telegram audio and video server issues

### ISSUE THREAD

**Issue by helisong427** [pion/webrtc#2964]
Hello, we are currently developing a secondary application based on Telegram. The client is completely using Telegram’s client, and we are implementing our own server. We encountered difficulties when using Pion to implement a multi-person audio and video server. Packet capture revealed that Telegram does not use SDP. The signaling only exchanges the following information:

Message sent by the client：
[request.json](https://github.com/user-attachments/files/18018875/request.json)

Message replied by the server：
[response.json](https://github.com/user-attachments/files/18018889/response.json)

we are using Pion’s ORTC to establish a connection. The ICE negotiation is successful, and we can receive RTP audio data. However, although the video data is received at the socket level, the RtpReceiver does not parse it. It might be due to the video using Simulcast. The implementation logic is currently quite messy, and we are still trying different approaches.

Questions:
	1.	Can you help analyze the server-side implementation logic?
	2.	What are the key points to consider?
	3.	Can this be achieved using pion/webrtc or pion/ortc?
	4.	Is it necessary to modify Pion?
	5.	If you have any information related to Telegram’s multi-person audio and video functionalities, could you please recommend it?

Looking forward to your reply ！

**Comment by Sean-Der** [comment]
Hi @helisong427 

I would love to help with this! Is your code Open Source? If you can share a repo I would love to help.

Drop the repo here or on https://pion.ly/slack and mention Sean-Der and I will try my best to help!
