### ISSUE TITLE
DataChannel: support adding data channels after signaling

### ISSUE THREAD

**Issue by backkem** [pion/webrtc#305]
Currently `PeerConnection.CreateDataChannel` doesn't open a data channel. It assumes the channel will be opened when the network manager is started. This doesn't happen if a data channel is created (with in-band negotiation) after signaling.
We also have to take into account that the `OnOpen` callback can only be registered after the RTCDataChannel is returned to the user. But we can't assume `OnOpen` will always be set. Related: w3c/ortc#873.

**Comment by backkem** [comment]
May be fixed by #342, to verify.

**Comment by backkem** [comment]
The first point was fixed by #342. The problem with OnOpen remains.

**Comment by Sean-Der** [comment]
Hey @backkem 

If the first point was fixed I think we can close this!

For the second point we check if it is already open, and then fire the callback right away https://github.com/pion/webrtc/blob/master/datachannel.go#L192

please re-open if I am wrong though :) I did a little sleuthing, but I am not 100% confident

**Comment by enobufs** [comment]
@Sean-Der @backkem 
https://github.com/pion/webrtc/issues/834#issuecomment-532320752

As this ticket is closed, if pion receives offer without `m=application 9 UDP/DTLS/SCTP webrtc-datachannel` can still establish data-channel? (just trying to understand if this is possble now..)

**Comment by Sean-Der** [comment]
I need to confirm, but I am pretty sure the Offerer must create a datachannel (otherwise it will not start up the SCTP subsystem)

I will confirm with Chromium, but I think if you add one video track in the offerer, and then create a DataChannel in the answerer you will not have Datachannels. So this isn't a constraint on our side (I really need to confirm this though) then we can close out that other ticket!

**Comment by enobufs** [comment]
I see, I thought so too - thanks. I wasn't fully sure what the expected behavior in WebRTC protocol spec, either and I need to go back to the spec.

**Comment by Sean-Der** [comment]
I will get a jsfiddle going and resolve that other ticket! Sorry been a busy week :(

Thanks for responding to tickets so much and helping people on Slack, really awesome to see how much people are helping each other out :)
