### ISSUE TITLE
Don't start unused networking

### ISSUE THREAD

**Issue by backkem** [pion/webrtc#346]
- When there are no data channels in the SDP: Don't spawn SCTP.
- When there are no media tracks in the SDP: Don't spawn SRTP.
- When no DataChannel has been opened don't offer SCTP

**Comment by Sean-Der** [comment]
This is going to happen because of #54 

There will be some API breakage unfortunately. Right now we always create a `recvonly` candidate for audio/video.

In the future we will need to require people do `peerConnection.AddTransceiver`

**Comment by Sean-Der** [comment]
Fixed by f78334d9d4cb163b7280be77c848aacca168d0e6

SRTP is always going to be spawned because it happens with the DTLS handshake. SCTP is only spawned when the Remote Session Description contains the application media section.
