### ISSUE TITLE
gcc congestion algorithm support

### ISSUE THREAD

**Issue by KouChongYang** [pion/webrtc#359]
when can support congestion algorithm gcc or other congestion algorithm

**Comment by wdouglass** [comment]
I assume you mean this:
https://tools.ietf.org/html/draft-ietf-rmcat-gcc-02

I don't think it's on the roadmap now, @Sean-Der or @backkem may correct me....
It's a neat feature though!

**Comment by Sean-Der** [comment]
https://brage.bibsys.no/xmlui/bitstream/handle/11250/2456126/17761_FULLTEXT.pdf

**Comment by Sean-Der** [comment]
Moving this to v2.1.0 planning
