### ISSUE TITLE
Logging cleanup

### ISSUE THREAD

**Issue by mjmac** [pion/webrtc#361]
Creating an umbrella issue for log messages which are deemed by consensus to be at the wrong log level (e.g. at Debug when Trace would be more reasonable). Refer to this issue when creating PRs for logging adjustments.

**Comment by gissleh** [comment]
Does this issue also include removing std outputs like this one from `gatherCandidatesLocal()` in `agent.go`? These are very unhelpful when using stdin and stdout for IPC.
 
```
could not listen udp fe80::2c36:8bff:fea6:ab50
```

**Comment by mjmac** [comment]
Hi @gissleh!

Sure, I think so. We've been gradually replacing all of those with proper logging statements but I'm not surprised that a few got missed.

**Comment by backkem** [comment]
Other points that need investigating:
- Logging is now global. This may lead to issues when using multiple instances of the library.
- Logging is now limited to package webrtc. We should roll this out to the other ones.

**Comment by backkem** [comment]
After #535 lands we need to move all variants of `fmt.Println` over to `pions/logging`.
