### ISSUE TITLE
No globals

### ISSUE THREAD

**Issue by backkem** [pion/webrtc#434]
This ticket tracks avoiding globals in the library.

**defaultAPI**
We currently use a global variable `defaultAPI` in `api.go` to enable a global API. This global API allows for simple examples covering the basic use-cases. This reduces the learning curve of the library.
In these basic cases we mostly do:
```go
webrtc.RegisterDefaultCodecs()
pc, err := webrtc.NewPeerConnection(config)
```
I suggest to change the global `NewPeerConnection` so it:
- Constructs it's own API object.
- Always registers the default codecs, supporting most browsers.

This way we can avoid the `defaultAPI` global variable and still have a nice API for simple use-cases. Users with more specific use-cases can construct their own API object and configure it to their needs.
Example:
```go
// Create a MediaEngine and set your codecs
m := webrtc.MediaEngine{}
m.RegisterCodec(webrtc.NewRTPOpusCodec(webrtc.DefaultPayloadTypeOpus, 48000, 2))

// Create an API object with the engine
api := webrtc.NewAPI(webrtc.WithMediaEngine(m))

// Create the PeerConnection
peerConnection, err := api.NewPeerConnection(config)

// Or use ORTC
gatherer, err := api.NewICEGatherer(iceOptions)
```

**Logging**
See #361

TODO:
- [x] Avoid `DefaultAPI`
- [x] Avoid global logging
- [ ] Avoid MuxFuncs as global variables
- [ ] Enable `gochecknoinits` & `gochecknoglobals` linters

**Comment by maxhawkins** [comment]
This makes sense to me. Global state is bad news.

I'd like to propose making the settings stuff more explicit by passing it in as a parameter. That way it will be more discoverable via godoc for people just discovering the library. It also has the benefit that if we rename or remove a parameter users will be notified via their type checker.

Here's an API that would eliminate the need for `SettingsEngine` and `MediaEngine` by providing an explicit `Settings` object.

`webrtc.Settings` would contain all the non-RFC options that can be passed to a peer connection.

```go
pc, err := webrtc.NewPeerConnection(
    webrtc.Configuration{
        IceServers: iceServers,
        RTCPMuxPolicy: webrtc.RTCPMuxPolicyNegotiate
    },
    &webrtc.Options{
        Codecs: webrtc.DefaultCodecs, // omitting this defaults to webrtc.DefaultCodecs
        UDPPortMin: 8080,
        UDPPortMax: 0, // omitting or setting to zero means there is no max
        DetachDataChannels: true,
        ICEConnectionTimeout: 2 * time.Minute,
        ICEKeepaliveTimeout: time.Duration(0), // omitting or setting to zero disables timeout
    },
)
```

In the usual case, you could just pass nil to get the defaults:

```go
pc, err := webrtc.NewPeerConnection(webrtc.Configuration{IceServers: iceServers}, nil)
```

**Comment by backkem** [comment]
This needs more work:
- `TestPeerConnection_ShutdownNoDTLS` disables DLTS by overwriting `mux.MatchDTLS`. This may be an easy way to make this kind of tests but it does prove why globals are a horrible idea.
- supportedNetworks & supportedNetworkTypes need replaces. Probably by a function that returns the slice.

**Comment by maxhawkins** [comment]
What's the status on this issue?

**Comment by backkem** [comment]
The OP list is up-to-date. `gochecknoinits` has been activated. `gochecknoglobals` is still a WIP. There are some simple globals to avoid and a harder one mentioned in https://github.com/pion/webrtc/issues/434#issuecomment-474960304.
