### ISSUE TITLE
Consolidating all packages into one repository

### ISSUE THREAD

**Issue by enobufs** [pion/webrtc#439]
Looking at the current dependency graph, we are loading different versions of the same package, which could bloat our resulting object size unnecessarily:
```
webrtc$ go mod graph
go: finding github.com/pions/sctp v1.4.1
go: finding github.com/pions/sdp/v2 v2.1.0
github.com/pions/webrtc github.com/pions/datachannel@v1.2.0
github.com/pions/webrtc github.com/pions/dtls@v1.2.1
github.com/pions/webrtc github.com/pions/quic@v0.0.1
github.com/pions/webrtc github.com/pions/rtcp@v1.0.0
github.com/pions/webrtc github.com/pions/rtp@v1.0.0
github.com/pions/webrtc github.com/pions/sctp@v1.4.1
github.com/pions/webrtc github.com/pions/sdp/v2@v2.1.0
github.com/pions/webrtc github.com/pions/srtp@v1.0.3
github.com/pions/webrtc github.com/pions/stun@v0.2.0
github.com/pions/webrtc github.com/pions/transport@v0.2.0
github.com/pions/webrtc github.com/pkg/errors@v0.8.1
github.com/pions/webrtc github.com/stretchr/testify@v1.3.0
github.com/pions/datachannel@v1.2.0 github.com/pions/sctp@v1.3.0
github.com/pions/datachannel@v1.2.0 github.com/pkg/errors@v0.8.1
github.com/pions/srtp@v1.0.3 github.com/pions/rtcp@v1.0.0
github.com/pions/srtp@v1.0.3 github.com/pions/rtp@v1.0.0
github.com/pions/srtp@v1.0.3 github.com/pkg/errors@v0.8.1
github.com/pions/srtp@v1.0.3 github.com/stretchr/testify@v1.3.0
github.com/stretchr/testify@v1.3.0 github.com/davecgh/go-spew@v1.1.0
github.com/stretchr/testify@v1.3.0 github.com/pmezard/go-difflib@v1.0.0
github.com/stretchr/testify@v1.3.0 github.com/stretchr/objx@v0.1.0
github.com/pions/sctp@v1.4.1 github.com/pions/transport@v0.2.0
github.com/pions/sctp@v1.4.1 github.com/pkg/errors@v0.8.0
github.com/pions/sctp@v1.4.1 github.com/stretchr/testify@v1.3.0
github.com/pions/dtls@v1.2.1 github.com/pions/transport@v0.1.0
github.com/pions/dtls@v1.2.1 golang.org/x/crypto@v0.0.0-20190123085648-057139ce5d2b
github.com/pions/stun@v0.2.0 github.com/pkg/errors@v0.8.1
github.com/pions/stun@v0.2.0 github.com/stretchr/testify@v1.3.0
github.com/pions/quic@v0.0.1 github.com/cheekybits/genny@v1.0.0
github.com/pions/quic@v0.0.1 github.com/cloudflare/sidh@v0.0.0-20181111220428-fc8e6378752b
github.com/pions/quic@v0.0.1 github.com/golang/mock@v1.2.0
github.com/pions/quic@v0.0.1 github.com/onsi/ginkgo@v1.7.0
github.com/pions/quic@v0.0.1 github.com/onsi/gomega@v1.4.3
github.com/pions/quic@v0.0.1 github.com/pions/qtls-vendor-extracted@v0.0.0-20190210024908-018998217c65
github.com/pions/quic@v0.0.1 github.com/pions/quic-go@v0.7.1-0.20190211221741-ec20a8498576
github.com/pions/quic@v0.0.1 github.com/pions/transport@v0.2.0
github.com/pions/quic@v0.0.1 golang.org/x/crypto@v0.0.0-20190219172222-a4c6cb3142f2
github.com/onsi/gomega@v1.4.3 github.com/fsnotify/fsnotify@v1.4.7
github.com/onsi/gomega@v1.4.3 github.com/golang/protobuf@v1.2.0
github.com/onsi/gomega@v1.4.3 github.com/hpcloud/tail@v1.0.0
github.com/onsi/gomega@v1.4.3 github.com/onsi/ginkgo@v1.6.0
github.com/onsi/gomega@v1.4.3 golang.org/x/net@v0.0.0-20180906233101-161cd47e91fd
github.com/onsi/gomega@v1.4.3 golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f
github.com/onsi/gomega@v1.4.3 golang.org/x/sys@v0.0.0-20180909124046-d0be0721c37e
github.com/onsi/gomega@v1.4.3 golang.org/x/text@v0.3.0
github.com/onsi/gomega@v1.4.3 gopkg.in/fsnotify.v1@v1.4.7
github.com/onsi/gomega@v1.4.3 gopkg.in/tomb.v1@v1.0.0-20141024135613-dd632973f1e7
github.com/onsi/gomega@v1.4.3 gopkg.in/yaml.v2@v2.2.1
github.com/pions/sctp@v1.3.0 github.com/pions/transport@v0.0.0-20190110151433-e7cbf7d5f464
github.com/pions/sctp@v1.3.0 github.com/pkg/errors@v0.8.0
github.com/pions/sctp@v1.3.0 github.com/stretchr/testify@v1.3.0
gopkg.in/yaml.v2@v2.2.1 gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405
```

Also, making changes to submodules require multiple pull requests for repositories affected, which takes us extra time.

On the other hand, having separate repositories for each sub-packages allows us to up/down-grade as we needed. But this, I believe, we could achieve with the consolidated repository, if we maintain go.mod file for each package (while sub-packages are referenced by `replace` keyword with relative path basically). Also, the consolidation of the packages would not prevent us from using just one of these packages. That said, I really do not see the real advantage of having separate repositories...

I think the consolidation of the repositories would allow us to move fast.

Any thoughts?

**Comment by backkem** [comment]
I do agree that the separate repositories case a bit of extra work. I kinda hope the Go community can come up with good tooling to automation some of this.
One thing to take into account is that many of these repositories are also usable on their own. Many of them represent networking protocols that are also useful outside of the WebRTC context. If they are just sub-packages of pions/webrtc they're way less likely to attract those use-case.

**Comment by Sean-Der** [comment]
Oof that isn't good @enobufs nice catch.

We started out as a mono-repo, but split it up for all the reasons @backkem mentioned. I think that was the right decision though. We are seeing a lot of people contributing to the individual packages (which is great) and using them for their own projects!

I think we need to find a way to make sure our deps don't get bloated though. What do you think of making a `cron` job or something like that @enobufs that watches this? We can make a new repo `github.com/pions/pions` (or something like that) and can run automated checks across all our repos!

We could do a lot of cool things.
* Make sure our README.md is good
* Make sure our dependency tree isn't bloated
* Make sure all our linters are updated etc...
* (and more goodies!)

I think that will help solve this issue!

**Comment by enobufs** [comment]
Thanks @backem @Sean-Der for your comments.

> What do you think of making a `cron` job or something like that

Needing to have this kind of extra works is exactly what I am pointing out though... If we had everything in one place, we did not even have to do this IMO.

> If they are just sub-packages of pions/webrtc they're way less likely to attract those use-case.

That may be true. But, for instance, I am totally comfortable with using only `assert` package in the testify module.  If bringing awareness of those individual packages or attracting people who want to use just one of these packages, we can always provide them with examples, which is far more useful item than the cron job for us to spend time for them.

From a contributor's perspective, being able to run tests from other depending packages in one place makes things so much easier and faster.  After all, dependencies between these packages won't change by having separate packages...

**Comment by Sean-Der** [comment]
Hey @enobufs 
I took some time to dig into this (trying to close out tickets I haven't done enough on)

* Go modules will grab the highest versions, so the mismatch should be fine!
```
