### ISSUE TITLE
Unexpected behavior caused by examples/signal package

### ISSUE THREAD

**Issue by toldjuuso** [pion/webrtc#461]
Hi,

First, thanks for the package!

I have an issue with this line: https://github.com/pions/webrtc/blob/master/examples/internal/signal/signal.go#L40

The line causes unexpected behavior in your demos if someone like me tries to establish a Unix pipe straight to FFMPEG, like one could with the save-to-disk example. The problem is that `fmt.Println()` writes to `os.Stdout`. That is, when using a Unix pipe or write operator (e.g., `|` or `>`) the line causes the output to be prepended with an empty line (imagine `cat key.txt | ./save-to-disk > out.ivf`, here out.ivf is 1 byte file with an empty line because of the signal package). This behavior then breaks encoders, like FFMPEG, if coupled like `cat key.txt | ./save-to-disk | ffmpeg -i out.webm -y`.

If you are okay with removing the line, please let me know and I can open a PR for it.

Thanks again for the project!

**Comment by Sean-Der** [comment]
Hey @toldjuuso!

We need to document this better, but `save-to-disk` doesn't output the `ivf` via stdout. We updated it so it puts out a `ivf` and `opus` file now! and it directly saves it for you :)

I would love a PR fixing the documentation though! Hopefully all that makes sense.

We could probably update it to do `stdio` also to make it easier on people (and make it a command line argument)

**Comment by toldjuuso** [comment]
Ah yes, I meant it becomes a problem if someone modifies the demo to do it via stdout, like I did. Only in this case is the internal package a problem, and I thought the extra Println is a bug.

Anyhow, the diff to make it pipe-compliant is not that hard, I can push the code sometime soon, and you could take a look at what you want to incorporate.

**Comment by Sean-Der** [comment]
@toldjuuso 

Yea that changes works for me! Mind just moving the `fmt.Println` up a layer, so we won't see a behavior difference but still make it easy for people to make changes like this :)

thanks @toldjuuso

**Comment by toldjuuso** [comment]
The initial streaming code is now here: https://github.com/toldjuuso/handover2019okwuibe/blob/master/main.go

I will eventually tidy it up a bit so the HTTP server is removed and you can get an example of it. I'll open PR once that's done.

**Comment by Sean-Der** [comment]
Hey @toldjuuso 

Anything I can do to help with this? We have finished up our v2.0.0 rush so happy to help!

**Comment by toldjuuso** [comment]
Hi, thanks for letting me know, I will soon update to v2.0.0 and see if everything works on my end. If it does, I will make a PR with the stuff I have.

**Comment by toldjuuso** [comment]
Further, I think this issue can be closed, we can continue on the PR later on.
