### ISSUE TITLE
WASM: Setup testing

### ISSUE THREAD

**Issue by backkem** [pion/webrtc#490]
Setup testing for the WASM implementation. Related [documentation](https://github.com/golang/go/wiki/WebAssembly#executing-webassembly-with-nodejs).

**Comment by albrow** [comment]
I started working on this in https://github.com/pions/webrtc/pull/504.

**Comment by albrow** [comment]
Partly solved by #504 but we probably want in-browser integration tests at some point.

**Comment by Sean-Der** [comment]
The testing we have has worked great. No further changes needed.
