### ISSUE TITLE
WASM: Add support for tracks, streams, and media

### ISSUE THREAD

**Issue by albrow** [pion/webrtc#500]
#479 only adds support for `DataChannel`, but eventually we would like to support video and audio functionality by implementing bindings for `Track` and other related objects/methods.

**Comment by gedw99** [comment]
So this is working towards a browser based video conferencing system ? All golang ?

**Comment by backkem** [comment]
@gedw99 Yes, in WASM the Pion API forms a wrapper around the JavaScript WebRTC API so you can use it in the same (or very similar) way you would on the server. For the media stuff there will probably be some differences in the API between the JavaScript and native implementation. This would indeed allow you to write both the server and the client side of a video conferencing system in Go.

**Comment by gedw99** [comment]
thanks @backkem - much appreciated.

**Comment by Sean-Der** [comment]
I added support for addTransceiver. This is a good start and we can just iterate as we get more demand
