### ISSUE TITLE
H.264 answer no longer works

### ISSUE THREAD

**Issue by kixelated** [pion/webrtc#518]
### Your environment.
Chrome 73.0.3683.75 
pions/webrtc: 3426d00e2cda

### What did you do?
Chrome generates the offer, and my program generates the answer only with h.264 support. It then creates a H.264 track and sends it to the browser.

### What did you expect?
Chrome to play back correctly.

### What happened?
Chrome receives the packets but is unable to decode them. webrtc-internals shows that the SSRC is a VP9 stream, not H.264 like expected. This was working as of last night but there was probably a Chrome update. It does not work for the rest of my team either.

I tried a number of things to fix the issue, but what ultimately worked was having my application generate the offer instead. This implies that there is some SDP nonsense going on.

**Comment by Sean-Der** [comment]
Fixed with 40f5b9459b25de413bae4af6bc5ccbfd5861a013
