### ISSUE TITLE
Support  unified-plan

### ISSUE THREAD

**Issue by notedit** [pion/webrtc#54]
firefox supports unified-plan,  latest chrome supports unified-plan too.  

https://tools.ietf.org/html/draft-roach-mmusic-unified-plan-00

https://bugs.chromium.org/p/chromium/issues/detail?id=799030

**Comment by backkem** [comment]
Thanks @notedit . Let us know if you have any specific needs for this feature. That allow us to determine the correct priority.

**Comment by notedit** [comment]
If we have want to support multi MediaStreams  or build a SFU,  we need this feature.

**Comment by notedit** [comment]
unified plan is default  in chrome m72  now.

**Comment by trivigy** [comment]
@notedit Any specific parts regarding the unified-plan that you need? Personally I only need the BUNDLE protocol to work according to the unified-plan, and only related to data channels. What about you? I am going to end up fixing whatever is wrong but only related to data channels. If I know what you need, I might try looking into it along the way.

**Comment by notedit** [comment]
@trivigy here is the specific https://tools.ietf.org/html/draft-roach-mmusic-unified-plan-00
What i want is that multi streams use one ice transport,  it is common in the sfu server,  one peer receive multi remote streams through one peerconnection.
