### ISSUE TITLE
rtcp package issue

### ISSUE THREAD

**Issue by jinleileiking** [pion/webrtc#553]
## Summary

rtcp package have some bad behaviour in some cases.

## Motivation

Safety

## Describe alternatives you've considered

Think of sfu-ws example.

In example, we should use rtcp package.   --> example uses version 1.2.0

webrtc project also uses rtcp ---> webrtc uses version 1.3.0

Then there will be some bad  case:

application program(sfu-ws) and core(webrtc) uses different rtcp version!

I can not find a way to solve this for now.

**Comment by Sean-Der** [comment]
That's a good point!

Maybe we can add some scripts to the `.travis.yml` that check that our examples are using the newest versions available?

I remember this coming up before, and I believe this *might* not be an issue. Go might use the same version for all package (walks the tree and uses the oldest/newest version)

@maxhawkins @kixelated ^ I think one of you told me about this maybe?

**Comment by jinleileiking** [comment]
Waiting the gurus answers

**Comment by maxhawkins** [comment]
I don't completely understand this issue. Is this a go module thing where it's resolving different versions?

**Comment by jinleileiking** [comment]
Yes. So close for now
