### ISSUE TITLE
Move examples with dependencies to a dedicated repo

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#561]
## Summary

I think we should move all examples that involve 3rd party repos to a dedicated repo. We should only keep examples that have no external dependencies in the `pions/webrtc` repo.

## Motivation

As Pion has grown more people have contribute examples, and the rate this is happening has increased. This has a few small issues however.

* Dependencies in `examples/` directory is putting a greater burden on developers. Right now to lint the full project developers need to install GStreamer C libs.

* People think that dependencies in the `examples/` directory are needed for the main project, and is confusing. 

* Code added to the `examples/` directory is growing the project, I don't want to make every checkout include unneeded C/Flutter code. I have had a few users assume that GStreamer is required to use pion WebRTC

* We can have a lower barrier of entry for the `webrtc-example-applications` repo. I would like to encourage people to add lots of things, and we can encourage first time contributors to build interesting things.

* We still want some simple `examples` though. Personally I start by copying examples, and then editing. I think if we keep them all simple we are doing the right thing by users.

**Comment by Sean-Der** [comment]
@jinleileiking what do you think of this as a good middle ground?

This way we can keep simple examples in `webrtc` but anything that uses a 3rd party library (GStreamer, websockets, janus etc...) would go in another repo.

re: @cloudwebrtc @maxhawkins @backkem I feel like you might be passionate/care about this also.

**Comment by cloudwebrtc** [comment]
@Sean-Der I think this is a good thing, which keeps the pions/webrtc library clean and small.
