### ISSUE TITLE
nil pointer in openSRTP

### ISSUE THREAD

**Issue by maxhawkins** [pion/webrtc#563]
### Your environment.
  - Version: 8ef5b7034ff4664530938fa48873d34d3f9672fc

### What did you do?
Created a PeerConnection between two Pion instances and sent data using `track.WriteSample`.

### What happened?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x42ed3dd]

goroutine 32 [running]:
github.com/pions/webrtc.(*PeerConnection).openSRTP.func1(0xc000132480, 0xc0000004d2, 0x2)
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190328075210-8ef5b7034ff4/peerconnection.go:991 +0x2bd
created by github.com/pions/webrtc.(*PeerConnection).openSRTP
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190328075210-8ef5b7034ff4/peerconnection.go:962 +0x3fe
```

This is the line
```
			sdpCodec, err := pc.currentLocalDescription.parsed.GetCodecForPayloadType(receiver.Track().PayloadType())
			if err != nil {
				pc.log.Warnf("no codec could be found in RemoteDescription for payloadType %d", receiver.Track().PayloadType())
				return
			}
```

**Comment by maxhawkins** [comment]
Tracking this down...

`pc.currentLocalDescription` is `nil`

**Comment by maxhawkins** [comment]
In this case the answerer called CreateAnswer without calling SetLocalDescription afterward.

When I add SetLocalDescription(answer) the problem goes away

**Comment by Sean-Der** [comment]
That is for sure a annoying bug :)

This is what Chromium gives me for the same behavior
```
PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer
```

**Comment by mchlrhw** [comment]
We experience this in `2.0.15`. Does that sound like a regression?

> In this case the answerer called CreateAnswer without calling SetLocalDescription afterward.
> 
> When I add SetLocalDescription(answer) the problem goes away

The steps above reported by @maxhawkins also fixed it for us, but it should probably be fixed some other way to avoid improper use of the API causing a SIGSEGV.

**Comment by Sean-Der** [comment]
@mchlrhw oof nice catch. Are you able to share a stack trace?

Do you know how it is passing this check? https://github.com/pion/webrtc/blob/master/peerconnection.go#L724

We also have this test https://github.com/pion/webrtc/blob/master/peerconnection_go_test.go#L369 do you know what changes we need to do to make this fail.

**Comment by mchlrhw** [comment]
My reading of the above check and accompanying test is that they are only related to the remote description at the time of answer creation and not to the local description at the time of receiving data from the other peer.
We were htting it because we forgot to call `SetLocalDescription` after the API had changed to decouple it from `CreateAnswer`.
Maybe there is a missing check of the signalling state somewhere that allows `openSRTP` to progress further than it should in the wrong state? Should a local description be required to progress back to stable? I honestly don't know.
One slight difference I notice from the original issue is that we are not seeing this in pion<->pion, but iOS<->pion, although I wouldn't have expected that to be the problem.

**Comment by mchlrhw** [comment]
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa86c4b]

goroutine 16 [running]:
github.com/pion/webrtc/v2.(*PeerConnection).openSRTP.func1(0x1, 0xc0000991e5, 0x6, 0xc0000991ec, 0x5, 0x48fc1554, 0xc0001f8fc0)
/go/pkg/mod/github.com/pion/webrtc/v2@v2.0.15/peerconnection.go:1157 +0x3eb
created by github.com/pion/webrtc/v2.(*PeerConnection).openSRTP
/go/pkg/mod/github.com/pion/webrtc/v2@v2.0.15/peerconnection.go:1198 +0xb11```

**Comment by mchlrhw** [comment]
It seems that the pion<->pion example doesn't exercise this particular problem. It may be that datachannels alone aren't sufficient and you need A/V RTP to trigger it :man_shrugging:

**Comment by Sean-Der** [comment]
Ah nice now I understand! Will fix this up @mchlrhw
