### ISSUE TITLE
use of internal package

### ISSUE THREAD

**Issue by lrtxpra** [pion/webrtc#596]
when I update webrtc package
```
go get -u -v github.com/pions/webrtc
```
it report an error? I am not sure it is an error, about using internal package
```
github.com/pions/webrtc (download)
github.com/pion/datachannel (download)
github.com/pion/logging (download)
github.com/pion/sctp (download)
github.com/pkg/errors (download)
github.com/pion/dtls (download)
Fetching https://golang.org/x/crypto/curve25519?go-get=1
Parsing meta tags from https://golang.org/x/crypto/curve25519?go-get=1 (status code 200)
get "golang.org/x/crypto/curve25519": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/curve25519?go-get=1
get "golang.org/x/crypto/curve25519": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
github.com/pion/ice (download)
github.com/pion/stun (download)
github.com/pion/transport (download)
github.com/pion/rtcp (download)
github.com/pion/rtp (download)
github.com/pion/sdp (download)
github.com/pion/srtp (download)
github.com/pion/webrtc (download)
../github.com/pions/webrtc/dtlstransport.go:18:2: use of internal package github.com/pion/webrtc/internal/mux not allowed
../github.com/pions/webrtc/dtlstransport.go:19:2: use of internal package github.com/pion/webrtc/internal/util not allowed

```
then I can't compile program which using old webrtc package version.
I simply search the problem, a little confused, it seems that internal package can't be import,

my go version, go1.12.1 linux/amd64

**Comment by lrtxpra** [comment]
emmm, I think this is my problem, there is 2 dirs, pion and pions,

**Comment by lrtxpra** [comment]
I think u should update godoc, because godoc signed package address as "github/pions/webrtc".
emmm, I copy address from godoc.......

**Comment by Sean-Der** [comment]
Hey @lrtxpra 

Is everything working after that? Thank you very much for using Pion though, sorry for the rename :(

**Comment by lrtxpra** [comment]
> Hey @lrtxpra
> 
> Is everything working after that? Thank you very much for using Pion though, sorry for the rename :(

yes, everything working well after that, I think you should update godoc, package address on godoc is still "github.com/pions/webrtc". And thanks for your work;
