### ISSUE TITLE
Connection can't be established

### ISSUE THREAD

**Issue by lrtxpra** [pion/webrtc#600]
After updating to v2.0.2, I try to run program which I wrote with v1.2.0, 
unfortunately, it seems that connection did not establish.
there is a js client and a webrtc sfu server wrote with "pion webrtc", I send sdp offer from js to sfu, both peers set local and remote description, but tracks data had not be transported to server, server ontrack method did not run.   
code runs perfectly under v1.2.0

**Comment by maxhawkins** [comment]
Hi @lrtxpra! Thank you for using Pion.

Maybe you forgot to call AddTransceiver for the incoming tracks? We switched over to [Unified Plan SDP](https://www.callstats.io/blog/what-is-unified-plan-and-how-will-it-affect-your-webrtc-development) in v2, so you need to explicitly declare incoming tracks.

```go
// Allow us to receive 1 audio track, and 2 video tracks
if _, err = peerConnection.AddTransceiver(webrtc.RTPCodecTypeAudio); err != nil {
	panic(err)
} else if _, err = peerConnection.AddTransceiver(webrtc.RTPCodecTypeVideo); err != nil {
	panic(err)
} else if _, err = peerConnection.AddTransceiver(webrtc.RTPCodecTypeVideo); err != nil {
	panic(err)
}
```

https://pion.ly/knowledge-base/release-notes/webrtc-v2.0.0/#you-must-call-addtransceiver-for-every-incoming-track

If you're still having trouble feel free to ask for help in our [slack channel](https://pion.ly/slack/). There are usually people there who can help.

**Comment by Sean-Der** [comment]
Hey @lrtxpra 

We also had a bug fix related to offer generation, this may have been your issue? https://github.com/pion/webrtc/commit/2eaa90b5f13192c8c41e3186d43b1dcfe8a1f963

**Comment by lrtxpra** [comment]
thanks, After reading your new version description, my code re-work, As for offer generation, I check it out . the problem is that I did not add transceiver,
thanks again, @maxhawkins @Sean-Der
