### ISSUE TITLE
Connection can't be established under Chrome, v2.0.2 

### ISSUE THREAD

**Issue by nindolabs** [pion/webrtc#601]
### Your environment.
  - Version: v2.0.2
  - Browser: Chrome 73.0.3683.103

### What did you do?
Upgrade from v1.2.0 to v2.0.2

### What did you expect?
Keep working!

### What happened?
Working under Edge, Firefox after many seconds, not on chrome.

I found that the group bundle are not appended any more:
https://github.com/pion/webrtc/blob/master/peerconnection.go#L463

This fixed the issue for me:
`d = d.WithValueAttribute(sdp.AttrKeyGroup, bundleValue)`

**Comment by Sean-Der** [comment]
Hey @nindolabs 

Are you doing video/audio, datachannels or both? If you are receiving media make sure to confirm you are using [AddTransceiver](https://pion.ly/knowledge-base/release-notes/webrtc-v2.0.0/#you-must-call-addtransceiver-for-every-incoming-track)

We also provide a [migration guide](https://pion.ly/knowledge-base/release-notes/webrtc-v2.0.0/) if that is helpful.

Can you try one of the `examples/` and confirm it still works with your setup? Just to confirm if it is a networking issue, or the API.

thanks!

**Comment by nindolabs** [comment]
Hi,

I'm using only video, sendonly, i create the offer in the server side, the offer does not contain the "group bundle", i dont know if there is some reason to remove it in v2.0.2, but it works well with it.

I tried sfu-minimal, it's working as expected.

Thanks.

**Comment by Sean-Der** [comment]
Oh I see sorry was looking at the answer code path, that is a bug thanks for catching that @nindolabs! 

Would you be mind opening a PR for that? I will merge and tag right away, sorry about that!
