### ISSUE TITLE
Example paths were incompletely updated on master (see save to disk example)

### ISSUE THREAD

**Issue by wpdildine** [pion/webrtc#603]
### Your environment.
  - Version: *Release or SHA*
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

**Comment by wpdildine** [comment]
https://github.com/pion/webrtc/commit/dbde6114a2129070cd6e82d0c39a849c9e7f6cda#diff-13425e98cc3c9fcb4c7f70de8e31531f

This commit appears to break some stuff.

**Comment by Sean-Der** [comment]
Hey @wpdildine 

I am able to use the examples currently, what error are you getting?

What version of Go are you using? We do use Go modules, so we require `1.9.7+` `1.10.3+` or `1.11 and greater`

**Comment by wpdildine** [comment]
I needed to pull down a newer version of the repo -- I was copy pasting from the github examples and using an older commit.  This can be closed.

**Comment by Sean-Der** [comment]
Awesome, Sorry about the breakage, moving to `/v2` has broken a few people :(

Thanks for using Pion!
