### ISSUE TITLE
go get error pkt.DestinationSSRC undefined

### ISSUE THREAD

**Issue by rukavina** [pion/webrtc#613]
go get github.com/pion/webrtc

responds with 

```
# github.com/pion/srtp
session_srtcp.go:120:26: pkt.DestinationSSRC undefined (type []rtcp.Packet has no field or method DestinationSSRC)
```

go lang version is 1.12

**Comment by Sean-Der** [comment]
Hey @rukavina 

Thanks for filing! I just hit this as well, will check it out

**Comment by Sean-Der** [comment]
Hey @rukavina 

This is fixed! Sorry about the breakage, if possible I would use Go modules. Sometimes we have to break master when fixing issues across multiple repos.

thanks for using Pion :)
