### ISSUE TITLE
Add observability metrics

### ISSUE THREAD

**Issue by maxhawkins** [pion/webrtc#619]
## Summary

Add hooks in the PeerConnection that allow metrics tools like Prometheus or statsd to get information about the inner-workings of Pion.

Some stats that should be implemented:
* Number of open PeerConnections
* Number of failed PeerConnections
* Ports allocated
* ICE connection state count
* DTLS/ICE error count
* RTP statistics (jitter, loss, packets sent, etc)
* (others ?) comment below.

Export to [expvar](https://golang.org/pkg/expvar/) by default, but support common metrics packages like Prometheus.

## Motivation

Exposing metrics can help find bugs and configuration issues in production, optimize complicated Pion installations, and catch issues early.

Some metrics (like those related to low-level DTLS metrics) are difficult to reach from the application layer because they sit at the far end of the stack. Exposing metrics would give users better observability into the low level parts of the library.

## Describe alternatives you've considered

Perhaps this can be moved further up the stack and help us avoid straying from the RTCWEB spec. Could the same functionality be built with the GetStats API (#610) and Prometheus?

**Comment by jinleileiking** [comment]
Prometheus is the basic

**Comment by maxhawkins** [comment]
Closing in favor of #610
