### ISSUE TITLE
Issue with profile-level-id for h264 on chome android 

### ISSUE THREAD

**Issue by Bogdan-D** [pion/webrtc#62]
Current profile-level-id doesn't work for chrome android. 
With current implementation video playing does not start on such devices.
If works fine if it's replaced from "42001f" to "42e01f"

**Comment by Sean-Der** [comment]
Hi @Bogdan-D 

You can easily override this yourself via the API now. We can't assume a certain profile however, maybe we should revisit this entirely (and not have any defaults)

**Comment by Bogdan-D** [comment]
Hi @Sean-Der, 

Sure, that's exactly what I'm doing right now. 
Just informing you that SDP exachange should be not hardcoded values, 
I think the best if you could rely on client's SDP profiles in response, so browser will able to think they are working with correct SDP profile.. etc

**Comment by Sean-Der** [comment]
Hey @Bogdan-D 

Using values from the clients SDP would be incorrect though. If you are sending H264 you need to properly declare what you are sending 

If you want to craft your SDP depending on the client, can you have them answer and set your values depending on what they send?

**Comment by Sean-Der** [comment]
Hey @Bogdan-D 

I am going to close for now, I don't think there is anything we are going to do here. You can set the values that match your outbound H264.

If I am missing something, or you think there is still a bug please re-open. thanks for using Pion!
