### ISSUE TITLE
CreateDataChannel returns with "SCTP not establisched" error

### ISSUE THREAD

**Issue by masterada** [pion/webrtc#628]
Creating a data channel while the sctp is not established returns with an error. 

I belive
https://github.com/pion/webrtc/blob/0c5f0e088bb1f51e20d049c95455bc3c23bb01da/peerconnection.go#L1489
should be:
```
if pc.sctpTransport != nil && pc.sctpTransport.association != nil {
```

This change fixed the issue for me.

**Comment by backkem** [comment]
@masterada good catch. Mind sending us a PR?
