### ISSUE TITLE
Update documentation to mention module requirement

### ISSUE THREAD

**Issue by ekoome** [pion/webrtc#633]
I get the following error when trying to get packages for Webrtc v2 

package github.com/pion/webrtc/v2: cannot find package "github.com/pion/webrtc/v2"
package github.com/pion/webrtc/v2/pkg/media: cannot find package "github.com/pion/webrtc/v2/pkg/media"
github.com/pion/webrtc/v2/pkg/media/ivfwriter: cannot find package "github.com/pion/webrtc/v2/pkg/media/ivfwriter" 
github.com/pion/webrtc/v2/pkg/media/opuswriter: cannot find package "github.com/pion/webrtc/v2/pkg/media/opuswriter"

**Comment by jinleileiking** [comment]
Update go to 1.12 and use go mod

**Comment by chhsiao1981** [comment]
If you are using govendor for package-management, you can do the following workaround:

govendor fetch github.com/pion/webrtc
govendor fetch github.com/pion/webrtc/internal/mux
govendor fetch github.com/pion/webrtc/internal/util
govendor fetch github.com/pion/webrtc/pkg/media
govendor fetch github.com/pion/webrtc/pkg/rtcerr

# remove the original v2 and soft-link the webrtc as v2.
cd vendor/github.com/pion/webrtc && rm -rf v2 && ln -s . v2

**Comment by Sean-Der** [comment]
Hey @ekoome

Thanks for using Pion! We do require modules, the examples should work if you do ‘export GO111MODULE=on‘

I will update the documentation so people don’t run into this in the future
