### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jinleileiking** [pion/webrtc#635]
## Summary

We need a file or wiki to record changelogs

**Comment by jinleileiking** [comment]
Use github project is an option. But I don't know if a CHANGLOG.md is better. Or keep changelogs in detail

**Comment by Sean-Der** [comment]
Hey @jinleileiking 

Thanks for pushing for this, I started https://github.com/pion/webrtc/issues/732

Also when I tag the release I will update github appropriately with them. Thanks for the idea :)
