### ISSUE TITLE
IVF Reader

### ISSUE THREAD

**Issue by zhoub** [pion/webrtc#636]
## Summary

We have IVF Writer, but IVF Reader also makes sense.

## Motivation

Sometimes we need to read/broadcast the RAW VP8 video to  to peer.

## Describe alternatives you've considered

Add new class/package IVFReader.

## Additional context

None.

**Comment by Sean-Der** [comment]
Hey @zhoub thanks for using Pion!

This would be nice, we also have `rtpdump` support so you can playback things later. I don't have plans to work on it, but if others are interested PR is welcome!
