### ISSUE TITLE
Single port mode

### ISSUE THREAD

**Issue by masterada** [pion/webrtc#639]
## Summary

Currently every candidate created will open up a new UDP connection. This makes it hard to configure some loadbalancers/firewalls that do not support configuring port ranges, and can also impact performance if there are thousands of forwarded ports. I would like to suggest a `single port mode` option that allows listening on a single UDP port instead. This consists of 2 parts:

1. Server reflexive candidates should not open a separate port, but use the same port as the corresponding host candidate. Some examples in the rfc suggests this kind of behaviour, although it's never stated explicitly

RFC: https://tools.ietf.org/html/rfc8445#appendix-B.2
> The initiating agent obtains a host candidate on its IP address on
   network C (10.0.1.100:2498) and a host candidate on its IP address on
   network A (192.168.1.100:3344).  It performs a STUN query to its
   configured STUN server from 192.168.1.100:3344. 

2. The rfc contains some notes about the possiblity of using a single ICE candidate for multiple ICE sessions. I think it would be possible to gather local candidates once, and share them through the whole lifetime of the server. The packets can be sorted based on the source address returned by PacketConn.ReadFrom .

RFC: https://tools.ietf.org/html/rfc8445#section-8.3.1
> (a candidate may be used by multiple ICE sessions, e.g., in forking scenarios)

## Motivation

To make loadbalancer/firewall configurations simpler by only listening on a single UDP port. Will be also useful once TCP support is implemented, because the server can listen on tcp port 80 (some hotel/public wifis only allow outgoing requests to TCP port 80 and 443).

## Implementation ideas

I can think of two ways to implement this, and I would be happy to do either of them (or anything else if someine has a better idea):
- make candidate gathering pluggable (with a Candidate interface), and write a plugin for single port mode
- make a configuration option for single port mode, and modify the candidate struct to handle multiple connections (and multiple agents).

## Questions

- What do you think of the idea in general?
- Would you like (1.) to be part of the core functionality?
- Would you like (2.) to be part of the core functionality?
- Would you mind if I made the gathering part of the agent pluggable in order to support this?

**Comment by Sean-Der** [comment]
Hey @masterada 

You can do this right now! I shared this modification a little while back to our example for `gstreamer-send` https://gist.github.com/Sean-Der/80cfd8e0555c51ade56aa73f86b1a965

This should cover your use case! Right now our design has been `All non-standard behavior goes in the SettingEngine`, I think this will continue to work but if not I am all ears!

**Comment by Sean-Der** [comment]
We also have a systemic issue around poor-documentation/user experience.

I am trying to get pion.ly off the ground, but haven't had much luck (I am working on wireframes atm)

**Comment by jinleileiking** [comment]
Closed for now. Reopen ss your wish

**Comment by Sean-Der** [comment]
Hey @jinleileiking 

Lets give @masterada 24 hours to respond, I am not sure if this solves the issue for him yet! Could be other issues that come up.

thanks!

**Comment by masterada** [comment]
@Sean-Der thanks, but this is not exactly what i'm looking for. You example only allows a single peer connection. The second PeerConnection will not have any host candidates, and there is also a warning in the log about it: `warn ice: could not listen udp 172.18.0.3`. Also, server reflexive candidates currently ignore this setting altogether (this is noted on the SetEphemeralUDPPortRange method).

**Comment by jinleileiking** [comment]
Are you looking for reoffer？

And welcome to the slack

**Comment by Sean-Der** [comment]
@masterada  Oh I see what you mean!

You are right, not possible out of the box! You want each PeerConnection to share one socket, and then demux depending on the src address.

If you don't mind doing a full proposal first, and we can get feedback and iterate on it I am in full support! I would prefer it be pluggable, we are building up lots of options around ICE and maybe we can get away from that going down this route.

thanks

**Comment by masterada** [comment]
thanks, extended the contributing wiki page:
https://github.com/pion/webrtc/wiki/Contributing

**Comment by masterada** [comment]
Sadly this is not possible. 

During ice connectivity checks, if there is an incoming stun binding request from a previously unknown remote address, there is no way of knowing who sent the packet (normally the sender address is turned into a peer reflexive candidate). So the server could actually build the connection, but there would be no way of knowing who we built the connection with :D

**Comment by niklaskorz** [comment]
https://github.com/notedit/media-server-go is able to run on a single port, so surely it should be possible to do this in Pion as well?
I currently have no time to investigate this further (maybe next month), but in this case, I think it would make sense to leave this issue open.

**Comment by Sean-Der** [comment]
@niklaskorz @Prinzhorn thanks for the kind words about Pion :) and I do think this is possible! Possibly not in `pion/ice`.

We can put some sort of `tee` in front of each PeerConnection, and it would handle demuxing the traffic. For `peer-reflexive` traffic we could check each packet and see which uPwd/uFrag matches. This could use the same infrastructure as `vnet` so I don't think there is anything extra we need to add. I we could just call it `icedemux` or something like that.

We need to have some basic error handling and return errors if we can't properly demux the remote (same 3 tuple shared by two peers) but beyond that I don't see any reason this couldn't work!

We do have the ability to restrict ports currently if that is helpful! Two PeerConnections may not share the same socket however.

**Comment by Sean-Der** [comment]
I am available in [Slack](https://pion.ly/slack) if you want to chat. Happy to answer questions about WebRTC/Pion and see what I can do to help :)

**Comment by Sean-Der** [comment]
This is tracked in https://github.com/pion/webrtc/wiki/Big-Ideas#single-port-mode now

I am moving all our `Big Ideas` tickets into the wiki, having so many GitHub issues is causing some things to get missed.

**Comment by avarf** [comment]
Hi,
Is there any update regarding adding single-port mode?

**Comment by sahdman** [comment]
Hey, I had the same requirement, so went up and implemented a single mode for pion/ice and used it in my application. It may not be a very standard, but does the job well. 

You can check it out here - https://github.com/sahdman/ice

I am still working on it, and will make it more configurable in the coming days.

**Comment by keverw** [comment]
@sahdman Very neat! Hopefully things be more stable and can be merged into the main project. A little over my head personally. I got an idea for a virtual world type project, but right now just bits of codes and ideas. I decided to go back to school again, but planning to just play with it on the side as a hobby since a lot of the tech I want to use is bleeding edge.

But this would be great for corporate firewalls, then if you have a backend using containers simpler system. I haven't worked with Go too much, but I think when I'm farther along I'd probably write a sorta proxy in Go and then my main business logic in Node/TypeScript, and just stick both projects in the same container. Maybe write a micro supervisor where it just forks the node process and watches it.

**Comment by lzhou-em** [comment]
@sahdman good works. There are some tricks in https://github.com/notedit/media-server-go to multiplex single port.
1. using remote ip&port to identify peer
2. ssrc of RTCP. They enforce an incremental sender's ID to identify different stream. It's useful when relay many streams between two media servers, in which each stream must have unique ID.

Single port is import for using webrtc in media server, hope it can be merged into master

**Comment by ForestJohnson** [comment]
Is this implemented by https://github.com/pion/webrtc/tree/master/examples/ice-single-port ??

**Comment by Sean-Der** [comment]
@ForestJohnson Yes that is the example of the feature described here.

**Comment by Sean-Der** [comment]
If you have any questions happy to help here or on [Slack](https://pion.ly/slack)

**Comment by ForestJohnson** [comment]
Thanks. I'm going to try using this with uPnP (universal plug n play) to create a WebRTC-peer-on-the-server who can be connected to by a web browser on an LTE network (its behind what I believe is called a "symmetric NAT", where browser-to-browser WebRTC normally  wont work without TURN), and I will report back.

**Comment by allright** [comment]
It is a good Idea to have for WebRTC SFU only two candidates TCP and UDP on 443 port.
And you can spread RTP streams, coming to this port only by SSRC.
But pion does not support this thing.
One to many.
Many connections from different IP:PORTS to single 443 port.

But:
 https://github.com/pion/webrtc/issues/639#issuecomment-487084335

May we can find out the workaround for this ?

**Comment by Sean-Der** [comment]
Hi @allright 

Would you mind explaining more? I don't understand the issue.

Pion does support many remote candidates connect to the same 443 port (and is demuxed properly)

What impact would SSRC have on the demuxing?

**Comment by allright** [comment]
> Hi @allright
> 
> Would you mind explaining more? I don't understand the issue.
> Pion does support many remote candidates connect to the same 443 port (and is demuxed properly)

I want to have only 443 UDP port opened on media server.
So all candidates, which PeerConnection generates will be for 443 UDP port.
But, when I configure this way:

```
	m := &webrtc.MediaEngine{}
	if err := m.RegisterDefaultCodecs(); err != nil {
		return
	}

	i := &interceptor.Registry{}
	if err := webrtc.RegisterDefaultInterceptors(m, i); err != nil {
		return
	}
	s := webrtc.SettingEngine{}

	s.SetEphemeralUDPPortRange(443, 443)

	api := webrtc.NewAPI(
		webrtc.WithMediaEngine(m),
		webrtc.WithInterceptorRegistry(i),
		webrtc.WithSettingEngine(s))
```
I figured out that only the first created server PeerConnection is able to connect with client PeerConnection.

If I allow bigger port range - all is OK.

This does not correlate with:
"Pion does support many remote candidates connect to the same 443 port"

Please provide correct pion configuration for "one to many".

**Comment by Sean-Der** [comment]
Awesome! If you ever have any questions always happy to help on here or [Slack](https://pion.ly/slack)

**Comment by shynome** [comment]
Hi, I have try using single port mode with offer, but it's failed, data channel is connecting forever

run `TestDC`, you will see the second pc data channel state is connecting (loop)
```go
package main

import (
	"context"
	"log"
	"net"
	"testing"
	"time"

	"github.com/pion/ice/v3"
	"github.com/pion/webrtc/v4"
	"github.com/shynome/err0/try"
)

var offerCh = make(chan webrtc.SessionDescription)
var answerCh = make(chan webrtc.SessionDescription)

func TestMain(m *testing.M) {
	eg := webrtc.SettingEngine{}
	c := try.To1(net.ListenUDP("udp", &net.UDPAddr{Port: 0}))
	udp := ice.NewUDPMuxDefault(ice.UDPMuxParams{UDPConn: c})
	// udp := try.To1(ice.NewMultiUDPMuxFromPort(0))
	eg.SetICEUDPMux(udp)
	api := webrtc.NewAPI(webrtc.WithSettingEngine(eg))
	go func() {
		for offer := range offerCh {
			go handle(api, offer)
		}
	}()
	m.Run()
}

func TestDC(t *testing.T) {
	eg := webrtc.SettingEngine{}
	if true {
		c := try.To1(net.ListenUDP("udp", &net.UDPAddr{Port: 7799}))
		defer c.Close()
		udp := ice.NewUDPMuxDefault(ice.UDPMuxParams{UDPConn: c})
		eg.SetICEUDPMux(udp)
	}
	// udp := try.To1(ice.NewMultiUDPMuxFromPort(7799))
	// defer udp.Close()
	api := webrtc.NewAPI(webrtc.WithSettingEngine(eg))
	for _, index := range []int{1, 2} {
		log.Println("index", index)
		ttt(api)
	}
}

func ttt(api *webrtc.API) {
	wcfg := webrtc.Configuration{}
	pc := try.To1(api.NewPeerConnection(wcfg))
	dc := try.To1(pc.CreateDataChannel("xhe", nil))
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	dc.OnOpen(func() {
		log.Println("opennnnn")
		dc.SendText("hello")
	})
	dc.OnMessage(func(msg webrtc.DataChannelMessage) {
		log.Println("msg", string(msg.Data))
		cancel()
	})
	offer := try.To1(pc.CreateOffer(nil))
	try.To(pc.SetLocalDescription(offer))
	offer = *pc.LocalDescription()
	offerCh <- offer
	answer := <-answerCh
	// log.Println("answer", answer.SDP)
	go func() {
		t := time.NewTicker(time.Second)
		defer t.Stop()
		for {
			select {
			case <-t.C:
				log.Println("dc state", dc.ReadyState())
			case <-ctx.Done():
				return
			}
		}
	}()
	try.To(pc.SetRemoteDescription(answer))

	<-ctx.Done()
}

func handle(api *webrtc.API, sdp webrtc.SessionDescription) {
	wcfg := webrtc.Configuration{}
	pc := try.To1(api.NewPeerConnection(wcfg))
	try.To(pc.SetRemoteDescription(sdp))
	answer := try.To1(pc.CreateAnswer(nil))
	gatherComplete := webrtc.GatheringCompletePromise(pc)
	try.To(pc.SetLocalDescription(answer))
	<-gatherComplete
	answer = *pc.LocalDescription()
	answerCh <- answer
	pc.OnDataChannel(func(dc *webrtc.DataChannel) {
		dc.OnMessage(func(msg webrtc.DataChannelMessage) {
			dc.SendText("world")
		})
	})
}

```
