### ISSUE TITLE
Add project status in readme

### ISSUE THREAD

**Issue by jinleileiking** [pion/webrtc#640]
Like libp2p. There will be a pic show the issue status.

[![Throughput Graph](https://graphs.waffle.io/libp2p/go-libp2p/throughput.svg)](https://waffle.io/libp2p/go-libp2p/metrics/throughput)

There seems to have stargazer too. I can not find the example

**Comment by Sean-Der** [comment]
Oh yea this great! Would love to see something like this in the README.

We really need to burn down PRs/Issues more, haven't had much free time lately.

**Comment by jinleileiking** [comment]
waffle is closed. Does not know other links.
