### ISSUE TITLE
Add pull request requirements to contributing page

### ISSUE THREAD

**Issue by masterada** [pion/webrtc#641]
Please add the pull request requirements to https://github.com/pion/webrtc/wiki/Contributing, it's very hard to reverse engineer the travis pipeline to make all tests pass. I suggest adding something like this:

### Linting
Code must pass all enabled linters. 
- `golangci-lint run`
- `cd examples && golangci-lint run -D gochecknoinits`

### Running tests
There are two modes to run tests.
- pure go: `go test -race -v ./...`
- wasm binding: `yarn install && GOOS=js GOARCH=wasm go test -exec="./test-wasm/go_js_wasm_exec" -v ./...`

Both set of tests must run without an error.

### Code coverage
Code coverage percentage must not be reduced by the contribution.

### Commit messages
Commit messages must be in the form:
```
Subject line, capitalized, no period, max 50 chars

Commit message body, describe the changes exactle here. Use full
sentences. Wrap the commit message body at 72 characters.
```

### Contributor
The contributor's name (the commiter's name) must be added to the README.md.

**Comment by jinleileiking** [comment]
Goooood issue. Every contributor will encounter this issue. Then sean will give the same answer EVERY TIME. 😂😂🤣

**Comment by Sean-Der** [comment]
Hey @masterada 

Thank you so much for writing this up/sticking with it :) I agree that contributing to Pion is harder then it needs to be. I would love to change things/make it easier for everyone.

I added you to the organization, you should have access to change everything now. I would love to work together 1:1 and figure out how I can encourage future people (and get you more involved)

thanks again!

**Comment by masterada** [comment]
thanks, extended the contributing wiki page:
https://github.com/pion/webrtc/wiki/Contributing
