### ISSUE TITLE
Log the peerconnection id.

### ISSUE THREAD

**Issue by jinleileiking** [pion/webrtc#647]
## Motivation

For now, there is no log about pc id. We should make a uid for each connection/socket . When there  are many pcs, it is easy for debugging

**Comment by Sean-Der** [comment]
@jinleileiking 

WebRTC doesn't have concept of `PeerConnection id` unfortunately so I don't know how we would implement this https://www.w3.org/2018/04/12-webrtc-minutes#item06

**Comment by Sean-Der** [comment]
If you have an alternative proposal/other ideas I am happy to explore them! Just don't see a clear path forward right now :(

**Comment by jinleileiking** [comment]
What about use the address of `PeerConnection`?

**Comment by trivigy** [comment]
@jinleileiking Not entirely sure what you mean by address of peerConnection. A peer connection uses ICE process under the hood which negotiates multiple addresses. Furthermore, these underlying addresses sometimes are renegotiated during a session.

One way you can introduce the idea of IDs is by using the encryption keys and simply hashing the public key using some kind of hashing function. That does seem like an application level implementation requirement.

**Comment by Sean-Der** [comment]
Also thinking about it we also have to log everything under all the subsystems (ICE, DTLS, SCTP...) and I don't see how that would be possible.

I think a few production users like @hugoArregui have robust logging solutions so might be worth asking them and then we can write a `Knowledge Base` post on it.

This is a great idea/problem to solve though. We need to solve this, but don't think we can do it in the code :(

**Comment by enobufs** [comment]
@jinleileiking One you think could do is create your own logger factory for each instance of peer connection (via [SettingEngine](https://godoc.org/github.com/pion/webrtc#SettingEngine)) to dump logs into separate files.

**Comment by hugoArregui** [comment]
Indeed! Since the LoggerFactory starts from the peer connection but then spreads everywhere, you can use it to customize whatever you want at connection level, I use it to log a peer id everywhere:

https://github.com/decentraland/webrtc-broker/blob/master/internal/webrtc/webrtc.go#L47
https://github.com/decentraland/webrtc-broker/blob/master/internal/logging/logging.go

But you can also dump each connection to a file as @enobufs suggests or whatever you want.
