### ISSUE TITLE
v2.0.12 examples sfu-minimal is not work!

### ISSUE THREAD

**Issue by dearkk** [pion/webrtc#663]
before v2.0.10, I use webrtc api  test video sfu is normal but update to v2.0.12 my projuect can't work normally video transfer to peer but not show out, I see the chrome debug info show packet loss is very serious.  what different v2.0.12 to before？

**Comment by Sean-Der** [comment]
Hey @dearkk 

I just was able to use `minimal-sfu` with one publisher and two viewers.

What browser are you using? Is it possible that network conditions have changed at all.

thanks!

**Comment by Sean-Der** [comment]
Hey @dearkk 

I am going to close for now since I can't reproduce. If you can find a specific commit I would to help. I am available on [Slack](https://pion.ly/slack) to help at anytime.

thanks for using Pion!
