### ISSUE TITLE
Remove annoying log from datachannel on pc.Close()

### ISSUE THREAD

**Issue by trivigy** [pion/webrtc#664]
### Your environment.
  - Version: v2.0.12

### What did you do?
Calling `peerConn.Close()` on a peer with a datachannel attached causes the printout of some unhandled errors.
```
ortc ERROR: 2019/05/07 11:11:18 Failed to accept data channel: The association is closed
ortc ERROR: 2019/05/07 11:11:18 Failed to accept data channel: The association is closed
```

### What did you expect?
No error messages to be printed to the screen.

### Investigation Results
The actual printout is produced by this line https://github.com/pion/webrtc/blob/master/sctptransport.go#L142 which returns this error https://github.com/pion/sctp/blob/master/association.go#L26. I followed the sequence of events and it seems that once a datachannel is created and consequently an association is initialized, the sctp association start procedure creates a goroutine https://github.com/pion/webrtc/blob/master/sctptransport.go#L101 for handling passing datachannel creating. In particular, the `datachannel.Accept()` is called and blocked on https://github.com/pion/datachannel/blob/master/datachannel.go#L118 waiting for a new stream to be submitted at https://github.com/pion/sctp/blob/master/association.go#L1019. The issue that occurs is that when the underlying `peerConn.Close()` is called, the sequence of events causes `a.acceptCh` to close and return an error, which is an expected behavior, however the `acceptDataChannels()` function doesn't handle the error gracefully as an expected association termination and prints an error.

**Comment by trivigy** [comment]
Figured out more information and just wanted to record it here. It looks like the `pion/sctp` doesn't handle the ABORT chunk properly. According to the RFC https://tools.ietf.org/html/rfc4960#section-3.3.7 and https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-close (sec. 7) this should be used during the pc.Close() procedure. This should be the "indicator" to the other side that the association is being terminated completely and no errors should be printed.

**Comment by enobufs** [comment]
The plan:

1. Return io.EOF from AcceptStream() when acceptCh closes (Currently, that's the only error we return from the func)
2. Modify SCTPTransport.acceptDataChannels() to log only when the err is not io.EOF. (in case we introduce other errors from AcceptStream())

> io.EOF has been used different places to indicate "the end".
