### ISSUE TITLE
Sending a large amount of data after initial connection is never received

### ISSUE THREAD

**Issue by PaulBGD** [pion/webrtc#677]
### Your environment.
  - Version: master
  - Browser: not relevant
  - Other Information - https://github.com/PaulBGD/webrtc/commit/7e8a7e29e8ad5c0f461acb94bc60a47941236e27

### What did you do?
Sending a large initial byte array, then a second small byte array causes both buffers to not be received (although when the first byte array is at the max size of 65535 I noticed that sending a third byte arraycauses all three to be received)

### What did you expect?
All data should be sent and received

### What happened?
Messages were not received

I slightly modified `pion-to-pion` to produce a simple test case of the issue here: https://github.com/PaulBGD/webrtc/commit/7e8a7e29e8ad5c0f461acb94bc60a47941236e27

**Comment by Sean-Der** [comment]
Hey @PaulBGD 
Sorry for the delay, triaging all our issues now.

I *believe* this is fixed! Using your example I get the following. It looks like the answerer gets both messages now.
```
seaduboi@38f9d359441f:~/go/src/github.com/pion/webrtc/examples/pion-to-pion/answer$ go run main.go
Listening on :50000
ICE Connection State has changed: checking
ICE Connection State has changed: connected
New DataChannel data 824635376880
Data channel 'data'-'824635376880' open. Random messages will now be sent to any connected DataChannels every 5 seconds
Message from DataChannel 'data': '%!s(int=16385)'
Message from DataChannel 'data': '%!s(int=1)'
```

**Comment by Sean-Der** [comment]
If you get a chance would really appreciate if you can confirm that, and then we can resolve :) 

I will wait a few days though, totally understand if Pion didn't work out because of this bug. Sorry it took so long, lots of issues came in at once.

**Comment by PaulBGD** [comment]
Yep! All fixed.

No worries, I've actually be running the project in production for over 2 months now. I had a workaround in place for this problem, which ended up working better in browsers anyways.
