### ISSUE TITLE
API: Implement Session Negotiation Model

### ISSUE THREAD

**Issue by backkem** [pion/webrtc#70]
Implement [Session Negotiation Model](https://w3c.github.io/webrtc-pc/#x4-7-session-negotiation-model) 

**TODO** (Among others)
- [ ] Determine how to 'debounce' the NegotiationNeeded event without operations queue
- [ ] NegotiationNeeded event

**Comment by Sean-Der** [comment]
This is done!

* We have an operations queue
* We have `NegotiationNeeded`
