### ISSUE TITLE
Datachannels don't reconnect when ICE comes back

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#706]
I haven't confirmed this personally, as a start we need to write a test to confirm exactly how this happens (and then make sure it doesn't regress)

**Comment by enobufs** [comment]
Ref: [5.1.9 RTCIceState Enum](https://dev.w3.org/2011/webrtc/editor/webrtc-20120920.html#rtcicestate-enum)

**Comment by Sean-Der** [comment]
@enobufs this is a great use case for `vnet`!

We could add something that drops all traffic for n seconds (enough for ICE to fail) and then bring it back and check on how things do.
