### ISSUE TITLE
OnSelectedCandidatePairChange doesn't work

### ISSUE THREAD

**Issue by enobufs** [pion/webrtc#713]
### Your environment.
  - Version: v2.0.22
  - Browser: n/a

### What did you do?
Attempted to set callback handler via OnSelectedCandidatePairChange() in order to learn the resulting selected-pair for diagnostic purpose.

My app is DC-only.  iceTranport is obtained via dc => sctpTransport => dtlsTransprot => iceTransport...

### What did you expect?
The callback would be made to report the current selected-pair.

#### Offerer:
* Not possible to set the callback because dc.sctpTransport is nil
* When OnOpen is called, sctpTransport was non-nil, but callback was already made (too late)
#### Answerer:
* dc.sctpTransport is never set

**Comment by Sean-Der** [comment]
@enobufs 

We need to expose `sctp` as a member of `PeerConnection` and that should be non-nil after `SetLocalDescription` is set.

```
ppc = new RTCPeerConnection(); 
pc.createDataChannel('pion'); 
pc.createOffer().then(o => pc.setLocalDescription(o)); 
console.log(pc.sctp)

RTCSctpTransport {transport: RTCDtlsTransport, state: "connecting", maxMessageSize: Infinity, maxChannels: null, onstatechange: null}
```
