### ISSUE TITLE
Answer tried to set recv when offer did not set send

### ISSUE THREAD

**Issue by thetooth** [pion/webrtc#717]
### Your environment.
  - Version: 2838b1a83649
  - Browser: Firefox 67.0.2

### What did you do?
When setting up a one way broadcast with the client creating the offer and server answering with a video and audio media channel, the SDP exchange fails with "InvalidSessionDescriptionError: Answer tried to set recv when offer did not set send".

I went and read the RFC to double check a change I noticed in #657. The RFC says "If a media stream is listed as recvonly in the offer, the answer MUST be marked as sendonly or inactive in the answer."

I think I understand the reason it was changed to sendrecv, as we can now share tracks between peer connections, this change would make that easy if this attribute is stored in the track itself.

Perhaps we could compare the offer when creating the answer and erroneously report it as sendonly for compatibility, that way we retain the easy track sharing API.

**Comment by wezzle** [comment]
Unfortunately I ran into the same problem. I tried adding a receiver manually with sendonly but this is not supported and triggers the error `AddTransceiver currently only suports recvonly and sendrecv`.

> Side note: there is a typo in supports

When changing the [PeerConnection's AddTransceiver](https://github.com/pion/webrtc/blob/master/peerconnection.go#L1383) method to include the following case I got it to work:
```go
case RTPTransceiverDirectionSendonly:
	payloadType := DefaultPayloadTypeOpus
	if trackOrKind == RTPCodecTypeVideo {
		payloadType = DefaultPayloadTypeVP8
	}

	track, err := pc.NewTrack(uint8(payloadType), mathRand.Uint32(), util.RandSeq(trackDefaultIDLength), util.RandSeq(trackDefaultLabelLength))
	if err != nil {
		return nil, err
	}

	sender, err := pc.api.NewRTPSender(track, pc.dtlsTransport)
	if err != nil {
		return nil, err
	}

	return pc.newRTPTransceiver(
		nil,
		sender,
		RTPTransceiverDirectionSendonly,
		trackOrKind,
	), nil
```

You can then call:

```go
peerConnection.AddTransceiver(webrtc.RTPCodecTypeVideo, webrtc.RtpTransceiverInit{
	Direction: webrtc.RTPTransceiverDirectionSendonly,
})
```

Before adding a track and creating the answer. The answer will then have `a=sendonly` as expected by Firefox and the RFC.

As I'm unfamiliar with the codebase I have no idea if this is the way to go but I'm happy to create a pull request out of it if one of the contributors can confirm.

**Comment by Sean-Der** [comment]
@wezzle I would love to have you involved! Happy to answer any questions [This](https://pion.ly/knowledge-base/pion-internals/contributing/) hopefully is useful. Would love your feedback on where that document could be better also! It is all on GitHub (in the footer you can get a link directly to the markdown)

---

`AddTransceiver` we can/should extend that! The hard part is you can't specify the codec, not sure how to fix that yet. Maybe we just take the first available codec of that type (audio or video)

@mchlrhw has context on this issue as well. Chromium and FireFox differ behavior wise for pairing Transceivers. Chromium will match a `sendrecv` with a `recvonly` while FireFox will not.

We should confirm this behavior, but this feels like something we should bring up on `webrtc-discuss` and confirm exactly what the behavior should be.

**Comment by mchlrhw** [comment]
As previously mentioned in Slack, this browser-side fix has been tested to work with both Chromium and Firefox: https://github.com/pion/example-webrtc-applications/commit/c641b530a001eb057d8b481185c50bf67d1931b4
It's not ideal, because we should probably try to match the offer in a more compatible way in Pion, but it's a reasonable stop gap; unless someone can see a security hole in setting `sendrcv` when really you want `recvonly`?

**Comment by EdoaLive** [comment]
Hello,
I'm still having trouble with this problem, only with Firefox, only when there's just one track (only audio, only video, or only desktop) in a stream.

- Version: v2.2.17
- Firefox: 78.0.2 (64-bit)

Firefox seems to create an SDP with at least 2 tracks, one of which is set to recvonly, and does not like the answer.
Here's what Firefox is sending as SDP with only a video track (webcam) enabled:
```
v=0
o=mozilla...THIS_IS_SDPARTA-78.0.2 8230216235499582354 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 0B:BC:E4:9D:FE:C8:7C:B0:80:51:00:89:D2:89:65:9D:3C:D0:AC:21:4E:A3:75:E4:9D:1D:4D:1E:7F:6B:3D:D6
a=group:BUNDLE 0 1
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 UDP/TLS/RTP/SAVPF 120 121 126 97
c=IN IP4 0.0.0.0
a=sendrecv
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
a=extmap:6/recvonly http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:120 max-fs=12288;max-fr=60
a=fmtp:121 max-fs=12288;max-fr=60
a=ice-pwd:15fd3acc2db4ae284c3ad1b7014f30f8
a=ice-ufrag:08958635
a=mid:0
a=msid:{6e7e5a2a-ff2f-4097-92e6-8202a5e7e903} {9f775b83-90bc-4223-b24b-4f8059934320}
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtpmap:121 VP9/90000
a=rtpmap:126 H264/90000
a=rtpmap:97 H264/90000
a=setup:actpass
a=ssrc:1081107407 cname:{cc048206-ad61-4e57-bfca-17a60f774dcf}
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=recvonly
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:15fd3acc2db4ae284c3ad1b7014f30f8
a=ice-ufrag:08958635
a=mid:1
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:3196314260 cname:{cc048206-ad61-4e57-bfca-17a60f774dcf}
```

**Comment by Sean-Der** [comment]
If someone is interested in taking this here is a test they can drop in! 

```
// TestPeerConnection_Transceiver_Direction asserts that after 
// matching transceivers are matched we return the proper direction 
func TestPeerConnection_Transceiver_Direction(t *testing.T) { 
  lim := test.TimeOut(time.Second * 30)
  defer lim.Stop()
 
  report := test.CheckRoutines(t)
  defer report()
 
  assertTransceiverDirections := func(offerDirection, answerDirection RTPTransceiverDirection, sdpValue string) {
    pcOffer, pcAnswer, err := newPair()
    assert.NoError(t, err)
 
    _, err = pcOffer.AddTransceiverFromKind(
      RTPCodecTypeVideo,
      RtpTransceiverInit{Direction: offerDirection},
    )
    assert.NoError(t, err)
 
    _, err = pcAnswer.AddTransceiverFromKind(
      RTPCodecTypeVideo,
      RtpTransceiverInit{Direction: answerDirection},
    )
    assert.NoError(t, err)
 
    offer, err := pcOffer.CreateOffer(nil)
    assert.NoError(t, err)
 
    assert.NoError(t, pcAnswer.SetRemoteDescription(offer))
    answer, err := pcAnswer.CreateAnswer(nil)
    assert.NoError(t, err)
 
    assert.Contains(t, answer.SDP, sdpValue)
 
    assert.NoError(t, pcOffer.Close())
    assert.NoError(t, pcAnswer.Close())
 
  }
 
  t.Run("offer sendrecv/answer sendrecv", func(t *testing.T) {
    assertTransceiverDirections(RTPTransceiverDirectionSendrecv, RTPTransceiverDirectionSendrecv, "a=sendrecv\r\n")
  })
 
  t.Run("offer send/answer sendrecv", func(t *testing.T) {
    assertTransceiverDirections(RTPTransceiverDirectionSendonly, RTPTransceiverDirectionSendrecv, "a=recvonly\r\n")
  })
 
  t.Run("offer recv/answer sendrecv", func(t *testing.T) {
    assertTransceiverDirections(RTPTransceiverDirectionRecvonly, RTPTransceiverDirectionSendrecv, "a=sendonly\r\n")
  })
} 
```

**Comment by rajnada** [comment]
**KVSWEBRTC LIVE STREAMING IS NOT WORKING IN FIREFOX BROWSER**

when I try to play video in firefox. I will get an answer and then received "event" in which I got the "stream: restricted" attribute,
while the same video works perfectly on google chrome and I also got a media stream object

**Error in Firefox:-**
DOMException: Answer tried to set recv when an offer did not set send

**Logs of Mozilla Firefox:-**

this is a screenshot of the Mozilla Firefox log for reference:-
https://prnt.sc/112azpx

**Logs of Google chrome:-**

this is a screenshot of the google chrome log for reference:-
https://prnt.sc/112ay7m

**the answer which I received:-**

answer => {type: "answer", sdp: "v=0
↵o=- 461485223 2 IN IP4 127.0.0.1
↵s=-
↵t=0 0
…x/90000
↵a=fmtp:118 apt=123
↵a=rtcp-fb:123 nack
↵"}sdp: "v=0
↵o=- 461485223 2 IN IP4 127.0.0.1
↵s=-
↵t=0 0
↵a=group:BUNDLE 0 1
↵a=msid-semantic: WMS myKvsVideoStream
↵m=audio 9 UDP/TLS/RTP/SAVPF 0
↵c=IN IP4 127.0.0.1
↵a=msid:myKvsVideoStream myAudioTrack
↵a=ssrc:534900171 cname:u+sFyw1MPSrSqi6F
↵a=ssrc:534900171 msid:myKvsVideoStream myAudioTrack
↵a=ssrc:534900171 mslabel:myKvsVideoStream
↵a=ssrc:534900171 label:myAudioTrack
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=ice-ufrag:Mz3o
↵a=ice-pwd:QVRV2NtgRaAQvNahNU2OSQQy
↵a=ice-options:trickle
↵a=fingerprint:sha-256 FD:CA:06:7D:2C:6F:DF:9B:DB:2C:C8:DA:88:96:25:C8:6D:1F:B6:C4:FB:B2:5D:9E:35:34:A4:0F:F5:42:80:B5
↵a=setup:active
↵a=mid:0
↵a=sendrecv
↵a=rtcp-mux
↵a=rtcp-rsize
↵a=rtpmap:0 PCMU/8000
↵a=rtcp-fb:0 nack
↵m=video 9 UDP/TLS/RTP/SAVPF 123 118
↵c=IN IP4 127.0.0.1
↵a=msid:myKvsVideoStream myVideoTrackRTX
↵a=ssrc-group:FID 2062660401 318622851
↵a=ssrc:2062660401 cname:u+sFyw1MPSrSqi6F
↵a=ssrc:2062660401 msid:myKvsVideoStream myVideoTrack
↵a=ssrc:2062660401 mslabel:myKvsVideoStream
↵a=ssrc:2062660401 label:myVideoTrack
↵a=ssrc:318622851 cname:u+sFyw1MPSrSqi6F
↵a=ssrc:318622851 msid:myKvsVideoStream myVideoTrackRTX
↵a=ssrc:318622851 mslabel:myKvsVideoStreamRTX
↵a=ssrc:318622851 label:myVideoTrackRTX
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=ice-ufrag:Mz3o
↵a=ice-pwd:QVRV2NtgRaAQvNahNU2OSQQy
↵a=ice-options:trickle
↵a=fingerprint:sha-256 FD:CA:06:7D:2C:6F:DF:9B:DB:2C:C8:DA:88:96:25:C8:6D:1F:B6:C4:FB:B2:5D:9E:35:34:A4:0F:F5:42:80:B5
↵a=setup:active
↵a=mid:1
↵a=sendrecv
↵a=rtcp-mux
↵a=rtcp-rsize
↵a=rtpmap:123 H264/90000
↵a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
↵a=rtpmap:118 rtx/90000
↵a=fmtp:118 apt=123
↵a=rtcp-fb:123 nack
↵"type: "answer"proto: Object

Can anyone help me with this situation
thank you in advance :)

**Comment by luxurystorecc1** [comment]
Corporate Wellness: The Impact of Active Wear in the Office
Introduction: The Health-Conscious Workplace
The workplace of 2026 has undergone a wellness revolution. Corporations are now encouraging active movement throughout the day, leading to a new dress code that prioritizes physical health and mobility. Leading this cultural shift are the [Air Jordan 1 retro high-top sneakers](https://www.airjordan-1.com/), which have become the standard-bearer for the "Corporate-Active" aesthetic.

Bridging the Gap Between Sport and Business
Modern professionals need clothing that facilitates a midday gym session or a walking meeting. The [Jordan 1s high-performance basketball shoes](https://www.jordan1s.com/) provide the technical integrity for physical activity while maintaining a prestige look. For a more conservative office environment, the [classic Jordan 1 mid-top variations](https://www.jordan1s.com/) offer a sleek silhouette that pairs well with tailored trousers.

Innovation is also seen in the [adidas Yeezy boost collection](https://www.yeezyboost-350.com/collections/adidas-yeezy), which provides all-day cushioning for professionals who are constantly on the move. For creative offices, [premium Yeezy slides and foam runners](https://www.yeezyboost-350.com/) have become acceptable symbols of a progressive, health-focused work culture.

Networking Through Sports Culture
The office environment is a hub for social connection, often centered around shared sports interests. Utilizing the [official NFL shop online store](https://www.nflshopofficialonline-store.com/) ensures that your workplace fan gear is authentic and professional. The trend of the [customized replica NFL jersey](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) allows employees to build personal connections based on shared team loyalty.

Global sports influence is also visible in the workplace through items like the [Spain national team soccer jersey](https://www.soccerjerseysstore.com/collections/national-teams-europe-spain) and [MLS jerseys for soccer fans](https://www.soccerjerseysstore.com/collections/national-teams). These pieces are often accessorized with [NFL headwear and official team caps](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear), blending professional success with an active lifestyle.

Elite Performance: Peter Millar
For executives who lead the wellness movement, [Peter Millar clothing for golf and lifestyle](https://www.peter-milla.com/) offers a sophisticated solution. These garments are designed to move with the wearer, providing a level of comfort that supports a focused, productive workday. The [Peter Millar luxury apparel line](https://www.peter-milla.com/) continues to define the standard for the modern, healthy professional.
