### ISSUE TITLE
Failed to run examples

### ISSUE THREAD

**Issue by zerjioang** [pion/webrtc#723]
### Your environment.
  - Version: *Release or SHA*
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

just downloaded example project to check it out and package internal could no tbe resolved via dep tool

### What did you expect?

to have a successful working example code

### What happened?

`internal` package of example packages cannot be downloaded via `dep` tool

**Comment by Sean-Der** [comment]
Hey @zerjioang 

We only support modules [FAQ](https://pion.ly/knowledge-base/pion-basics/faq/#when-running-any-pion-webrtc-code-i-get-cannot-find-package-github-com-pion-webrtc-v2)

dep does have a PR to support them, but it looks like development has stalled.

thanks for checking out Pion! Sorry about it not working with dep, unfortunately I don't think there is anything we can do on our side to fix.
