### ISSUE TITLE
IVFWriter does not write frame count on close

### ISSUE THREAD

**Issue by shouichi** [pion/webrtc#731]
### Your environment.
  - Version: v2.0.23
  - Browser:
  - Other Information:

### What did you do?

I was reading the `ivfwriter` package and realized that `IVFWriter` instantiated by `NewWith` does not write frame count on close. `IVFWriter.Close` only writes frame count if `IVFWriter.fd` is non nil but `NewWith` does not set `IVFWriter.fd`. See the following excerpt.

```
func NewWith(out io.Writer) (*IVFWriter, error) {
	writer := &IVFWriter{
		stream: out,
	}
	return writer, nil
}

func (i *IVFWriter) Close() error {
	if i.fd == nil {
		// Returns no error as it may be convenient to call
		// Close() multiple times
		return nil
	}
}
```

### What happened?

**Comment by Sean-Der** [comment]
Hey @shouichi 
Thanks for the bug report (and using Pion WebRTC!)

I am not sure what we can do here unfortunately. If we don't have a `fd` we can't rewind and update frame count. We also can't buffer if we are doing `NewWith`, would it be helpful if we added a function so you can extract the frame count?

**Comment by shouichi** [comment]
> We also can't buffer if we are doing `NewWith`, would it be helpful if we added a function so you can extract the frame count?

Sounds reasonable. In addition, it would be great if the current behavior is clearly documented.

Thanks for the awesome project, it helped me a lot to understand WebRTC (thanks to the project being pure go). Talking about pure go, https://github.com/pion/example-webrtc-applications which uses cgo is also great 👍

**Comment by seppo0010** [comment]
I think this issue can be closed now, @Sean-Der

**Comment by Sean-Der** [comment]
Hey @seppo0010 

Thanks for triaging issues! I added you to the `pion` organization, feel free to close/prune any ticket you see.
