### ISSUE TITLE
Write v2.1.0 Release Notes

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#732]
----

The Pion team is excited to announce the `v2.1.0` release of Pion WebRTC. This release represents 3 months of feature development and testing across a variety of Pion projects. The headline features are:

# TURN Support
Thanks to @enobufs  Pion WebRTC now has full TURN support. This has been tested against multiple Open Source and hosted TURN providers.

# Stats
@hugoArregui has added support for [webrtc-stats](https://www.w3.org/TR/webrtc-stats/). This initial implementation collects stats related to the PeerConnection, DataChannels, ICECandidates and ICECandidatePairs. The status and remaining work is being tracked in [#610](https://github.com/pion/webrtc/issues/610)

# mDNS Host Candidates
WebRTC has added mDNS candidates to help with privacy when using WebRTC, you can read the RFC [here](https://tools.ietf.org/id/draft-ietf-rtcweb-mdns-ice-candidates-02.html). We are able to parse and connect to these candidates. Currently we don't generate them, but in the future we will make this controllable by the user.

# vnet
Pion WebRTC now implements a virtual network layer. You can read more about it [here](https://github.com/pion/transport/tree/master/vnet). This feature allows people to construct networks that only exist in software. This will allow users to simulate real world network conditions simulating NATs, packet loss, bandwidth and jitter without every actually sending a packet. Thanks to this feature written by @enobufs we have fixed multiple bugs in `pion/turn` and `pion/ice` already!

# Trickle ICE
Trickle ICE is now available! This is controlled by the SettingEngine. We will make this the default in Pion `v3` since it is a breaking change, and is not apparent to the user via an API change. Thank you @trivigy for all your work on this.

**Comment by Sean-Der** [comment]
@hugoArregui @enobufs @trivigy (anything I should add/I missed?)

I think `vnet` would be great to write about! I personally want to stop working on anything else and help with `vnet` and make it part of `v2.1.0` after I finish a bug sweep.

**Comment by hugoArregui** [comment]
Maybe stats?

**Comment by Sean-Der** [comment]
Oh yes stats are huge! @hugoArregui you have a blurb in mind (or I can write it!) but I think your words will be much better then mine :)

**Comment by hugoArregui** [comment]
Yes, but please review my english :grin: 

Basic connection stats are now available. This initial implementation collects stats related to the PeerConnection, DataChannels, ICECandidates and ICECandidatePairs. The status and remaining work is being tracked in https://github.com/pion/webrtc/issues/610

**Comment by Sean-Der** [comment]
@enobufs what do you think of adding `vnet`? I think that is something that people would really be interested in.

Even if we can't pass it to the PeerConnection yet I think know would be a great time to get people excited about it!

**Comment by enobufs** [comment]
As a user, the fact that pion is tested with complex network topologies
means a lot. In fact, we identied the problem with rely-prflx case and
fixed it. So, my thumbs up.

**Comment by backkem** [comment]
Sounds like a baller blog post as well.

**Comment by mchlrhw** [comment]
This looks good to me, and I agree with @backkem that it'll be great publicity.

I would maybe change the wording of:
> This contains 3 months of and lots of different work across many different Pion projects. The highlight of these features are.

To something like:
> This release represents 3 months of feature development and testing across a variety of Pion projects. The headline features are:

Mainly because of this bit: "of and lots of different", so feel free to just change that specific wording.

**Comment by Sean-Der** [comment]
Update, thanks for proof reading @mchlrhw :)
