### ISSUE TITLE
Make STUN URL parsing more permissive

### ISSUE THREAD

**Issue by mchlrhw** [pion/webrtc#735]
## Summary

The STUN URL parser in the `ice` package is strict about not allowing URLs in the `stun:` scheme with a query, e.g `stun:global.stun.twilio.com:3478?transport=udp`, and returns `ErrSTUNQuery` if it finds one.

The current implementation of `configuration.go` rejects any URL that errors during parsing:
```go
url, err := ice.ParseURL(rawURL)
if err != nil {
    return nil, err
}
```

Both behaviours are technically correct, but they prevent apps from using ICE configuration generated by a third party without modification (unless the response is completely to spec), e.g. unmarshaling the response to a request to the Twilio Network Traversal API straight into the `Configuration`.

We could solve this by either implementing a more permissive parser that detects queries and strips them before returning the URL, or we could make `getICEServers` more resistant to invalid ICE server config by allowing it to omit invalid URLs, i.e. simply `continue` when we hit an error.

Either solution is more user friendly than a hard fail and could include appropriate WARN-level logging to notify the user that "something is wrong, but we're carrying on with what we've got anyway".

## Motivation

The suggested change would make it easier for users to work with non-compliant ICE server configurations without having to implement any parsing or sanitisation of their own.

## Describe alternatives you've considered

The alternative is to leave the code as-is and leave it up to app developers to sanitise URLs before adding the `ICEServer` struct to the `Configuration`.

**Comment by Sean-Der** [comment]
@mchlrhw Nice catch!

Do we reject things that work in the browser? My vote would be to match that behavior exactly. This also seems like a great candidate for `js` tests as well! Nice way we can match `wrtc` behavior.

**Comment by mchlrhw** [comment]
We pull Twilio ICE server config in the browser using the built-in peer connection API and we don't see any errors, so I believe they are more permissive than Pion. I'm not wuite sure what they do yet though, either ignore or truncate.

**Comment by mjmac** [comment]
Wouldn't it be better to adjust the behavior of ice.ParseURL() to be more permissive? Leaving it to the caller presumes a certain amount of understanding about when an error isn't an error on the part of the caller, which may not always be true. If the browser accepts URLs with these schemes then we should too, IMO.

**Comment by mchlrhw** [comment]
That's a fair point and I'm fine with that approach, I just didn't feel I had enough authority (or experience) to remove the error completely :smile:
My plan once pion/ice#77 was merged was to modify the behaviour of `configuration.go` to detect the error, log a warning, and then use the URL anyway.
Is your preferred solution to start allowing stun(s) URLs with a query?

**Comment by mjmac** [comment]
IMO, we should evaluate what the browser does and mirror that behavior. Some test cases to verify that the code works as expected would help, too.

**Comment by Sean-Der** [comment]
@mchlrhw thanks for the PR/doing all the work here :)

I am always 100% happy if we mirror browser behavior. For this I wouldn't modify `pion/ice`, just nice to keep that simpler. 

I would extended the URL parsing and make them work in `pion/webrtc`. If we add some unit tests to that you got an instant approve from me. Happy to help also if you are short on time!

**Comment by mchlrhw** [comment]
@Sean-Der do you mean move the parsing into `webrtc`? If not then `ice` would have to be modified somehow.

**Comment by Sean-Der** [comment]
@mchlrhw yes I would do the parsing in `webrtc` and leave the URL handling in `ice` as is. I think this might be a `webrtc` only quirk, and just want to keep `ice` ignorant of WebRTC stuff if possible.

I found a couple RFCS, and I think the query makes it invalid. But I think we should match the browser behavior and support it!

https://tools.ietf.org/html/rfc7064
https://tools.ietf.org/html/draft-nandakumar-rtcweb-stun-uri
