### ISSUE TITLE
Asynchronous callback behavior

### ISSUE THREAD

**Issue by ZizhengTai** [pion/webrtc#744]
The Pion `PeerConnection` API is supposed to mirror the JavaScript `RTCPeerConnection` API closely, but the current way Pion (v2.0) runs event handlers is different from what JS does: Pion [spawns a new goroutine](https://github.com/pion/webrtc/blob/master/peerconnection.go#L282) to run the handler, while JS is single-threaded.

For example, the `OnTrack` handler in the [echo example](https://github.com/pion/webrtc/blob/master/examples/echo/main.go#L45) runs an infinite loop, which in JS will block the event loop and prevent everything else from running. The implementation of actual handlers (e.g. [`onTrack`](https://github.com/pion/webrtc/blob/master/peerconnection.go#L270)) also returns a channel, which I guess is supposed to be used as a synchronization mechanism, but is not really used anywhere. (We should probably either use the channels or remove them, but that's a different issue.)

In addition to the deviation from the JS API, a bigger problem is that the built-in parallelism forces users of Pion to handle synchronization to avoid data races caused by callbacks running in parallel. To demonstrate the problem:

```go
func cleanUp(pc *webrtc.PeerConnection) {
  pc.Close()
  nonAtomicallyRemoveFromRegistry(pc)
}

...

pc.OnTrack(func(track *webrtc.Track, ...) {
  for {
    p, err := track.ReadRTP()
    if err != nil {
      cleanUp(pc)
      break
    }
    ... // write to output track
  }
})

pc.OnICEConnectionStateChange(func(st webrtc.ICEConnectionState) {
  switch (st) {
  case
    webrtc.ICEConnectionStateClosed,
    webrtc.ICEConnectionStateDisconnected,
    webrtc.ICEConnectionStateFailed:
    cleanUp(pc)
  ... // other cases
  }
})
```

In the code above, `cleanUp` can be called from different handlers in parallel, causing a data race.

What do people think about making the handlers run in a same goroutine? This adheres to the JS API, and is also more flexible: If the user wants synchronization, they don't need to do anything; if they don't need synchronization and need more parallelism, they can just spawn new goroutines from within the handlers themselves.

**Comment by Sean-Der** [comment]
@ZizhengTai that is a good point! 

We have run into this before, people are confused by `OnMessage` getting fired before the last one has completed. 

This probably is also more expensive then in needs to be right now, we are firing up lots of goroutines for no reason. I would be really interested if we could benchmark it and see how it performs.

It will be hard to change this though, lots of people depend on the current behavior. Maybe we can make it a `/v3` thing?

**Comment by Sean-Der** [comment]
One compromise/idea that might be interesting is using one goroutine for all user facing things. I just want to make sure that users can't block any I/O stuff.

**Comment by ZizhengTai** [comment]
Yeah this is definitely a big breaking change, probably should be a v3 thing.

Also, I think the core issue here is that `PeerConnection` is a JS API, and while it's interface is idiomatic in JS, it's awkward in Go. In Go people usually expect a blocking API and handle concurrency themselves with goroutines. I find it awkward to integrate the current `PeerConnection` API into our existing codebase without introducing a blocking wrapper API on top of it.

Perhaps one thing we can do in Pion (even before v3) is provide an alternative/higher level/more-idiomatic-in-Go interface for `PeerConnection`?

**Comment by ZizhengTai** [comment]
That being said, the focus of this issue is still about the callback behavior. Currently it's a mix of JS (callback, not parallel) and Go (blocking, parallel) idioms which makes it sometimes confusing. It'd be nice if we can provide a consistent API, either adhering to JS or designing specifically for Go.

**Comment by Sean-Der** [comment]
I think the goal should be adhering to the WebRTC API (if possible) when we diverge is probably a mistake.

The only time we have to be careful is if we can cause some user breakage, but if there is no user impact I am happy making changes right away! We have `/v3` planned for when we make Trickle ICE the default.

We probably will do one more `v2` release for re-negotiation and then rip off the band-aid with another major release. I don't have timelines yet though.

**Comment by Sean-Der** [comment]
@ZizhengTai 

Going forward what do you think of cutting this up into smaller issues? I would love to land things/improve them. Would be great to split them up into Breaking/Non-breaking changes and we can land them appropriately. 

I would also totally support the `non-WebRTC API` implementation! If you want I can add you to the Pion organization and you can start prototyping :) I am pretty hands off when it comes to projects though. You will have to do most of the work, but we have a great community that will love to get involved!

**Comment by lherman-cs** [comment]
I totally agree with this topic. It's so awkward to code in Go and hard to get right. I wish that the API used channels rather than callbacks.

**Comment by Sean-Der** [comment]
Hey @lherman-cs 

Thanks for checking out Pion :) if you are interested we would love to have you involved/contributing.

Unfortunately we will never be able to have channels in the public API, we did originally but it caused lots of issues for users https://github.com/pion/webrtc/issues/405

**Comment by Sean-Der** [comment]
I agree that the API can be frustrating, but I think we get more benefits (then negatives) from the callback based API we have today.

* Users coming from JS are able to pick up our API easily. 
* We don't have subjectivity when designing the API. Much less for the devs to bikeshed about.

If someone does want a non-callback based API they can use ORTC today! I haven't seen much interest however. If anyone is interested in implementing/exploring this please re-open and would love to help.
