### ISSUE TITLE
Implement RTCDataChannel onError

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#746]
Currently RTCDataChannel doesn't bubble up errors to users (and just logs them)

Implement `onError` and have it be called in the appropriate places. Search this issue's ID to find all the places that need to be updated.

**Comment by spaceCh1mp** [comment]
I'm not entirely clear on this. should it "bubble up"? and is it just that one place that needs to be updated?

**Comment by Sean-Der** [comment]
Yea just one place that needs to be updated!

We need to `onErrorHandler` member https://github.com/pion/webrtc/blob/master/datachannel.go#L51 and allow users to set it. You can just copy this function and set the appropriate names https://github.com/pion/webrtc/blob/master/datachannel.go#L225

Then when that is done instead of logging this error call the `onErrorHandler` instead https://github.com/pion/webrtc/blob/master/datachannel.go#L298!
