### ISSUE TITLE
Allow for transports to notify PeerConnection of fatal errors

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#754]
We have decoupled transports and the PeerConnection, but now that makes it hard for hard errors to tear down the PeerConnection.

I have made a notes in the code base using this issue # where it is relevant. This will require a careful design to make sure we don't tie things together accidentally again.

**Comment by Sean-Der** [comment]
This is actually really easy! Someone just needs to add `OnError` to `SCTPTransport`. This way it can work both for ORTC and WebRTC.

**Comment by faroyam** [comment]
Hello
Am i right that this issue concerns adding `onErrorHandler` field along with `onError`/`OnError` functions to 'SCTPTransport' structure? Again, correct me if I'm wrong, but if it is what I understand it is, I'll take it.

**Comment by Sean-Der** [comment]
@faroyam exactly! The the `PeerConnection` object can be notified of issues. On creating of the `SCTPTransport` we set those callbacks and we can handle async errors gracefully. 

Also if users want they can construct the `SCTPTransport` themselves and do things via ORTC.

**Comment by Sean-Der** [comment]
Resolved by 896f8e360f96498092b41ae24876de4ba012f63d great work @faroyam !
