### ISSUE TITLE
Is GPU Hardware Acceleration Supported?

### ISSUE THREAD

**Issue by ghafran** [pion/webrtc#773]
Does this framework support hardware acceleration for encode/decode and video rendering from the video streams?

**Comment by csiwek** [comment]
Pion does not transcode media. Encoding and decoding is usually required to provide MCU functionality.

**Comment by Sean-Der** [comment]
Yep that is exactly right!

@ghafran Pion WebRTC only does transport. So if you want to do any media coding you could use something like `ffmpeg`, `GStreamer` or `OpenCV`. If you have any questions about using them I happy to answer on [Slack](https://pion.ly/slack)

thanks for checking out Pion, hope it works out for you!

**Comment by qpaozixu** [comment]
How could I use ffmpeg gpu encoding my opengl render frame and use webrtc to stream to web?

**Comment by Sean-Der** [comment]
Hey @qpaozixu I answered your question over in our discussions area. https://github.com/pion/webrtc/discussions/1648

thanks!
