### ISSUE TITLE
How to obtain SDPMid and SDPMLineIndex from OnICECandidate callback

### ISSUE THREAD

**Issue by lamhai1401** [pion/webrtc#776]
Currently, we need to send candidate signal from pion PeerConnection to other peers, but  they differ in `iceCandidate` interface between `OnICECandidate(func(*webrtc.ICECandidate))` callback and `AddICECandidate(iceCandidate ICECandidateInit)` method.

```go
iceCandidateInit := &webrtc.ICECandidateInit{
  Candidate: iceCandidate.String(),
  SDPMid:           <?>, //Which SDPMid should be pass here 
  SDPMLineIndex:    <?>, //Which SDPMLineIndex should be pass here
  // UsernameFragment: "def",
},
```

and iceCandidate strings are also different between browser and pion

pion
![Screenshot from 2019-08-08 16-55-20](https://user-images.githubusercontent.com/31619361/62694194-13692380-b9fe-11e9-8a12-51cd9a9ed8a5.png)
client
![Screenshot from 2019-08-08 16-56-03](https://user-images.githubusercontent.com/31619361/62694223-1ebc4f00-b9fe-11e9-8a3b-df06f510fa1b.png)

Would you show us how to obtain right candidate format in both cases ?

Thanks in advance !

**Comment by hugoArregui** [comment]
The iceCandidate.ToJson() method returns a ICECandidateInit that you can serialize

**Comment by Sean-Der** [comment]
@lamhai1401 thanks for using Pion :)

This is a rough edge, is there anyway documentation wise we could make this easier? Where did you look/expect to see this info? Would love to make sure other people don't get stuck on this!

**Comment by lamhai1401** [comment]
Thanks for  your quick response ! We have solved the problem.
The PION source code is quite clean and easy to understand.
