### ISSUE TITLE
gstreamer-send sintel example does not work

### ISSUE THREAD

**Issue by chrbsg** [pion/webrtc#791]
### Your environment.
  - Version: git master HEAD 3e5c7b4f5cc7a59a54284586c11b996d34496f6e
  - Browser: Chrome 76.0.3809.100 on Ubuntu 18.04
  - Other Information - 

### What did you do?
example-webrtc-applications/gstreamer-send/README.md has instructions for sintel.mkv. 
I followed the instructions to install on Ubuntu, then ran examples using `go run examples.go  -address :8080` and loaded http://localhost:8080 in Chrome.
I then downloaded Sintel.2010.720p.mkv using the link in the README, and following the README, tried running the gstreamer-send command line there and copy/pasting the relevant SDP. There was no working audio and video in browser. I tried adding "! videoconvert" as in the webcam example and the video now worked. But audio is corrupted, maybe not correct frequency or channels or something.

### What did you expect?
README should have correct command line for gstreamer-send to produce a working video and audio stream of Sintel in web browser.

The not-working command from README is: `echo $BROWSER_SDP | gstreamer-send -video-src "uridecodebin uri=file:///tmp/sintel.mkv ! videoscale ! video/x-raw, width=320, height=240 ! queue " -audio-src "uridecodebin uri=file:///tmp/sintel.mkv ! queue ! audioconvert"`

### What happened?
Command line in README does not work. Video can be fixed with "! videoconvert" but audio is still not working.

(aside, is the gstreamer-send example supposed to have two copies of the video on the left/right, I'm presuming it's supposed to be like this?)

**Comment by Sean-Der** [comment]
Hey @chrbsg sorry for the delay, busy week :( I will try and get this triaged/debugged ASAP!

Are you able to try on any other OSes/Browsers? I am Chrome on MacOS, I just want to rule out any issues around that. 

The Linux media pipeline for libwebrtc is different then MacOS, so my guess would be that we are doing something that isn't portable.

**Comment by Sean-Der** [comment]
Hey @chrbsg 

Sorry this didn't get addressed. I am closing for now, if you still want to talk about this please re-open!

thanks
