### ISSUE TITLE
parsing go.mod: unexpected module path

### ISSUE THREAD

**Issue by gazhayes** [pion/webrtc#795]
```
$ go get -v github.com/pion/webrtc
go: github.com/pion/webrtc@v1.2.0: parsing go.mod: unexpected module path "github.com/pions/webrtc"
go: error loading module requirements
```

Note the `s`: `github.com/pions/webrtc`

I can't seem to find where this is actually coming from.

**Comment by at-wat** [comment]
Try using `github.com/pion/webrtc/v2`.

As described in the official wiki (https://github.com/golang/go/wiki/Modules#semantic-import-versioning), major version of the module `/vN` must be included at the end of the module path.

**Comment by backkem** [comment]
@at-wat is right. This issue exists since we renamed the organisation from `pions` to `pion` between v1 and v2. We should probably call out the correct import path in the readme.

**Comment by Sean-Der** [comment]
@backkem That would be awesome. I think we need to redo the README honestly. It doesn't convey enough information, and it is wasting the readers time.

I was look at WebTorrent's the other day and it so friendly, and does a great job of selling why the project is exciting!

**Comment by gazhayes** [comment]
Thanks @backkem @Sean-Der and @at-wat. I have updated the README in the examples in #797

**Comment by Sean-Der** [comment]
Glad to see the contribution @gazhayes :)

Do you consider this issue closed, or anything else we can do to make Pion more user friendly! I am up for any and all input :) thanks

**Comment by gazhayes** [comment]
Thanks @Sean-Der, yeah I'll close it now :)
