### ISSUE TITLE
The big tinygo thread

### ISSUE THREAD

**Issue by backkem** [pion/webrtc#798]
## Summary

This is a tracking issue to experiment with support for tinygo. It seems rather early for the tinygo project to try this. However, it's still interesting to see how far we can get.

## Known issues

- encoding/json is missing but we should be able to live without it.
- There may be no good source of cryptographic randomness.
- We need to use their custom net package.

## Steps

- [ ] Add support for PacketConn to their espat driver.
- [ ] Port a simple protocol (e.g. STUN) to using their net package (E.g. using build flags).
- ...

**Comment by Prinzhorn** [comment]
What is the main motivation behind that? For me personally the main motivation would be smaller WebAssembly builds (the examples have about 8MB). Which might also make for a good MVP / first step? Instead of having to port all of the networking to tinygo the first step would be to make the `*_js.go` (`// +build js,wasm`) files compile. Which is mostly `system/js` stuff. But does that even exist in tinygo? I'm not too familiar with how this all works but I wanted to get my thoughts out.

**Comment by backkem** [comment]
Hi @Prinzhorn, I haven't had time to look further into this. All these are all open questions for me as well.

**Comment by Prinzhorn** [comment]
@backkem no worries. I'm currently sick, but I'm interested in checking out TinyGo in the future. There seems to be a lot going on regarding WebAssembly. I also hope the regular Go builds will get significantly smaller in the future, but everything is still experimental right now. But it's amazing to see that the pion code works seamlessly on client and server.

**Comment by Sean-Der** [comment]
@Prinzhorn 

If you are interested in getting `tinygo` working for WASM builds that would be amazing! Would love to have the contribution.

I am interested in seeing if we can provide DataChannels to IoT devices. I am not sure how many people will actually find it useful, but I think it could enable things that don't exist now! AFAIK there are no WebRTC implementation that can target these devices currently.

**Comment by Prinzhorn** [comment]
@Sean-Der I've decided to put the project on hold, so unfortunately you cannot expect any contribution from me in the near future. But I hope to come back to Go and WebRTC in the future!

**Comment by Sean-Der** [comment]
This has an entry in [Big Ideas](https://github.com/pion/webrtc/wiki/Big-Ideas)
