### ISSUE TITLE
Scalable Topology

### ISSUE THREAD

**Issue by breebee** [pion/webrtc#831]
## Summary
Test/improve on Muaz Khan scalable broadcast topology he implements in his library where each user relays the the media to the next peer and removing CPU/Bandwidth from the equation. 

## Motivation
I believe webrtc needs to connect people on a global scale, and this library written in go seems to be the best fully featured open source collaboration that can actually achieve a large scale production. 

## Describe alternatives you've considered
Alternatives to use this topology can only be found with npm and the libraries provided by Muaz Khan.

## Additional context
Possibly having the server available as a third peer connection between each  two peers can be used as a fallback SUF type drop in replacement if this topology has draw backs in renegotiating for the closest peer.

I found this image regarding the scalable topology

https://camo.githubusercontent.com/ba7847532dc882327df2c603ae09a244d761c0ba/68747470733a2f2f73697465732e676f6f676c652e636f6d2f736974652f7765627274636578706572696d656e74732f5765625254432d6174746163682d72656d6f74652d73747265616d2e706e67

**Comment by Sean-Der** [comment]
Interesting @breebee 

I think Pion WebRTC could easily be able to build something like this! 

Another interesting idea I was thinking of playing with is what if you connected to an SFU, but then some media sections were actually from a different peer? It could give the user a possibility to seamlessly switch between P2P/SFU as more users join/leave the call.

The local PeerConnection would have no idea, but it would actually be communicating with two different PeerConnections and just one ICETransport for P2P and one for the SFU.

**Comment by Sean-Der** [comment]
This conversation is probably done better via [Slack](https://pion.ly/slack) or maybe email! I will leave this issue open, but I don't think there is any dev work I can do here.

Feel free to chat here, or close and we can talk via w/e method you prefer :)

**Comment by breebee** [comment]
Thank you for the quick response, I would love to discuss via email if you can. I am not sure how to make my email visible only to you.

**Comment by Sean-Der** [comment]
My email is sean@pion.ly feel free to email me anytime/with any question!

**Comment by breebee** [comment]
I am so excited to here this is possible and can be improved with the double peer connection hop. Where can I follow/commit for the example implementation? I am diving into golang coming from Rust and trying to learn webrtc, however with lack of resources in rust I found pion so golang it is :)
 
-----Original Message-----
