### ISSUE TITLE
"sctp ERROR: ... retransmission failure: T1-init" when trying to start datachannel with chrome/firefox

### ISSUE THREAD

**Issue by chrbsg** [pion/webrtc#834]
### Your environment.
  - Version: 2.1.4
  - Browser: chrome 76.0.3809.100 (Official Build) (64-bit) / Firefox 69.0
  - Other Information - Using latest Ubuntu 18.04

### What did you do?
Tried to create a data channel in a server using pion and connect to it from chrome javascript

### What did you expect?
dc.OnOpen to run on server
dc.ondatachannel to run on chrome

### What happened?
No data channel. Instead after about 5.5 mins:

sctp ERROR: 2019/09/16 16:23:08 [0xc000284000] retransmission failure: T1-init

To reproduce use attached example files:

go run server.go
server says:
    offer?
in chrome load datachannel.html
copy/paste content of top Input from chrome to server.go terminal and press enter
server says: 
    server: ICE state changed: checking
    answer = eyJ0...
copy answer to chrome box 2 and hit enter
server says:
    server: ICE state changed: connected
server will eventually time out and say:
    sctp ERROR: 2019/09/16 17:49:34 [0xc000246000] retransmission failure: T1-init

For comparison, try client.go instead of chrome. client.go works and both server and client run data channel handlers.

[It may be that I have done something wrong here, but as far as I can see both the javascript code and client.go are doing exactly the same createOffer, setLocalDescription, setRemoteDescription, so this appears to be a bug]
[code.zip](https://github.com/pion/webrtc/files/3617288/code.zip)

**Comment by Sean-Der** [comment]
Thanks for the bug report @chrbsg!

` retransmission failure: T1-init` usually means the other side isn't running SCTP at all (so we timed out waiting for them)

I will check out the code, but for the time being do our samples work at all for you? `data-channels` and `data-channels-create` are both working for me locally, so if those don't work might help us get into this bug easier.

thanks!

**Comment by enobufs** [comment]
I tried to run the attached code but it does not let me enter the offer (base64 string) on my terminal... (might be my iterm2 issue)
One thing I noticed is, the offer generated by Chrome does not have candidates in it. You would either collect the candidates generated by [onicecandidate](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onicecandidate) before generating base64 string of the offer...  I guess the connection is established only one way...

**Comment by chrbsg** [comment]
Yes, the examples work. I wonder if what I tried to do is simply unsupported? I create an offer in the browser, then in server create the data channel and send answer to browser. But data-channels-create creates the data channel in the server, then generates the offer to be sent to the browser, so the initial offer has a data channel.

If I modify my example datachannel.html to create a data channel (pc.createDataChannel('foo'); before createOffer) then the example works, presumably because the browser is now aware that there is at least one data channel, and incorporates that in to the initial offer?

**Comment by chrbsg** [comment]
The offer from Chrome with a createDataChannel includes the line: 

    m=application 9 UDP/DTLS/SCTP webrtc-datachannel

So, it looks like Chrome will only advertise support for data channels if a data channel is actually created by the javascript. Otherwise the offer won't include that line.

**Comment by enobufs** [comment]
Ah... good point. I guess this is a known limitation with pion... @Sean-Der can you confirm that pion needs to see `m=application 9 UDP/DTLS/SCTP ...` line in the incoming offer for data channel to work correctly?

**Comment by Sean-Der** [comment]
@enobufs @chrbsg 

Sorry this took so long, but here is an example. https://jsfiddle.net/Lw3ye0hk/2/

If the answerer creates the datachannel nothing happens. If you switch `ondatachannel` and `createDataChannel` everything works, so I don't believe there is anything we can do here.

@chrbsg I am closing for now, but if anything comes up please re-open and we will fix it up. Thanks for using Pion :)
