### ISSUE TITLE
Support 1:1 NAT option

### ISSUE THREAD

**Issue by enobufs** [pion/webrtc#835]
## Motivation
Pion could be used in  C/S topology, one end is a client and the other end is a server (just like Janus G/W does). But in this case, the server must have a routable (public) IP address. Many server environments may not have access to public IP address to bind to the local interface.

Janus provides the following option. Pion could provide something equivalent.
```
    -1, --nat-1-1=ip              Public IP to put in all host candidates,
                                  assuming a 1:1 NAT is in place (e.g., Amazon
                                  EC2 instances, default=none)
```

## Describe alternatives you've considered
Use STUN server for the server-side nodes.

**Comment by seppo0010** [comment]
I would like this option as well, I might work on a patch for this. @enobufs should a port or somehow port mapping be allowed to be provided as well? In case the public endpoint's IP is not the same as the local one

**Comment by Sean-Der** [comment]
We just are rewriting the SDP right? So when we emit `host` candidates we are swapping out the local interface IPs for a hardcoded `public IP` that the user can specify.

This seems like a great candidate for the `SettingEngine`. One pushback from me though is that the user could accomplish this already (with a little SDP munging) so this ends up being a convenience feature. Make this is something we put in `pkg` and have a `SDPRewriter` or something along those lines.

Possibly not be as intuitive, but I am afraid if we blow up `SettingEngine` with every non-standard behavior beginners will find themselves overwhelmed. This is all subjective though.

**Comment by seppo0010** [comment]
I think that would be unnecessary complex, @Sean-Der. And people are used to having long configurations that they can ignore most of it. For example, [`http.Transport`](https://golang.org/pkg/net/http/#Transport) has around 20 settings and some of those are functions or maps of functions.

Also the `SDPRewriter` would have to handle the case of n candidates becoming m candidates.

Having one IP would make the gathering process faster as well for those cases.

In the future once demux is implemented a pion server could be listening to a port on startup and providing a fixed endpoint would work great there.

**Comment by Sean-Der** [comment]
Ok I say go for it!

I bet a lot of people will appreciate this feature, they just haven't brought it up yet :) Send the PR my way and happy to approve/review.

**Comment by enobufs** [comment]
@Sean-Der @seppo0010 @hugoArregui I have one idea and I'd like to hear your opinion about it.

With 1:1 NAT option, we can eliminate the necessity of STUN server for the server-side node, reducing one point of failure, which is good.  I initially thought to replace host candidate with the external IP address, but that has a drawback, which is server-side nodes cannot talk to each other.  (AWS's 1:1 NAT does not do hairpin routing if I'm right.)

So, instead of relacing the host candidate with external (public) IP, what don't we just add the external IP as a srflx candidate when that option is enabled (&& STUN is NOT enabled)? What do you think?

**Comment by enobufs** [comment]
Justifications:
* Resulting set of candidates are identical to the one gathered result if STUN was used.
*

**Comment by enobufs** [comment]
Here is the code, Janus replaces the local IP with the provided external IP (janus.c:3969):
```
	if(item && item->value) {
		JANUS_LOG(LOG_VERB, "Using nat_1_1_mapping for public ip - %s\n", item->value);
		if(!janus_network_string_is_valid_address(janus_network_query_options_any_ip, item->value)) {
			JANUS_LOG(LOG_WARN, "Invalid nat_1_1_mapping address %s, disabling...\n", item->value);
		} else {
			nat_1_1_mapping = item->value;
			janus_set_public_ip(item->value);
			janus_ice_enable_nat_1_1();
		}
	}
```
Janus, is completely giving up the original host candidate. (I believe it did not have to)

**Comment by enobufs** [comment]
1:1 NAT IP as srflx vs ICE lite...  might be something we need to worry about? If we go with "1:1 NAT IP as srflx", then ICE-lite may allow srflx only when that was 1:1 NAT IP, or can we safely assume ICE-lite won't be used along with 1:1 NAT?  This is just a detail, not essential, however.

**Comment by hugoArregui** [comment]
I love your idea of an extra srflx candidate @enobufs! this way we can avoid stun for no cost, I'm actually using the host private address for server2server communications so I would like to keep it.

**Comment by seppo0010** [comment]
> 1:1 NAT IP as srflx vs ICE lite... might be something we need to worry about? If we go with "1:1 NAT IP as srflx", then ICE-lite may allow srflx only when that was 1:1 NAT IP, or can we safely assume ICE-lite won't be used along with 1:1 NAT env?

Quite the opposite, I want to use ICE lite with a fixed IP address. In my use case I have multiple `pion` servers behind a load balancer (with an affinity rule to maintain connections). I want to be able to provide the load balancer public address while using ICE lite as I know that address will be reachable by the client. No STUN is used (they are not provided and ICE Lite is enabled).

I even want to be able to provide a single port for the load balancer and demux by client endpoint (which is being addressed in another issue, but also part of this client-server problem).

**Comment by enobufs** [comment]
So, we have two ways...

(1) Opportunistic srflx IP
* Simply add srflx candidate with IP address given via config (without using STUN server)
* Works with 1:1 NAT while host candidate is still available

(2) 1:1 NAT IP
* Replace host candidate's IP address with the one given via config
* Works with 1:1 NAT, but original local IP won't be offered.

**Comment by seppo0010** [comment]
Is there any reason why you want it to be a server reflexive candidate besides having a lower priority than host candidates?

I guess in summary we want to be able to add srflx/host candidates (for 1 and 2) and skip gathering (for 2).

**Comment by hugoArregui** [comment]
I don't see any disadvantages for (1), I really really like it.

@seppo0010 yes, I think it could be a host candidate as well, but right now with STUN server you will get the public ip as a srflx candidate. if we consider this an optimization to bypass STUN server it makes sense to behave as if we have one. That been said I'm not against making it a host candidate if that's what the majority prefers

**Comment by enobufs** [comment]
When server-server finds a valid pair with srflx and host candidates, then it should choose host candidate. In server-client, the host candidate from the server won't be valid for the client, so srflx candidate would be the highest priority possible.

I guess 1:1NAT/OpportunisticSrflx and ICE-lite options are orthogonal, aren't they? (where I assume, ICE-lite is to skip gathering srflx and relay candidates - I have to read ICE-lite spec..)

**Comment by enobufs** [comment]
My project would want to take advantage of (1) - leaving the ability of server-server connection for a diagnostic purpose (health check inside the VPC/security group, etc).  I guess, now the question is whether the option (2) is needed when (1) is available.

**Comment by seppo0010** [comment]
> That been said I'm not against making it a host candidate if that's what the majority prefers

It's not what I prefer (I really don't mind either way) but RFC 8445 states that Lite agents only use host candidates:

> 5.2.  Lite Implementation Procedures

> Lite implementations only utilize host candidates.

https://tools.ietf.org/html/rfc8445#section-5.2

**Comment by seppo0010** [comment]
For my use case I really need to skip local IP addresses (since I must to go through a load balancer that may assign another server for the client), but I can address that in a different issue.

**Comment by enobufs** [comment]
Thanks @seppo0010. I think we should support both of them.
My proposal:
```go
func (*SettingEngine) Set1To1NAT(ip string)
```
It takes two styles of a string, for example:
* "1.2.3.4" - replaces the host IP (Just like Janus does)
* "srflx:1.2.3.4" - insert srflx candidate

Consideration for future enhancements:
In case we need to map both IPv4 and IPv6, we can simply concatenate them with comma.
* "1.2.3.4,2601:1234::5678"
Also, in case we'd like to explicitly specify the local IP to be mapped to, we should allow using slash (borrowing idea from coturn's -X option)
* "1.2.3.4/10.0.0.1"

Let's focus on the first (let's not implement the future enhancement part at this poin. YAGNI principle I personally tend to follow)

**Comment by enobufs** [comment]
@seppo0010 I have just gone over RFC 8445. As I was reading about Lite implementation, I am beginning to feel that we should not have supported it. (correct me if I am wrong)

From [RFC 8445 Appendix A](https://tools.ietf.org/html/rfc8445#appendix-A)
```
   It is important to note that the lite implementation was added to
   this specification to provide **a stepping stone** to full
   implementation.  Even for devices that are always connected to the
   public Internet with just a single IPv4 address, a full
   implementation is preferable if achievable.  Full implementations
   also **obtain the security benefits of ICE** unrelated to NAT traversal.
```

Pion/webrtc already support full implementation. I really do not see the need of ICE-Lite when there are many cases it could break, for instance, do all other webrtc libraries support ICE-Lite? (Do they correctly handle "a=ice-lite"?)

I think you just needed 1:1 NAT support didn't you? (I am still trying to understand things correctly... ;)

**Comment by seppo0010** [comment]
@enobufs I'm sorry if I seem too eager to have ICE Lite, but it is really required in my use case. If I have a full agent deployed then a better route may be discovered, but my project required another one to be used, as I need to go through a load balancer, to, well, balance the load, and it also may gather statistics about network usage, logging, etc. The company I work for already does that for HTTP(S) requests and is not willing to sacrifice it. Also I don't want to allow users to inject traffic to arbitrary addresses inside a corporate network. I do not know if all libraries support ICE Lite.

I prefer a second parameter to indicate the type of candidate and make it an array instead of a single string to avoid the comma-separated parsing, but that's a matter of taste.

How about this?

```
func (*SettingEngine) Set1To1NATIPs(typ ICECandidateType, ips []string)
```

(personally I prefer ip addresses to be `net.IP` instead of `string` but it seems like strings have been used all around the API so it's better to be consistent)

In the future it would be nice to also support a public port different from the private port (turnserver does not support that use case).

I don't think I can completely skip gathering by setting network types to an empty array as empty array is the default value:

`icegatherer.go`:
```
        if len(requestedNetworkTypes) == 0 {
                requestedNetworkTypes = supportedNetworkTypes()
        }
```

**Comment by enobufs** [comment]
Hi @seppo0010 No worries. I am just learning from you, trying to understand the issue you have and the ICE-lite spec also. ;)

I think I get it if your server (with "full implementation") tries to support clients with "lite implementation", but not trying to make pion a "lite implementation". - then that makes sense!

Besides ice-lite, you should be able to skip gathering of specific candidate type:
https://godoc.org/github.com/pion/webrtc#SettingEngine.SetNetworkTypes

Do you mean, it did not work for you? (a bug?)

**Comment by enobufs** [comment]
As for the method proposed, we can take array of string. But I am not sure ICECandidateType is a good idea because we also need to support WebAssembly. We tend to use types compatible with JavaScript I believe...

**Comment by seppo0010** [comment]
> I think I get it if your server (with "full implementation") tries to support clients with "lite implementation", but not trying to make pion behave as "lite implementation". - then that makes sense!

Oh, I'm making the opposite, an ICE lite pion server and a browser full client. To be more clear, I want users to upload a video using webrtc since I'll be processing the image in real time.

> Besides ice-lite, you should be able to skip gathering of specific candidate type according to the document...:

I have not tried it yet because I don't have `Set1To1NATIP`, but I think if I try to skip all methods and just set the IP it will not be possible at the moment.

> But I am not sure ICECandidateType is a good idea because we also need to support WebAssembly

Good point. But isn't ICECandidateType just an integer?

**Comment by enobufs** [comment]
> I'm making the opposite, an ICE lite pion server and a browser full client.
In that case, I believe you don't need ice-lite.

> Good point. But isn't ICECandidateType just an integer?
Yeah, then I believe string is clearer for JavaScript API users.

Let's go with:
```
func (*SettingEngine) Set1To1NATIPs(typ candidateType string, ips []string)
```
We should document that `typ` can only be "host" or "srflx", and defaults to "host".

**Comment by seppo0010** [comment]
> > I'm making the opposite, an ICE lite pion server and a browser full client.
> 
> In that case, I believe you don't need ice-lite.

I don't really need ICE Lite if I want the best NAT traversal. But I have other constraints, like I need to go through a load balancer and having a full ICE implementation will not honor that.

**Comment by enobufs** [comment]
> But I have other constraints, like I need to go through a load balancer and having a full ICE implementation will not honor that.

Could you please elaborate that?

**Comment by enobufs** [comment]
My understanding is, your issue could be solved by having followings sorted out:
* Use public IP for the host candidate (this ticket)
* Skip reflexive candidate gathering (may not be working?)

**Comment by seppo0010** [comment]
I work in a company that uses [f5 load balancer](https://www.f5.com/services/resources/glossary/load-balancer) to handle incoming traffic. All public endpoint are currently receiving incoming HTTP/HTTPS and I need to add UDP traffic to handle WebRTC. The public IP of the servers is the load balancer's public IP. I want the users to stream their video camera using WebRTC to a cluster of servers through the Load Balancers. The public users should not be able to get to my servers private IP (because they are not on the company LAN) but my computer and my colleagues' computers can. I want all traffic, including the company users, to go through the Load Balancers because they provide more features besides load balancing. In summary, I don't really want the optimal route between my laptop's browser and the server pion agent but I want a fixed one that I know will work.

> Skip reflexive candidate gathering (SetNetworkTypes may not be working? then we need to fix.)

I want to skip _all candidate gathering_, including host candidates.

**Comment by enobufs** [comment]
Oh.. F5! Used it a while ago. Would it understand WebRTP protocol? Or does it use IP/port-sticky to retain a session?

> I want to skip all candidate gathering, including host candidates.

Host candidate gathering is a simple local IP address/port binding (lite ver does this also). It does not talk to external entity, so I think it has nothing to do with lite or full. I understand the srflx candidate gathering for behind load balancer wouldn't help. So I think. the above two points are resolved, then I think your system would work. In other word, your server-side node would offer in its SDP, only one HOST candidate with Public IP of the load balancer.

**Comment by seppo0010** [comment]
We are using IP+port for stickiness.

> In other word, your server-side node would offer in its SDP, only one HOST candidate with Public IP of the load balancer.

That's the desired behavior! That's why I want to skip host candidate gathering. You are right it is not part strictly related to ICE Lite but I have no way right now to produce an SDP with just the public IP address of the Load Balancer.

**Comment by enobufs** [comment]
OK! Let me get started with implementing Set1To1NATIP.  I will look into SetNetworkTypes() also make sure there's only one host candidate in the SDP.  Thanks @seppo0010 for being patient with me understanding your goal. :)

**Comment by seppo0010** [comment]
Thank you!

**Comment by enobufs** [comment]
@Sean-Der, I need your insight / opinion.
 
There's a case where the 1:1 NAT mapping and mDNS options would collide from what I can see.

I believe if mDNSMode is either:
* MulticastDNSModeDisabled
* MulticastDNSModeQueryOnly
Then we could 1:1 NAT mapping option could "safely" be effective.

But, If the mDNSMode is MulticastDNSModeQueryAndGather and 1:1 NAT mapping (typ = "host"), I think we should do one of the following options:
1. Return an error to alert developers that these options are not compatible
2. Ignore 1:1 NAT option
3. Disable mDNS

My personal preference is 1. What do you think? (please correct me if I am wrong)

> if 1:1 NAT option is enabled for `srflx` type, then this won't be a problem. We can take advantage of both mDNS and 1:1 NAT! (beautiful!)

**Comment by enobufs** [comment]
1:1 NAT option in pion/ice is almost done but need to write a test.
I am going to add a new NAT behavior "NAT1To1" to vnet so that I can test it on a more realistic configuration.

**Comment by enobufs** [comment]
As we discussed this earlier... Let me summarize my understanding.

Which candidate type to gather can be controlled by ICEServer URLs along with ICETransportPolicy (gatherPolicy). As I was writing a table (open the link below), there was a couple of patterns current pion does not support. When I look at libwebrtc (webrtc.org) code, they have ICETransportPolicyNoHost (not exposed by w3c) to fill the blank.

https://docs.google.com/spreadsheets/d/1doEPGTC5WHaN5N-9XcsF3I_-yB8rp04Jkv0HLHxkbtw

**Comment by enobufs** [comment]
## Status
* Land PR https://github.com/pion/ice/pull/103
* Expose 1:1 NAT config options to pion/webrtc API (SettingEngine)

**Comment by yohaoquan** [comment]
Hi. I am sorry for posting here as I am only asking a question. I hope someone can clearify this for me:

If I created a new API with SetNAT1To1IPs set to my public IP in SettingsEngine, is it normal for all the video traffic to go through the server before reaching the other peer?

Sorry again for commenting on an already closed issue.. If I do not get any answers, I will probably start a new issue..

**Comment by Sean-Der** [comment]
Hey @yohaoquan 

`SetNAT1To1IPs` is a replacement for using a STUN server. Instead of creating a NAT binding you just supply a candidate directly.

I am not sure what you mean by 'is it normal for all the video traffic to go through the server before reaching the other peer'. Pion is just a WebRTC implementation. So everything is always P2P. You can create a SFU using Pion though!

The best place to ask questions is probably [slack](https://pion.ly/slack) happy to help anytime!
