### ISSUE TITLE
SettingsEngine.DetachDataChannels() makes attached data channels unusable.

### ISSUE THREAD

**Issue by AeroNotix** [pion/webrtc#838]
I'm not sure if this is intended or not but when you set `.DetachDataChannels()` in the SettingsEngine you _must_ detach the data channel for it to be usable at all.

### What did you expect?

`webrtc.SettingsEngine{}.DetachDataChannels()` would still allow attached data channels to function

### What happened?

`webrtc.SettingsEngine{}.DetachDataChannels()` means that you _must_ detach the datachannel to interact with it.

**Comment by Sean-Der** [comment]
This is by design, but we should probably add some logging/assertion if we don't detach!

```
DetachDataChannels enables detaching data channels. When enabled data channels have to be detached in the OnOpen callback using the DataChannel.Detach method.
```

After the `OnOpen` we should check if it was properly detached and throw an error message if it wasn't. Super easy PR if someone wants to grab that!
