### ISSUE TITLE
Support PCM

### ISSUE THREAD

**Issue by yourchanges** [pion/webrtc#851]
I test on a Hik camera, but can't get the audio works, so please support the pcm codecs, thank you!

here is the stream info:

```
Input #0, rtsp, from 'rtsp://xxx:xxxk@xxxxxx:40052/Streaming/Channels/701':
  Metadata:
    title           : HIK Media Server V3.4.62
    comment         : HIK Media Server Session Description : standard
  Duration: N/A, bitrate: 64 kb/s
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

```

the original audio stream is:  "Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s"
it seems not h264 standard aac codecs, it will work on webrtc ?

it seems, there is  no stream in chrome://webrtc-internals

```

Statistics RTCInboundRTPAudioStream_2608133663
--
timestamp | 2019/9/26 下午6:26:55
ssrc | 2608133663
isRemote | false
mediaType | audio
kind | audio
trackId | RTCMediaStreamTrack_receiver_3
transportId | RTCTransport_0_1
packetsReceived | 0
[packetsReceived/s] | 0
bytesReceived | 0
[bytesReceived/s] | 0
packetsLost | 0
jitter | 0


```

**Comment by Sean-Der** [comment]
Hey @yourchanges 

I am working on this now, I hope to have it done by tomorrow! I will resolve this ticket when all the work is done

Thanks for using Pion!

**Comment by ccdeer** [comment]
Awesome!It is useful to IP Camera.

**Comment by yourchanges** [comment]
:+1::+1::+1::+1::+1:

**Comment by yourchanges** [comment]
I'll test it later.
