### ISSUE TITLE
PeerConnection.Close doesn't always close the underlying turn client

### ISSUE THREAD

**Issue by AeroNotix** [pion/webrtc#854]
Conversation carried on from: https://gophers.slack.com/archives/CAK2124AG/p1569602730038100

**Comment by Sean-Der** [comment]
I unfortunately haven't been able to reproduce this. I am just getting familiar with the TURN code base though.

I am about ~1/3 done with adding TCP (and TCP/TLS) support now. As I work through the code base I am trying to cull as much as I can. If I see anything that jumps out at me will make sure to investigate more!

**Comment by AeroNotix** [comment]
Ah! I forgot to come and close this as the PR in https://github.com/pion/ice/pull/111 fixes this - what was happening is this: 

* A peer connection is created between two peers
* Local and remote descriptions are set properly
* Communication ceases at this point

This left the _controlled_ side of the connection in limbo as it was stuck waiting for candidates. Due to how the code was structured it never timed out so the connection stuck around forever. I had mistakenly believed I was actually calling the `.Close` method as I just assumed it would have received the timeout.

Since the _controlled_ peer never actually timed out, I never received the Failed/Disconnected event and thus, in the way I was closing connections - never called `.Close`.

Once https://github.com/pion/ice/pull/111 is merged, this PR can be closed.
