### ISSUE TITLE
introduce webrtc.ICEGathererConfig

### ISSUE THREAD

**Issue by enobufs** [pion/webrtc#872]
Now, webrtc.NewICEGatherer() takes **17 arguments** - lol
Every time we introduce a parameter for ice.Agent:
* We break API (it is an exposed function!) every time!
* Has to modify the function signature many places
* Code is unreadable (hard to tell what we are passing to the method)

Let's use a struct for it.

**Comment by Sean-Der** [comment]
Yes! This looks so bad in the tests where we pass `0, 0, 0, 0`

I am fine with breaking the API also since it is ORTC! I doubt we have very many users (if any).

**Comment by enobufs** [comment]
Ok I will modify that when I expose vnet to webrtc!

> I am fine with breaking the API also since it is ORTC!

Yea, yes.. i  mean, we have been breaking API when we added ICELite, NAT1To1IPs, etc, etc... lol

**Comment by at-wat** [comment]
How about using functional options pattern?
It would be one of the nice way to safely add new options with non-zero default values, and also good at readability.

**Comment by Sean-Der** [comment]
I do like the functional options pattern, only downside is that our existing code doesn't follow that pattern. I think users will probably find that confusing :/

I would love to see that for new code/internal interfaces though! It also makes the `godoc` a lot more approachable, and we can assert values much easier.

**Comment by enobufs** [comment]
The functional options pattern is good and elegant - maybe way more elegant than necessary for ICEGatherer...(?)

I was looking at [Dave Cheney's awesome blog](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) and had a few thoughts:

* Would we end up with having to expose internal params or methods for them?
* If so, then wouldn't we need to worry about thread-safety because it would allow callers to alter the value afterward.
* All these extra code and concern would add up our maintenance cost for slightly better readability..(?)
