### ISSUE TITLE
RemoteDescription contained media section without mid value

### ISSUE THREAD

**Issue by tylerlong** [pion/webrtc#879]
### Your environment.
  - Version: v2.1.8
  - Browser: None
  - Other Information - I am create a softphone using SIP and this library

### What did you do?
So I received SDP offer from SIP INVITE, it's

```
v=0
o=- 5305405169010475891 908790132696250821 IN IP4 104.245.57.182
s=SmcSip
c=IN IP4 104.245.57.182
t=0 0
m=audio 20040 RTP/SAVPF 109 111 18 0 8 9 96 101
a=rtpmap:109 OPUS/16000
a=fmtp:109 useinbandfec=1
a=rtcp-fb:109 ccm tmmbr
a=rtpmap:111 OPUS/48000/2
a=fmtp:111 useinbandfec=1
a=rtcp-fb:111 ccm tmmbr
a=rtpmap:18 g729/8000
a=fmtp:18 annexb=no
a=rtpmap:0 pcmu/8000
a=rtpmap:8 pcma/8000
a=rtpmap:9 g722/8000
a=rtpmap:96 ilbc/8000
a=fmtp:96 mode=20
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:20041
a=rtcp-mux
a=setup:actpass
a=fingerprint:sha-1 E2:F8:90:C6:37:7E:82:17:3C:63:CF:55:68:4E:1D:16:17:2C:D9:4D
a=ice-ufrag:atwbXWRm
a=ice-pwd:32SCWdSoU7BgkXxet5g5mlId5E
a=candidate:muEZ8Bb5Zhy8XFSL 1 UDP 2130706431 104.245.57.182 20040 typ host
a=candidate:muEZ8Bb5Zhy8XFSL 2 UDP 2130706430 104.245.57.182 20041 typ host

```

### What did you expect?

This library should accept the SDP

### What happened?

This library panic with error: "RemoteDescription contained media section without mid value"

I know the SDP doesn't have something like "a=mid:0". But this SDP is valid for browser `RTCPeerConnection`. I mean browser WebRTC accepts this SDP.

**Comment by Sean-Der** [comment]
Hey thank you for using Pion, and filing this bug report. I really appreciate it.

I think Pion is doing the right thing here, looking at the RFC https://tools.ietf.org/html/rfc5888#section-6

```
   All of the "m" lines of a session description that uses "group" MUST
   be identified with a "mid" attribute whether they appear in the group
   line(s) or not.  If a session description contains at least one "m"
   line that has no "mid" identification, the application MUST NOT
   perform any grouping of media lines.
```

libwebrtc is tolerating an invalid SDP. I think if we make this change it could cause future breakage in the future when communicating with other WebRTC clients.

**Comment by tylerlong** [comment]
@Sean-Der What you said makes sense. But even the spec doesn't say that it is invalid. 

> If a session description contains at least one "m"
   line that has no "mid" identification, the application MUST NOT
   perform any grouping of media lines.

No `mid` mean no grouping needed.

I only analyzed it literally. I am really not a SDP expert.

**Comment by Sean-Der** [comment]
ACK! Ok that makes sense to me, let me fix that and add a test :)

thanks for reporting it!

**Comment by Sean-Der** [comment]
I will not be fixing this. Me and @tylerlong discussed this on [Slack](https://gophers.slack.com/archives/CAK2124AG/p1571603069243600)

Our SDP parsing is just targeted at working with WebRTC clients. If people are trying to operating with other clients that use SDP it would be best to rewrite to make it work with Pion. I think the LoC added/complexity outweighs the cost in this case.

If this is blocking anyone/you disagree please re-open!

**Comment by mostafafarzane** [comment]
I have the same problem: `RemoteDescription contained media section without mid value`

@Sean-Der  Can you please elaborate on how can I fix this problem?

**Comment by Sean-Der** [comment]
Hey @mostafafarzane 

What is generating the SDP? If you share I am happy to help debug. I am also available on https://pion.ly/slack to help.

thanks

**Comment by mostafafarzane** [comment]
I added `a=mid:application` under `m=application 0 UDP/DTLS/SCTP webrtc-datachannel` in the SDP and the problem gone.

Thanks @Sean-Der for your response.
