### ISSUE TITLE
Set track.Read() minimum size

### ISSUE THREAD

**Issue by tylerlong** [pion/webrtc#887]
## Summary

Every time I call track.Read() it only gives me a few bytes. I want to set a minimum size for example 64 bytes.  Then it should give me no less than 64 bytes unless end of stream.

## Motivation

I am feeding track to https://github.com/faiface/beep/wiki/Hello,-Beep!

It panics with "short buffer". I did some debug and I find it is caused by track.Read() returns too small data size.

## Describe alternatives you've considered

I could create a wrapper buffer reader and do the job.
But I think there should be a more native/idomatic way.

## Additional context

Is this about package size controlling: https://github.com/pion/webrtc/blob/master/examples/save-to-disk/main.go#L85-L93 ?

**Comment by Sean-Der** [comment]
WebRTC is datagram/message based (and not a stream like files or TCP) so I don't know if we can set a size. We are just giving you the messages/RTP packets from the other side

If the reads are combining multiple RTP packets it will end up building invalid data.

----

`track.Read()` returns RTP, so I don't think you will want to use that. If you use `ReadRTP` the `Payload` member will give you raw audio data that should work!

**Comment by tylerlong** [comment]
> track.Read() returns RTP, so I don't think you will want to use that. If you use ReadRTP the Payload member will give you raw audio data that should work!

I thought it supported the reader pattern out of box: https://medium.com/@matryer/golang-advent-calendar-day-seventeen-io-reader-in-depth-6f744bb4320b

If I use track.ReadRTP() I need to manually create an adapter to use the reader pattern which  https://github.com/faiface/beep requires.

It is not a big deal for me but maybe we can change pion a little bit. Just my $0.02.

**Comment by Sean-Der** [comment]
Yea that is unfortunate it doesn't fit nicely, you just want the raw media.
 
People are using `Read` pattern directly because they want raw `RTP Packets`. Maybe we can add an additional method that gives a `Media Reader` maybe?

I love the feedback! I really appreciate the ideas :)

**Comment by Sean-Der** [comment]
Closing this for now. Since WebRTC is datagram based we can't really set the `Read()` size. If people have ideas would love to see us doing something here!

I will work on getting an example of using `oto` I think that could go a long way to unblocking people.
