### ISSUE TITLE
Implement H.264 writer

### ISSUE THREAD

**Issue by gqgs** [pion/webrtc#889]
## Summary

Implement H.264 writer.

## Motivation

Apparently the only video writer currently available is the IVF VP8 writer.
https://github.com/pion/webrtc/blob/758476212459d4faa882aa82934bf7099fe6a86e/pkg/media/ivfwriter/ivfwriter.go#L72

It would be useful to have a writer for H.264 as well.
Since the support for both codecs is required by the WebRTC specification the user would be able to use and save to disk whichever format best fits his/her use case.

**Comment by Sean-Der** [comment]
Agree! If there is a simple container format I am all for adding it to `pion/webrtc`

For now I would use webm, there is an example here https://github.com/pion/example-webrtc-applications/tree/master/save-to-webm

Maybe we should add a comment to `save-to-disk` to use `webm` if you want multiple tracks in one file or to support other codecs! I think that would be a great PR, could really help others in the future :)
