### ISSUE TITLE
[question]  How can I take pictures periodically from video track

### ISSUE THREAD

**Issue by isqad** [pion/webrtc#901]
Hello! Thank you for amazing project. 
I have a question: can I take picture from raw video track? How I do it? 

Regards, 
Andrew

**Comment by Sean-Der** [comment]
Hey @isqad, thanks for using Pion :)

Unfortunately that isn't something we can do easily. We only get a stream of video from the other side (that video stream will contain some complete pictures, but lots of inter-frames)

I would try first the `save-to-disk` examples, and then you can extract pictures from that via `ffmpeg` (or the tool of your choice)

If you are interested in contributing would be happy to work together on building a complete demo/solution for example-webrtc-applications! We could have something that generates images into a directory in a single application.

**Comment by isqad** [comment]
Thank you for reply!

> If you are interested in contributing would be happy to work together on building a complete demo/solution for example-webrtc-applications!

I'll try to develop this)
