### ISSUE TITLE
accumulated delay time

### ISSUE THREAD

**Issue by mabaohong** [pion/webrtc#910]
### Your environment.
  - Version: *master  latest version*
  - Browser: chrome 78
  - Other Information  two pcs all in local network, chrome video decode:hardware accelerated.

### What did you do?
I capture desktop and encode the picture captured to h264 stream, using nvidia display card on windows 10 , then send the stream to chrome pages, based on the example “play-from-disk”.
I capture one frame, the encode it to h264 frame I or P, and send it immidiately. The GOP size is 125.
The fps is 30 or 60, resolution is 1920x1080 or 1280x720, the bitrate is 6 mbps。
The time capturing one frame low than 2 ms, the time encoding one frame average low than 10ms.
### What did you expect?
It works. And I expect the delay time between the desktop screen and the video screen displaying on the chrome page keep stable.
### What happened?
But the delay time beteen  desktop screen and the video screen displaying on the chrome page keep increasing. Is there any API or configure file, I can set some parameters to control the delay?

**Comment by Sean-Der** [comment]
@mabaohong Thanks for using Pion!

Do you mind looking in the `chrome://webrtc-internals` I am curious if the browser is introducing the delay. How is your CPU usage 

Pion itself doesn't introduce any delay, so my guess it is one of the following issues.
* Capturing/Encoding is falling behind. It might be encoding for quality and not real-time?
* Browser is introducing delay (perhaps it thinks there is packet loss?)
* Decoding is falling behind. If you are doing SW decoding, how is the CPU usage?

**Comment by mabaohong** [comment]
@Sean-Der  Thank you for answer.
chrome://webrtc-internals snapshot is attached. Chrome use HW decoding, and the CPU usage about 5-10%.
![QQ图片20191118093030clientgpuenable](https://user-images.githubusercontent.com/50134776/69018682-70ef1200-09e8-11ea-9d48-2a220bb3e4da.png)
![QQ图片20191118093054webrtcinternal](https://user-images.githubusercontent.com/50134776/69018691-75b3c600-09e8-11ea-9b6e-baeda0512379.png)
but after about 40minutes, the delay increases from about 50ms to about 500ms.

**Comment by mabaohong** [comment]
![QQ图片20191118093127delay (2)](https://user-images.githubusercontent.com/50134776/69018812-02f71a80-09e9-11ea-830d-bee24ffaf55d.jpg)
And My Capturing/Encoding PC CPU usage is about 26%, GPU encode usage is about 44%.
![QQ图片20191118093747cpuusage (2)](https://user-images.githubusercontent.com/50134776/69018928-7731be00-09e9-11ea-889d-8a67bc014c67.png)

**Comment by mabaohong** [comment]
![QQ图片20191118094442 (2)](https://user-images.githubusercontent.com/50134776/69019002-bcee8680-09e9-11ea-814c-888ea827f04d.jpg)

**Comment by Sean-Der** [comment]
@mabaohong thanks for the details!

For WebRTC by default it only does SW encode/decode I believe (OpenH264). It is behind a flag, mind checking if enabled for you? My assumption from looking at everything is that the video is coming in properly, but the decoder is having issues and adding latency every time it happens.

Looking at the nvenc docs can you also set the following? 
* Can you do `Constrained Baseline`?
* Can you do the `LOW LATENCY HP` mode?

**Comment by mabaohong** [comment]
@Sean-Der  I made a mistake. Sending H264 frame packet data, using RTP. I set a wrong samples.

Thank you very much!

**Comment by Sean-Der** [comment]
@mabaohong nice! did that fix it/no more delay issues?

It is really hard to debug this stuff, maybe we can build a better tool with Pion. Not sure though. Feels like Chromium needs to be extended with better debug tools, not sure where to dive in on that :)

**Comment by Sean-Der** [comment]
@mabaohong thanks for using Pion :) if you are still having issues happy to help on here or [Slack](https://pion.ly/slack)!
