### ISSUE TITLE
TestDataChannelBufferedAmount is flaky

### ISSUE THREAD

**Issue by langep** [pion/webrtc#938]
I modified the TestEOF test in datachannel_go_test.go but the `TestDataChannelBufferedAmount/set_after_datachannel_becomes_open` test failed in CI.

### What did you expect?
I expected the unmodified test to pass.

### What happened?
It failed with the following output:

--- FAIL: TestDataChannelBufferedAmount (2.91s)
    --- FAIL: TestDataChannelBufferedAmount/set_before_datachannel_becomes_open (1.45s)
        datachannel_test.go:23: 
            	Error Trace:	datachannel_test.go:23
            	            				datachannel_go_test.go:243
            	Error:      	Received unexpected error:
            	            	EOF
            	Test:       	TestDataChannelBufferedAmount/set_before_datachannel_becomes_open
    --- PASS: TestDataChannelBufferedAmount/set_after_datachannel_becomes_open (1.46s)

**Comment by at-wat** [comment]
Test failures related to datachannel can be reproduced locally by increasing CPU load during the test and repeating hundreds of times.

```
# occupy most of the cores before running the test
yes > /dev/null &
yes > /dev/null &
...
go test . -run=TestDataChannelBufferedAmount -count=100
```

Similar error occurs also on `TestDataChannel_Open`.

**Comment by at-wat** [comment]
`EOF` error is transferred from:
`net.Conn.Close()` -> `sctp.Association.Close()` -> `SCTPTransport.Stop()` -> `PeerConnection.Close()`

**Comment by at-wat** [comment]
Fixed by https://github.com/pion/dtls/pull/162 and https://github.com/pion/webrtc/pull/955 🎉
