### ISSUE TITLE
I wonder how can sfu-minimal work 

### ISSUE THREAD

**Issue by mabaohong** [pion/webrtc#941]
I download webrtc-2.1.18， and follow the Instructions of README.md like this:
I  open jsfiddle.net in one of my windows pc, ip is 10.0.1.128, call it A pc
Run main.go in sfu-minimal;
In A pc chrome browser, Click Publish a Broadcast, a video view screen appears, wait about 3 minuts, Browser base64 Session Description appears: eyJ0eXBlIjoib2Zm................cclxuIn0=
cmd.exe localhost:8080/sdp -d "eyJ0eXBlIjoib2Zm................cclxuIn0="
sfu-minimal.exe response: eyJ0eXBlIjoiYW5...................0ZXNcclxuIn0
copy eyJ0eXBlIjoiYW5...................0ZXNcclxuIn0 to Golang base64 Session Description, int A pc, Then press Start Session.
Then, Logs appears: 
checking
connected

In B pc( whose ip is 10.0.1.88) chrome browser, Click Join a Broadcast,  a video view screen appears, wait about 1 minuts,Browser base64 Session Description appears: eyJ0eXBlIjo...............kZGU2ZVxyXG4ifQ==
cmd.exe localhost:8080/sdp -d "eyJ0eXBlIjo...............kZGU2ZVxyXG4ifQ=="
sfu-minimal.exe response: eyJ0eXBlIjoiYW5zd2Vy........................pZGF0ZXNcclxuIn0=
copy eyJ0eXBlIjoiYW5zd2Vy........................pZGF0ZXNcclxuIn0= to Golang base64 Session Description in pc B .Then press Start Session.
Then, Logs appears: 
checking
disconnected

I try about 3 times, the same result. I wonder how can it work?

**Comment by Sean-Der** [comment]
Hey @mabaohong 

Sorry I missed this! If you are trying to use Pion and still have issues I am available to help in [Slack](https://pion.ly/slack)

thanks
