### ISSUE TITLE
No matching versions for query "latest"

### ISSUE THREAD

**Issue by Dimpiv** [pion/webrtc#950]
`
GOROOT=/home/putty/go/go1.13 #gosetup
GOPATH=/home/putty/go #gosetup
/home/putty/go/go1.13/bin/go build -o /tmp/___go_build_main_go /home/putty/code/webrtc/examples/gstreamer-send/main.go #gosetup
go: finding github.com/pions/webrtc/pkg latest
go: finding github.com/pions/webrtc/pkg/ice latest
go: finding github.com/pions/webrtc/examples/gstreamer-send/gst latest
go: finding github.com/pions/webrtc/examples/gstreamer-send latest
go: finding github.com/pions/webrtc/examples latest

**build github.com/pions/webrtc: cannot load github.com/pions/webrtc/examples/gstreamer-send/gst: no matching versions for query "latest"**
`
Hello, I am cloning the repository, I am trying to compile any project and cannot initialize the necessary packages when initializing the imports.

**Comment by Sean-Der** [comment]
Hi @Dimpiv 

What version of the repo is this? We renamed from ‘pions’ -> ‘pion’ about a year ago, I think this broke things for old code.

Can you try https://github.com/pion/example-webrtc-applications/tree/master/gstreamer-send instead

Thanks!

**Comment by Sean-Der** [comment]
Hi @Dimpiv 

Hopefully this worked for you! If you are still have issues please reopen, thanks for using Pion! I am also available on [Slack](https://pion.ly/slack) if you need help.
