### ISSUE TITLE
Why do anyone use WebRTC in the backend?

### ISSUE THREAD

**Issue by cyantarek** [pion/webrtc#952]
As it's clear that, WebRTC is totally a client side of things. So when building applications like audio/video chat, we use the client side logic to initiate and make/answer offers.

So what is the use case to use WebRTC on the server side like Go? What is the use of it? What can I build with pions and golang server side? I don't find any real use cases.

Please let us know.

Thanks

**Comment by Sean-Der** [comment]
@cyantarek Check out [awesome-pion](https://github.com/pion/awesome-pion) there are a few server side applications (harmony and cloud-game are good ones)

For non-Pion I would look into
* mixer.com
* Google Stadio
* Janus

**Comment by enobufs** [comment]
@cyantarek 
Even in C/S application, WebRTC is the only technology that allows us to take advantage of UDP transport (low latency where packet loss can be tolerated.) on browsers at the moment IMO. Pion allows us to write server-side logic purely in Go.
