### ISSUE TITLE
Implement other SDP media protos

### ISSUE THREAD

**Issue by encounter** [pion/webrtc#983]
Hi, I'm attempting to connect to a Wowza streaming engine service that offers 
```
m=video 9 RTP/SAVPF 97
m=audio 9 RTP/SAVPF 96
```

However, the SDP answer generated by this library appears to use 
```
m=video 9 UDP/TLS/RTP/SAVPF 97
m=audio 9 UDP/TLS/RTP/SAVPF 96
```
unconditionally, and then the library complains about DTLS connection timeouts.

When running a packet capture for the original video player, I see no DTLS packets at all. I'm not too familiar with the WebRTC spec, so I'm not entirely sure if I'm on the right track here, or conflating different issues.

**Comment by Sean-Der** [comment]
Hey @encounter, thanks for checking out Pion!

The `actpass` value in the SDP controls who initiates the DTLS traffic. You mind sharing those? It sounds like Pion is running as the client (starting the DTLS handshake) but Wowza is never responding. If you can use `wireshark` or `tcpdump` and capture DTLS traffic that would be really helpful.

* Pion only supports DTLS v1.2, it is possible the wowza service only supports 1.0 (which is insecure and we never plan on supporting)

**Comment by encounter** [comment]
Yes, I'm using `SetAnsweringDTLSRole(webrtc.DTLSRoleClient)` to set `a=setup:active` in the answer, mostly to try to match Chrome's behavior. The offer uses `setup:actpass`, and pion defaults to `passive`, which didn't work either. It may very well be a (D)TLS version mismatch, so I'll investigate that more.

**Comment by Sean-Der** [comment]
@encounter bummer!

I think the next best step is getting a packet capture of both scenarios. If you don't feel comfortable sharing them here feel free to email me sean @ pion.ly and can take a look!

**Comment by encounter** [comment]
Thanks, I'll open a new issue if I find anything of note.
