### ISSUE TITLE
Cannot send audio data back to the sender over a 'sendrecv' track

### ISSUE THREAD

**Issue by enobufs** [pion/webrtc#988]
### Your environment.
  - Version: v2.1.18

### What did you do?
I am having difficulty creating a bidirectional track (using Opus)… 

I am seeing this error:
```
--- FAIL: TestSessDataAndAudioChannels (0.23s)
    session_test.go:437: this is a remote track and must not be written to
```

Offer side creates a track like this:
```
		mediaTrack, err := sess.pc.NewTrack(mediaInfo.Spec.PayloadType, rand.Uint32(), trackID, mediaInfo.Spec.Label)
		if err != nil {
			return "", err
		}
		transceiver, err := sess.pc.AddTransceiverFromTrack(mediaTrack, webrtc.RtpTransceiverInit{
			Direction: webrtc.RTPTransceiverDirectionSendrecv,
		})
		if err != nil {
			return "", err
		}
```
Answer side prepares to receive one audio track like this:
```
	// Allow us to receive 1 audio track
	transceiver, err := sess.pc.AddTransceiver(webrtc.RTPCodecTypeAudio)
	if err != nil {
		return "", err
	}
	sess.pc.OnTrack(func(track *webrtc.Track, rtpReceiver *webrtc.RTPReceiver) {
		sess.mutex.Lock()
		defer sess.mutex.Unlock()
```

In this OnTrack function, I store `track`, then later I call track.Write() assuming that the track is bidirectional, but I get the above error.

Here's offerer and answerer's SDP:
```
{"type":"offer","sdp":"v=0\r\no=- 691837551 1580083348 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 D7:43:37:4B:14:69:68:9C:FF:5D:B6:E5:0F:80:BB:F7:76:5A:4A:80:20:BF:28:E1:BA:B0:15:05:F3:B6:EB:06\r\na=group:BUNDLE 0 1\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=mid:0\r\na=ice-ufrag:EsYEVEDqgWmvZSmX\r\na=ice-pwd:XvPbiHzupfdCtOFdepBPJHTQgHzsdFKW\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=ssrc:2596996162 cname:audio\r\na=ssrc:2596996162 msid:audio bar\r\na=ssrc:2596996162 mslabel:audio\r\na=ssrc:2596996162 label:bar\r\na=msid:audio 
bar\r\na=sendrecv\r\na=candidate:foundation 1 udp 2130706431 10.0.0.135 57244 typ host generation 0\r\na=candidate:foundation 2 udp 2130706431 10.0.0.135 57244 typ host generation 0\r\na=end-of-candidates\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=mid:1\r\na=sendrecv\r\na=sctpmap:5000 webrtc-datachannel 1024\r\na=ice-ufrag:EsYEVEDqgWmvZSmX\r\na=ice-pwd:XvPbiHzupfdCtOFdepBPJHTQgHzsdFKW\r\na=candidate:foundation 1 udp 2130706431 10.0.0.135 57244 typ host generation 0\r\na=candidate:foundation 2 udp 2130706431 10.0.0.135 57244 typ host generation 0\r\na=end-of-candidates\r\n"}
```

```
{"type":"answer","sdp":"v=0\r\no=- 203655353 1580083348 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 93:76:31:F6:F2:A3:5D:49:19:4A:95:2B:47:37:C9:D3:44:85:0C:B9:F9:8D:25:26:CA:58:CE:E9:13:7B:A7:88\r\na=group:BUNDLE 0 1\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 0.0.0.0\r\na=setup:passive\r\na=mid:0\r\na=ice-ufrag:xqNezbnKVKvmqoxr\r\na=ice-pwd:lDfpVajWfyGraMBIsfUYulKIIBFwLuQW\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=ssrc:4039455774 cname:KTplbapucrxtiKUk\r\na=ssrc:4039455774 msid:KTplbapucrxtiKUk kJcdbrMXhNAvsryK\r\na=ssrc:4039455774 mslabel:KTplbapucrxtiKUk\r\na=ssrc:4039455774 label:kJcdbrMXhNAvsryK\r\na=msid:KTplbapucrxtiKUk kJcdbrMXhNAvsryK\r\na=sendrecv\r\na=candidate:foundation 1 udp 2130706431 10.0.0.135 57401 typ host generation 0\r\na=candidate:foundation 2 udp 2130706431 10.0.0.135 57401 typ host generation 0\r\na=candidate:foundation 1 udp 1694498815 98.207.205.254 50876 typ srflx raddr 0.0.0.0 rport 50876 generation 0\r\na=candidate:foundation 2 udp 1694498815 98.207.205.254 50876 typ srflx raddr 0.0.0.0 rport 50876 generation 0\r\na=candidate:foundation 1 udp 1694498815 2601:646:c202:12d0:dd92:2f0e:ecb8:b134 50877 typ srflx raddr :: rport 50877 generation 0\r\na=candidate:foundation 2 udp 1694498815 2601:646:c202:12d0:dd92:2f0e:ecb8:b134 50877 typ srflx raddr :: rport 50877 generation 0\r\na=end-of-candidates\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=setup:passive\r\na=mid:1\r\na=sendrecv\r\na=sctpmap:5000 webrtc-datachannel 1024\r\na=ice-ufrag:xqNezbnKVKvmqoxr\r\na=ice-pwd:lDfpVajWfyGraMBIsfUYulKIIBFwLuQW\r\na=candidate:foundation 1 udp 2130706431 10.0.0.135 57401 typ host generation 0\r\na=candidate:foundation 2 udp 2130706431 10.0.0.135 57401 typ host generation 0\r\na=candidate:foundation 1 udp 1694498815 98.207.205.254 50876 typ srflx raddr 0.0.0.0 rport 50876 generation 0\r\na=candidate:foundation 2 udp 1694498815 98.207.205.254 50876 typ srflx raddr 0.0.0.0 rport 50876 generation 0\r\na=candidate:foundation 1 udp 1694498815 2601:646:c202:12d0:dd92:2f0e:ecb8:b134 50877 typ srflx raddr :: rport 50877 generation 0\r\na=candidate:foundation 2 udp 1694498815 2601:646:c202:12d0:dd92:2f0e:ecb8:b134 50877 typ srflx raddr :: rport 50877 generation 0\r\na=end-of-candidates\r\n"}
```

Would there be a good example actually sending and receiving audio with pion?

**Comment by enobufs** [comment]
According to [the spec](https://w3c.github.io/webrtc-pc/#rtcrtpsender-interface), RTPSender has read-only attribute "track", but pion's RTPSender does not have it.

I still do not fully understand concept of RTPTranceiver.  Looking at [the slide](https://www.slideshare.net/alexpiwi5/webrtc-object-model-api-transceivers), the Transceiver binds remote and local tracks together.

So, it looks to me that RTPSender.Track is missing in pion for the sendrecv scenario.

**Comment by enobufs** [comment]
@Sean-Der 
I have made a little bit of progress by exposing RTPSender.track:

```
+// Track returns the RTCRtpTransceiver track
+func (r *RTPSender) Track() *Track {
+       r.mu.RLock()
+       defer r.mu.RUnlock()
+       return r.track
+}
+
```

I noticed the track instance from RTPSender has a randomly assigned track ID and Label. I am wondering if application (answerer side) has an opportunity to create the label...

(It's been tough for me because I don't know exactly how WebRTC API for transceivers work... :p)

**Comment by Sean-Der** [comment]
Hey @enobufs 

I *think* things are working as designed, the terminology is kind of confusing though so here is how it works. I want to massively refactor all this stuff though, so maybe this is a good chance to review :)

* You will never be able to call `Write` on the `Track` emitted by `OnTrack`. Tracks themselves are never bi-directional, you either get to call `Read` or `Write` on them. Maybe we should update things and have a `TrackReader` and `TrackWriter` ?

* `Transceivers` are bi-directional. They are also created by `AddTrack` in your case of sending+receiving I would just have each side call `AddTrack` and everything will work great! 

* The random Id+Label you are getting is correct. I don't know how to make that API more user friendly without conflicting with the W3C more :/

I will leave this open! But I think the only actionable thing we can do (short term) is add `Track()` to RTPSender.

**Comment by enobufs** [comment]
> Tracks themselves are never bi-directional
Yes, it took a bit of time to figure this out.

> Transceivers are bi-directional. They are also created by AddTrack in your case of sending+receiving I would just have each side call AddTrack and everything will work great!

I wanted to Transceiver tho... To do that I was doing this:

Offerer:
1. pc.NewTrack()
1. pc.AddTransceiverFromTrack()
1. pc.CreateOffer()

Answerer:
1. pc.AddTransceiver()
2. pc.CreateAnswer()

This will let both ends a set of tracks successfully but requires RTPSender.Track() method being public on the answerer end because it does not involve pc.NewTrack().

As you said, "I would just have each side call AddTrack", do you mean, both ends should call NewTrack() and call AddTrack()?  I that case, how can I create a transceiver? Is there a way to create transceiver afterward or are you suggesting not to use transceiver? (sorry - i fee so dumb on media part :p)   An example of bidirectional media with (and without) transceivers would be super helpful for people like me...

**Comment by enobufs** [comment]
Ah I guess we can do this:

Offerer:
1. pc.NewTrack()
1. pc.AddTransceiverFromTrack()
1. pc.CreateOffer()

Answerer:
1. pc.NewTrack()
1. pc.AddTransceiverFromTrack()
1. pc.CreateAnswer()

And, if we don't need to use transceivers:
Offerer:
1. pc.NewTrack()
1. pc.AddTrack()
1. pc.CreateOffer()

Answerer:
1. pc.NewTrack()
1. pc.AddTrack()
1. pc.CreateAnswer()

Correct?

**Comment by Sean-Der** [comment]
@enobufs yep exactly!

`AddTrack` in the background is doing `AddTransceiverFromTrack` also. The API is sort of funky because.

* WebRTC has `AddTrack` and `AddTransceiver` and hasn't committed to API breakage yet.
* `AddTransceiver` in the browser accepts either a `string` or `Track` and we can't do multi-method dispatch in Go, making it impossible to match their API exactly :(

**Comment by enobufs** [comment]
> AddTrack in the background is doing AddTransceiverFromTrack also.
I see...
I was initially thought that I would need to use `AddTransceiver` because I wanted to use the same `m=` line for both direction because addTransceiver alows us to specify the direction.
```
		transceiver, err := sess.pc.AddTransceiverFromTrack(mediaTrack, webrtc.RtpTransceiverInit{
			Direction: webrtc.RTPTransceiverDirectionSendrecv,
		})
```

If we just use addTrack() for both ends, would it still be sharing the same `m=` with sendrecv?
Well, I can try testing it - thanks for answering to my novice questions on media channels!. ;)

**Comment by enobufs** [comment]
My code has been working fine with using a transceiver.
I think RTPSender.track could be exposed so that I don't have to hold on to the local track for send when I am also holding on to the transceiver which has both local and remote tracks - but this is trivial...

Let me close this issue - thanks Sean!
