### ISSUE TITLE
Codec problem in the OnTrack function

### ISSUE THREAD

**Issue by varadely** [pion/webrtc#991]
Hi, 
I wanted to make an Update of your librairy (my old version :  June 2019). And while doing the update I have a codec problem when I build for windows only: 
output from pion/example-webrtc-applications/gstreamer-receive : 
On windows: 
```
Connection State has changed connected 
Track has started, of type 0: PCMU 
Track has started, of type 96: VP8 
```

on Linux : 
```
Connection State has changed connected 
Track has started, of type 111: OPUS 
Track has started, of type 96: VP8 
```
Any idea ?

**Comment by Sean-Der** [comment]
Hi @varadely 

What SHA1 are you using now? We did fix a bug around this with 6a29bdf3040f4227ad0e785da9cf479600cabd3c

**Comment by Sean-Der** [comment]
Could you also try before 5a752da6831a61700a22df00ae117ca2ec24c7d9 this was when G711 support was added

**Comment by varadely** [comment]
I use the this https://github.com/pion/webrtc/commit/537c841073600e9fb176d1677ee1b3c41b8baca7
Is this the correct SHA1 ? Or if not, where do I find it?

**Comment by varadely** [comment]
> Hi @varadely
> 
> What SHA1 are you using now? We did fix a bug around this with [6a29bdf](https://github.com/pion/webrtc/commit/6a29bdf3040f4227ad0e785da9cf479600cabd3c)

I've this correction in my code : 
```
	m.RegisterCodec(NewRTPPCMUCodec(DefaultPayloadTypePCMU, 8000))
	m.RegisterCodec(NewRTPPCMACodec(DefaultPayloadTypePCMA, 8000))
	m.RegisterCodec(NewRTPOpusCodec(DefaultPayloadTypeOpus, 48000))
```

**Comment by varadely** [comment]
> Could you also try before [5a752da](https://github.com/pion/webrtc/commit/5a752da6831a61700a22df00ae117ca2ec24c7d9) this was when G711 support was added

How I can install an older version ? 
When I wanted to build, I had problems with dependencies on outdated packages (src\github.com\pion\webrtc\dtlstransport.go:245:3: unknown field 'Certificate' in struct literal of type dtls.Config) .

**Comment by varadely** [comment]
I overwrite the PayloadType and it's work. I don't know why it's 0, in the SDP, the codec is OPUS.
In track.go : 
```
func (t *Track) determinePayloadType() error {
	r, err := t.ReadRTP()
	if err != nil {
		return err
	}

	t.mu.Lock()
	if r.PayloadType == 0 {
		r.PayloadType = 111
	}
	t.payloadType = r.PayloadType
	defer t.mu.Unlock()

	return nil
}
```

**Comment by Sean-Der** [comment]
@varadely I think the issue is that PCM is at the top, so the other side is just taking the top codec we support.

Would you mind trying out https://github.com/pion/webrtc/pull/992 ? You can also instantiate your own MediaEngine and set codec preferences, but I think this new behavior is the best default.

thanks

**Comment by varadely** [comment]
Hi @seppo0010 
Big thanks, it's works. You can close this issie. 
I've some questions : 
So, the first codec is necessarily the one used ? how to do if the browser uses another codec ? (mainly for Safari on iphone)

**Comment by Sean-Der** [comment]
WebRTC clients try to find an intersection of supported codecs. Each side publishes the list of codecs they support via the Offer/Answer messages.

If they both have `Opus` as the first one that is what they will use!

You can use the `MediaEngine` interface to declare was codecs you are willing to accept. If you don't support any codecs the browser supports `SetRemoteDescription` will return an error.

thanks for using Pion :)
